# Generated by Django 5.0.9 on 2025-12-23 21:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActaReunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "numero_acta",
                    models.CharField(
                        help_text="Número de acta (ej: ACTA-COPASST-001/2024)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "desarrollo",
                    models.TextField(
                        help_text="Desarrollo de la reunión y temas tratados"
                    ),
                ),
                (
                    "conclusiones",
                    models.TextField(
                        blank=True, help_text="Conclusiones de la reunión"
                    ),
                ),
                (
                    "decisiones",
                    models.TextField(blank=True, help_text="Decisiones tomadas"),
                ),
                (
                    "proxima_reunion_fecha",
                    models.DateField(
                        blank=True,
                        help_text="Fecha programada para próxima reunión",
                        null=True,
                    ),
                ),
                (
                    "proxima_reunion_agenda",
                    models.TextField(
                        blank=True, help_text="Temas para próxima reunión"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("REVISION", "En Revisión"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="BORRADOR",
                        help_text="Estado del acta",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de aprobación del acta", null=True
                    ),
                ),
                (
                    "aprobada_por_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del usuario que aprobó el acta",
                        null=True,
                    ),
                ),
                (
                    "aprobada_por_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del usuario que aprobó (denormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Archivo PDF del acta firmada",
                        null=True,
                        upload_to="comites/actas/",
                    ),
                ),
                (
                    "firmas",
                    models.JSONField(
                        default=list, help_text="Lista de firmas digitales del acta"
                    ),
                ),
                (
                    "observaciones_revision",
                    models.TextField(
                        blank=True, help_text="Observaciones durante la revisión"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de Reunión",
                "verbose_name_plural": "Actas de Reunión",
                "db_table": "hseq_acta_reunion",
                "ordering": ["reunion__comite", "-reunion__fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="Comite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "codigo_comite",
                    models.CharField(
                        help_text="Código único del comité (ej: COPASST-2024-2026)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del comité activo", max_length=200
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(help_text="Fecha de inicio del periodo"),
                ),
                (
                    "fecha_fin",
                    models.DateField(help_text="Fecha de finalización del periodo"),
                ),
                (
                    "periodo_descripcion",
                    models.CharField(
                        help_text="Descripción del periodo (ej: 2024-2026)",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CONFORMACION", "En Conformación"),
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="CONFORMACION",
                        help_text="Estado del comité",
                        max_length=20,
                    ),
                ),
                (
                    "acta_conformacion",
                    models.FileField(
                        blank=True,
                        help_text="Acta de conformación del comité",
                        null=True,
                        upload_to="comites/actas_conformacion/",
                    ),
                ),
                (
                    "fecha_conformacion",
                    models.DateField(
                        blank=True, help_text="Fecha de conformación oficial", null=True
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones generales del comité"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comité",
                "verbose_name_plural": "Comités",
                "db_table": "hseq_comite",
                "ordering": ["empresa_id", "-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "numero_compromiso",
                    models.CharField(help_text="Número del compromiso", max_length=50),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Descripción del compromiso"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCION", "Acción a ejecutar"),
                            ("SEGUIMIENTO", "Seguimiento"),
                            ("VERIFICACION", "Verificación"),
                            ("INVESTIGACION", "Investigación"),
                            ("CAPACITACION", "Capacitación"),
                            ("INSPECCION", "Inspección"),
                            ("OTRO", "Otro"),
                        ],
                        default="ACCION",
                        help_text="Tipo de compromiso",
                        max_length=50,
                    ),
                ),
                (
                    "responsable_id",
                    models.IntegerField(
                        db_index=True, help_text="ID del responsable del compromiso"
                    ),
                ),
                (
                    "responsable_nombre",
                    models.CharField(
                        help_text="Nombre del responsable (denormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "area_responsable",
                    models.CharField(
                        blank=True, help_text="Área responsable", max_length=200
                    ),
                ),
                (
                    "fecha_compromiso",
                    models.DateField(
                        help_text="Fecha en que se adquirió el compromiso"
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(help_text="Fecha límite de cumplimiento"),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de cierre del compromiso",
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADO", "Completado"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        help_text="Estado del compromiso",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Porcentaje de avance del compromiso",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        help_text="Prioridad del compromiso",
                        max_length=20,
                    ),
                ),
                (
                    "evidencias",
                    models.JSONField(
                        default=list, help_text="Lista de evidencias del cumplimiento"
                    ),
                ),
                (
                    "verificado_por_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del usuario que verificó el cumplimiento",
                        null=True,
                    ),
                ),
                (
                    "verificado_por_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del verificador (denormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "fecha_verificacion",
                    models.DateField(
                        blank=True, help_text="Fecha de verificación", null=True
                    ),
                ),
                (
                    "observaciones_verificacion",
                    models.TextField(
                        blank=True, help_text="Observaciones de la verificación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones generales del compromiso"
                    ),
                ),
                (
                    "acta",
                    models.ForeignKey(
                        help_text="Acta de la que se deriva el compromiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compromisos",
                        to="gestion_comites.actareunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromiso",
                "verbose_name_plural": "Compromisos",
                "db_table": "hseq_compromiso",
                "ordering": ["acta__reunion__comite", "-fecha_limite"],
            },
        ),
        migrations.CreateModel(
            name="MiembroComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "empleado_id",
                    models.IntegerField(
                        db_index=True, help_text="ID del empleado miembro del comité"
                    ),
                ),
                (
                    "empleado_nombre",
                    models.CharField(
                        help_text="Nombre completo del empleado (denormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "empleado_cargo",
                    models.CharField(
                        blank=True,
                        help_text="Cargo del empleado (denormalizado)",
                        max_length=200,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        help_text="Rol en el comité (ej: Presidente, Secretario, Representante)",
                        max_length=50,
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=True,
                        help_text="Si es miembro principal (False = suplente)",
                    ),
                ),
                (
                    "representa_a",
                    models.CharField(
                        blank=True,
                        help_text="A quién representa (ej: Empleador, Trabajadores)",
                        max_length=100,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(help_text="Fecha de inicio como miembro"),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de finalización como miembro",
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si el miembro está activo"
                    ),
                ),
                (
                    "numero_votos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de votos obtenidos en elección",
                        null=True,
                    ),
                ),
                (
                    "acta_eleccion",
                    models.FileField(
                        blank=True,
                        help_text="Acta de elección del miembro",
                        null=True,
                        upload_to="comites/actas_eleccion/",
                    ),
                ),
                (
                    "motivo_retiro",
                    models.CharField(
                        blank=True,
                        help_text="Motivo de retiro del comité",
                        max_length=200,
                    ),
                ),
                (
                    "comite",
                    models.ForeignKey(
                        help_text="Comité al que pertenece",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="gestion_comites.comite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de Comité",
                "verbose_name_plural": "Miembros de Comité",
                "db_table": "hseq_miembro_comite",
                "ordering": ["comite", "-es_principal", "rol", "empleado_nombre"],
            },
        ),
        migrations.CreateModel(
            name="Reunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "numero_reunion",
                    models.CharField(
                        help_text="Número correlativo de la reunión (ej: 001/2024)",
                        max_length=50,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ORDINARIA", "Ordinaria"),
                            ("EXTRAORDINARIA", "Extraordinaria"),
                        ],
                        default="ORDINARIA",
                        help_text="Tipo de reunión",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateField(help_text="Fecha programada para la reunión"),
                ),
                (
                    "hora_inicio_programada",
                    models.TimeField(help_text="Hora de inicio programada"),
                ),
                (
                    "hora_fin_programada",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de finalización programada",
                        null=True,
                    ),
                ),
                (
                    "fecha_realizada",
                    models.DateField(
                        blank=True, help_text="Fecha real de la reunión", null=True
                    ),
                ),
                (
                    "hora_inicio_real",
                    models.TimeField(
                        blank=True, help_text="Hora real de inicio", null=True
                    ),
                ),
                (
                    "hora_fin_real",
                    models.TimeField(
                        blank=True, help_text="Hora real de finalización", null=True
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        help_text="Lugar donde se realiza la reunión", max_length=200
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("VIRTUAL", "Virtual"),
                            ("HIBRIDA", "Híbrida"),
                        ],
                        default="PRESENCIAL",
                        help_text="Modalidad de la reunión",
                        max_length=20,
                    ),
                ),
                (
                    "enlace_virtual",
                    models.URLField(
                        blank=True, help_text="Enlace para reunión virtual"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_CURSO", "En Curso"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                            ("REPROGRAMADA", "Reprogramada"),
                        ],
                        default="PROGRAMADA",
                        help_text="Estado de la reunión",
                        max_length=20,
                    ),
                ),
                (
                    "cumple_quorum",
                    models.BooleanField(
                        default=False, help_text="Si se cumplió el quorum"
                    ),
                ),
                (
                    "num_asistentes",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de asistentes"
                    ),
                ),
                ("agenda", models.TextField(help_text="Agenda de la reunión")),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones de la reunión"
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.CharField(
                        blank=True,
                        help_text="Motivo de cancelación o reprogramación",
                        max_length=500,
                    ),
                ),
                (
                    "comite",
                    models.ForeignKey(
                        help_text="Comité que realiza la reunión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reuniones",
                        to="gestion_comites.comite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reunión",
                "verbose_name_plural": "Reuniones",
                "db_table": "hseq_reunion",
                "ordering": ["comite", "-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="AsistenciaReunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "asistio",
                    models.BooleanField(
                        default=False, help_text="Si asistió a la reunión"
                    ),
                ),
                (
                    "hora_llegada",
                    models.TimeField(
                        blank=True, help_text="Hora de llegada", null=True
                    ),
                ),
                (
                    "excusa",
                    models.CharField(
                        blank=True, help_text="Excusa por inasistencia", max_length=500
                    ),
                ),
                (
                    "excusa_justificada",
                    models.BooleanField(
                        default=False, help_text="Si la excusa fue justificada"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones sobre la asistencia"
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        help_text="Miembro del comité",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="gestion_comites.miembrocomite",
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        help_text="Reunión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="gestion_comites.reunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia a Reunión",
                "verbose_name_plural": "Asistencias a Reuniones",
                "db_table": "hseq_asistencia_reunion",
                "ordering": ["reunion", "miembro"],
            },
        ),
        migrations.AddField(
            model_name="actareunion",
            name="reunion",
            field=models.OneToOneField(
                help_text="Reunión a la que corresponde el acta",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acta",
                to="gestion_comites.reunion",
            ),
        ),
        migrations.CreateModel(
            name="SeguimientoCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "fecha_seguimiento",
                    models.DateField(help_text="Fecha del seguimiento"),
                ),
                (
                    "avance_reportado",
                    models.PositiveIntegerField(
                        help_text="Porcentaje de avance reportado",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "descripcion_avance",
                    models.TextField(help_text="Descripción del avance realizado"),
                ),
                (
                    "evidencias",
                    models.JSONField(default=list, help_text="Evidencias del avance"),
                ),
                (
                    "dificultades",
                    models.TextField(blank=True, help_text="Dificultades encontradas"),
                ),
                (
                    "requiere_apoyo",
                    models.BooleanField(
                        default=False, help_text="Si requiere apoyo adicional"
                    ),
                ),
                (
                    "tipo_apoyo_requerido",
                    models.CharField(
                        blank=True, help_text="Tipo de apoyo requerido", max_length=500
                    ),
                ),
                (
                    "registrado_por_id",
                    models.IntegerField(
                        help_text="ID del usuario que registró el seguimiento"
                    ),
                ),
                (
                    "registrado_por_nombre",
                    models.CharField(
                        help_text="Nombre del usuario (denormalizado)", max_length=200
                    ),
                ),
                (
                    "compromiso",
                    models.ForeignKey(
                        help_text="Compromiso al que se hace seguimiento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="gestion_comites.compromiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Compromiso",
                "verbose_name_plural": "Seguimientos de Compromisos",
                "db_table": "hseq_seguimiento_compromiso",
                "ordering": ["compromiso", "-fecha_seguimiento"],
            },
        ),
        migrations.CreateModel(
            name="TipoComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del tipo de comité (ej: COPASST, COCOLA, CSV)",
                        max_length=20,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del tipo de comité", max_length=200
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción y alcance del comité"
                    ),
                ),
                (
                    "normativa_base",
                    models.CharField(
                        blank=True,
                        help_text="Marco normativo que regula este comité (ej: Resolución 2013 de 1986)",
                        max_length=500,
                    ),
                ),
                (
                    "periodicidad_reuniones",
                    models.CharField(
                        choices=[
                            ("MENSUAL", "Mensual"),
                            ("BIMESTRAL", "Bimestral"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("SEMESTRAL", "Semestral"),
                            ("ANUAL", "Anual"),
                            ("PERSONALIZADO", "Personalizado"),
                        ],
                        default="MENSUAL",
                        help_text="Frecuencia de reuniones ordinarias",
                        max_length=20,
                    ),
                ),
                (
                    "num_minimo_miembros",
                    models.PositiveIntegerField(
                        default=2, help_text="Número mínimo de miembros requerido"
                    ),
                ),
                (
                    "num_maximo_miembros",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número máximo de miembros permitido",
                        null=True,
                    ),
                ),
                (
                    "requiere_eleccion",
                    models.BooleanField(
                        default=True,
                        help_text="Si requiere proceso de elección de miembros",
                    ),
                ),
                (
                    "duracion_periodo_meses",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Duración del periodo en meses (ej: 24 para COPASST)",
                    ),
                ),
                (
                    "roles_disponibles",
                    models.JSONField(
                        default=list,
                        help_text="Roles disponibles en el comité (ej: ['Presidente', 'Secretario', 'Representante'])",
                    ),
                ),
                (
                    "requiere_quorum",
                    models.BooleanField(
                        default=True,
                        help_text="Si requiere quorum mínimo para sesionar",
                    ),
                ),
                (
                    "porcentaje_quorum",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Porcentaje mínimo de asistencia para quorum",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si el tipo de comité está activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Comité",
                "verbose_name_plural": "Tipos de Comité",
                "db_table": "hseq_tipo_comite",
                "ordering": ["empresa_id", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "activo"],
                        name="hseq_tipo_c_empresa_80edfe_idx",
                    ),
                    models.Index(
                        fields=["codigo"], name="hseq_tipo_c_codigo_4b5dd7_idx"
                    ),
                ],
                "unique_together": {("empresa_id", "codigo")},
            },
        ),
        migrations.AddField(
            model_name="comite",
            name="tipo_comite",
            field=models.ForeignKey(
                help_text="Tipo de comité",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comites",
                to="gestion_comites.tipocomite",
            ),
        ),
        migrations.CreateModel(
            name="Votacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "numero_votacion",
                    models.CharField(help_text="Número de la votación", max_length=50),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título de la votación", max_length=300),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del tema a votar"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ELECCION", "Elección de miembros"),
                            ("DECISION", "Decisión del comité"),
                            ("APROBACION", "Aprobación de documento"),
                            ("OTRO", "Otro"),
                        ],
                        default="DECISION",
                        help_text="Tipo de votación",
                        max_length=50,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        help_text="Fecha y hora de inicio de votación"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        help_text="Fecha y hora de cierre de votación"
                    ),
                ),
                (
                    "es_secreta",
                    models.BooleanField(
                        default=False, help_text="Si la votación es secreta"
                    ),
                ),
                (
                    "requiere_mayoria_simple",
                    models.BooleanField(
                        default=True, help_text="Si requiere mayoría simple (50%+1)"
                    ),
                ),
                (
                    "porcentaje_mayoria_requerido",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Porcentaje de mayoría requerido",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "permite_abstencion",
                    models.BooleanField(
                        default=True, help_text="Si permite abstención"
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        default=list,
                        help_text="Opciones de votación (ej: [{'id': 1, 'texto': 'A favor'}, ...])",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_CURSO", "En Curso"),
                            ("CERRADA", "Cerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        help_text="Estado de la votación",
                        max_length=20,
                    ),
                ),
                (
                    "total_votos_emitidos",
                    models.PositiveIntegerField(
                        default=0, help_text="Total de votos emitidos"
                    ),
                ),
                (
                    "resultados",
                    models.JSONField(
                        default=dict, help_text="Resultados de la votación"
                    ),
                ),
                (
                    "opcion_ganadora",
                    models.CharField(
                        blank=True, help_text="Opción ganadora", max_length=500
                    ),
                ),
                (
                    "fecha_cierre_real",
                    models.DateTimeField(
                        blank=True, help_text="Fecha real de cierre", null=True
                    ),
                ),
                (
                    "cerrada_por_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del usuario que cerró la votación",
                        null=True,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones de la votación"
                    ),
                ),
                (
                    "comite",
                    models.ForeignKey(
                        help_text="Comité que realiza la votación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votaciones",
                        to="gestion_comites.comite",
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reunión en la que se realiza la votación (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votaciones",
                        to="gestion_comites.reunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votación",
                "verbose_name_plural": "Votaciones",
                "db_table": "hseq_votacion",
                "ordering": ["comite", "-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="VotoMiembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(
                        db_index=True, help_text="ID de la empresa (multi-tenant)"
                    ),
                ),
                (
                    "fecha_voto",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora del voto"
                    ),
                ),
                (
                    "opcion_id",
                    models.IntegerField(
                        blank=True, help_text="ID de la opción votada", null=True
                    ),
                ),
                (
                    "opcion_texto",
                    models.CharField(
                        blank=True,
                        help_text="Texto de la opción votada (denormalizado)",
                        max_length=500,
                    ),
                ),
                (
                    "es_abstencion",
                    models.BooleanField(
                        default=False, help_text="Si es una abstención"
                    ),
                ),
                (
                    "justificacion_abstencion",
                    models.TextField(
                        blank=True, help_text="Justificación de la abstención"
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, help_text="Comentarios adicionales del voto"
                    ),
                ),
                (
                    "voto_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash del voto para votaciones secretas",
                        max_length=64,
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        help_text="Miembro que emite el voto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="gestion_comites.miembrocomite",
                    ),
                ),
                (
                    "votacion",
                    models.ForeignKey(
                        help_text="Votación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="gestion_comites.votacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto de Miembro",
                "verbose_name_plural": "Votos de Miembros",
                "db_table": "hseq_voto_miembro",
                "ordering": ["votacion", "fecha_voto"],
            },
        ),
        migrations.AddIndex(
            model_name="compromiso",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_compro_empresa_8168a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromiso",
            index=models.Index(fields=["acta"], name="hseq_compro_acta_id_7d75ac_idx"),
        ),
        migrations.AddIndex(
            model_name="compromiso",
            index=models.Index(
                fields=["responsable_id"], name="hseq_compro_respons_e80335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromiso",
            index=models.Index(
                fields=["fecha_limite"], name="hseq_compro_fecha_l_134da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compromiso",
            index=models.Index(
                fields=["estado", "fecha_limite"], name="hseq_compro_estado_2f4b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="miembrocomite",
            index=models.Index(
                fields=["empresa_id", "activo"], name="hseq_miembr_empresa_c60530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="miembrocomite",
            index=models.Index(
                fields=["comite", "activo"], name="hseq_miembr_comite__1519e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="miembrocomite",
            index=models.Index(
                fields=["empleado_id"], name="hseq_miembr_emplead_060bf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reunion",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_reunio_empresa_a918b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reunion",
            index=models.Index(
                fields=["comite", "fecha_programada"],
                name="hseq_reunio_comite__2a4e18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reunion",
            index=models.Index(
                fields=["fecha_programada"], name="hseq_reunio_fecha_p_6f9008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asistenciareunion",
            index=models.Index(
                fields=["empresa_id"], name="hseq_asiste_empresa_20f29b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asistenciareunion",
            index=models.Index(
                fields=["reunion"], name="hseq_asiste_reunion_f4b342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asistenciareunion",
            index=models.Index(
                fields=["miembro"], name="hseq_asiste_miembro_8be1dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asistenciareunion",
            unique_together={("reunion", "miembro")},
        ),
        migrations.AddIndex(
            model_name="actareunion",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_acta_r_empresa_8c2f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actareunion",
            index=models.Index(
                fields=["reunion"], name="hseq_acta_r_reunion_623de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actareunion",
            index=models.Index(
                fields=["numero_acta"], name="hseq_acta_r_numero__c6ebe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientocompromiso",
            index=models.Index(
                fields=["empresa_id"], name="hseq_seguim_empresa_05da87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientocompromiso",
            index=models.Index(
                fields=["compromiso", "fecha_seguimiento"],
                name="hseq_seguim_comprom_421238_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comite",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_comite_empresa_429985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comite",
            index=models.Index(
                fields=["tipo_comite", "estado"], name="hseq_comite_tipo_co_1c94ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comite",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="hseq_comite_fecha_i_431cb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="votacion",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_votaci_empresa_4e213c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votacion",
            index=models.Index(
                fields=["comite", "fecha_inicio"], name="hseq_votaci_comite__c88c7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votacion",
            index=models.Index(
                fields=["reunion"], name="hseq_votaci_reunion_fe0445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votomiembro",
            index=models.Index(
                fields=["empresa_id"], name="hseq_voto_m_empresa_97bfc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votomiembro",
            index=models.Index(
                fields=["votacion"], name="hseq_voto_m_votacio_35a3e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votomiembro",
            index=models.Index(
                fields=["miembro"], name="hseq_voto_m_miembro_956178_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="votomiembro",
            unique_together={("votacion", "miembro")},
        ),
    ]
