# Generated by Django 5.0.9 on 2026-01-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaContabilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_origen', models.CharField(db_index=True, max_length=50, verbose_name='Módulo de Origen')),
                ('documento_origen_tipo', models.CharField(max_length=50, verbose_name='Tipo Documento Origen')),
                ('documento_origen_id', models.IntegerField(db_index=True, verbose_name='ID Documento Origen')),
                ('prioridad', models.IntegerField(choices=[(1, 'Muy Alta'), (3, 'Alta'), (5, 'Normal'), (7, 'Baja'), (9, 'Muy Baja')], db_index=True, default=5, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('datos_json', models.JSONField(default=dict, verbose_name='Datos JSON')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('intentos', models.IntegerField(default=0, verbose_name='Intentos')),
                ('max_intentos', models.IntegerField(default=3, verbose_name='Máximo de Intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('procesado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('proximo_intento_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Próximo Intento')),
            ],
            options={
                'verbose_name': 'Cola de Contabilización',
                'verbose_name_plural': 'Colas de Contabilización',
                'db_table': 'accounting_cola_contabilizacion',
                'ordering': ['prioridad', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_origen', models.CharField(db_index=True, max_length=50, verbose_name='Módulo de Origen')),
                ('documento_origen_tipo', models.CharField(max_length=50, verbose_name='Tipo Documento Origen')),
                ('documento_origen_id', models.IntegerField(db_index=True, verbose_name='ID Documento Origen')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('exitoso', 'Exitoso'), ('error', 'Error'), ('revertido', 'Revertido')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_json', models.JSONField(default=dict, verbose_name='Datos JSON')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('procesado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
            ],
            options={
                'verbose_name': 'Log de Integración',
                'verbose_name_plural': 'Logs de Integración',
                'db_table': 'accounting_log_integracion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('modulo', models.CharField(choices=[('tesoreria', 'Tesorería'), ('nomina', 'Nómina'), ('inventarios', 'Inventarios'), ('activos_fijos', 'Activos Fijos'), ('ventas', 'Ventas'), ('compras', 'Compras')], db_index=True, max_length=50, verbose_name='Módulo')),
                ('clave', models.CharField(db_index=True, help_text='Identificador del parámetro (ej: cuenta_banco, cuenta_caja)', max_length=100, verbose_name='Clave de Mapeo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('configuracion_json', models.JSONField(blank=True, default=dict, verbose_name='Configuración JSON')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Parámetros de Integración',
                'verbose_name_plural': 'Parámetros de Integración',
                'db_table': 'accounting_parametros_integracion',
                'ordering': ['modulo', 'clave'],
            },
        ),
    ]
