# Generated by Django 5.0.14 on 2026-04-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_catalogo_productos", "0002_productoespeccalidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproducto",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Las categorías del sistema son protegidas y no se pueden eliminar",
                verbose_name="Es del sistema",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Las unidades del sistema son protegidas y no se pueden eliminar",
                verbose_name="Es del sistema",
            ),
        ),
    ]
