# Generated by Django 5.0.14 on 2026-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infra_catalogo_productos",
            "0003_categoriaproducto_is_system_unidadmedida_is_system",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_referencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor estimado para presupuesto inicial. El precio real se define por proveedor en Supply Chain > Precios.",
                max_digits=15,
                null=True,
                verbose_name="Precio estimado (referencia)",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sku",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de barras, referencia del proveedor o código externo (EAN-13, SAP, INVIMA, etc.)",
                max_length=100,
                verbose_name="SKU / Código externo",
            ),
        ),
    ]
