# Generated by Django 5.0.14 on 2026-04-22 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_catalogo_productos", "0012_producto_requiere_qc_recepcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoEspecCalidadParametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre_parametro",
                    models.CharField(
                        db_index=True,
                        help_text="Ej: acidez, humedad, pH, densidad",
                        max_length=80,
                        verbose_name="Nombre del parámetro",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Unidad de medida del parámetro. Ej: %, ppm, pH, g/cm³",
                        max_length=20,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "valor_min",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Valor mínimo aceptable",
                    ),
                ),
                (
                    "valor_max",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Valor máximo aceptable",
                    ),
                ),
                (
                    "es_critico",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, un valor medido fuera de rango rechaza el lote (voucher no aprobable). Si es False, solo genera advertencia y puede justificar ajuste de precio.",
                        verbose_name="Es crítico",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de presentación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "espec_calidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros",
                        to="infra_catalogo_productos.productoespeccalidad",
                        verbose_name="Especificación de calidad",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro de especificación de calidad",
                "verbose_name_plural": "Parámetros de especificación de calidad",
                "ordering": ["orden", "nombre_parametro"],
                "indexes": [
                    models.Index(
                        fields=["espec_calidad", "orden"],
                        name="catalogo_pr_espec_c_3e3a16_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productoespeccalidadparametro",
            constraint=models.CheckConstraint(
                check=models.Q(("valor_max__gte", models.F("valor_min"))),
                name="ck_espec_calidad_parametro_rango_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoespeccalidadparametro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("espec_calidad", "nombre_parametro"),
                name="uq_espec_calidad_parametro_por_espec",
            ),
        ),
    ]
