# Generated by Django 5.0.14 on 2026-04-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_catalogo_productos", "0014_backfill_parametro_acidez"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoproveedor",
            name="tipos_productos_permitidos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de tipos de producto que este tipo de proveedor puede suministrar. Valores válidos: MATERIA_PRIMA, INSUMO, PRODUCTO_TERMINADO, SERVICIO. Vacío = se permiten todos.",
                verbose_name="Tipos de productos/servicios permitidos",
            ),
        ),
    ]
