# Generated by Django 5.0.14 on 2026-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_catalogo_productos", "0026_normalize_db_table_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="productos_suministrados",
            field=models.ManyToManyField(
                blank=True,
                db_table="catalogo_productos_proveedor_productos_suministrados",
                related_name="proveedores_ct",
                to="infra_catalogo_productos.producto",
                verbose_name="Productos que suministra",
            ),
        ),
    ]
