# Generated by Django 5.0.14 on 2026-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sc_recoleccion", "0004_talonario_manual_planta"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="voucherrecoleccion",
            new_name="supply_chai_proveed_d8f13f_idx",
            old_name="sc_vrc_prov_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="voucherrecoleccion",
            new_name="supply_chai_origen__c32976_idx",
            old_name="sc_vrc_origen_fecha_idx",
        ),
        migrations.AlterField(
            model_name="voucherrecoleccion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único (VRC-001). Se auto-genera si viene vacío.",
                max_length=50,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="voucherrecoleccion",
            name="fecha_recoleccion",
            field=models.DateField(
                help_text="Día en que se recogió a este productor.",
                verbose_name="Fecha de recolección",
            ),
        ),
        migrations.AlterField(
            model_name="voucherrecoleccion",
            name="notas",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Observaciones de la parada (clima, novedades, etc.).",
                verbose_name="Notas",
            ),
        ),
    ]
