# Generated by Django 5.0.14 on 2026-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sc_recoleccion", "0006_voucherrecoleccion_documento_archivado_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherrecoleccion",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Kilos entregados por el productor en esta parada (1 decimal — báscula industrial).",
                max_digits=12,
                verbose_name="Cantidad (kilos)",
            ),
        ),
    ]
