# Generated by Django 5.0.9 on 2026-02-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_initial'),
        ('configuracion', '0003_alter_empresaconfig_options_and_more'),
        ('proceso_disciplinario', '0002_ley2466_compliance'),
        ('reglamentos_internos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaAcosoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('es_anonima', models.BooleanField(default=False, help_text='Si la denuncia se realiza de forma anónima', verbose_name='Denuncia Anónima')),
                ('tipo_acoso', models.CharField(choices=[('maltrato', 'Maltrato Laboral'), ('persecucion', 'Persecución Laboral'), ('discriminacion', 'Discriminación Laboral'), ('entorpecimiento', 'Entorpecimiento Laboral'), ('inequidad', 'Inequidad Laboral'), ('desproteccion', 'Desprotección Laboral')], db_index=True, help_text='Modalidad de acoso según Art. 2 Ley 1010/2006', max_length=20, verbose_name='Tipo de Acoso')),
                ('descripcion_hechos', models.TextField(help_text='Descripción detallada de los hechos de acoso', verbose_name='Descripción de los Hechos')),
                ('fecha_hechos', models.DateField(help_text='Fecha aproximada de los hechos denunciados', verbose_name='Fecha de los Hechos')),
                ('lugar_hechos', models.CharField(blank=True, help_text='Lugar donde ocurrieron los hechos', max_length=255, verbose_name='Lugar de los Hechos')),
                ('evidencia', models.FileField(blank=True, help_text='Archivo de evidencia (correos, fotos, grabaciones permitidas)', null=True, upload_to='talent_hub/acoso_laboral/evidencias/', verbose_name='Evidencia')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('investigacion', 'En Investigación'), ('comite', 'Remitida a Comité de Convivencia'), ('resolucion', 'En Resolución'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], db_index=True, default='recibida', help_text='Estado actual de la denuncia', max_length=20, verbose_name='Estado')),
                ('comite_convivencia_notificado', models.BooleanField(default=False, help_text='Si el Comité de Convivencia Laboral ha sido notificado', verbose_name='Comité de Convivencia Notificado')),
                ('fecha_notificacion_comite', models.DateField(blank=True, help_text='Fecha en que se notificó al Comité de Convivencia', null=True, verbose_name='Fecha Notificación al Comité')),
                ('resolucion', models.TextField(blank=True, help_text='Resolución o decisión tomada sobre la denuncia', verbose_name='Resolución')),
                ('medidas_correctivas', models.JSONField(default=list, help_text='Lista de medidas correctivas adoptadas', verbose_name='Medidas Correctivas')),
                ('fecha_cierre', models.DateField(blank=True, help_text='Fecha de cierre de la denuncia', null=True, verbose_name='Fecha de Cierre')),
            ],
            options={
                'verbose_name': 'Denuncia de Acoso Laboral',
                'verbose_name_plural': 'Denuncias de Acoso Laboral',
                'db_table': 'talent_hub_denuncia_acoso_laboral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notificaciondisciplinaria',
            new_name='talent_hub__empresa_252ccd_idx',
            old_name='th_notif_disc_emp_col_idx',
        ),
        migrations.RenameIndex(
            model_name='notificaciondisciplinaria',
            new_name='talent_hub__tipo_4fb8c0_idx',
            old_name='th_notif_disc_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='pruebadisciplinaria',
            new_name='talent_hub__descarg_0827e6_idx',
            old_name='th_prueba_disc_desc_pres_idx',
        ),
        migrations.AlterField(
            model_name='descargo',
            name='apelado',
            field=models.BooleanField(default=False, help_text='El colaborador apeló la decisión del descargo', verbose_name='Apelado'),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='representante_sindical',
            field=models.CharField(blank=True, help_text='Nombre del representante sindical presente', max_length=200, verbose_name='Representante Sindical'),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargos_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por'),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='resultado_apelacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('modificado', 'Modificado'), ('revocado', 'Revocado')], default='pendiente', max_length=15, verbose_name='Resultado Apelación'),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='tipo_acompanante',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('sindical', 'Representante Sindical'), ('abogado', 'Abogado'), ('companero', 'Compañero de Trabajo')], default='ninguno', help_text='Ley 2466/2025: Derecho a acompañante en diligencia de descargos', max_length=20, verbose_name='Tipo de Acompañante'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='acuse_recibo',
            field=models.BooleanField(default=False, help_text='El colaborador firmó acuse de recibo', verbose_name='Acuse de Recibo'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='notificaciondisciplinaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='admitida',
            field=models.BooleanField(blank=True, help_text='Nulo=pendiente, True=admitida, False=rechazada', null=True, verbose_name='Admitida'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='pruebadisciplinaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='denunciado',
            field=models.ForeignKey(help_text='Colaborador denunciado por acoso laboral', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_acoso_recibidas', to='colaboradores.colaborador', verbose_name='Denunciado'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='denunciante',
            field=models.ForeignKey(blank=True, help_text='Usuario que realiza la denuncia (vacío = anónima)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_acoso_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='reglamento_aplicable',
            field=models.ForeignKey(blank=True, help_text='Reglamento interno de trabajo que sustenta las medidas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reglamentos_internos.reglamento', verbose_name='Reglamento Aplicable'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='testigos',
            field=models.ManyToManyField(blank=True, help_text='Colaboradores testigos de los hechos', related_name='testigo_en_denuncias_acoso', to='colaboradores.colaborador', verbose_name='Testigos'),
        ),
        migrations.AddField(
            model_name='denunciaacosolaboral',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='denunciaacosolaboral',
            index=models.Index(fields=['empresa', 'estado'], name='talent_hub__empresa_a71b04_idx'),
        ),
        migrations.AddIndex(
            model_name='denunciaacosolaboral',
            index=models.Index(fields=['empresa', 'tipo_acoso'], name='talent_hub__empresa_b200fe_idx'),
        ),
        migrations.AddIndex(
            model_name='denunciaacosolaboral',
            index=models.Index(fields=['denunciado'], name='talent_hub__denunci_147b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='denunciaacosolaboral',
            index=models.Index(fields=['fecha_hechos'], name='talent_hub__fecha_h_ce4330_idx'),
        ),
    ]
