# Generated by Django 5.0.9 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipevr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizipevr',
            name='cargo_id_ref',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID del cargo en core.Cargo para consultas cross-module', null=True, verbose_name='Cargo (referencia)'),
        ),
    ]
