# Generated by Django 5.0.14 on 2026-04-27 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0009_tiposede_rol_proveedor_interno"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpresoraTermica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_conexion",
                    models.CharField(
                        choices=[
                            ("BLUETOOTH", "Bluetooth"),
                            ("USB", "USB"),
                            ("RED", "Red"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        help_text="MAC para BT, ruta USB, IP:puerto para RED.",
                        max_length=100,
                    ),
                ),
                (
                    "ancho_papel",
                    models.IntegerField(
                        choices=[(58, "58mm"), (80, "80mm")], default=80
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        choices=[
                            ("UTF8", "UTF-8"),
                            ("CP437", "CP437"),
                            ("CP858", "CP858"),
                        ],
                        default="CP858",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si esta seteado, es impresora compartida de la sede.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impresoras",
                        to="configuracion.sedeempresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "usuario_asignado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si esta seteado, es impresora personal del usuario.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impresoras_personales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impresora termica",
                "verbose_name_plural": "Impresoras termicas",
                "ordering": ["nombre"],
            },
        ),
    ]
