# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calidad", "0002_initial"),
        ("configuracion", "0002_initial"),
        ("gestion_clientes", "0001_initial"),
        ("pedidos_facturacion", "0001_initial"),
        ("producto_terminado", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanalRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono para UI",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canal de Recepción",
                "verbose_name_plural": "Canales de Recepción",
                "db_table": "crm_canal_recepcion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoPQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                (
                    "es_inicial",
                    models.BooleanField(
                        default=False,
                        help_text="Estado por defecto para nuevas PQRS",
                        verbose_name="Es estado inicial",
                    ),
                ),
                (
                    "es_final",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que la PQRS ha terminado su ciclo",
                        verbose_name="Es estado final",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de PQRS",
                "verbose_name_plural": "Estados de PQRS",
                "db_table": "crm_estado_pqrs",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="NivelSatisfaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "valor_numerico",
                    models.PositiveIntegerField(
                        help_text="Valor de 1 a 5 para cálculos",
                        verbose_name="Valor numérico",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        help_text="Emoji representativo (ej: 😞, 😐, 😊)",
                        max_length=10,
                        null=True,
                        verbose_name="Emoji",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nivel de Satisfacción",
                "verbose_name_plural": "Niveles de Satisfacción",
                "db_table": "crm_nivel_satisfaccion",
                "ordering": ["valor_numerico", "orden"],
            },
        ),
        migrations.CreateModel(
            name="PreguntaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("pregunta", models.TextField(verbose_name="Pregunta")),
                (
                    "tipo_respuesta",
                    models.CharField(
                        choices=[
                            ("ESCALA", "Escala (1-5)"),
                            ("TEXTO", "Texto libre"),
                            ("OPCION_MULTIPLE", "Opción múltiple"),
                            ("SI_NO", "Sí/No"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de respuesta",
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Para opción múltiple: ["Opción 1", "Opción 2", ...]',
                        verbose_name="Opciones de respuesta",
                    ),
                ),
                (
                    "es_obligatoria",
                    models.BooleanField(default=False, verbose_name="Es obligatoria"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pregunta de Encuesta",
                "verbose_name_plural": "Preguntas de Encuesta",
                "db_table": "crm_pregunta_encuesta",
                "ordering": ["orden", "pregunta"],
            },
        ),
        migrations.CreateModel(
            name="PrioridadPQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "nivel",
                    models.PositiveIntegerField(
                        help_text="1=Más baja, valores mayores=Mayor prioridad",
                        verbose_name="Nivel de prioridad",
                    ),
                ),
                (
                    "tiempo_sla_horas",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Horas máximas para respuesta según prioridad",
                        verbose_name="Tiempo SLA (horas)",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prioridad de PQRS",
                "verbose_name_plural": "Prioridades de PQRS",
                "db_table": "crm_prioridad_pqrs",
                "ordering": ["-nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: QUEJA, RECLAMO, SUGERENCIA)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de PQRS",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "tiempo_respuesta_dias",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Días hábiles para responder según normativa",
                        verbose_name="Tiempo de respuesta (días)",
                    ),
                ),
                (
                    "requiere_investigacion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo requiere investigación formal",
                        verbose_name="Requiere investigación",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="Color para identificación visual",
                        max_length=7,
                        null=True,
                        verbose_name="Color (HEX)",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de PQRS",
                "verbose_name_plural": "Tipos de PQRS",
                "db_table": "crm_tipo_pqrs",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EncuestaSatisfaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Código autogenerado ENC-YYYY-####",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        help_text="Fecha límite para responder",
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ENVIADA", "Enviada"),
                            ("RESPONDIDA", "Respondida"),
                            ("VENCIDA", "Vencida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ENVIADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "nps_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Net Promoter Score: 0-10 (¿Recomendaría nuestro servicio?)",
                        null=True,
                        verbose_name="NPS Score",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios del cliente"
                    ),
                ),
                (
                    "sugerencias",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sugerencias de mejora"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones internas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encuestas_satisfaccion",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encuestas_satisfaccion",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "enviada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviada por",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas_satisfaccion",
                        to="pedidos_facturacion.factura",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas_satisfaccion",
                        to="pedidos_facturacion.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "satisfaccion_general",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encuestas",
                        to="servicio_cliente.nivelsatisfaccion",
                        verbose_name="Satisfacción general",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuesta de Satisfacción",
                "verbose_name_plural": "Encuestas de Satisfacción",
                "db_table": "crm_encuesta_satisfaccion",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="PQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Código autogenerado PQRS-YYYY-####",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "contacto_nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del contacto"
                    ),
                ),
                (
                    "contacto_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono de contacto",
                    ),
                ),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "fecha_radicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de radicación"
                    ),
                ),
                (
                    "fecha_vencimiento_sla",
                    models.DateTimeField(
                        blank=True,
                        help_text="Calculada automáticamente según tipo y prioridad",
                        null=True,
                        verbose_name="Fecha vencimiento SLA",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "dias_respuesta",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Días calendario entre radicación y respuesta",
                        null=True,
                        verbose_name="Días de respuesta",
                    ),
                ),
                (
                    "solucion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la solución implementada",
                        null=True,
                        verbose_name="Solución dada",
                    ),
                ),
                (
                    "requiere_accion_correctiva",
                    models.BooleanField(
                        default=False,
                        help_text="Para quejas graves que requieren mejora continua",
                        verbose_name="Requiere acción correctiva",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones internas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accion_correctiva_generada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_origen",
                        to="calidad.noconformidad",
                        verbose_name="Acción correctiva generada",
                    ),
                ),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "canal_recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pqrs",
                        to="servicio_cliente.canalrecepcion",
                        verbose_name="Canal de recepción",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pqrs_recibidas",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "escalado_a",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario al que se escaló el caso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_escaladas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Escalado a",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pqrs",
                        to="servicio_cliente.estadopqrs",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "pedido_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs",
                        to="pedidos_facturacion.pedido",
                        verbose_name="Pedido relacionado",
                    ),
                ),
                (
                    "producto_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs",
                        to="producto_terminado.productoterminado",
                        verbose_name="Producto relacionado",
                    ),
                ),
                (
                    "satisfaccion_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pqrs_evaluadas",
                        to="servicio_cliente.nivelsatisfaccion",
                        verbose_name="Satisfacción del cliente",
                    ),
                ),
                (
                    "prioridad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pqrs",
                        to="servicio_cliente.prioridadpqrs",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pqrs",
                        to="servicio_cliente.tipopqrs",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "PQRS",
                "verbose_name_plural": "PQRS",
                "db_table": "crm_pqrs",
                "ordering": ["-fecha_radicacion", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaFidelizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del programa"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "puntos_por_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Puntos otorgados por cada $1.000 de compra",
                        max_digits=5,
                        verbose_name="Puntos por $1.000",
                    ),
                ),
                (
                    "valor_punto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Valor en pesos de cada punto para canjes",
                        max_digits=10,
                        verbose_name="Valor del punto ($)",
                    ),
                ),
                (
                    "nivel_bronce_puntos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos para nivel Bronce"
                    ),
                ),
                (
                    "nivel_plata_puntos",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Puntos para nivel Plata"
                    ),
                ),
                (
                    "nivel_oro_puntos",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Puntos para nivel Oro"
                    ),
                ),
                (
                    "beneficios_bronce",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Descuento 5%", "Envío gratis pedidos >$100.000"]',
                        verbose_name="Beneficios nivel Bronce",
                    ),
                ),
                (
                    "beneficios_plata",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Beneficios nivel Plata"
                    ),
                ),
                (
                    "beneficios_oro",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Beneficios nivel Oro"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programas_fidelizacion_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programas_fidelizacion",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Fidelización",
                "verbose_name_plural": "Programas de Fidelización",
                "db_table": "crm_programa_fidelizacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PuntosFidelizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntos_acumulados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos acumulados totales"
                    ),
                ),
                (
                    "puntos_canjeados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos canjeados"
                    ),
                ),
                (
                    "puntos_disponibles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos disponibles"
                    ),
                ),
                (
                    "nivel_actual",
                    models.CharField(
                        choices=[
                            ("BRONCE", "Bronce"),
                            ("PLATA", "Plata"),
                            ("ORO", "Oro"),
                        ],
                        default="BRONCE",
                        max_length=10,
                        verbose_name="Nivel actual",
                    ),
                ),
                (
                    "fecha_nivel",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Fecha en que alcanzó el nivel actual",
                        verbose_name="Fecha de nivel actual",
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_fidelizacion",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_clientes",
                        to="servicio_cliente.programafidelizacion",
                        verbose_name="Programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puntos de Fidelización",
                "verbose_name_plural": "Puntos de Fidelización",
                "db_table": "crm_puntos_fidelizacion",
            },
        ),
        migrations.CreateModel(
            name="MovimientoPuntos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACUMULACION", "Acumulación por compra"),
                            ("CANJE", "Canje de puntos"),
                            ("EXPIRACION", "Expiración"),
                            ("AJUSTE", "Ajuste manual"),
                            ("BONIFICACION", "Bonificación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "puntos",
                    models.IntegerField(
                        help_text="Positivo para acumulación, negativo para canje/expiración",
                        verbose_name="Puntos",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_puntos",
                        to="pedidos_facturacion.factura",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_puntos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "puntos_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="servicio_cliente.puntosfidelizacion",
                        verbose_name="Puntos cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Puntos",
                "verbose_name_plural": "Movimientos de Puntos",
                "db_table": "crm_movimiento_puntos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respuesta_texto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Respuesta (texto)"
                    ),
                ),
                (
                    "respuesta_valor",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Respuesta (valor numérico)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="servicio_cliente.encuestasatisfaccion",
                        verbose_name="Encuesta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="servicio_cliente.preguntaencuesta",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Encuesta",
                "verbose_name_plural": "Respuestas de Encuesta",
                "db_table": "crm_respuesta_encuesta",
            },
        ),
        migrations.CreateModel(
            name="SeguimientoPQRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("COMENTARIO", "Comentario"),
                            ("LLAMADA", "Llamada telefónica"),
                            ("EMAIL", "Correo electrónico"),
                            ("VISITA", "Visita presencial"),
                            ("ESCALAMIENTO", "Escalamiento"),
                            ("ASIGNACION", "Asignación"),
                            ("RESOLUCION", "Resolución"),
                            ("CIERRE", "Cierre"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acción",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "es_visible_cliente",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta acción es visible para el cliente",
                        verbose_name="Visible para el cliente",
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pqrs/seguimientos/%Y/%m/",
                        verbose_name="Archivo adjunto",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pqrs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="servicio_cliente.pqrs",
                        verbose_name="PQRS",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_pqrs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de PQRS",
                "verbose_name_plural": "Seguimientos de PQRS",
                "db_table": "crm_seguimiento_pqrs",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(fields=["codigo"], name="crm_encuest_codigo_bc421b_idx"),
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(
                fields=["empresa"], name="crm_encuest_empresa_47c1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(
                fields=["cliente"], name="crm_encuest_cliente_2aab59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(fields=["estado"], name="crm_encuest_estado_28a76b_idx"),
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(
                fields=["fecha_envio"], name="crm_encuest_fecha_e_37e4d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encuestasatisfaccion",
            index=models.Index(
                fields=["deleted_at"], name="crm_encuest_deleted_aa198f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntosfidelizacion",
            index=models.Index(
                fields=["cliente"], name="crm_puntos__cliente_966e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntosfidelizacion",
            index=models.Index(
                fields=["programa"], name="crm_puntos__program_9e0620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntosfidelizacion",
            index=models.Index(
                fields=["nivel_actual"], name="crm_puntos__nivel_a_e5510f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="puntosfidelizacion",
            unique_together={("cliente", "programa")},
        ),
        migrations.AddIndex(
            model_name="movimientopuntos",
            index=models.Index(
                fields=["puntos_cliente"], name="crm_movimie_puntos__13a693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientopuntos",
            index=models.Index(fields=["tipo"], name="crm_movimie_tipo_632e80_idx"),
        ),
        migrations.AddIndex(
            model_name="movimientopuntos",
            index=models.Index(fields=["fecha"], name="crm_movimie_fecha_cd0c12_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="respuestaencuesta",
            unique_together={("encuesta", "pregunta")},
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(fields=["codigo"], name="crm_pqrs_codigo_07fe2b_idx"),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(fields=["empresa"], name="crm_pqrs_empresa_d698c7_idx"),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(fields=["cliente"], name="crm_pqrs_cliente_c7db89_idx"),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(fields=["tipo"], name="crm_pqrs_tipo_id_5b0301_idx"),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(fields=["estado"], name="crm_pqrs_estado__1c4483_idx"),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(
                fields=["prioridad"], name="crm_pqrs_priorid_377288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(
                fields=["fecha_radicacion"], name="crm_pqrs_fecha_r_39c2e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(
                fields=["asignado_a"], name="crm_pqrs_asignad_4d001a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pqrs",
            index=models.Index(
                fields=["deleted_at"], name="crm_pqrs_deleted_40a6a2_idx"
            ),
        ),
    ]
