# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticoOcupacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_cie10",
                    models.CharField(
                        db_index=True,
                        help_text="Código de diagnóstico según CIE-10",
                        max_length=20,
                        unique=True,
                        verbose_name="Código CIE-10",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=300, verbose_name="Nombre del Diagnóstico"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría principal del CIE-10",
                        max_length=10,
                        verbose_name="Categoría CIE-10",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("OCUPACIONAL", "Ocupacional"),
                            ("COMUN", "Común"),
                            ("AMBOS", "Ambos"),
                        ],
                        default="COMUN",
                        help_text="Clasificación según origen",
                        max_length=20,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "riesgos_relacionados",
                    models.TextField(
                        blank=True,
                        help_text="Riesgos laborales asociados a este diagnóstico",
                        null=True,
                        verbose_name="Riesgos Relacionados",
                    ),
                ),
                (
                    "requiere_vigilancia",
                    models.BooleanField(
                        default=False,
                        help_text="Si amerita inclusión en PVE",
                        verbose_name="Requiere Vigilancia Epidemiológica",
                    ),
                ),
                (
                    "programa_vigilancia_sugerido",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Programa Vigilancia Sugerido",
                    ),
                ),
                (
                    "requiere_reporte_arl",
                    models.BooleanField(
                        default=False,
                        help_text="Si debe reportarse a la ARL",
                        verbose_name="Requiere Reporte a ARL",
                    ),
                ),
                (
                    "requiere_reporte_secretaria",
                    models.BooleanField(
                        default=False,
                        help_text="Si debe reportarse a Secretaría de Salud",
                        verbose_name="Requiere Reporte a Secretaría",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico Ocupacional",
                "verbose_name_plural": "Diagnósticos Ocupacionales",
                "db_table": "medicina_laboral_diagnostico_ocupacional",
                "ordering": ["codigo_cie10"],
                "indexes": [
                    models.Index(
                        fields=["codigo_cie10"], name="medicina_la_codigo__3ecc67_idx"
                    ),
                    models.Index(
                        fields=["origen", "is_active"],
                        name="medicina_la_origen_f9c67f_idx",
                    ),
                    models.Index(
                        fields=["requiere_vigilancia"],
                        name="medicina_la_requier_3a1bca_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadisticaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "anio",
                    models.PositiveIntegerField(
                        help_text="Año del consolidado", verbose_name="Año"
                    ),
                ),
                (
                    "mes",
                    models.PositiveIntegerField(
                        help_text="Mes del consolidado (1-12)", verbose_name="Mes"
                    ),
                ),
                (
                    "total_colaboradores",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de colaboradores activos en el período",
                        verbose_name="Total Colaboradores",
                    ),
                ),
                (
                    "examenes_realizados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exámenes Realizados"
                    ),
                ),
                (
                    "examenes_ingreso",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exámenes de Ingreso"
                    ),
                ),
                (
                    "examenes_periodicos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exámenes Periódicos"
                    ),
                ),
                (
                    "examenes_egreso",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exámenes de Egreso"
                    ),
                ),
                ("aptos", models.PositiveIntegerField(default=0, verbose_name="Aptos")),
                (
                    "aptos_con_restricciones",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Aptos con Restricciones"
                    ),
                ),
                (
                    "no_aptos_temporal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="No Aptos Temporal"
                    ),
                ),
                (
                    "no_aptos_permanente",
                    models.PositiveIntegerField(
                        default=0, verbose_name="No Aptos Permanente"
                    ),
                ),
                (
                    "restricciones_activas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Restricciones Activas"
                    ),
                ),
                (
                    "restricciones_nuevas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Restricciones Nuevas en el Mes"
                    ),
                ),
                (
                    "restricciones_levantadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Restricciones Levantadas"
                    ),
                ),
                (
                    "casos_vigilancia_activos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Casos en Vigilancia Activos"
                    ),
                ),
                (
                    "casos_nuevos",
                    models.PositiveIntegerField(default=0, verbose_name="Casos Nuevos"),
                ),
                (
                    "casos_cerrados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Casos Cerrados"
                    ),
                ),
                (
                    "diagnosticos_ocupacionales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Diagnósticos Ocupacionales"
                    ),
                ),
                (
                    "diagnosticos_comunes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Diagnósticos Comunes"
                    ),
                ),
                (
                    "top_diagnosticos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top 10 diagnósticos del mes (JSON array)",
                        verbose_name="Top Diagnósticos",
                    ),
                ),
                (
                    "porcentaje_aptitud",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de aptos sin restricciones",
                        max_digits=5,
                        verbose_name="% Aptitud",
                    ),
                ),
                (
                    "porcentaje_cobertura_examenes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de cobertura de exámenes médicos",
                        max_digits=5,
                        verbose_name="% Cobertura Exámenes",
                    ),
                ),
                (
                    "costo_total_examenes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Costo Total Exámenes",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "created_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Generado Por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Generación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística Médica",
                "verbose_name_plural": "Estadísticas Médicas",
                "db_table": "medicina_laboral_estadistica",
                "ordering": ["-anio", "-mes"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "anio", "mes"],
                        name="medicina_la_empresa_402831_idx",
                    ),
                    models.Index(
                        fields=["anio", "mes"], name="medicina_la_anio_1be70a_idx"
                    ),
                ],
                "unique_together": {("empresa_id", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="ProgramaVigilancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del programa",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Programa"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OSTEOMUSCULAR", "Desórdenes Osteomusculares"),
                            ("CARDIOVASCULAR", "Riesgo Cardiovascular"),
                            ("AUDITIVO", "Conservación Auditiva"),
                            ("RESPIRATORIO", "Riesgo Respiratorio"),
                            ("VISUAL", "Conservación Visual"),
                            ("PSICOSOCIAL", "Riesgo Psicosocial"),
                            ("DERMATOLOGICO", "Riesgo Dermatológico"),
                            ("BIOLOGICO", "Riesgo Biológico"),
                            ("QUIMICO", "Exposición a Químicos"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Programa",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del programa",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        help_text="Objetivo del programa de vigilancia",
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "alcance",
                    models.TextField(
                        blank=True,
                        help_text="Alcance del programa",
                        null=True,
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "cargos_aplicables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de cargos a los que aplica (JSON array)",
                        verbose_name="Cargos Aplicables",
                    ),
                ),
                (
                    "areas_aplicables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de áreas a las que aplica (JSON array)",
                        verbose_name="Áreas Aplicables",
                    ),
                ),
                (
                    "actividades_vigilancia",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de actividades del programa (JSON array)",
                        verbose_name="Actividades de Vigilancia",
                    ),
                ),
                (
                    "frecuencia_evaluacion_meses",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Cada cuántos meses se evalúa",
                        verbose_name="Frecuencia Evaluación (meses)",
                    ),
                ),
                (
                    "indicadores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Indicadores de seguimiento del programa (JSON array)",
                        verbose_name="Indicadores",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del programa",
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de última revisión",
                        null=True,
                        verbose_name="Fecha Revisión",
                    ),
                ),
                (
                    "proxima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Revisión"
                    ),
                ),
                (
                    "responsable_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del usuario responsable del programa",
                        null=True,
                        verbose_name="ID Responsable",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("EN_REVISION", "En Revisión"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "archivo_programa",
                    models.FileField(
                        blank=True,
                        help_text="Documento del programa de vigilancia",
                        null=True,
                        upload_to="medicina_laboral/programas/%Y/",
                        verbose_name="Archivo del Programa",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "created_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Creado Por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Vigilancia Epidemiológica",
                "verbose_name_plural": "Programas de Vigilancia Epidemiológica",
                "db_table": "medicina_laboral_programa_vigilancia",
                "ordering": ["tipo", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "tipo"],
                        name="medicina_la_empresa_8c8e10_idx",
                    ),
                    models.Index(
                        fields=["codigo"], name="medicina_la_codigo_23c37d_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="medicina_la_estado_e5246c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TipoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo de examen",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de examen",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Examen de Ingreso"),
                            ("PERIODICO", "Examen Periódico"),
                            ("EGRESO", "Examen de Egreso"),
                            ("POST_INCAPACIDAD", "Post-Incapacidad"),
                            ("RETIRO", "Examen de Retiro"),
                            ("CAMBIO_OCUPACION", "Cambio de Ocupación"),
                        ],
                        help_text="Clasificación del examen",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del examen",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("UNICO", "Único (ingreso/egreso)"),
                            ("ANUAL", "Anual"),
                            ("BIENAL", "Bienal (cada 2 años)"),
                            ("TRIENAL", "Trienal (cada 3 años)"),
                            ("PERSONALIZADO", "Personalizado"),
                        ],
                        default="UNICO",
                        help_text="Frecuencia de realización del examen",
                        max_length=20,
                        verbose_name="Periodicidad",
                    ),
                ),
                (
                    "meses_periodicidad",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de meses para periodicidad personalizada",
                        null=True,
                        verbose_name="Meses de Periodicidad",
                    ),
                ),
                (
                    "incluye_clinico",
                    models.BooleanField(
                        default=True,
                        help_text="Si incluye evaluación clínica general",
                        verbose_name="Incluye Examen Clínico",
                    ),
                ),
                (
                    "incluye_laboratorio",
                    models.BooleanField(
                        default=False,
                        help_text="Si incluye exámenes de laboratorio",
                        verbose_name="Incluye Laboratorio",
                    ),
                ),
                (
                    "incluye_paraclinicos",
                    models.BooleanField(
                        default=False,
                        help_text="Si incluye estudios paraclínicos (RX, ECG, etc.)",
                        verbose_name="Incluye Paraclínicos",
                    ),
                ),
                (
                    "incluye_audiometria",
                    models.BooleanField(
                        default=False,
                        help_text="Si incluye evaluación audiométrica",
                        verbose_name="Incluye Audiometría",
                    ),
                ),
                (
                    "incluye_visiometria",
                    models.BooleanField(
                        default=False,
                        help_text="Si incluye evaluación de agudeza visual",
                        verbose_name="Incluye Visiometría",
                    ),
                ),
                (
                    "incluye_espirometria",
                    models.BooleanField(
                        default=False,
                        help_text="Si incluye prueba de función pulmonar",
                        verbose_name="Incluye Espirometría",
                    ),
                ),
                (
                    "enfasis_osteomuscular",
                    models.BooleanField(
                        default=False,
                        help_text="Evaluación especial de sistema osteomuscular",
                        verbose_name="Énfasis Osteomuscular",
                    ),
                ),
                (
                    "enfasis_cardiovascular",
                    models.BooleanField(
                        default=False,
                        help_text="Evaluación especial de sistema cardiovascular",
                        verbose_name="Énfasis Cardiovascular",
                    ),
                ),
                (
                    "enfasis_respiratorio",
                    models.BooleanField(
                        default=False,
                        help_text="Evaluación especial de sistema respiratorio",
                        verbose_name="Énfasis Respiratorio",
                    ),
                ),
                (
                    "enfasis_neurologico",
                    models.BooleanField(
                        default=False,
                        help_text="Evaluación especial de sistema neurológico",
                        verbose_name="Énfasis Neurológico",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre el tipo de examen",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si el tipo de examen está activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Examen",
                "verbose_name_plural": "Tipos de Exámenes",
                "db_table": "medicina_laboral_tipo_examen",
                "ordering": ["tipo", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="medicina_la_codigo_a8d0c6_idx"
                    ),
                    models.Index(
                        fields=["tipo", "is_active"], name="medicina_la_tipo_51fb53_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamenMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "numero_examen",
                    models.CharField(
                        db_index=True,
                        help_text="Número único del examen",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Examen",
                    ),
                ),
                (
                    "colaborador_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID del colaborador evaluado",
                        verbose_name="ID Colaborador",
                    ),
                ),
                (
                    "cargo_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del cargo del colaborador al momento del examen",
                        null=True,
                        verbose_name="ID Cargo",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateField(
                        help_text="Fecha programada para el examen",
                        verbose_name="Fecha Programada",
                    ),
                ),
                (
                    "fecha_realizado",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se realizó el examen",
                        null=True,
                        verbose_name="Fecha Realizado",
                    ),
                ),
                (
                    "entidad_prestadora",
                    models.CharField(
                        blank=True,
                        help_text="IPS o entidad que realizó el examen",
                        max_length=200,
                        null=True,
                        verbose_name="Entidad Prestadora",
                    ),
                ),
                (
                    "medico_evaluador",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del médico que realizó la evaluación",
                        max_length=200,
                        null=True,
                        verbose_name="Médico Evaluador",
                    ),
                ),
                (
                    "licencia_medica",
                    models.CharField(
                        blank=True,
                        help_text="Número de licencia del médico evaluador",
                        max_length=100,
                        null=True,
                        verbose_name="Licencia Médica",
                    ),
                ),
                (
                    "concepto_aptitud",
                    models.CharField(
                        choices=[
                            ("APTO", "Apto"),
                            ("APTO_CON_RESTRICCIONES", "Apto con Restricciones"),
                            ("NO_APTO_TEMPORAL", "No Apto Temporal"),
                            ("NO_APTO_PERMANENTE", "No Apto Permanente"),
                            ("PENDIENTE", "Pendiente"),
                        ],
                        default="PENDIENTE",
                        help_text="Concepto médico sobre aptitud laboral",
                        max_length=30,
                        verbose_name="Concepto de Aptitud",
                    ),
                ),
                (
                    "hallazgos_relevantes",
                    models.TextField(
                        blank=True,
                        help_text="Hallazgos médicos relevantes",
                        null=True,
                        verbose_name="Hallazgos Relevantes",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones médicas",
                        null=True,
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "diagnosticos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de diagnósticos CIE-10 (JSON array de {codigo, nombre})",
                        verbose_name="Diagnósticos",
                    ),
                ),
                (
                    "requiere_restricciones",
                    models.BooleanField(
                        default=False,
                        help_text="Si el examen generó restricciones médicas",
                        verbose_name="Requiere Restricciones",
                    ),
                ),
                (
                    "restricciones_temporales",
                    models.TextField(
                        blank=True,
                        help_text="Restricciones temporales indicadas",
                        null=True,
                        verbose_name="Restricciones Temporales",
                    ),
                ),
                (
                    "restricciones_permanentes",
                    models.TextField(
                        blank=True,
                        help_text="Restricciones permanentes indicadas",
                        null=True,
                        verbose_name="Restricciones Permanentes",
                    ),
                ),
                (
                    "requiere_seguimiento",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere seguimiento médico",
                        verbose_name="Requiere Seguimiento",
                    ),
                ),
                (
                    "tipo_seguimiento",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de seguimiento requerido",
                        max_length=200,
                        null=True,
                        verbose_name="Tipo de Seguimiento",
                    ),
                ),
                (
                    "fecha_proximo_control",
                    models.DateField(
                        blank=True,
                        help_text="Fecha del próximo control médico",
                        null=True,
                        verbose_name="Fecha Próximo Control",
                    ),
                ),
                (
                    "archivo_resultado",
                    models.FileField(
                        blank=True,
                        help_text="PDF del resultado del examen",
                        null=True,
                        upload_to="medicina_laboral/examenes/%Y/%m/",
                        verbose_name="Archivo Resultado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PROGRAMADO",
                        help_text="Estado del examen",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "costo_examen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo del examen médico",
                        max_digits=12,
                        null=True,
                        verbose_name="Costo del Examen",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "created_by_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del usuario que creó el registro",
                        null=True,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "tipo_examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examenes",
                        to="medicina_laboral.tipoexamen",
                        verbose_name="Tipo de Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Médico",
                "verbose_name_plural": "Exámenes Médicos",
                "db_table": "medicina_laboral_examen_medico",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="CasoVigilancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "numero_caso",
                    models.CharField(
                        db_index=True,
                        help_text="Número único del caso",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Caso",
                    ),
                ),
                (
                    "colaborador_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID del colaborador en seguimiento",
                        verbose_name="ID Colaborador",
                    ),
                ),
                (
                    "cargo_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID Cargo"
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(
                        help_text="Fecha de apertura del caso",
                        verbose_name="Fecha Apertura",
                    ),
                ),
                (
                    "descripcion_caso",
                    models.TextField(
                        help_text="Descripción detallada del caso",
                        verbose_name="Descripción del Caso",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MODERADA", "Moderada"),
                            ("SEVERA", "Severa"),
                            ("CRITICA", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "diagnosticos_cie10",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de diagnósticos relacionados (JSON array)",
                        verbose_name="Diagnósticos CIE-10",
                    ),
                ),
                (
                    "factores_riesgo_identificados",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Factores de Riesgo Identificados",
                    ),
                ),
                (
                    "exposicion_laboral",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la exposición laboral relacionada",
                        null=True,
                        verbose_name="Exposición Laboral",
                    ),
                ),
                (
                    "plan_intervencion",
                    models.TextField(
                        blank=True,
                        help_text="Plan de intervención y control",
                        null=True,
                        verbose_name="Plan de Intervención",
                    ),
                ),
                (
                    "acciones_implementadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de acciones implementadas (JSON array)",
                        verbose_name="Acciones Implementadas",
                    ),
                ),
                (
                    "seguimientos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Registro de seguimientos (JSON array de {fecha, descripcion, responsable})",
                        verbose_name="Seguimientos",
                    ),
                ),
                (
                    "fecha_ultimo_seguimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Último Seguimiento"
                    ),
                ),
                (
                    "fecha_proximo_seguimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Próximo Seguimiento"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Cierre"
                    ),
                ),
                (
                    "motivo_cierre",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de Cierre"
                    ),
                ),
                (
                    "resultado_final",
                    models.TextField(
                        blank=True,
                        help_text="Resultado y conclusiones del caso",
                        null=True,
                        verbose_name="Resultado Final",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("EN_SEGUIMIENTO", "En Seguimiento"),
                            ("CONTROLADO", "Controlado"),
                            ("CERRADO", "Cerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medicina_laboral/casos/%Y/%m/",
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "created_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Creado Por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos",
                        to="medicina_laboral.programavigilancia",
                        verbose_name="Programa de Vigilancia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso en Vigilancia",
                "verbose_name_plural": "Casos en Vigilancia",
                "db_table": "medicina_laboral_caso_vigilancia",
                "ordering": ["-fecha_apertura"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "colaborador_id"],
                        name="medicina_la_empresa_32b10c_idx",
                    ),
                    models.Index(
                        fields=["numero_caso"], name="medicina_la_numero__0bd0e9_idx"
                    ),
                    models.Index(
                        fields=["programa", "estado"],
                        name="medicina_la_program_146631_idx",
                    ),
                    models.Index(
                        fields=["severidad", "estado"],
                        name="medicina_la_severid_85efac_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RestriccionMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "codigo_restriccion",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la restricción",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "colaborador_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID del colaborador",
                        verbose_name="ID Colaborador",
                    ),
                ),
                (
                    "cargo_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del cargo actual del colaborador",
                        null=True,
                        verbose_name="ID Cargo",
                    ),
                ),
                (
                    "tipo_restriccion",
                    models.CharField(
                        choices=[
                            ("TEMPORAL", "Temporal"),
                            ("PERMANENTE", "Permanente"),
                            ("CONDICIONAL", "Condicional"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Restricción",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("CARGA", "Manipulación de Cargas"),
                            ("POSTURA", "Posturas"),
                            ("MOVIMIENTO", "Movimientos Repetitivos"),
                            ("ALTURA", "Trabajo en Alturas"),
                            ("ESPACIOS_CONFINADOS", "Espacios Confinados"),
                            ("QUIMICOS", "Exposición a Químicos"),
                            ("RUIDO", "Exposición a Ruido"),
                            ("TEMPERATURA", "Temperaturas Extremas"),
                            ("JORNADA", "Jornada Laboral"),
                            ("OTRAS", "Otras"),
                        ],
                        max_length=30,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la restricción",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "actividades_restringidas",
                    models.TextField(
                        help_text="Detalle de actividades que no puede realizar",
                        verbose_name="Actividades Restringidas",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha de inicio de la restricción",
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de fin (solo para restricciones temporales)",
                        null=True,
                        verbose_name="Fecha Fin",
                    ),
                ),
                (
                    "medico_ordena",
                    models.CharField(
                        help_text="Nombre del médico que ordenó la restricción",
                        max_length=200,
                        verbose_name="Médico que Ordena",
                    ),
                ),
                (
                    "licencia_medica",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Licencia Médica",
                    ),
                ),
                (
                    "requiere_evaluacion_periodica",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere evaluación médica periódica",
                        verbose_name="Requiere Evaluación Periódica",
                    ),
                ),
                (
                    "frecuencia_evaluacion_meses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cada cuántos meses debe evaluarse",
                        null=True,
                        verbose_name="Frecuencia Evaluación (meses)",
                    ),
                ),
                (
                    "proxima_evaluacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Evaluación"
                    ),
                ),
                (
                    "ajuste_realizado",
                    models.BooleanField(
                        default=False,
                        help_text="Si se realizó ajuste en el puesto de trabajo",
                        verbose_name="Ajuste Realizado",
                    ),
                ),
                (
                    "descripcion_ajuste",
                    models.TextField(
                        blank=True,
                        help_text="Detalle del ajuste realizado",
                        null=True,
                        verbose_name="Descripción del Ajuste",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("VENCIDA", "Vencida"),
                            ("LEVANTADA", "Levantada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_levantamiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se levantó la restricción",
                        null=True,
                        verbose_name="Fecha Levantamiento",
                    ),
                ),
                (
                    "motivo_levantamiento",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo Levantamiento"
                    ),
                ),
                (
                    "archivo_soporte",
                    models.FileField(
                        blank=True,
                        help_text="Documento médico de soporte",
                        null=True,
                        upload_to="medicina_laboral/restricciones/%Y/%m/",
                        verbose_name="Archivo Soporte",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "created_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Creado Por"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "examen_medico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Examen médico que originó la restricción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restricciones",
                        to="medicina_laboral.examenmedico",
                        verbose_name="Examen Médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restricción Médica",
                "verbose_name_plural": "Restricciones Médicas",
                "db_table": "medicina_laboral_restriccion_medica",
                "ordering": ["-fecha_inicio"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "colaborador_id"],
                        name="medicina_la_empresa_0d6722_idx",
                    ),
                    models.Index(
                        fields=["codigo_restriccion"],
                        name="medicina_la_codigo__f5c4e9_idx",
                    ),
                    models.Index(
                        fields=["estado", "fecha_fin"],
                        name="medicina_la_estado_6f14c1_idx",
                    ),
                    models.Index(
                        fields=["tipo_restriccion", "categoria"],
                        name="medicina_la_tipo_re_dc25d1_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="examenmedico",
            index=models.Index(
                fields=["empresa_id", "colaborador_id"],
                name="medicina_la_empresa_b2fca0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examenmedico",
            index=models.Index(
                fields=["numero_examen"], name="medicina_la_numero__558355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examenmedico",
            index=models.Index(
                fields=["estado", "fecha_programada"],
                name="medicina_la_estado_ff7b46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examenmedico",
            index=models.Index(
                fields=["concepto_aptitud"], name="medicina_la_concept_ef766d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examenmedico",
            index=models.Index(
                fields=["fecha_realizado"], name="medicina_la_fecha_r_907cad_idx"
            ),
        ),
    ]
