# Generated by Django 5.0.14 on 2026-02-25 14:22
# Modified: data-safe FK→IntegerField via SeparateDatabaseAndState

from django.db import migrations, models


def _drop_fk_sql(table, column):
    """SQL to drop FK constraints and allow NULL on a column (per-schema safe)."""
    return [f"""
DO $$
DECLARE _con TEXT;
BEGIN
    FOR _con IN
        SELECT con.conname FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
        WHERE nsp.nspname = current_schema()
          AND rel.relname = '{table}'
          AND att.attname = '{column}'
          AND con.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', '{table}', _con);
    END LOOP;
    BEGIN
        EXECUTE 'ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL';
    EXCEPTION WHEN others THEN
        NULL;
    END;
END $$;"""]


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_proveedor_fk_to_user"),
        (
            "medicina_laboral",
            "0003_rename_ml_caso_emp_col_idx_medicina_la_empresa_32b10c_idx_and_more",
        ),
    ]

    operations = [
        # Step 1: Add new cache CharField fields (genuinely new DB columns)
        migrations.AddField(
            model_name="casovigilancia",
            name="colaborador_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: nombre completo del colaborador",
                max_length=200,
                verbose_name="Nombre Colaborador",
            ),
        ),
        migrations.AddField(
            model_name="examenmedico",
            name="colaborador_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: nombre completo del colaborador",
                max_length=200,
                verbose_name="Nombre Colaborador",
            ),
        ),
        migrations.AddField(
            model_name="restriccionmedica",
            name="colaborador_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: nombre completo del colaborador",
                max_length=200,
                verbose_name="Nombre Colaborador",
            ),
        ),
        # Step 2: Data-safe FK→IntegerField swap
        # DB column name stays the same (colaborador_id), only FK constraint is dropped
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="casovigilancia",
                    name="medicina_la_empresa_32b10c_idx",
                ),
                migrations.RemoveIndex(
                    model_name="examenmedico",
                    name="medicina_la_empresa_b2fca0_idx",
                ),
                migrations.RemoveIndex(
                    model_name="restriccionmedica",
                    name="medicina_la_empresa_0d6722_idx",
                ),
                migrations.RemoveField(
                    model_name="casovigilancia",
                    name="colaborador",
                ),
                migrations.RemoveField(
                    model_name="examenmedico",
                    name="colaborador",
                ),
                migrations.RemoveField(
                    model_name="restriccionmedica",
                    name="colaborador",
                ),
                migrations.AddField(
                    model_name="casovigilancia",
                    name="colaborador_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del colaborador en seguimiento (talent_hub.Colaborador)",
                        null=True,
                        verbose_name="ID Colaborador",
                    ),
                ),
                migrations.AddField(
                    model_name="examenmedico",
                    name="colaborador_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del colaborador evaluado (talent_hub.Colaborador)",
                        null=True,
                        verbose_name="ID Colaborador",
                    ),
                ),
                migrations.AddField(
                    model_name="restriccionmedica",
                    name="colaborador_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del colaborador con restricción (talent_hub.Colaborador)",
                        null=True,
                        verbose_name="ID Colaborador",
                    ),
                ),
                migrations.AddIndex(
                    model_name="casovigilancia",
                    index=models.Index(
                        fields=["empresa_id", "colaborador_id"],
                        name="medicina_la_empresa_32b10c_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="examenmedico",
                    index=models.Index(
                        fields=["empresa_id", "colaborador_id"],
                        name="medicina_la_empresa_b2fca0_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="restriccionmedica",
                    index=models.Index(
                        fields=["empresa_id", "colaborador_id"],
                        name="medicina_la_empresa_0d6722_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        _drop_fk_sql("medicina_laboral_casovigilancia", "colaborador_id")
                        + _drop_fk_sql("medicina_laboral_examenmedico", "colaborador_id")
                        + _drop_fk_sql("medicina_laboral_restriccionmedica", "colaborador_id")
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
