# Generated by Django 5.0.9 — Sprint Consecutivos Transversal
# Allows blank codigo for auto-generation via auto_generate_codigo()

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_induccion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduloinduccion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del módulo (ej: IND-001)",
                max_length=20,
                verbose_name="Código del Módulo",
            ),
        ),
    ]
