# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("colaboradores", "0001_initial"),
        ("config_indicadores", "0001_initial"),
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_medicion",
                    models.DateField(
                        help_text="Fecha en que se realizó la medición",
                        verbose_name="Fecha de Medición",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Identificador del período (ej: 2025-01, 2025-Q1, 2025)",
                        max_length=20,
                        verbose_name="Período",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor real medido del indicador",
                        max_digits=15,
                        verbose_name="Valor Medido",
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Meta que se esperaba alcanzar en este período",
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Meta del Período",
                    ),
                ),
                (
                    "semaforo",
                    models.CharField(
                        choices=[
                            ("verde", "Verde - Óptimo"),
                            ("amarillo", "Amarillo - Alerta"),
                            ("rojo", "Rojo - Crítico"),
                        ],
                        help_text="Color del semáforo según umbrales configurados",
                        max_length=10,
                        verbose_name="Color Semáforo",
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de cumplimiento vs meta",
                        max_digits=6,
                        null=True,
                        verbose_name="% Cumplimiento",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios sobre el valor medido",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Cuándo se registró el valor en el sistema",
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "datos_origen",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos crudos usados para calcular el valor (JSON)",
                        verbose_name="Datos de Origen",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="config_indicadores.catalogokpi",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores_kpi_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de KPI",
                "verbose_name_plural": "Valores de KPIs",
                "db_table": "analytics_valor_kpi",
                "ordering": ["kpi", "-fecha_medicion"],
            },
        ),
        migrations.CreateModel(
            name="AccionPorKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("accion_correctiva", "Acción Correctiva"),
                            ("plan_mejora", "Plan de Mejora"),
                            ("seguimiento", "Seguimiento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acción",
                    ),
                ),
                (
                    "accion_correctiva_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="ID de acción correctiva del módulo HSEQ (si aplica)",
                        null=True,
                        verbose_name="ID Acción Correctiva HSEQ",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción de la acción a tomar",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "fecha_compromiso",
                    models.DateField(
                        help_text="Fecha límite para completar la acción",
                        verbose_name="Fecha Compromiso",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True,
                        help_text="Cuándo se completó o canceló la acción",
                        null=True,
                        verbose_name="Fecha de Cierre",
                    ),
                ),
                (
                    "efectividad",
                    models.TextField(
                        blank=True,
                        help_text="Evaluación de la efectividad de la acción",
                        verbose_name="Efectividad",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Colaborador responsable de ejecutar la acción",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones_kpi",
                        to="colaboradores.colaborador",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "valor_kpi",
                    models.ForeignKey(
                        help_text="Valor de KPI que generó esta acción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones",
                        to="indicadores_area.valorkpi",
                        verbose_name="Valor KPI",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción por KPI",
                "verbose_name_plural": "Acciones por KPIs",
                "db_table": "analytics_accion_kpi",
                "ordering": ["fecha_compromiso", "estado"],
            },
        ),
        migrations.CreateModel(
            name="AlertaKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("umbral_rojo", "KPI en Umbral Rojo"),
                            ("tendencia_negativa", "Tendencia Negativa Detectada"),
                            ("sin_medicion", "Sin Medición en Período"),
                            ("meta_no_cumplida", "Meta No Cumplida"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Alerta",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Descripción de la alerta", verbose_name="Mensaje"
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "esta_leida",
                    models.BooleanField(default=False, verbose_name="¿Leída?"),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="config_indicadores.catalogokpi",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "leida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_kpi_leidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leída por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de KPI",
                "verbose_name_plural": "Alertas de KPIs",
                "db_table": "analytics_alerta_kpi",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "esta_leida"],
                        name="analytics_a_empresa_9ab4e8_idx",
                    ),
                    models.Index(
                        fields=["kpi", "fecha_generacion"],
                        name="analytics_a_kpi_id_af9e1b_idx",
                    ),
                    models.Index(
                        fields=["tipo_alerta"], name="analytics_a_tipo_al_a95d22_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="valorkpi",
            index=models.Index(
                fields=["empresa", "kpi"], name="analytics_v_empresa_9999d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valorkpi",
            index=models.Index(
                fields=["fecha_medicion"], name="analytics_v_fecha_m_bfc7ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valorkpi",
            index=models.Index(
                fields=["semaforo"], name="analytics_v_semafor_92c6eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valorkpi",
            index=models.Index(
                fields=["empresa", "kpi", "fecha_medicion"],
                name="analytics_v_empresa_3e3525_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="valorkpi",
            unique_together={("empresa", "kpi", "periodo")},
        ),
        migrations.AddIndex(
            model_name="accionporkpi",
            index=models.Index(
                fields=["empresa", "estado"], name="analytics_a_empresa_30608c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accionporkpi",
            index=models.Index(
                fields=["responsable", "estado"], name="analytics_a_respons_9b7989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accionporkpi",
            index=models.Index(
                fields=["fecha_compromiso"], name="analytics_a_fecha_c_86044b_idx"
            ),
        ),
    ]
