# Generated by Django 5.0.14 on 2026-02-25 14:22
# Modified: data-safe FK→IntegerField via SeparateDatabaseAndState

from django.conf import settings
from django.db import migrations, models


def _drop_fk_sql(table, column):
    """SQL to drop FK constraints and allow NULL on a column (per-schema safe)."""
    return [f"""
DO $$
DECLARE _con TEXT;
BEGIN
    FOR _con IN
        SELECT con.conname FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
        WHERE nsp.nspname = current_schema()
          AND rel.relname = '{table}'
          AND att.attname = '{column}'
          AND con.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', '{table}', _con);
    END LOOP;
    BEGIN
        EXECUTE 'ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL';
    EXCEPTION WHEN others THEN
        NULL;
    END;
END $$;"""]


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_legacy_fields"),
        ("indicadores_area", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add new cache CharField field (genuinely new DB column)
        migrations.AddField(
            model_name="accionporkpi",
            name="responsable_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: nombre completo del responsable",
                max_length=200,
                verbose_name="Nombre Responsable",
            ),
        ),
        # Step 2: Data-safe FK→IntegerField swap
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="accionporkpi",
                    name="analytics_a_respons_9b7989_idx",
                ),
                migrations.RemoveField(
                    model_name="accionporkpi",
                    name="responsable",
                ),
                migrations.AddField(
                    model_name="accionporkpi",
                    name="responsable_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del colaborador responsable (talent_hub.Colaborador)",
                        null=True,
                        verbose_name="ID Responsable",
                    ),
                ),
                migrations.AddIndex(
                    model_name="accionporkpi",
                    index=models.Index(
                        fields=["responsable_id", "estado"],
                        name="analytics_a_respons_9b7989_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=_drop_fk_sql("indicadores_area_accionporkpi", "responsable_id"),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
