# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accioncorrectiva",
            name="responsable",
            field=models.ForeignKey(
                help_text="Responsable de ejecutar la acción",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acciones_correctivas_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accioncorrectiva",
            name="verificador",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable de verificar la eficacia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_verificar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noconformidad",
            name="detectado_por",
            field=models.ForeignKey(
                help_text="Usuario que detectó la NC",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="no_conformidades_detectadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noconformidad",
            name="responsable_analisis",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable de analizar la causa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nc_analisis_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noconformidad",
            name="responsable_cierre",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable de verificar y cerrar",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nc_cierres_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accioncorrectiva",
            name="no_conformidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones_correctivas",
                to="calidad.noconformidad",
            ),
        ),
        migrations.AddField(
            model_name="salidanoconforme",
            name="detectado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salidas_nc_detectadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salidanoconforme",
            name="no_conformidad",
            field=models.ForeignKey(
                blank=True,
                help_text="NC generada por esta salida no conforme",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salidas_no_conformes",
                to="calidad.noconformidad",
            ),
        ),
        migrations.AddField(
            model_name="salidanoconforme",
            name="responsable_disposicion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salidas_nc_disponer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salidanoconforme",
            name="responsable_evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salidas_nc_evaluar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudcambio",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_aprobados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudcambio",
            name="responsable_implementacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_implementar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudcambio",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudcambio",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cambios_solicitados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="controlcambio",
            name="solicitud_cambio",
            field=models.OneToOneField(
                help_text="Solicitud de cambio asociada",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control",
                to="calidad.solicitudcambio",
            ),
        ),
        migrations.AddIndex(
            model_name="noconformidad",
            index=models.Index(
                fields=["empresa_id", "estado"], name="calidad_no__empresa_06df0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noconformidad",
            index=models.Index(
                fields=["empresa_id", "origen"], name="calidad_no__empresa_9b5e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noconformidad",
            index=models.Index(fields=["codigo"], name="calidad_no__codigo_ec9180_idx"),
        ),
        migrations.AddIndex(
            model_name="noconformidad",
            index=models.Index(
                fields=["fecha_deteccion"], name="calidad_no__fecha_d_00a933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accioncorrectiva",
            index=models.Index(
                fields=["empresa_id", "estado"], name="calidad_acc_empresa_60402b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accioncorrectiva",
            index=models.Index(
                fields=["no_conformidad", "estado"],
                name="calidad_acc_no_conf_4ff940_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accioncorrectiva",
            index=models.Index(
                fields=["responsable", "estado"], name="calidad_acc_respons_66eee2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salidanoconforme",
            index=models.Index(
                fields=["empresa_id", "estado"], name="calidad_sal_empresa_0a3e4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salidanoconforme",
            index=models.Index(
                fields=["empresa_id", "bloqueada"],
                name="calidad_sal_empresa_36d6bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salidanoconforme",
            index=models.Index(
                fields=["lote_numero"], name="calidad_sal_lote_nu_9e5283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudcambio",
            index=models.Index(
                fields=["empresa_id", "estado"], name="calidad_sol_empresa_24d3c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudcambio",
            index=models.Index(
                fields=["empresa_id", "prioridad"],
                name="calidad_sol_empresa_ffc812_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudcambio",
            index=models.Index(
                fields=["solicitante", "estado"], name="calidad_sol_solicit_e63c99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlcambio",
            index=models.Index(
                fields=["empresa_id", "fecha_fin_implementacion"],
                name="calidad_con_empresa_71835e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlcambio",
            index=models.Index(
                fields=["solicitud_cambio"], name="calidad_con_solicit_d4c82d_idx"
            ),
        ),
    ]
