# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GestorAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20)),
                (
                    "tipo_gestor",
                    models.CharField(
                        choices=[
                            ("RESIDUOS", "Gestor de Residuos"),
                            ("VERTIMIENTOS", "Gestor de Vertimientos"),
                            ("EMISIONES", "Gestor de Emisiones"),
                            ("RECICLAJE", "Empresa de Reciclaje"),
                            ("APROVECHAMIENTO", "Aprovechamiento"),
                            ("DISPOSICION_FINAL", "Disposición Final"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "numero_licencia_ambiental",
                    models.CharField(blank=True, max_length=100),
                ),
                ("fecha_expedicion_licencia", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento_licencia", models.DateField(blank=True, null=True)),
                (
                    "autoridad_ambiental_emisor",
                    models.CharField(
                        blank=True,
                        help_text="CAR, CRA, Corporación Autónoma Regional, etc.",
                        max_length=255,
                    ),
                ),
                ("contacto_nombre", models.CharField(blank=True, max_length=255)),
                ("contacto_telefono", models.CharField(blank=True, max_length=50)),
                ("contacto_email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "certificaciones",
                    models.TextField(blank=True, help_text="ISO 14001, BASC, etc."),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gestor Ambiental",
                "verbose_name_plural": "Gestores Ambientales",
                "db_table": "gestion_ambiental_gestor",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="CalculoHuellaCarbono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("periodo_year", models.IntegerField(help_text="Año del cálculo")),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "metodologia",
                    models.CharField(
                        default="GHG Protocol",
                        help_text="GHG Protocol, ISO 14064, PAS 2050, etc.",
                        max_length=100,
                    ),
                ),
                ("version_metodologia", models.CharField(blank=True, max_length=50)),
                (
                    "alcance1_combustion_estacionaria",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de combustión en instalaciones fijas",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance1_combustion_movil",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de vehículos propios",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance1_emisiones_proceso",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de procesos industriales",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance1_emisiones_fugitivas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de fugas de refrigerantes, gases, etc.",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance1_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total Alcance 1 (tCO2e)",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance2_electricidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de consumo eléctrico",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance2_vapor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de vapor comprado",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance2_calefaccion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de calefacción/refrigeración",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance2_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total Alcance 2 (tCO2e)",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_viajes_negocio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de viajes de negocios",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_desplazamiento_empleados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de desplazamiento de empleados",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_transporte_upstream",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de transporte de materias primas",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_transporte_downstream",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de distribución de productos",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_residuos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de gestión de residuos",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_otros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e de otras fuentes indirectas",
                        max_digits=12,
                    ),
                ),
                (
                    "alcance3_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total Alcance 3 (tCO2e)",
                        max_digits=12,
                    ),
                ),
                (
                    "huella_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Huella total (tCO2e)",
                        max_digits=12,
                    ),
                ),
                (
                    "numero_empleados",
                    models.IntegerField(
                        blank=True,
                        help_text="Número de empleados en el período",
                        null=True,
                    ),
                ),
                (
                    "huella_per_capita",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="tCO2e por empleado",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "detalle_calculos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detalle de factores de emisión y fuentes utilizadas",
                    ),
                ),
                ("verificado", models.BooleanField(default=False)),
                ("verificador_externo", models.CharField(blank=True, max_length=255)),
                ("fecha_verificacion", models.DateField(blank=True, null=True)),
                (
                    "compensaciones_co2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="tCO2e compensadas (bonos, proyectos)",
                        max_digits=12,
                    ),
                ),
                (
                    "huella_neta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Huella neta después de compensaciones",
                        max_digits=12,
                    ),
                ),
                (
                    "informe_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gestion_ambiental/huella_carbono/",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Cálculo de Huella de Carbono",
                "verbose_name_plural": "Cálculos de Huella de Carbono",
                "db_table": "gestion_ambiental_huella_carbono",
                "ordering": ["-periodo_year"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "periodo_year"],
                        name="gestion_amb_empresa_ef148e_idx",
                    )
                ],
                "unique_together": {("empresa_id", "periodo_year")},
            },
        ),
        migrations.CreateModel(
            name="FuenteEmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_fuente",
                    models.CharField(
                        choices=[
                            ("FIJA_PUNTUAL", "Fija Puntual"),
                            ("FIJA_DISPERSA", "Fija Dispersa"),
                            ("MOVIL", "Móvil"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area_ubicacion", models.CharField(blank=True, max_length=255)),
                ("coordenadas", models.CharField(blank=True, max_length=100)),
                (
                    "altura_chimenea_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altura de la chimenea en metros (para fuentes fijas)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "proceso_generador",
                    models.CharField(
                        blank=True,
                        help_text="Proceso productivo que genera las emisiones",
                        max_length=255,
                    ),
                ),
                (
                    "tipo_combustible",
                    models.CharField(
                        blank=True,
                        help_text="Gas natural, ACPM, carbón, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "sistema_control",
                    models.TextField(
                        blank=True, help_text="Filtros, ciclones, lavadores, etc."
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fuente de Emisión",
                "verbose_name_plural": "Fuentes de Emisión",
                "db_table": "gestion_ambiental_fuente_emision",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "tipo_fuente"],
                        name="gestion_amb_empresa_ab9539_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TipoRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("AGUA", "Agua"),
                            ("ENERGIA", "Energía"),
                            ("GAS", "Gas"),
                            ("COMBUSTIBLE", "Combustible"),
                            ("MATERIAL", "Material"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        help_text="m³, kWh, galones, kg, etc.", max_length=20
                    ),
                ),
                (
                    "factor_emision_co2_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Factor de emisión de CO2 por unidad de recurso",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo promedio por unidad",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Recurso",
                "verbose_name_plural": "Tipos de Recursos",
                "db_table": "gestion_ambiental_tipo_recurso",
                "ordering": ["categoria", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["categoria", "activo"],
                        name="gestion_amb_categor_bb0e5e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TipoResiduo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno del tipo de residuo",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "clase",
                    models.CharField(
                        choices=[
                            ("PELIGROSO", "Peligroso"),
                            ("NO_PELIGROSO", "No Peligroso"),
                            ("RECICLABLE", "Reciclable"),
                            ("ORGANICO", "Orgánico"),
                            (
                                "RAEE",
                                "RAEE (Residuos de Aparatos Eléctricos y Electrónicos)",
                            ),
                            ("RCD", "RCD (Residuos de Construcción y Demolición)"),
                            ("ESPECIAL", "Especial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "codigo_cer",
                    models.CharField(
                        blank=True,
                        help_text="Código según Lista Europea de Residuos (LER/CER)",
                        max_length=10,
                    ),
                ),
                ("es_corrosivo", models.BooleanField(default=False)),
                ("es_reactivo", models.BooleanField(default=False)),
                ("es_explosivo", models.BooleanField(default=False)),
                ("es_toxico", models.BooleanField(default=False)),
                ("es_inflamable", models.BooleanField(default=False)),
                ("es_infeccioso", models.BooleanField(default=False)),
                ("requiere_tratamiento_especial", models.BooleanField(default=False)),
                ("instrucciones_manejo", models.TextField(blank=True)),
                (
                    "color_contenedor",
                    models.CharField(
                        blank=True,
                        help_text="Color del contenedor según normativa (ej: verde, gris, rojo)",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Residuo",
                "verbose_name_plural": "Tipos de Residuos",
                "db_table": "gestion_ambiental_tipo_residuo",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["clase", "activo"], name="gestion_amb_clase_8a479d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroResiduo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("GENERACION", "Generación"),
                            ("DISPOSICION", "Disposición"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("APROVECHAMIENTO", "Aprovechamiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogramos"),
                            ("TON", "Toneladas"),
                            ("LT", "Litros"),
                            ("M3", "Metros cúbicos"),
                            ("UND", "Unidades"),
                        ],
                        default="KG",
                        max_length=10,
                    ),
                ),
                (
                    "area_generadora",
                    models.CharField(
                        blank=True,
                        help_text="Área o proceso que genera el residuo",
                        max_length=255,
                    ),
                ),
                (
                    "tratamiento_aplicado",
                    models.CharField(
                        blank=True,
                        help_text="Reciclaje, incineración, relleno sanitario, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "numero_manifiesto",
                    models.CharField(
                        blank=True,
                        help_text="Número de manifiesto de carga o certificado de disposición",
                        max_length=100,
                    ),
                ),
                (
                    "certificado_disposicion",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gestion_ambiental/certificados_residuos/",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("registrado_por", models.CharField(blank=True, max_length=255)),
                (
                    "gestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residuos_gestionados",
                        to="gestion_ambiental.gestorambiental",
                    ),
                ),
                (
                    "tipo_residuo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="gestion_ambiental.tiporesiduo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Residuo",
                "verbose_name_plural": "Registros de Residuos",
                "db_table": "gestion_ambiental_registro_residuo",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="gestorambiental",
            name="tipos_residuos",
            field=models.ManyToManyField(
                blank=True, related_name="gestores", to="gestion_ambiental.tiporesiduo"
            ),
        ),
        migrations.CreateModel(
            name="Vertimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("fecha_vertimiento", models.DateField()),
                ("hora_vertimiento", models.TimeField(blank=True, null=True)),
                (
                    "tipo_vertimiento",
                    models.CharField(
                        choices=[
                            ("DOMESTICO", "Doméstico"),
                            ("INDUSTRIAL", "Industrial"),
                            ("PLUVIAL", "Pluvial"),
                            ("MIXTO", "Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "punto_vertimiento",
                    models.CharField(
                        help_text="Identificación del punto de descarga", max_length=255
                    ),
                ),
                ("coordenadas", models.CharField(blank=True, max_length=100)),
                (
                    "cuerpo_receptor",
                    models.CharField(
                        choices=[
                            ("ALCANTARILLADO", "Alcantarillado Municipal"),
                            ("RIO", "Río"),
                            ("QUEBRADA", "Quebrada"),
                            ("LAGO", "Lago"),
                            ("MAR", "Mar"),
                            ("SUELO", "Suelo"),
                            ("PTAR", "Planta de Tratamiento"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "nombre_cuerpo_receptor",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "caudal_m3_dia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Caudal en metros cúbicos por día",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("14")),
                        ],
                    ),
                ),
                (
                    "temperatura_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dbo5_mg_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Demanda Bioquímica de Oxígeno (mg/L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dqo_mg_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Demanda Química de Oxígeno (mg/L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sst_mg_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sólidos Suspendidos Totales (mg/L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "grasas_aceites_mg_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grasas y Aceites (mg/L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "parametros_adicionales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Otros parámetros: metales pesados, nitrógeno, fósforo, etc.",
                    ),
                ),
                (
                    "cumple_normativa",
                    models.BooleanField(
                        blank=True,
                        help_text="¿Cumple con los límites máximos permisibles?",
                        null=True,
                    ),
                ),
                (
                    "norma_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Resolución 631/2015, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "tratamiento_previo",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del tratamiento antes de la descarga",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("laboratorio_analisis", models.CharField(blank=True, max_length=255)),
                (
                    "numero_informe_laboratorio",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "archivo_informe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gestion_ambiental/informes_vertimientos/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertimiento",
                "verbose_name_plural": "Vertimientos",
                "db_table": "gestion_ambiental_vertimiento",
                "ordering": ["-fecha_vertimiento"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "fecha_vertimiento"],
                        name="gestion_amb_empresa_e49977_idx",
                    ),
                    models.Index(
                        fields=["tipo_vertimiento", "cumple_normativa"],
                        name="gestion_amb_tipo_ve_1c65f8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroEmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("fecha_medicion", models.DateField()),
                ("hora_medicion", models.TimeField(blank=True, null=True)),
                (
                    "material_particulado_mg_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Material Particulado (mg/m³)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "pm10_ug_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="PM10 (µg/m³)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "pm25_ug_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="PM2.5 (µg/m³)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "so2_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dióxido de Azufre (ppm)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "nox_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Óxidos de Nitrógeno (ppm)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "co_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monóxido de Carbono (ppm)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "co2_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dióxido de Carbono (ppm)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cov_mg_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Compuestos Orgánicos Volátiles (mg/m³)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "temperatura_gases_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "velocidad_gases_m_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Velocidad de los gases (m/s)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "humedad_relativa_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "cumple_normativa",
                    models.BooleanField(
                        blank=True,
                        help_text="¿Cumple con los límites máximos permisibles?",
                        null=True,
                    ),
                ),
                (
                    "norma_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Resolución 909/2008, etc.",
                        max_length=255,
                    ),
                ),
                ("laboratorio_medicion", models.CharField(blank=True, max_length=255)),
                ("numero_informe", models.CharField(blank=True, max_length=100)),
                (
                    "archivo_informe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gestion_ambiental/informes_emisiones/",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "fuente_emision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="gestion_ambiental.fuenteemision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Emisión",
                "verbose_name_plural": "Registros de Emisiones",
                "db_table": "gestion_ambiental_registro_emision",
                "ordering": ["-fecha_medicion"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "fecha_medicion"],
                        name="gestion_amb_empresa_9439f0_idx",
                    ),
                    models.Index(
                        fields=["fuente_emision", "cumple_normativa"],
                        name="gestion_amb_fuente__9fb7c4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CertificadoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("numero_certificado", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            ("DISPOSICION_RESIDUOS", "Disposición de Residuos"),
                            ("APROVECHAMIENTO", "Aprovechamiento"),
                            ("RECICLAJE", "Reciclaje"),
                            ("VERTIMIENTO", "Vertimiento"),
                            ("EMISION", "Emisión"),
                            ("CUMPLIMIENTO_AMBIENTAL", "Cumplimiento Ambiental"),
                            ("COMPENSACION_CO2", "Compensación CO2"),
                            ("ISO_14001", "ISO 14001"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "emisor",
                    models.CharField(
                        help_text="Gestor ambiental, autoridad ambiental, certificadora",
                        max_length=255,
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "descripcion",
                    models.TextField(help_text="Descripción del certificado"),
                ),
                (
                    "cantidad_certificada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unidad_medida", models.CharField(blank=True, max_length=20)),
                (
                    "archivo_certificado",
                    models.FileField(
                        help_text="PDF del certificado",
                        upload_to="gestion_ambiental/certificados/",
                    ),
                ),
                ("vigente", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "gestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_emitidos",
                        to="gestion_ambiental.gestorambiental",
                    ),
                ),
                (
                    "residuos_relacionados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="certificados",
                        to="gestion_ambiental.registroresiduo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Ambiental",
                "verbose_name_plural": "Certificados Ambientales",
                "db_table": "gestion_ambiental_certificado",
                "ordering": ["-fecha_emision"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "tipo_certificado"],
                        name="gestion_amb_empresa_6d5dc0_idx",
                    ),
                    models.Index(
                        fields=["fecha_vencimiento", "vigente"],
                        name="gestion_amb_fecha_v_bab434_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsumoRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.IntegerField(help_text="ID de la empresa (multi-tenant)"),
                ),
                ("periodo_year", models.IntegerField(help_text="Año del consumo")),
                (
                    "periodo_month",
                    models.IntegerField(
                        help_text="Mes del consumo (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "cantidad_consumida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fuente_suministro",
                    models.CharField(
                        blank=True,
                        help_text="Acueducto, empresa de energía, proveedor, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "area_consumidora",
                    models.CharField(
                        blank=True,
                        help_text="Producción, administrativa, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "lectura_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "lectura_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("numero_factura", models.CharField(blank=True, max_length=100)),
                (
                    "emision_co2_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Emisiones de CO2 equivalente generadas por este consumo",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "tipo_recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumos",
                        to="gestion_ambiental.tiporecurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de Recurso",
                "verbose_name_plural": "Consumos de Recursos",
                "db_table": "gestion_ambiental_consumo_recurso",
                "ordering": ["-periodo_year", "-periodo_month"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "periodo_year", "periodo_month"],
                        name="gestion_amb_empresa_ac420a_idx",
                    ),
                    models.Index(
                        fields=["tipo_recurso", "periodo_year"],
                        name="gestion_amb_tipo_re_8ec9aa_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "empresa_id",
                        "periodo_year",
                        "periodo_month",
                        "tipo_recurso",
                        "area_consumidora",
                    )
                },
            },
        ),
        migrations.AddIndex(
            model_name="registroresiduo",
            index=models.Index(
                fields=["empresa_id", "fecha"], name="gestion_amb_empresa_6eda46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroresiduo",
            index=models.Index(
                fields=["tipo_residuo", "tipo_movimiento"],
                name="gestion_amb_tipo_re_dd3dfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gestorambiental",
            index=models.Index(
                fields=["empresa_id", "tipo_gestor"],
                name="gestion_amb_empresa_479b05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gestorambiental",
            index=models.Index(fields=["nit"], name="gestion_amb_nit_07351b_idx"),
        ),
    ]
