# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogos", "0001_initial"),
        ("configuracion", "0001_initial"),
        ("gestion_proveedores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoEjecucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("es_estado_inicial", models.BooleanField(default=False)),
                ("es_estado_final", models.BooleanField(default=False)),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Ejecución",
                "verbose_name_plural": "Estados de Ejecución",
                "db_table": "supply_chain_estado_ejecucion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoLiquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_edicion",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la liquidación puede editarse en este estado",
                        verbose_name="Permite edición",
                    ),
                ),
                ("es_estado_inicial", models.BooleanField(default=False)),
                ("es_estado_final", models.BooleanField(default=False)),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Liquidación",
                "verbose_name_plural": "Estados de Liquidación",
                "db_table": "supply_chain_estado_liquidacion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoProgramacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "es_estado_inicial",
                    models.BooleanField(
                        default=False,
                        help_text="Estado por defecto para nuevas programaciones",
                        verbose_name="Es estado inicial",
                    ),
                ),
                (
                    "es_estado_final",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que la programación ha terminado (completada o cancelada)",
                        verbose_name="Es estado final",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Programación",
                "verbose_name_plural": "Estados de Programación",
                "db_table": "supply_chain_estado_programacion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: RECOLECCION, COMPRA_DIRECTA)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de operación",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_vehiculo",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo de operación requiere asignación de vehículo",
                        verbose_name="Requiere vehículo",
                    ),
                ),
                (
                    "requiere_conductor",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo de operación requiere asignación de conductor",
                        verbose_name="Requiere conductor",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="Color para identificación visual en calendario (ej: #FF5733)",
                        max_length=7,
                        null=True,
                        verbose_name="Color (HEX)",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Operación",
                "verbose_name_plural": "Tipos de Operación",
                "db_table": "supply_chain_tipo_operacion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Programacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Código autogenerado de la programación",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        help_text="Fecha y hora programada para la operación",
                        verbose_name="Fecha programada",
                    ),
                ),
                (
                    "fecha_ejecucion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora real de ejecución",
                        null=True,
                        verbose_name="Fecha de ejecución",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones generales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Configuración de empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones_abastecimiento",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones",
                        to="programacion_abastecimiento.estadoprogramacion",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones",
                        to="gestion_proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Usuario responsable de la programación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        help_text="Sede donde se realiza la operación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones_abastecimiento",
                        to="configuracion.sedeempresa",
                        verbose_name="Sede",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones",
                        to="programacion_abastecimiento.tipooperacion",
                        verbose_name="Tipo de operación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación de Abastecimiento",
                "verbose_name_plural": "Programaciones de Abastecimiento",
                "db_table": "supply_chain_programacion",
                "ordering": ["-fecha_programada", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ejecucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(verbose_name="Fecha y hora de inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de finalización",
                    ),
                ),
                (
                    "kilometraje_inicial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilometraje del vehículo al inicio de la operación",
                        max_digits=10,
                        null=True,
                        verbose_name="Kilometraje inicial",
                    ),
                ),
                (
                    "kilometraje_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilometraje del vehículo al final de la operación",
                        max_digits=10,
                        null=True,
                        verbose_name="Kilometraje final",
                    ),
                ),
                (
                    "cantidad_recolectada",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad de materia prima obtenida",
                        max_digits=12,
                        verbose_name="Cantidad recolectada/comprada",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones de ejecución"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ejecutado_por",
                    models.ForeignKey(
                        help_text="Usuario que realizó/registró la ejecución",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ejecuciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ejecutado por",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ejecuciones",
                        to="catalogos.unidadmedida",
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ejecuciones",
                        to="programacion_abastecimiento.estadoejecucion",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "programacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ejecucion",
                        to="programacion_abastecimiento.programacion",
                        verbose_name="Programación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Programación",
                "verbose_name_plural": "Ejecuciones de Programaciones",
                "db_table": "supply_chain_ejecucion",
                "ordering": ["-fecha_inicio", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehiculo",
                    models.CharField(
                        blank=True,
                        help_text="Identificación del vehículo asignado (placa, código interno, etc.)",
                        max_length=100,
                        null=True,
                        verbose_name="Vehículo",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observaciones de asignación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asignado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario asignado como conductor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_conductor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Conductor",
                    ),
                ),
                (
                    "programacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignacion_recurso",
                        to="programacion_abastecimiento.programacion",
                        verbose_name="Programación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Recurso",
                "verbose_name_plural": "Asignaciones de Recursos",
                "db_table": "supply_chain_asignacion_recurso",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_liquidacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de liquidación"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio por unidad de medida acordado con el proveedor",
                        max_digits=12,
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad a liquidar (debe coincidir con cantidad recolectada)",
                        max_digits=12,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente: precio_unitario * cantidad",
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "deducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto total de deducciones aplicadas",
                        max_digits=12,
                        verbose_name="Deducciones",
                    ),
                ),
                (
                    "detalle_deducciones",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de las deducciones aplicadas",
                        null=True,
                        verbose_name="Detalle de deducciones",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente: subtotal - deducciones",
                        max_digits=14,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "genera_cxp",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si esta liquidación genera una cuenta por pagar en contabilidad",
                        verbose_name="Genera cuenta por pagar",
                    ),
                ),
                (
                    "numero_cxp",
                    models.CharField(
                        blank=True,
                        help_text="Número de la cuenta por pagar generada (si aplica)",
                        max_length=50,
                        null=True,
                        verbose_name="Número de CxP",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observaciones de liquidación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que aprobó la liquidación",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "ejecucion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidacion",
                        to="programacion_abastecimiento.ejecucion",
                        verbose_name="Ejecución",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="programacion_abastecimiento.estadoliquidacion",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "liquidado_por",
                    models.ForeignKey(
                        help_text="Usuario que realizó la liquidación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Liquidado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación",
                "verbose_name_plural": "Liquidaciones",
                "db_table": "supply_chain_liquidacion",
                "ordering": ["-fecha_liquidacion", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ejecucion"], name="supply_chai_ejecuci_6e360b_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="supply_chai_estado__8e99b7_idx"
                    ),
                    models.Index(
                        fields=["fecha_liquidacion"],
                        name="supply_chai_fecha_l_c5dbe7_idx",
                    ),
                    models.Index(
                        fields=["liquidado_por"], name="supply_chai_liquida_75534d_idx"
                    ),
                    models.Index(
                        fields=["aprobado_por"], name="supply_chai_aprobad_d12e7c_idx"
                    ),
                    models.Index(
                        fields=["genera_cxp"], name="supply_chai_genera__a5a2e9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ejecucion",
            index=models.Index(
                fields=["programacion"], name="supply_chai_program_529eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ejecucion",
            index=models.Index(
                fields=["fecha_inicio"], name="supply_chai_fecha_i_7fa315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ejecucion",
            index=models.Index(
                fields=["estado"], name="supply_chai_estado__ac4937_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ejecucion",
            index=models.Index(
                fields=["ejecutado_por"], name="supply_chai_ejecuta_e27321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(fields=["codigo"], name="supply_chai_codigo_b10bc6_idx"),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["fecha_programada"], name="supply_chai_fecha_p_83684f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["estado"], name="supply_chai_estado__3313e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["proveedor"], name="supply_chai_proveed_0467b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(fields=["sede"], name="supply_chai_sede_id_67f087_idx"),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["deleted_at"], name="supply_chai_deleted_26cf7d_idx"
            ),
        ),
    ]
