# Generated by Django 5.0.14 on 2026-02-15 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0003_alter_empresaconfig_options_and_more"),
        ("core", "0009_reorder_talent_hub_sidebar"),
        ("gestion_documental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="es_politica_integral",
            field=models.BooleanField(
                default=False,
                help_text="Indica si es una política integral del sistema de gestión",
                verbose_name="Es Política Integral",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="fecha_expiracion",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que el documento expira",
                null=True,
                verbose_name="Fecha de Expiración",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="motivo_cambio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Razón del cambio de versión",
                verbose_name="Motivo del Cambio",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="norma_iso",
            field=models.ForeignKey(
                blank=True,
                help_text="Norma/Sistema de gestión asociado (solo para políticas)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="configuracion.normaiso",
                verbose_name="Norma ISO",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="responsable_cargo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo responsable del documento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_responsable",
                to="core.cargo",
                verbose_name="Cargo Responsable",
            ),
        ),
    ]
