# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documental", "0002_add_policy_fields_to_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantilladocumento",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Código de Plantilla"
            ),
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código único del tipo (ej: PR, IN, FT, MA)",
                max_length=20,
                verbose_name="Código",
            ),
        ),
    ]
