# Generated by Django 5.0.14 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documental", "0003_fases_4_6_7_8"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="fecha_sellado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Sellado"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="hash_pdf_sellado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 del PDF sellado",
                max_length=64,
                verbose_name="Hash PDF Sellado",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="pdf_sellado",
            field=models.FileField(
                blank=True,
                help_text="PDF sellado con X.509 y firmas visuales",
                null=True,
                upload_to="documentos/sellados/%Y/%m/",
                verbose_name="PDF Sellado",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="sellado_estado",
            field=models.CharField(
                choices=[
                    ("NO_APLICA", "No Aplica"),
                    ("PENDIENTE", "Pendiente"),
                    ("PROCESANDO", "Procesando"),
                    ("COMPLETADO", "Completado"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="NO_APLICA",
                max_length=20,
                verbose_name="Estado Sellado",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="sellado_metadatos",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"certificado_serial": "...", "algoritmo": "sha256WithRSA", "error": "..."}',
                verbose_name="Metadatos Sellado",
            ),
        ),
    ]
