# Generated by Django 5.0.14 on 2026-04-04 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documental", "0013_add_categoria_to_tipo_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aceptaciondocumental",
            name="invalidada",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True cuando se publica una nueva versión del documento. Las aceptaciones invalidadas no aparecen en mis-pendientes.",
                verbose_name="Invalidada",
            ),
        ),
        migrations.AddIndex(
            model_name="aceptaciondocumental",
            index=models.Index(
                fields=["invalidada"], name="documental__invalid_694c20_idx"
            ),
        ),
    ]
