# Generated by Django 5.0.14 on 2026-04-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documental", "0014_add_invalidada_aceptacion"),
        ("organizacion", "0002_add_is_system_to_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="proceso",
            field=models.ForeignKey(
                blank=True,
                help_text="Proceso SGI principal. Define el código: TIPO-PROCESO-NNN (ej: PR-SST-001)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_gd",
                to="organizacion.area",
                verbose_name="Proceso",
            ),
        ),
    ]
