# Generated by Django 5.0.14 on 2026-04-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documental", "0015_add_proceso_fk"),
        ("organizacion", "0002_add_is_system_to_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaRetencionDocumental",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serie_documental", models.CharField(blank=True, default="", help_text="Serie según normativa AGN (ej: Actas de COPASST, Historias Laborales)", max_length=200, verbose_name="Serie Documental")),
                ("tiempo_gestion_anos", models.PositiveIntegerField(default=2, help_text="Años en archivo de gestión (acceso frecuente)", verbose_name="Archivo de Gestión (años)")),
                ("tiempo_central_anos", models.PositiveIntegerField(default=5, help_text="Años en archivo central (consulta esporádica)", verbose_name="Archivo Central (años)")),
                ("disposicion_final", models.CharField(choices=[("ELIMINAR", "Eliminar"), ("CONSERVAR_PERMANENTE", "Conservar permanentemente"), ("SELECCIONAR", "Seleccionar (muestreo)"), ("DIGITALIZAR", "Digitalizar y eliminar físico")], default="ELIMINAR", max_length=30, verbose_name="Disposición Final")),
                ("soporte_legal", models.TextField(blank=True, default="", help_text="Normativa que justifica la retención (ej: Decreto 1072/2015, Ley 594/2000)", verbose_name="Soporte Legal")),
                ("requiere_acta_destruccion", models.BooleanField(default=True, verbose_name="Requiere Acta de Destrucción")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("empresa_id", models.PositiveBigIntegerField(db_index=True, verbose_name="Empresa ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proceso", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trd_reglas", to="organizacion.area", verbose_name="Proceso")),
                ("tipo_documento", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trd_reglas", to="gestion_documental.tipodocumento", verbose_name="Tipo Documental")),
            ],
            options={
                "verbose_name": "Regla de Retención Documental",
                "verbose_name_plural": "Tabla de Retención Documental",
                "db_table": "documental_tabla_retencion",
                "ordering": ["tipo_documento__codigo", "proceso__code"],
                "indexes": [models.Index(fields=["empresa_id", "activo"], name="documental__empresa_93de1e_idx")],
                "unique_together": {("tipo_documento", "proceso", "empresa_id")},
            },
        ),
    ]
