"""
Management command para cargar catálogo inicial de Riesgos Ocupacionales
Basado en GTC 45:2012 - Aplicable a TODAS las industrias

Este catálogo es universal y puede ser usado por cualquier tipo de empresa:
- Manufactura, Servicios, Construcción, Transporte, Salud, etc.

Clasificaciones GTC 45:
1. BIOLÓGICO - Virus, bacterias, hongos, parásitos, fluidos, animales
2. FÍSICO - Ruido, vibración, temperaturas, radiación, iluminación, presión
3. QUÍMICO - Polvos, humos, gases, vapores, líquidos, sólidos
4. PSICOSOCIAL - Gestión organizacional, condiciones de la tarea, jornada, relaciones
5. BIOMECÁNICO - Posturas, movimientos repetitivos, manipulación de cargas
6. CONDICIONES DE SEGURIDAD - Mecánico, eléctrico, locativo, tecnológico, tránsito
7. FENÓMENOS NATURALES - Sismo, inundación, deslizamiento, tormenta

Uso:
    python manage.py seed_riesgos_ocupacionales
"""
from django.core.management.base import BaseCommand
from apps.core.models import RiesgoOcupacional


class Command(BaseCommand):
    help = 'Carga catálogo inicial de Riesgos Ocupacionales GTC 45 (universal para todas las industrias)'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.HTTP_INFO('=' * 70))
        self.stdout.write(self.style.HTTP_INFO('CARGANDO CATÁLOGO DE RIESGOS OCUPACIONALES GTC 45'))
        self.stdout.write(self.style.HTTP_INFO('=' * 70))

        riesgos_data = self.get_riesgos_data()

        created_count = 0
        updated_count = 0

        for riesgo_dict in riesgos_data:
            code = riesgo_dict.pop('code')
            riesgo, created = RiesgoOcupacional.objects.update_or_create(
                code=code,
                defaults=riesgo_dict
            )

            if created:
                created_count += 1
                self.stdout.write(f'  + {code}: {riesgo.name}')
            else:
                updated_count += 1
                self.stdout.write(f'  ~ {code}: {riesgo.name} (actualizado)')

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS('=' * 70))
        self.stdout.write(self.style.SUCCESS(
            f'COMPLETADO: {created_count} creados, {updated_count} actualizados'
        ))
        self.stdout.write(self.style.SUCCESS(f'Total riesgos en catálogo: {RiesgoOcupacional.objects.count()}'))
        self.stdout.write(self.style.SUCCESS('=' * 70))

    def get_riesgos_data(self):
        """
        Catálogo completo de riesgos ocupacionales GTC 45
        Aplicable a TODAS las industrias
        """
        return [
            # =================================================================
            # RIESGOS BIOLÓGICOS (BIO-XXX)
            # =================================================================
            {
                'code': 'BIO-001',
                'name': 'Virus',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a agentes virales que pueden causar enfermedades infecciosas',
                'fuente': 'Contacto con personas infectadas, superficies contaminadas, aerosoles',
                'efectos_posibles': 'Infecciones respiratorias, gastrointestinales, hepatitis, COVID-19, influenza',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Vacunación, higiene de manos, EPP, ventilación, protocolos de bioseguridad',
            },
            {
                'code': 'BIO-002',
                'name': 'Bacterias',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a microorganismos bacterianos patógenos',
                'fuente': 'Alimentos contaminados, agua, suelos, residuos orgánicos, fluidos corporales',
                'efectos_posibles': 'Infecciones dérmicas, gastrointestinales, respiratorias, septicemia',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Higiene personal, desinfección, EPP, manipulación segura de alimentos',
            },
            {
                'code': 'BIO-003',
                'name': 'Hongos',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a hongos y esporas en ambientes húmedos o con materia orgánica',
                'fuente': 'Ambientes húmedos, materiales en descomposición, sistemas de ventilación',
                'efectos_posibles': 'Micosis cutáneas, infecciones respiratorias, alergias, aspergilosis',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Control de humedad, ventilación, limpieza, EPP respiratorio',
            },
            {
                'code': 'BIO-004',
                'name': 'Parásitos',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a organismos parásitos (protozoos, helmintos)',
                'fuente': 'Agua contaminada, alimentos, suelos, contacto con animales',
                'efectos_posibles': 'Parasitosis intestinal, leishmaniasis, toxoplasmosis, malaria',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Agua potable, higiene de alimentos, control de vectores, EPP',
            },
            {
                'code': 'BIO-005',
                'name': 'Ricketsias',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a microorganismos transmitidos por artrópodos',
                'fuente': 'Picaduras de garrapatas, piojos, pulgas',
                'efectos_posibles': 'Fiebre Q, tifus, rickettsiosis',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Control de vectores, ropa protectora, repelentes, inspección corporal',
            },
            {
                'code': 'BIO-006',
                'name': 'Fluidos o excrementos',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Contacto con sangre, orina, heces, secreciones corporales',
                'fuente': 'Atención de personas, limpieza de sanitarios, manejo de residuos',
                'efectos_posibles': 'Hepatitis B y C, VIH, infecciones gastrointestinales',
                'nivel_riesgo': 'II',
                'controles_existentes': 'EPP (guantes, delantal), protocolos de bioseguridad, vacunación',
            },
            {
                'code': 'BIO-007',
                'name': 'Picaduras de insectos',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Exposición a picaduras de mosquitos, abejas, avispas, arañas',
                'fuente': 'Trabajo al aire libre, áreas con vegetación, zonas endémicas',
                'efectos_posibles': 'Dengue, zika, chikungunya, reacciones alérgicas, anafilaxia',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Repelentes, ropa protectora, fumigación, mosquiteros',
            },
            {
                'code': 'BIO-008',
                'name': 'Mordeduras de animales',
                'clasificacion': 'BIOLOGICO',
                'descripcion': 'Riesgo de mordeduras de perros, roedores, serpientes u otros animales',
                'fuente': 'Trabajo en campo, granjas, veterinarias, zonas rurales',
                'efectos_posibles': 'Rabia, leptospirosis, tétanos, envenenamiento, infecciones',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Vacunación antirrábica, botas altas, guantes, capacitación',
            },

            # =================================================================
            # RIESGOS FÍSICOS (FIS-XXX)
            # =================================================================
            {
                'code': 'FIS-001',
                'name': 'Ruido continuo',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición prolongada a ruido constante superior a 80 dB(A)',
                'fuente': 'Maquinaria industrial, motores, compresores, ventiladores',
                'efectos_posibles': 'Hipoacusia neurosensorial, fatiga auditiva, estrés, tinnitus',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Protectores auditivos, encapsulamiento de fuentes, rotación, audiometrías',
            },
            {
                'code': 'FIS-002',
                'name': 'Ruido de impacto o intermitente',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a ruidos súbitos o fluctuantes de alta intensidad',
                'fuente': 'Martillos, prensas, disparos, explosiones controladas',
                'efectos_posibles': 'Trauma acústico, pérdida auditiva súbita, sobresalto',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Doble protección auditiva, señalización, alejamiento',
            },
            {
                'code': 'FIS-003',
                'name': 'Vibración cuerpo entero',
                'clasificacion': 'FISICO',
                'descripcion': 'Vibración transmitida al cuerpo completo desde superficies vibrantes',
                'fuente': 'Vehículos, plataformas vibratorias, maquinaria pesada',
                'efectos_posibles': 'Lesiones de columna vertebral, hernias discales, trastornos digestivos',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Asientos con amortiguación, mantenimiento de equipos, pausas',
            },
            {
                'code': 'FIS-004',
                'name': 'Vibración segmentaria (mano-brazo)',
                'clasificacion': 'FISICO',
                'descripcion': 'Vibración transmitida a extremidades superiores por herramientas',
                'fuente': 'Taladros, pulidoras, motosierras, martillos neumáticos',
                'efectos_posibles': 'Síndrome de Raynaud, síndrome del túnel carpiano, neuropatías',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Guantes antivibración, herramientas con amortiguación, rotación',
            },
            {
                'code': 'FIS-005',
                'name': 'Temperaturas extremas - Calor',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a ambientes con temperaturas elevadas',
                'fuente': 'Hornos, fundiciones, trabajo al aire libre en verano, calderas',
                'efectos_posibles': 'Deshidratación, golpe de calor, calambres, agotamiento, síncope',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Hidratación, pausas en sombra, ventilación, ropa ligera',
            },
            {
                'code': 'FIS-006',
                'name': 'Temperaturas extremas - Frío',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a ambientes con temperaturas bajas',
                'fuente': 'Cuartos fríos, congeladores, trabajo en exteriores en invierno',
                'efectos_posibles': 'Hipotermia, congelación de extremidades, entumecimiento',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ropa térmica, rotación de personal, bebidas calientes, calefacción',
            },
            {
                'code': 'FIS-007',
                'name': 'Radiación ionizante',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a rayos X, gamma, partículas alfa, beta, neutrones',
                'fuente': 'Equipos de rayos X, materiales radiactivos, medicina nuclear',
                'efectos_posibles': 'Síndrome de radiación aguda, cáncer, mutaciones genéticas, quemaduras',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Blindaje, dosimetría, distancia, tiempo de exposición limitado',
            },
            {
                'code': 'FIS-008',
                'name': 'Radiación no ionizante - Ultravioleta',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a radiación UV solar o artificial',
                'fuente': 'Trabajo al aire libre, soldadura, lámparas UV, cabinas de bronceado',
                'efectos_posibles': 'Quemaduras solares, envejecimiento de piel, cáncer de piel, cataratas',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Bloqueador solar, ropa protectora, gafas con filtro UV, sombra',
            },
            {
                'code': 'FIS-009',
                'name': 'Radiación no ionizante - Infrarroja',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a radiación infrarroja de fuentes de calor',
                'fuente': 'Hornos, metales fundidos, lámparas de calor',
                'efectos_posibles': 'Quemaduras, cataratas, daño en córnea',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Pantallas protectoras, gafas IR, distanciamiento',
            },
            {
                'code': 'FIS-010',
                'name': 'Radiación no ionizante - Radiofrecuencia y microondas',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a campos electromagnéticos de radiofrecuencia',
                'fuente': 'Antenas de telecomunicaciones, hornos microondas industriales, radares',
                'efectos_posibles': 'Calentamiento de tejidos, posibles efectos neurológicos',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Distanciamiento, blindaje, señalización, monitoreo de exposición',
            },
            {
                'code': 'FIS-011',
                'name': 'Iluminación deficiente',
                'clasificacion': 'FISICO',
                'descripcion': 'Niveles de luz insuficientes para la tarea visual requerida',
                'fuente': 'Luminarias inadecuadas, áreas de trabajo mal diseñadas, trabajo nocturno',
                'efectos_posibles': 'Fatiga visual, cefalea, errores, accidentes, tensión ocular',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Mejora de iluminación, lámparas de tarea, mantenimiento de luminarias',
            },
            {
                'code': 'FIS-012',
                'name': 'Iluminación en exceso (deslumbramiento)',
                'clasificacion': 'FISICO',
                'descripcion': 'Exposición a luz excesiva o deslumbramiento directo/reflejado',
                'fuente': 'Luz solar directa, superficies reflectantes, luminarias mal ubicadas',
                'efectos_posibles': 'Fatiga visual, cefalea, disminución de agudeza visual temporal',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Persianas, filtros antirreflejo, reubicación de luminarias',
            },
            {
                'code': 'FIS-013',
                'name': 'Presión atmosférica anormal - Alta',
                'clasificacion': 'FISICO',
                'descripcion': 'Trabajo en ambientes con presión superior a la atmosférica',
                'fuente': 'Buceo, cámaras hiperbáricas, túneles bajo agua',
                'efectos_posibles': 'Enfermedad por descompresión, barotrauma, narcosis de nitrógeno',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Tablas de descompresión, equipos certificados, personal capacitado',
            },
            {
                'code': 'FIS-014',
                'name': 'Presión atmosférica anormal - Baja',
                'clasificacion': 'FISICO',
                'descripcion': 'Trabajo en alturas geográficas con menor presión atmosférica',
                'fuente': 'Trabajo en montañas, aviación sin presurización',
                'efectos_posibles': 'Mal de altura, hipoxia, edema pulmonar, edema cerebral',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Aclimatación gradual, oxígeno suplementario, monitoreo médico',
            },

            # =================================================================
            # RIESGOS QUÍMICOS (QUI-XXX)
            # =================================================================
            {
                'code': 'QUI-001',
                'name': 'Polvos orgánicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a partículas de origen vegetal, animal o sintético',
                'fuente': 'Harinas, algodón, madera, granos, pelos de animales',
                'efectos_posibles': 'Asma ocupacional, rinitis, alveolitis alérgica, bisinosis',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ventilación, extracción localizada, EPP respiratorio, humidificación',
            },
            {
                'code': 'QUI-002',
                'name': 'Polvos inorgánicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a partículas minerales o metálicas',
                'fuente': 'Minería, construcción, fundición, cerámica, asbesto',
                'efectos_posibles': 'Silicosis, asbestosis, siderosis, neumoconiosis, cáncer pulmonar',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Control en fuente, ventilación, EPP respiratorio, vigilancia médica',
            },
            {
                'code': 'QUI-003',
                'name': 'Fibras',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a fibras naturales o sintéticas suspendidas',
                'fuente': 'Textiles, aislantes, fibra de vidrio, asbesto',
                'efectos_posibles': 'Irritación respiratoria, mesotelioma (asbesto), dermatitis',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Sustitución de materiales, ventilación, EPP, monitoreo',
            },
            {
                'code': 'QUI-004',
                'name': 'Humos metálicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a partículas metálicas generadas por calentamiento',
                'fuente': 'Soldadura, fundición, corte térmico, galvanizado',
                'efectos_posibles': 'Fiebre de los humos metálicos, intoxicación por plomo/zinc, neumoconiosis',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Extracción localizada, EPP respiratorio, ventilación, monitoreo biológico',
            },
            {
                'code': 'QUI-005',
                'name': 'Humos no metálicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a humos de combustión orgánica o plásticos',
                'fuente': 'Incendios, combustión de plásticos, asfalto, caucho',
                'efectos_posibles': 'Irritación respiratoria, intoxicación por CO, cáncer',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ventilación, EPP respiratorio con filtros apropiados, monitoreo',
            },
            {
                'code': 'QUI-006',
                'name': 'Gases y vapores irritantes',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a sustancias gaseosas que irritan mucosas',
                'fuente': 'Ácidos, amoníaco, cloro, formaldehído, óxidos de nitrógeno',
                'efectos_posibles': 'Irritación ocular y respiratoria, edema pulmonar, bronquitis química',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ventilación, extracción, EPP, duchas de emergencia, monitoreo ambiental',
            },
            {
                'code': 'QUI-007',
                'name': 'Gases y vapores asfixiantes',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a gases que desplazan el oxígeno o interfieren con su uso',
                'fuente': 'Monóxido de carbono, cianuro, nitrógeno, argón, metano',
                'efectos_posibles': 'Asfixia, pérdida de consciencia, muerte, daño neurológico',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Ventilación, detección de gases, EPP con suministro de aire, rescate',
            },
            {
                'code': 'QUI-008',
                'name': 'Gases y vapores anestésicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a sustancias con efecto narcótico o anestésico',
                'fuente': 'Solventes orgánicos, éter, cloroformo, gases anestésicos médicos',
                'efectos_posibles': 'Mareo, somnolencia, pérdida de consciencia, daño hepático/renal',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ventilación, sistemas cerrados, EPP respiratorio, monitoreo',
            },
            {
                'code': 'QUI-009',
                'name': 'Líquidos corrosivos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Contacto con ácidos o bases fuertes en estado líquido',
                'fuente': 'Ácido sulfúrico, clorhídrico, nítrico, sosa cáustica, hidróxidos',
                'efectos_posibles': 'Quemaduras químicas, daño ocular, perforación de tejidos',
                'nivel_riesgo': 'II',
                'controles_existentes': 'EPP (guantes, gafas, delantal), duchas, lavaojos, neutralizantes',
            },
            {
                'code': 'QUI-010',
                'name': 'Líquidos inflamables y combustibles',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Manejo de líquidos con punto de inflamación bajo',
                'fuente': 'Gasolina, alcohol, acetona, thinner, diesel, aceites',
                'efectos_posibles': 'Incendio, explosión, quemaduras, intoxicación',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Almacenamiento seguro, conexión a tierra, extintores, no fumar',
            },
            {
                'code': 'QUI-011',
                'name': 'Solventes orgánicos',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a sustancias utilizadas para disolver otras',
                'fuente': 'Pinturas, pegamentos, desengrasantes, limpiadores industriales',
                'efectos_posibles': 'Dermatitis, daño hepático/renal, neurotoxicidad, cáncer',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Sustitución, ventilación, EPP, monitoreo biológico',
            },
            {
                'code': 'QUI-012',
                'name': 'Plaguicidas y pesticidas',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a sustancias para control de plagas',
                'fuente': 'Agricultura, fumigación, control de vectores, jardinería',
                'efectos_posibles': 'Intoxicación aguda/crónica, daño neurológico, cáncer, dermatitis',
                'nivel_riesgo': 'I',
                'controles_existentes': 'EPP completo, capacitación, respeto de tiempos de reingreso',
            },
            {
                'code': 'QUI-013',
                'name': 'Sustancias cancerígenas',
                'clasificacion': 'QUIMICO',
                'descripcion': 'Exposición a agentes químicos clasificados como carcinógenos',
                'fuente': 'Benceno, asbesto, formaldehído, algunos metales pesados',
                'efectos_posibles': 'Desarrollo de diversos tipos de cáncer',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Sustitución obligatoria, control estricto, vigilancia médica especial',
            },

            # =================================================================
            # RIESGOS PSICOSOCIALES (PSI-XXX)
            # =================================================================
            {
                'code': 'PSI-001',
                'name': 'Gestión organizacional deficiente',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Fallas en el estilo de mando, comunicación, participación y reconocimiento',
                'fuente': 'Liderazgo autoritario, falta de retroalimentación, inequidad',
                'efectos_posibles': 'Estrés laboral, desmotivación, rotación de personal, conflictos',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Capacitación a líderes, canales de comunicación, evaluación de clima',
            },
            {
                'code': 'PSI-002',
                'name': 'Características de la organización del trabajo',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Problemas en la claridad de rol, demandas contradictorias, sobrecarga',
                'fuente': 'Funciones ambiguas, multiplicidad de jefes, metas inalcanzables',
                'efectos_posibles': 'Ansiedad, confusión, bajo desempeño, burnout',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Descripciones de cargo claras, organigrama definido, metas realistas',
            },
            {
                'code': 'PSI-003',
                'name': 'Características del grupo social de trabajo',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Conflictos interpersonales, acoso laboral, falta de cohesión',
                'fuente': 'Equipos disfuncionales, competencia desleal, discriminación',
                'efectos_posibles': 'Depresión, ansiedad, ausentismo, violencia laboral',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Comité de convivencia, protocolos antiacoso, actividades de integración',
            },
            {
                'code': 'PSI-004',
                'name': 'Condiciones de la tarea - Carga mental alta',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Demandas cognitivas excesivas: atención, memoria, toma de decisiones',
                'fuente': 'Trabajo complejo, responsabilidad por otros, presión de tiempo',
                'efectos_posibles': 'Fatiga mental, errores, ansiedad, agotamiento cognitivo',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Distribución de carga, pausas, automatización, capacitación',
            },
            {
                'code': 'PSI-005',
                'name': 'Condiciones de la tarea - Contenido repetitivo o monótono',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Tareas simples, repetitivas, sin variedad ni autonomía',
                'fuente': 'Líneas de producción, trabajo fragmentado, tareas simples',
                'efectos_posibles': 'Aburrimiento, desmotivación, trastornos musculoesqueléticos',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Rotación de tareas, enriquecimiento del trabajo, autonomía',
            },
            {
                'code': 'PSI-006',
                'name': 'Jornada de trabajo extensa',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Jornadas laborales superiores a 8 horas o trabajo frecuente extra',
                'fuente': 'Horas extras habituales, dobles turnos, guardias prolongadas',
                'efectos_posibles': 'Fatiga crónica, trastornos del sueño, accidentes, conflicto familia-trabajo',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Control de horas extra, descansos compensatorios, rotación',
            },
            {
                'code': 'PSI-007',
                'name': 'Trabajo nocturno o por turnos',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Trabajo en horarios nocturnos o rotación de turnos',
                'fuente': 'Operaciones 24 horas, turnos rotativos, guardias nocturnas',
                'efectos_posibles': 'Alteración circadiana, trastornos del sueño, problemas digestivos',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Rotación hacia adelante, descansos adecuados, alimentación saludable',
            },
            {
                'code': 'PSI-008',
                'name': 'Condiciones de inseguridad (violencia)',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Exposición a situaciones de violencia, atracos, orden público',
                'fuente': 'Manejo de dinero, zonas de conflicto, trabajo solitario, atención al público',
                'efectos_posibles': 'Estrés postraumático, ansiedad, lesiones físicas, muerte',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Trabajo en equipo, comunicación, rutas seguras, capacitación',
            },
            {
                'code': 'PSI-009',
                'name': 'Interfaz persona-tarea inadecuada',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Desajuste entre capacidades del trabajador y demandas del puesto',
                'fuente': 'Selección inadecuada, falta de capacitación, sobrecualificación',
                'efectos_posibles': 'Frustración, errores, accidentes, baja productividad',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Selección por competencias, inducción, capacitación continua',
            },
            {
                'code': 'PSI-010',
                'name': 'Acoso laboral (mobbing)',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Conductas persistentes de hostigamiento en el trabajo',
                'fuente': 'Jefes o compañeros con comportamientos abusivos',
                'efectos_posibles': 'Depresión, ansiedad, trastornos psicosomáticos, ideación suicida',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Política antiacoso, comité de convivencia, canales de denuncia',
            },
            {
                'code': 'PSI-011',
                'name': 'Acoso sexual',
                'clasificacion': 'PSICOSOCIAL',
                'descripcion': 'Conductas de naturaleza sexual no consentidas en el trabajo',
                'fuente': 'Comportamientos inapropiados de jefes o compañeros',
                'efectos_posibles': 'Trauma, ansiedad, depresión, abandono del trabajo',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Política de tolerancia cero, capacitación, canales de denuncia seguros',
            },

            # =================================================================
            # RIESGOS BIOMECÁNICOS (BIO-M-XXX)
            # =================================================================
            {
                'code': 'BIO-M-001',
                'name': 'Postura prolongada de pie',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Mantenimiento de posición de pie por períodos extensos',
                'fuente': 'Líneas de producción, atención al público, vigilancia',
                'efectos_posibles': 'Várices, dolor lumbar, fatiga de miembros inferiores, edema',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Tapetes antifatiga, bancos de descanso, pausas, calzado adecuado',
            },
            {
                'code': 'BIO-M-002',
                'name': 'Postura prolongada sentado',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Mantenimiento de posición sedente por períodos extensos',
                'fuente': 'Trabajo de oficina, conducción, control de procesos',
                'efectos_posibles': 'Dolor lumbar, problemas circulatorios, síndrome metabólico',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Sillas ergonómicas, pausas activas, ejercicio, ajuste de puesto',
            },
            {
                'code': 'BIO-M-003',
                'name': 'Posturas forzadas (antigravitacionales)',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Adopción de posturas incómodas contra la gravedad',
                'fuente': 'Trabajo en alturas, bajo vehículos, espacios reducidos, techos',
                'efectos_posibles': 'Lesiones musculoesqueléticas, fatiga, dolor articular',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Rediseño del puesto, herramientas extensibles, rotación',
            },
            {
                'code': 'BIO-M-004',
                'name': 'Movimientos repetitivos de miembros superiores',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Movimientos cíclicos de brazos, manos y dedos',
                'fuente': 'Digitación, ensamble, empaque, corte, costura',
                'efectos_posibles': 'Síndrome del túnel carpiano, tendinitis, epicondilitis, tenosinovitis',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Pausas activas, herramientas ergonómicas, rotación, automatización',
            },
            {
                'code': 'BIO-M-005',
                'name': 'Manipulación manual de cargas - Levantamiento',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Levantamiento manual de objetos pesados o voluminosos',
                'fuente': 'Almacenes, construcción, mudanzas, manufactura',
                'efectos_posibles': 'Lumbago, hernias discales, lesiones de hombro, fatiga',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Ayudas mecánicas, técnica de levantamiento, límites de peso, trabajo en equipo',
            },
            {
                'code': 'BIO-M-006',
                'name': 'Manipulación manual de cargas - Empuje/Arrastre',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Movimiento de objetos empujando o halando',
                'fuente': 'Carros de transporte, estibas, camillas, carritos',
                'efectos_posibles': 'Lesiones de espalda, hombro, fatiga muscular',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Carros con ruedas adecuadas, pisos nivelados, límites de fuerza',
            },
            {
                'code': 'BIO-M-007',
                'name': 'Aplicación de fuerza',
                'clasificacion': 'BIOMECANICO',
                'descripcion': 'Uso de fuerza significativa con manos o cuerpo',
                'fuente': 'Apretar, torcer, prensar, tirar, empujar con fuerza',
                'efectos_posibles': 'Lesiones musculotendinosas, fatiga, dolor articular',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Herramientas mecánicas, diseño ergonómico, rotación',
            },

            # =================================================================
            # RIESGOS DE CONDICIONES DE SEGURIDAD (SEG-XXX)
            # =================================================================
            {
                'code': 'SEG-001',
                'name': 'Mecánico - Elementos de máquinas',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Contacto con partes móviles de maquinaria (engranajes, poleas, ejes)',
                'fuente': 'Máquinas sin guardas, mantenimiento, limpieza de equipos',
                'efectos_posibles': 'Atrapamiento, amputación, aplastamiento, laceraciones',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Guardas de seguridad, LOTO, sensores, capacitación',
            },
            {
                'code': 'SEG-002',
                'name': 'Mecánico - Herramientas manuales',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Uso de herramientas manuales (martillos, destornilladores, cuchillos)',
                'fuente': 'Herramientas en mal estado, uso inadecuado',
                'efectos_posibles': 'Golpes, cortes, contusiones, heridas',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Herramientas en buen estado, capacitación, EPP, almacenamiento',
            },
            {
                'code': 'SEG-003',
                'name': 'Mecánico - Herramientas eléctricas/neumáticas',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Uso de taladros, pulidoras, sierras, pistolas neumáticas',
                'fuente': 'Operación de herramientas motorizadas',
                'efectos_posibles': 'Cortes, proyección de partículas, electrocución, atrapamiento',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Guardas, EPP, mantenimiento, capacitación, inspección',
            },
            {
                'code': 'SEG-004',
                'name': 'Mecánico - Manipulación de materiales',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Manejo de materiales cortantes, punzantes o pesados',
                'fuente': 'Láminas metálicas, vidrios, maderas, materiales pesados',
                'efectos_posibles': 'Cortes, laceraciones, aplastamiento, golpes',
                'nivel_riesgo': 'II',
                'controles_existentes': 'EPP (guantes, calzado), técnicas de manipulación, ayudas mecánicas',
            },
            {
                'code': 'SEG-005',
                'name': 'Mecánico - Proyección de partículas',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de impacto por partículas proyectadas',
                'fuente': 'Esmerilado, corte, pulido, torneado, soldadura',
                'efectos_posibles': 'Lesiones oculares, heridas en rostro/cuerpo',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Gafas de seguridad, caretas, pantallas protectoras',
            },
            {
                'code': 'SEG-006',
                'name': 'Eléctrico - Contacto directo',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Contacto con partes eléctricas energizadas',
                'fuente': 'Cables expuestos, tableros abiertos, equipos sin aislamiento',
                'efectos_posibles': 'Electrocución, quemaduras, paro cardíaco, muerte',
                'nivel_riesgo': 'I',
                'controles_existentes': 'LOTO, EPP dieléctrico, señalización, mantenimiento preventivo',
            },
            {
                'code': 'SEG-007',
                'name': 'Eléctrico - Contacto indirecto',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Contacto con partes metálicas energizadas por falla de aislamiento',
                'fuente': 'Equipos con falla de aislamiento, falta de puesta a tierra',
                'efectos_posibles': 'Electrocución, quemaduras, paro cardíaco',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Puesta a tierra, interruptores diferenciales, mantenimiento',
            },
            {
                'code': 'SEG-008',
                'name': 'Eléctrico - Electricidad estática',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Acumulación de cargas electrostáticas',
                'fuente': 'Fricción de materiales, atmósferas secas, plásticos',
                'efectos_posibles': 'Descargas, ignición de atmósferas explosivas, daño a equipos',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Conexión a tierra, humidificación, ropa antiestática',
            },
            {
                'code': 'SEG-009',
                'name': 'Locativo - Superficies de trabajo irregulares',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Pisos desnivelados, resbaladizos, con obstáculos',
                'fuente': 'Pisos en mal estado, derrames, objetos en pasillos',
                'efectos_posibles': 'Caídas al mismo nivel, torceduras, fracturas, contusiones',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Mantenimiento de pisos, orden y aseo, señalización, calzado antideslizante',
            },
            {
                'code': 'SEG-010',
                'name': 'Locativo - Condiciones de orden y aseo deficientes',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Desorden, acumulación de materiales, falta de limpieza',
                'fuente': 'Falta de programa 5S, almacenamiento inadecuado',
                'efectos_posibles': 'Caídas, golpes, incendios, plagas, accidentes varios',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Programa 5S, inspecciones, capacitación, áreas demarcadas',
            },
            {
                'code': 'SEG-011',
                'name': 'Locativo - Caídas de objetos',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de golpes por objetos que caen de estantes o niveles superiores',
                'fuente': 'Almacenamiento en altura, trabajo en niveles, estibado inadecuado',
                'efectos_posibles': 'Golpes en cabeza, fracturas, traumatismos craneoencefálicos',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Casco de seguridad, estanterías ancladas, almacenamiento seguro',
            },
            {
                'code': 'SEG-012',
                'name': 'Trabajo en alturas',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Trabajo a más de 1.5 metros sobre el nivel del piso',
                'fuente': 'Escaleras, andamios, techos, torres, postes',
                'efectos_posibles': 'Caídas de altura, politraumatismos, muerte',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Sistema de protección contra caídas, capacitación, permiso de trabajo, certificación',
            },
            {
                'code': 'SEG-013',
                'name': 'Espacios confinados',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Ingreso a espacios con acceso restringido y atmósfera potencialmente peligrosa',
                'fuente': 'Tanques, silos, pozos, alcantarillas, ductos',
                'efectos_posibles': 'Asfixia, intoxicación, atrapamiento, explosión, muerte',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Permiso de trabajo, medición atmosférica, ventilación, vigía, rescate',
            },
            {
                'code': 'SEG-014',
                'name': 'Tecnológico - Incendio',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de fuego por presencia de combustibles y fuentes de ignición',
                'fuente': 'Materiales inflamables, cortocircuitos, chispas, llamas abiertas',
                'efectos_posibles': 'Quemaduras, intoxicación por humo, muerte, pérdidas materiales',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Extintores, detección de incendios, plan de emergencias, capacitación',
            },
            {
                'code': 'SEG-015',
                'name': 'Tecnológico - Explosión',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de explosión por gases, polvos o presión',
                'fuente': 'Cilindros a presión, atmósferas explosivas, polvo combustible',
                'efectos_posibles': 'Quemaduras graves, traumatismos, muerte, destrucción de instalaciones',
                'nivel_riesgo': 'I',
                'controles_existentes': 'Control de fuentes de ignición, ventilación, equipos antiexplosivos',
            },
            {
                'code': 'SEG-016',
                'name': 'Tecnológico - Fuga de sustancias',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Escape no controlado de sustancias peligrosas',
                'fuente': 'Tuberías, válvulas, tanques, equipos de proceso',
                'efectos_posibles': 'Intoxicación, quemaduras, contaminación, incendio/explosión',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Mantenimiento, inspección, kit de derrames, plan de emergencias',
            },
            {
                'code': 'SEG-017',
                'name': 'Accidentes de tránsito',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de colisión, volcamiento o atropello en vehículos',
                'fuente': 'Conducción de vehículos, desplazamiento en vías, tránsito interno',
                'efectos_posibles': 'Politraumatismos, muerte, lesiones permanentes',
                'nivel_riesgo': 'I',
                'controles_existentes': 'PESV, mantenimiento vehicular, capacitación, cinturón, GPS',
            },
            {
                'code': 'SEG-018',
                'name': 'Público - Robos, atracos, asaltos',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo de ser víctima de actos delictivos',
                'fuente': 'Manejo de dinero, zonas de alta criminalidad, trabajo solitario',
                'efectos_posibles': 'Lesiones físicas, trauma psicológico, muerte',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Trabajo acompañado, rutas seguras, comunicación, no resistencia',
            },
            {
                'code': 'SEG-019',
                'name': 'Trabajo con animales',
                'clasificacion': 'CONDICIONES_SEGURIDAD',
                'descripcion': 'Riesgo por manejo o contacto con animales',
                'fuente': 'Veterinarias, granjas, zoológicos, control de plagas',
                'efectos_posibles': 'Mordeduras, cornadas, patadas, aplastamiento, zoonosis',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Capacitación, EPP, instalaciones adecuadas, protocolos de manejo',
            },

            # =================================================================
            # RIESGOS POR FENÓMENOS NATURALES (NAT-XXX)
            # =================================================================
            {
                'code': 'NAT-001',
                'name': 'Sismo / Terremoto',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Movimiento telúrico que puede afectar estructuras y personas',
                'fuente': 'Actividad sísmica natural de la región',
                'efectos_posibles': 'Colapso estructural, atrapamiento, lesiones, muerte',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Plan de emergencias, simulacros, diseño sismorresistente, evacuación',
            },
            {
                'code': 'NAT-002',
                'name': 'Inundación',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Anegación de instalaciones por lluvias intensas o desbordamiento',
                'fuente': 'Lluvias torrenciales, ríos, alcantarillado insuficiente',
                'efectos_posibles': 'Ahogamiento, electrocución, pérdidas materiales, enfermedades',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Drenajes adecuados, alarmas, plan de emergencias, ubicación segura',
            },
            {
                'code': 'NAT-003',
                'name': 'Deslizamiento / Derrumbe',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Movimiento de tierra en zonas de ladera o excavaciones',
                'fuente': 'Lluvias en zonas inestables, excavaciones, taludes',
                'efectos_posibles': 'Sepultamiento, aplastamiento, muerte',
                'nivel_riesgo': 'II',
                'controles_existentes': 'Estudios de suelo, estabilización de taludes, monitoreo, evacuación',
            },
            {
                'code': 'NAT-004',
                'name': 'Tormenta eléctrica',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Exposición a descargas eléctricas atmosféricas (rayos)',
                'fuente': 'Tormentas con actividad eléctrica',
                'efectos_posibles': 'Electrocución por rayo, incendio, daño a equipos',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Pararrayos, suspensión de trabajo exterior, refugio en edificaciones',
            },
            {
                'code': 'NAT-005',
                'name': 'Vendaval / Huracán',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Vientos fuertes que pueden causar daños estructurales',
                'fuente': 'Fenómenos meteorológicos extremos',
                'efectos_posibles': 'Golpes por objetos volantes, colapso de estructuras, lesiones',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Aseguramiento de estructuras, alertas meteorológicas, refugio',
            },
            {
                'code': 'NAT-006',
                'name': 'Erupción volcánica',
                'clasificacion': 'FENOMENOS_NATURALES',
                'descripcion': 'Afectación por actividad volcánica (ceniza, flujos piroclásticos)',
                'fuente': 'Volcanes activos en la región',
                'efectos_posibles': 'Problemas respiratorios, quemaduras, sepultamiento, evacuación',
                'nivel_riesgo': 'III',
                'controles_existentes': 'Monitoreo vulcanológico, plan de evacuación, EPP respiratorio',
            },
        ]
