# Generated by Django 5.0.14 on 2026-04-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo_productos", "0008_copy_proveedor_data_from_supply_chain"),
        ("sc_recepcion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherrecepcion",
            name="proveedor",
            field=models.ForeignKey(
                help_text="Proveedor que recibe la liquidación",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vouchers_recepcion",
                to="catalogo_productos.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
