# Generated by Django 5.0.14 on 2026-04-28 05:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sc_recepcion", "0011_documento_archivado_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherlineamp",
            name="peso_bruto_kg",
            field=models.DecimalField(
                decimal_places=1, max_digits=12, verbose_name="Peso bruto (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="voucherlineamp",
            name="peso_neto_kg",
            field=models.DecimalField(
                decimal_places=1,
                editable=False,
                max_digits=12,
                verbose_name="Peso neto (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="voucherlineamp",
            name="peso_tara_kg",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=12,
                verbose_name="Peso tara (kg)",
            ),
        ),
    ]
