# Generated by Django 5.0.14 on 2026-04-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0012_rutarecoleccion_conductor_principal_and_more"),
        ("sc_recepcion", "0013_voucherlineamp_almacen_destino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherrecepcion",
            name="almacen_destino",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy. El almacén se asigna por cada línea (VoucherLineaMP). Este campo solo se conserva por backward-compat con datos viejos.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vouchers_recepcion",
                to="catalogos.almacen",
                verbose_name="Almacén destino (legacy / fallback)",
            ),
        ),
    ]
