# Generated by Django 5.0.9 on 2025-11-19 16:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del cargo (ej: RECOLECTOR, SUPERVISOR)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del cargo",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del cargo y responsabilidades",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Operativo"),
                            (1, "Supervisión"),
                            (2, "Coordinación"),
                            (3, "Dirección"),
                        ],
                        default=0,
                        help_text="Nivel en la jerarquía organizacional (0=Operativo, 3=Dirección)",
                        verbose_name="Nivel jerárquico",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Si el cargo está activo en el sistema",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "parent_cargo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cargo al que reporta este cargo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinados",
                        to="core.cargo",
                        verbose_name="Cargo superior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "core_cargo",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono de contacto",
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        db_index=True,
                        help_text="Número de identificación único",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de documento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de eliminación lógica (soft delete)",
                        null=True,
                        verbose_name="Fecha de eliminación",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó este registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cargo del usuario en la organización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="core.cargo",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "core_user",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("CORE", "Core - Usuarios y Configuración"),
                            ("RECOLECCIONES", "Recolecciones"),
                            ("LOTES", "Lotes"),
                            ("LIQUIDACIONES", "Liquidaciones"),
                            ("PROVEEDORES", "Proveedores"),
                            ("UNIDADES", "Unidades de Recolección"),
                            ("CERTIFICADOS", "Certificados"),
                            ("REPORTES", "Reportes"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "Ver"),
                            ("CREATE", "Crear"),
                            ("EDIT", "Editar"),
                            ("DELETE", "Eliminar"),
                            ("APPROVE", "Aprobar"),
                            ("EXPORT", "Exportar"),
                            ("MANAGE", "Administrar"),
                        ],
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("OWN", "Propios"),
                            ("TEAM", "Equipo"),
                            ("ALL", "Todos"),
                        ],
                        default="OWN",
                        max_length=10,
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "core_permiso",
                "ordering": ["module", "action", "scope"],
                "indexes": [
                    models.Index(fields=["code"], name="core_permis_code_85752b_idx"),
                    models.Index(
                        fields=["module", "is_active"],
                        name="core_permis_module_38b42c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CargoPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_permisos",
                        to="core.cargo",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permisos_otorgados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_permisos",
                        to="core.permiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo-Permiso",
                "verbose_name_plural": "Cargos-Permisos",
                "db_table": "core_cargo_permiso",
                "ordering": ["cargo", "permiso"],
            },
        ),
        migrations.AddField(
            model_name="cargo",
            name="permisos",
            field=models.ManyToManyField(
                related_name="cargos",
                through="core.CargoPermiso",
                to="core.permiso",
                verbose_name="Permisos",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["document_number"], name="core_user_documen_5b66f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["cargo", "is_active"], name="core_user_cargo_i_38b6b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["deleted_at"], name="core_user_deleted_658058_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cargopermiso",
            unique_together={("cargo", "permiso")},
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["code"], name="core_cargo_code_b6c338_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["is_active", "level"], name="core_cargo_is_acti_389961_idx"
            ),
        ),
    ]
