# Generated by Django 5.0.9 on 2026-01-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del tipo (ej: EQUIPO, COMITE)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Equipo de Trabajo, Comité)', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('color', models.CharField(blank=True, help_text='Color para identificación visual (hex o nombre)', max_length=20, null=True, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Grupo',
                'verbose_name_plural': 'Tipos de Grupos',
                'db_table': 'core_grupo_tipo',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermisoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único de la acción (ej: VIEW, CREATE, APPROVE)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Ver, Crear, Aprobar)', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acción de Permiso',
                'verbose_name_plural': 'Acciones de Permisos',
                'db_table': 'core_permiso_accion',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermisoAlcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del alcance (ej: OWN, TEAM, ALL)', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Propios, Equipo, Todos)', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Explicación de qué registros incluye este alcance', null=True, verbose_name='Descripción')),
                ('nivel', models.PositiveIntegerField(default=0, help_text='0=más restrictivo, mayor=más permisivo', verbose_name='Nivel de acceso')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alcance de Permiso',
                'verbose_name_plural': 'Alcances de Permisos',
                'db_table': 'core_permiso_alcance',
                'ordering': ['nivel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del módulo (ej: CORE, SST, CALIDAD)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del módulo', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: mdi-cog, fa-users)', max_length=50, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listas', verbose_name='Orden')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo de Permisos',
                'verbose_name_plural': 'Módulos de Permisos',
                'db_table': 'core_permiso_modulo',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['modulo__orden', 'accion__orden', 'alcance__nivel'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.RemoveIndex(
            model_name='permiso',
            name='core_permis_module_38b42c_idx',
        ),
        migrations.AddField(
            model_name='permiso',
            name='recurso',
            field=models.CharField(blank=True, help_text='Recurso específico si aplica (ej: voucher, certificado)', max_length=100, null=True, verbose_name='Recurso específico'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='code',
            field=models.CharField(db_index=True, help_text='Código único del permiso (ej: recolecciones.view.all)', max_length=100, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo del permiso', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='group',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Categoría del grupo (Equipo, Comité, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='core.grupotipo', verbose_name='Tipo de Grupo'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='accion',
            field=models.ForeignKey(blank=True, help_text='Tipo de acción que permite este permiso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='core.permisoaccion', verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='alcance',
            field=models.ForeignKey(blank=True, help_text='Sobre qué registros aplica este permiso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='core.permisoalcance', verbose_name='Alcance'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Módulo al que pertenece este permiso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='core.permisomodulo', verbose_name='Módulo'),
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together={('modulo', 'accion', 'alcance', 'recurso')},
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo', 'is_active'], name='core_permis_modulo__0be749_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo', 'accion'], name='core_permis_modulo__f18b71_idx'),
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='action',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='module',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='scope',
        ),
    ]
