# Generated by Django 5.0.9 on 2025-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permiso",
            name="module",
            field=models.CharField(
                choices=[
                    ("CORE", "Core - Usuarios y Configuración"),
                    ("RECOLECCIONES", "Recolecciones"),
                    ("LOTES", "Lotes"),
                    ("LIQUIDACIONES", "Liquidaciones"),
                    ("PROVEEDORES", "Proveedores"),
                    ("UNIDADES", "Unidades de Recolección"),
                    ("CERTIFICADOS", "Certificados"),
                    ("REPORTES", "Reportes"),
                    ("DIRECCION_ESTRATEGICA", "Dirección Estratégica"),
                    ("TALENTO_HUMANO", "Talento Humano"),
                    ("GESTION_INTEGRAL", "Gestión Integral"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Módulo",
            ),
        ),
    ]
