# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("organizacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Área/departamento al que pertenece el cargo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos",
                to="organizacion.area",
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="parent_cargo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo al que reporta (supervisor directo)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to="core.cargo",
                verbose_name="Reporta a",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo del usuario en la organización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="core.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="cargopermiso",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_permisos",
                to="core.cargo",
            ),
        ),
        migrations.AddField(
            model_name="cargopermiso",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisos_otorgados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cargorole",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_roles",
                to="core.cargo",
            ),
        ),
        migrations.AddField(
            model_name="cargosectionaccess",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_accesses",
                to="core.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="cargosectionaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section_accesses_granted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Otorgado por",
            ),
        ),
        migrations.AddField(
            model_name="grouprole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles_grupo_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grouprole",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_roles",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría del grupo (Equipo, Comité, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="core.grupotipo",
                verbose_name="Tipo de Grupo",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="allowed_cargos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cargos que pueden ver este item",
                related_name="menu_items",
                to="core.cargo",
                verbose_name="Cargos permitidos",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de menu padre (para jerarquia)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.menuitem",
                verbose_name="Item padre",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="required_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos necesarios para ver este item",
                related_name="menu_items",
                to="core.permiso",
                verbose_name="Permisos requeridos",
            ),
        ),
        migrations.AddField(
            model_name="cargopermiso",
            name="permiso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_permisos",
                to="core.permiso",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="permisos",
            field=models.ManyToManyField(
                related_name="cargos",
                through="core.CargoPermiso",
                to="core.permiso",
                verbose_name="Permisos",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="accion",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de acción que permite este permiso",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permisos",
                to="core.permisoaccion",
                verbose_name="Acción",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="alcance",
            field=models.ForeignKey(
                blank=True,
                help_text="Sobre qué registros aplica este permiso",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permisos",
                to="core.permisoalcance",
                verbose_name="Alcance",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="modulo",
            field=models.ForeignKey(
                blank=True,
                help_text="Módulo al que pertenece este permiso",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permisos",
                to="core.permisomodulo",
                verbose_name="Módulo",
            ),
        ),
        migrations.AddField(
            model_name="permissionchangelog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó el cambio (NULL si fue automático)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_changes_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="permissionchangelog",
            name="content_type",
            field=models.ForeignKey(
                help_text="Tipo de modelo que fue modificado",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Tipo de objeto",
            ),
        ),
        migrations.AddField(
            model_name="permissionchangelog",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_change_logs",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="permissiontemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_templates_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="permissiontemplate",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria. NULL = plantilla global del sistema",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_templates",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="permissiontemplateapplication",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_applications_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aplicado por",
            ),
        ),
        migrations.AddField(
            model_name="permissiontemplateapplication",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_applications",
                to="core.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="permissiontemplateapplication",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.permissiontemplate",
                verbose_name="Plantilla",
            ),
        ),
        migrations.AddIndex(
            model_name="riesgoocupacional",
            index=models.Index(fields=["code"], name="core_riesgo_code_352b47_idx"),
        ),
        migrations.AddIndex(
            model_name="riesgoocupacional",
            index=models.Index(
                fields=["clasificacion", "is_active"],
                name="core_riesgo_clasifi_8abd41_idx",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="expuesto_riesgos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Riesgos a los que está expuesto el cargo",
                related_name="cargos_expuestos",
                to="core.riesgoocupacional",
                verbose_name="Riesgos Ocupacionales",
            ),
        ),
        migrations.AddField(
            model_name="roladicional",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles_adicionales_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="roladicionalpermiso",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisos_rol_adicional_otorgados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado por",
            ),
        ),
        migrations.AddField(
            model_name="roladicionalpermiso",
            name="permiso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rol_adicional_permisos",
                to="core.permiso",
                verbose_name="Permiso",
            ),
        ),
        migrations.AddField(
            model_name="roladicionalpermiso",
            name="rol_adicional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rol_adicional_permisos",
                to="core.roladicional",
                verbose_name="Rol Adicional",
            ),
        ),
        migrations.AddField(
            model_name="roladicional",
            name="permisos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos que otorga este rol adicional",
                related_name="roles_adicionales",
                through="core.RolAdicionalPermiso",
                to="core.permiso",
                verbose_name="Permisos",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles que pueden ver este item",
                related_name="menu_items",
                to="core.role",
                verbose_name="Roles permitidos",
            ),
        ),
        migrations.AddField(
            model_name="grouprole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_roles",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="core.GroupRole",
                to="core.role",
                verbose_name="Roles",
            ),
        ),
        migrations.AddField(
            model_name="cargorole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_roles",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="default_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_for_cargos",
                through="core.CargoRole",
                to="core.role",
                verbose_name="Roles por defecto",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="rol_sistema",
            field=models.ForeignKey(
                blank=True,
                help_text="Rol de permisos asignado por defecto al cargo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_asignados",
                to="core.role",
                verbose_name="Rol del Sistema",
            ),
        ),
        migrations.AddField(
            model_name="rolepermiso",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisos_rol_otorgados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolepermiso",
            name="permiso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permisos",
                to="core.permiso",
            ),
        ),
        migrations.AddField(
            model_name="rolepermiso",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permisos",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permisos",
            field=models.ManyToManyField(
                related_name="roles",
                through="core.RolePermiso",
                to="core.permiso",
                verbose_name="Permisos",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modulos que deben estar activos para que este funcione",
                related_name="dependents",
                to="core.systemmodule",
                verbose_name="Dependencias",
            ),
        ),
        migrations.AddField(
            model_name="moduletab",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="core.systemmodule",
                verbose_name="Modulo",
            ),
        ),
        migrations.AddField(
            model_name="tabsection",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.moduletab",
                verbose_name="Tab",
            ),
        ),
        migrations.AddField(
            model_name="cargosectionaccess",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_accesses",
                to="core.tabsection",
                verbose_name="Sección",
            ),
        ),
        migrations.AddField(
            model_name="twofactorauth",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario propietario de esta configuración 2FA",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_groups",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userroladicional",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles_adicionales_asignados_por_mi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado por",
            ),
        ),
        migrations.AddField(
            model_name="userroladicional",
            name="rol_adicional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_asignados",
                to="core.roladicional",
                verbose_name="Rol Adicional",
            ),
        ),
        migrations.AddField(
            model_name="userroladicional",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_roles_adicionales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles_adicionales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles especiales asignados además del cargo base (COPASST, Brigadista, etc.)",
                related_name="users",
                through="core.UserRolAdicional",
                to="core.roladicional",
                verbose_name="Roles Adicionales",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cargopermiso",
            unique_together={("cargo", "permiso")},
        ),
        migrations.AddIndex(
            model_name="permiso",
            index=models.Index(fields=["code"], name="core_permis_code_85752b_idx"),
        ),
        migrations.AddIndex(
            model_name="permiso",
            index=models.Index(
                fields=["modulo", "is_active"], name="core_permis_modulo__0be749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permiso",
            index=models.Index(
                fields=["modulo", "accion"], name="core_permis_modulo__f18b71_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permiso",
            unique_together={("modulo", "accion", "alcance", "recurso")},
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["changed_at"], name="core_permis_changed_0ac02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["changed_by", "changed_at"],
                name="core_permis_changed_e6d60c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["affected_entity_type", "affected_entity_id"],
                name="core_permis_affecte_f4e003_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["action", "changed_at"], name="core_permis_action_58b506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_permis_content_ea432e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionchangelog",
            index=models.Index(
                fields=["empresa", "changed_at"], name="core_permis_empresa_27564b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiontemplate",
            index=models.Index(fields=["code"], name="core_permis_code_dbdbd1_idx"),
        ),
        migrations.AddIndex(
            model_name="permissiontemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="core_permis_templat_0165fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissiontemplate",
            index=models.Index(
                fields=["empresa", "is_active"], name="core_permis_empresa_eb3eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiontemplateapplication",
            index=models.Index(
                fields=["template", "applied_at"], name="core_permis_templat_9ae41d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiontemplateapplication",
            index=models.Index(
                fields=["cargo", "applied_at"], name="core_permis_cargo_i_e237ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiontemplateapplication",
            index=models.Index(
                fields=["applied_by", "applied_at"],
                name="core_permis_applied_66d202_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roladicionalpermiso",
            unique_together={("rol_adicional", "permiso")},
        ),
        migrations.AddIndex(
            model_name="roladicional",
            index=models.Index(fields=["code"], name="core_rol_ad_code_67aa02_idx"),
        ),
        migrations.AddIndex(
            model_name="roladicional",
            index=models.Index(
                fields=["tipo", "is_active"], name="core_rol_ad_tipo_1f1d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roladicional",
            index=models.Index(
                fields=["is_active"], name="core_rol_ad_is_acti_6a830e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["code"], name="core_menu_i_code_d46e8f_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_active", "orden"], name="core_menu_i_is_acti_19ecdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["parent", "is_active"], name="core_menu_i_parent__da77e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouprole",
            unique_together={("group", "role")},
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["code"], name="core_group_code_49fc2e_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["is_active"], name="core_group_is_acti_abdf64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cargorole",
            unique_together={("cargo", "role")},
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["code"], name="core_cargo_code_b6c338_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["is_active", "nivel_jerarquico"],
                name="core_cargo_is_acti_d4c742_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["area"], name="core_cargo_area_id_e6c9e3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermiso",
            unique_together={("role", "permiso")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="core_role_code_41eecc_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="core_role_is_acti_cf5dc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduletab",
            index=models.Index(
                fields=["module", "is_enabled"], name="core_module_module__406458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduletab",
            index=models.Index(fields=["code"], name="core_module_code_75c27d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="moduletab",
            unique_together={("module", "code")},
        ),
        migrations.AddIndex(
            model_name="tabsection",
            index=models.Index(
                fields=["tab", "is_enabled"], name="core_tab_se_tab_id_c322f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tabsection",
            index=models.Index(fields=["code"], name="core_tab_se_code_60b1f1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tabsection",
            unique_together={("tab", "code")},
        ),
        migrations.AddIndex(
            model_name="cargosectionaccess",
            index=models.Index(fields=["cargo"], name="core_cargo__cargo_i_20b9e4_idx"),
        ),
        migrations.AddIndex(
            model_name="cargosectionaccess",
            index=models.Index(
                fields=["section"], name="core_cargo__section_04e977_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cargosectionaccess",
            unique_together={("cargo", "section")},
        ),
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="userroladicional",
            index=models.Index(
                fields=["user", "is_active"], name="core_user_r_user_id_39ff03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroladicional",
            index=models.Index(
                fields=["expires_at"], name="core_user_r_expires_adac39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroladicional",
            index=models.Index(
                fields=["certificacion_expira"], name="core_user_r_certifi_c85d1a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroladicional",
            unique_together={("user", "rol_adicional")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["document_number"], name="core_user_documen_5b66f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["cargo", "is_active"], name="core_user_cargo_i_38b6b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["deleted_at"], name="core_user_deleted_658058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="core_user_r_expires_a8aff2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="core_user_s_user_id_3a83a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token_hash"], name="core_user_s_refresh_c1236b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="core_user_s_expires_9b142f_idx"
            ),
        ),
    ]
