# Generated by Django 5.0.9 on 2026-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingconfig",
            name="background_color",
            field=models.CharField(
                default="#F5F5F5",
                help_text="Color de fondo general de la aplicacion",
                max_length=7,
                verbose_name="Color de Fondo",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="gradient_mission",
            field=models.CharField(
                blank=True,
                help_text="Clases Tailwind para gradiente de mision (ej: from-blue-500 to-purple-600)",
                max_length=100,
                null=True,
                verbose_name="Gradiente Mision",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="gradient_policy",
            field=models.CharField(
                blank=True,
                help_text="Clases Tailwind para gradiente de politica",
                max_length=100,
                null=True,
                verbose_name="Gradiente Politica",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="gradient_values",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de gradientes Tailwind para carrusel de valores corporativos",
                verbose_name="Gradientes Valores",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="gradient_vision",
            field=models.CharField(
                blank=True,
                help_text="Clases Tailwind para gradiente de vision",
                max_length=100,
                null=True,
                verbose_name="Gradiente Vision",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                help_text="Version del logo optimizada para fondos claros (si difiere del principal)",
                null=True,
                upload_to="branding/logos/",
                verbose_name="Logo para Modo Oscuro",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="showcase_background",
            field=models.CharField(
                default="#1F2937",
                help_text="Color de fondo para secciones showcase/presentaciones",
                max_length=7,
                verbose_name="Color Fondo Presentaciones",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="sidebar_color",
            field=models.CharField(
                default="#1E293B",
                help_text="Color de fondo del sidebar en formato HEX",
                max_length=7,
                verbose_name="Color del Sidebar",
            ),
        ),
    ]
