# Generated by Django 5.0.9 on 2026-01-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('core', '0002_add_dynamic_rbac_models'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área/departamento al que pertenece el cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='organizacion.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='user',
            name='sede_asignada',
            field=models.ForeignKey(blank=True, help_text='Ubicación física de trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='configuracion.sedeempresa', verbose_name='Sede Asignada'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sede_nombre',
            field=models.CharField(blank=True, help_text='Campo deprecated - usar campo sede_asignada (FK)', max_length=100, null=True, verbose_name='[DEPRECATED] Sede (texto)'),
        ),
    ]
