# Generated by Django 5.0.9 on 2025-12-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_permiso_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del grupo (ej: equipo_recolecciones)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del grupo",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del grupo y su propósito",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "core_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del rol (ej: aprobador_recolecciones)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del rol",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de las responsabilidades del rol",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "core_role",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="permiso",
            name="module",
            field=models.CharField(
                choices=[
                    ("CORE", "Core - Usuarios y Configuración"),
                    ("RECOLECCIONES", "Recolecciones"),
                    ("LOTES", "Lotes"),
                    ("LIQUIDACIONES", "Liquidaciones"),
                    ("PROVEEDORES", "Proveedores"),
                    ("ECOALIADOS", "Ecoaliados"),
                    ("PROGRAMACIONES", "Programaciones"),
                    ("UNIDADES", "Unidades de Recolección"),
                    ("CERTIFICADOS", "Certificados"),
                    ("REPORTES", "Reportes"),
                    ("DIRECCION_ESTRATEGICA", "Dirección Estratégica"),
                    ("TALENTO_HUMANO", "Talento Humano"),
                    ("GESTION_INTEGRAL", "Gestión Integral"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Módulo",
            ),
        ),
        migrations.CreateModel(
            name="GroupRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_grupo_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_roles",
                        to="core.group",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_roles",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo-Rol",
                "verbose_name_plural": "Grupos-Roles",
                "db_table": "core_group_role",
                "ordering": ["group", "role"],
                "unique_together": {("group", "role")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="core.GroupRole",
                to="core.role",
                verbose_name="Roles",
            ),
        ),
        migrations.CreateModel(
            name="RolePermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permisos_rol_otorgados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permisos",
                        to="core.permiso",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permisos",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol-Permiso",
                "verbose_name_plural": "Roles-Permisos",
                "db_table": "core_role_permiso",
                "ordering": ["role", "permiso"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permisos",
            field=models.ManyToManyField(
                related_name="roles",
                through="core.RolePermiso",
                to="core.permiso",
                verbose_name="Permisos",
            ),
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "is_leader",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario es líder del grupo",
                        verbose_name="Es líder",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grupos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="core.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Grupo",
                "verbose_name_plural": "Usuarios-Grupos",
                "db_table": "core_user_group",
                "ordering": ["user", "group"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que el rol expira automáticamente",
                        null=True,
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="core.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Rol",
                "verbose_name_plural": "Usuarios-Roles",
                "db_table": "core_user_role",
                "ordering": ["user", "role"],
            },
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["code"], name="core_group_code_49fc2e_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["is_active"], name="core_group_is_acti_abdf64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermiso",
            unique_together={("role", "permiso")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="core_role_code_41eecc_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="core_role_is_acti_cf5dc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="core_user_r_expires_a8aff2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
    ]
