# Generated by Django 5.0.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_rbac_roles_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='code',
            field=models.CharField(
                db_index=True,
                help_text='Código único del cargo (ej: RECOLECTOR, SUPERVISOR)',
                max_length=50,
                unique=True,
                verbose_name='Código'
            ),
        ),
    ]
