# Generated by Django 5.0.9 on 2025-12-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_extend_cargo_code_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECCION", "Dirección Estratégica"),
                    ("COMERCIAL", "Comercial"),
                    ("LOGISTICA", "Logística"),
                    ("PLANTA", "Planta"),
                    ("CALIDAD", "Calidad"),
                    ("SST", "Seguridad y Salud"),
                    ("TALENTO_HUMANO", "Talento Humano"),
                    ("FINANZAS", "Finanzas"),
                    ("OPERACIONES", "Operaciones"),
                ],
                db_index=True,
                help_text="Área funcional a la que pertenece el cargo",
                max_length=30,
                null=True,
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Los cargos del sistema no pueden eliminarse",
                verbose_name="Es del sistema",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Los roles del sistema no pueden ser eliminados desde la UI",
                verbose_name="Es del sistema",
            ),
        ),
        migrations.CreateModel(
            name="CargoRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_roles",
                        to="core.cargo",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_roles",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo-Rol por defecto",
                "verbose_name_plural": "Cargos-Roles por defecto",
                "db_table": "core_cargo_role",
                "ordering": ["cargo", "role"],
                "unique_together": {("cargo", "role")},
            },
        ),
        migrations.AddField(
            model_name="cargo",
            name="default_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_for_cargos",
                through="core.CargoRole",
                to="core.role",
                verbose_name="Roles por defecto",
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del item de menú (ej: menu.econorte)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible en el menú",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del frontend (ej: /proveedores/econorte)",
                        max_length=200,
                        null=True,
                        verbose_name="Ruta",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide (ej: Users, Truck, Package)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "macroprocess",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECCION_ESTRATEGICA", "Dirección Estratégica"),
                            ("GESTION_MISIONAL", "Gestión Misional"),
                            ("GESTION_APOYO", "Gestión de Apoyo"),
                            ("GESTION_INTEGRAL", "Gestión Integral"),
                        ],
                        db_index=True,
                        help_text="Macroproceso al que pertenece (solo para items de nivel 0)",
                        max_length=30,
                        null=True,
                        verbose_name="Macroproceso",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("purple", "Púrpura"),
                            ("blue", "Azul"),
                            ("green", "Verde"),
                            ("orange", "Naranja"),
                            ("red", "Rojo"),
                            ("gray", "Gris"),
                        ],
                        help_text="Color del macroproceso (solo para items de nivel 0)",
                        max_length=20,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de aparición en el menú",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Texto del badge (ej: Nuevo, Beta)",
                        max_length=20,
                        null=True,
                        verbose_name="Badge",
                    ),
                ),
                (
                    "is_category",
                    models.BooleanField(
                        default=False,
                        help_text="Si es un macroproceso (categoría sin ruta)",
                        verbose_name="Es categoría",
                    ),
                ),
                (
                    "allow_all",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, todos los usuarios autenticados pueden ver este item",
                        verbose_name="Permitir todos",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "allowed_cargos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cargos que pueden ver este item",
                        related_name="menu_items",
                        to="core.cargo",
                        verbose_name="Cargos permitidos",
                    ),
                ),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles que pueden ver este item",
                        related_name="menu_items",
                        to="core.role",
                        verbose_name="Roles permitidos",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item de menú padre (para jerarquía)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                        verbose_name="Item padre",
                    ),
                ),
                (
                    "required_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permisos necesarios para ver este item",
                        related_name="menu_items",
                        to="core.permiso",
                        verbose_name="Permisos requeridos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Menú",
                "verbose_name_plural": "Items de Menú",
                "db_table": "core_menu_item",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="core_menu_i_code_d46e8f_idx"),
                    models.Index(
                        fields=["is_active", "order"],
                        name="core_menu_i_is_acti_f5145f_idx",
                    ),
                    models.Index(
                        fields=["parent", "is_active"],
                        name="core_menu_i_parent__da77e1_idx",
                    ),
                ],
            },
        ),
    ]
