# Generated by Django 5.0.9 on 2026-01-08 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_cargo_section_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargosectionaccess',
            options={'ordering': ['cargo', 'section__tab__module__orden', 'section__tab__orden', 'section__orden'], 'verbose_name': 'Acceso a Sección por Cargo', 'verbose_name_plural': 'Accesos a Secciones por Cargo'},
        ),
        migrations.RenameIndex(
            model_name='cargosectionaccess',
            new_name='core_cargo__cargo_i_20b9e4_idx',
            old_name='core_cargo__cargo_i_idx',
        ),
        migrations.RenameIndex(
            model_name='cargosectionaccess',
            new_name='core_cargo__section_04e977_idx',
            old_name='core_cargo__section_idx',
        ),
        migrations.AddField(
            model_name='cargo',
            name='is_externo',
            field=models.BooleanField(default=False, help_text='Indica si es un cargo externo (contratista, consultor, auditor, socio)', verbose_name='Es Externo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_jerarquico',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('TACTICO', 'Táctico'), ('OPERATIVO', 'Operativo'), ('APOYO', 'Apoyo'), ('EXTERNO', 'Externo')], db_index=True, default='OPERATIVO', help_text='Clasificación estratégica del cargo', max_length=20, verbose_name='Nivel Jerárquico'),
        ),
        migrations.AlterField(
            model_name='cargosectionaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_accesses_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por'),
        ),
    ]
