# Generated by Django 5.0.9 on 2025-12-11 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_rbac_dynamic_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="StrateKaz",
                        max_length=200,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
                (
                    "company_short_name",
                    models.CharField(
                        default="GRASHNORTE", max_length=50, verbose_name="Nombre Corto"
                    ),
                ),
                (
                    "company_slogan",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Slogan"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/logos/",
                        verbose_name="Logo Principal",
                    ),
                ),
                (
                    "logo_white",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/logos/",
                        verbose_name="Logo Blanco (para fondos oscuros)",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#16A34A",
                        help_text="Color en formato HEX (ej: #16A34A)",
                        max_length=7,
                        verbose_name="Color Primario",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#059669", max_length=7, verbose_name="Color Secundario"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#10B981", max_length=7, verbose_name="Color de Acento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Branding",
                "verbose_name_plural": "Configuraciones de Branding",
                "db_table": "core_branding_config",
            },
        ),
        migrations.CreateModel(
            name="ConsecutivoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RECOLECCION", "Recolección"),
                            ("RECEPCION", "Recepción"),
                            ("LOTE", "Lote de Producción"),
                            ("DESPACHO", "Despacho"),
                            ("FACTURA", "Factura"),
                            ("ORDEN_COMPRA", "Orden de Compra"),
                            ("ORDEN_TRABAJO", "Orden de Trabajo"),
                            ("ACCION_CORRECTIVA", "Acción Correctiva"),
                            ("NO_CONFORMIDAD", "No Conformidad"),
                            ("AUDITORIA", "Auditoría"),
                            ("INCIDENTE", "Incidente"),
                            ("CAPACITACION", "Capacitación"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Prefijo del consecutivo (ej: REC, LOT, FAC)",
                        max_length=10,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Sufijo opcional del consecutivo",
                        max_length=10,
                        null=True,
                        verbose_name="Sufijo",
                    ),
                ),
                (
                    "current_number",
                    models.IntegerField(
                        default=0,
                        help_text="Último número utilizado",
                        verbose_name="Número Actual",
                    ),
                ),
                (
                    "padding",
                    models.IntegerField(
                        default=5,
                        help_text="Cantidad de dígitos con ceros a la izquierda (ej: 5 = 00001)",
                        verbose_name="Relleno",
                    ),
                ),
                (
                    "include_year",
                    models.BooleanField(
                        default=True,
                        help_text="Si se incluye el año en el consecutivo (ej: REC-2024-00001)",
                        verbose_name="Incluir Año",
                    ),
                ),
                (
                    "include_month",
                    models.BooleanField(
                        default=False,
                        help_text="Si se incluye el mes en el consecutivo",
                        verbose_name="Incluir Mes",
                    ),
                ),
                (
                    "reset_yearly",
                    models.BooleanField(
                        default=True,
                        help_text="Si el consecutivo se reinicia cada año",
                        verbose_name="Reiniciar Anualmente",
                    ),
                ),
                (
                    "reset_monthly",
                    models.BooleanField(
                        default=False,
                        help_text="Si el consecutivo se reinicia cada mes",
                        verbose_name="Reiniciar Mensualmente",
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Fecha de Reinicio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Consecutivo",
                "verbose_name_plural": "Configuraciones de Consecutivos",
                "db_table": "core_consecutivo_config",
                "ordering": ["document_type"],
            },
        ),
        migrations.CreateModel(
            name="CorporateIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        help_text="Declaración de misión de la organización",
                        verbose_name="Misión",
                    ),
                ),
                (
                    "vision",
                    models.TextField(
                        help_text="Declaración de visión de la organización",
                        verbose_name="Visión",
                    ),
                ),
                (
                    "integral_policy",
                    models.TextField(
                        help_text="Política integral del sistema de gestión (Calidad, SST, Ambiental)",
                        verbose_name="Política Integral",
                    ),
                ),
                (
                    "policy_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la firma digital",
                        null=True,
                        verbose_name="Fecha de firma",
                    ),
                ),
                (
                    "policy_signature_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 de la firma digital",
                        max_length=255,
                        null=True,
                        verbose_name="Hash de firma",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Fecha desde la cual esta identidad está vigente",
                        verbose_name="Fecha de vigencia",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Versión del documento (ej: 1.0, 2.1)",
                        max_length=20,
                        verbose_name="Versión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Solo una identidad puede estar activa",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identities_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "policy_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que firmó digitalmente la política",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_signed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identidad Corporativa",
                "verbose_name_plural": "Identidades Corporativas",
                "db_table": "core_corporate_identity",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="CorporateValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del valor (ej: Integridad, Compromiso)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del valor",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide (ej: Heart, Shield)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de aparición", verbose_name="Orden"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.corporateidentity",
                        verbose_name="Identidad Corporativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor Corporativo",
                "verbose_name_plural": "Valores Corporativos",
                "db_table": "core_corporate_value",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StrategicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del plan estratégico (ej: Plan Estratégico 2024-2026)",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción y alcance del plan",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("ANUAL", "Anual"),
                            ("BIANUAL", "Bianual"),
                            ("TRIANUAL", "Trianual"),
                            ("QUINQUENAL", "Quinquenal"),
                        ],
                        default="ANUAL",
                        max_length=20,
                        verbose_name="Tipo de período",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Fecha de inicio del plan",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Fecha de finalización del plan",
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "strategic_map_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="strategic_plans/maps/",
                        verbose_name="Imagen del Mapa Estratégico",
                    ),
                ),
                (
                    "strategic_map_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción del Mapa Estratégico",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Estratégico",
                "verbose_name_plural": "Planes Estratégicos",
                "db_table": "core_strategic_plan",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del módulo (ej: apps.supply_chain)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del módulo",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de las funcionalidades del módulo",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ESTRATEGICO", "Nivel Estratégico"),
                            ("MOTOR", "Motores del Sistema"),
                            ("INTEGRAL", "Gestión Integral"),
                            ("MISIONAL", "Nivel Misional"),
                            ("APOYO", "Nivel de Apoyo"),
                            ("INTELIGENCIA", "Inteligencia de Negocio"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Los módulos core no pueden desactivarse",
                        verbose_name="Es módulo core",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Si el módulo está activo en el sistema",
                        verbose_name="Habilitado",
                    ),
                ),
                (
                    "requires_license",
                    models.BooleanField(
                        default=False,
                        help_text="Si el módulo requiere licencia adicional",
                        verbose_name="Requiere licencia",
                    ),
                ),
                (
                    "license_expires_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de expiración de licencia",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Módulos que deben estar activos para que este funcione",
                        related_name="dependents",
                        to="core.systemmodule",
                        verbose_name="Dependencias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo del Sistema",
                "verbose_name_plural": "Módulos del Sistema",
                "db_table": "core_system_module",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del objetivo (ej: OE-001)",
                        max_length=20,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del objetivo estratégico",
                        max_length=300,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del objetivo",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "bsc_perspective",
                    models.CharField(
                        choices=[
                            ("FINANCIERA", "Financiera"),
                            ("CLIENTES", "Clientes"),
                            ("PROCESOS", "Procesos Internos"),
                            ("APRENDIZAJE", "Aprendizaje y Crecimiento"),
                        ],
                        db_index=True,
                        help_text="Perspectiva del Balanced Scorecard",
                        max_length=20,
                        verbose_name="Perspectiva BSC",
                    ),
                ),
                (
                    "iso_standards",
                    models.JSONField(
                        default=list,
                        help_text="Lista de normas ISO vinculadas",
                        verbose_name="Normas ISO",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor meta del indicador",
                        max_digits=10,
                        null=True,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor actual del indicador",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Actual",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unidad de medida (%, $, unidades, etc.)",
                        max_length=20,
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        help_text="Porcentaje de avance (0-100)",
                        verbose_name="Progreso %",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                            ("RETRASADO", "Retrasado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "responsible_cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_responsible",
                        to="core.cargo",
                        verbose_name="Cargo Responsable",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="core.strategicplan",
                        verbose_name="Plan Estratégico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo Estratégico",
                "verbose_name_plural": "Objetivos Estratégicos",
                "db_table": "core_strategic_objective",
                "ordering": ["bsc_perspective", "order", "code"],
                "unique_together": {("plan", "code")},
            },
        ),
    ]
