# Generated by Django on 2026-01-08

"""
Migración para agregar índices de performance en modelos RBAC.

Índices agregados:
- UserRole: (user, expires_at) para validación de roles activos
- CargoSectionAccess: (cargo, section) para lookups rápidos de permisos
- Cargo: area (activar índice comentado para queries por área)

Nota: Los índices en User (cargo, deleted_at) ya existen desde migraciones anteriores.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Agrega índices de performance para queries frecuentes en Control de Acceso."""

    dependencies = [
        ('core', '0005_add_is_externo_nivel_externo'),
    ]

    operations = [
        # Índice compuesto en UserRole para validación de roles activos por usuario
        # Query típico: UserRole.objects.filter(user=user, expires_at__gte=now())
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(
                fields=['user', 'expires_at'],
                name='core_userrole_user_exp_idx'
            ),
        ),

        # Índice compuesto en CargoSectionAccess para lookups rápidos
        # Query típico: CargoSectionAccess.objects.filter(cargo=cargo, section=section)
        # Nota: Ya existen índices simples, este índice compuesto mejora queries con ambos campos
        migrations.AddIndex(
            model_name='cargosectionaccess',
            index=models.Index(
                fields=['cargo', 'section'],
                name='core_cargosc_lookup_idx'
            ),
        ),

        # Índice en Cargo.area (activar el que estaba comentado)
        # Query típico: Cargo.objects.filter(area=area)
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(
                fields=['area'],
                name='core_cargo_area_idx'
            ),
        ),
    ]
