# Generated by Django 5.0.14 on 2026-03-23 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_firma_guardada"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "onboarding_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("jefe", "Jefe/Líder"),
                            ("empleado", "Empleado"),
                            ("proveedor", "Proveedor"),
                            ("cliente", "Cliente"),
                        ],
                        db_index=True,
                        default="empleado",
                        help_text="Determina qué pasos se muestran al usuario",
                        max_length=15,
                        verbose_name="Tipo de onboarding",
                    ),
                ),
                (
                    "has_photo",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando User.photo está definido",
                        verbose_name="Tiene foto de perfil",
                    ),
                ),
                (
                    "has_firma",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando User.firma_guardada está definido",
                        verbose_name="Tiene firma guardada",
                    ),
                ),
                (
                    "has_emergencia",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando InfoPersonal tiene nombre y teléfono de emergencia",
                        verbose_name="Tiene contacto de emergencia",
                    ),
                ),
                (
                    "profile_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Porcentaje ponderado de completitud del perfil (0–100)",
                        verbose_name="Porcentaje de perfil",
                    ),
                ),
                (
                    "steps_completed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Diccionario {step_key: bool} según el tipo de onboarding",
                        verbose_name="Pasos completados",
                    ),
                ),
                (
                    "completado_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Se establece cuando todos los pasos están completados",
                        null=True,
                        verbose_name="Fecha de finalización",
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="El usuario cerró el widget de onboarding manualmente",
                        verbose_name="Descartado",
                    ),
                ),
                (
                    "last_reminder_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha del último email de recordatorio de onboarding",
                        null=True,
                        verbose_name="Último recordatorio enviado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding de Usuario",
                "verbose_name_plural": "Onboardings de Usuarios",
                "db_table": "core_user_onboarding",
            },
        ),
    ]
