# Generated by Django 5.0.9 on 2025-12-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_strategic_management_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmodule",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("purple", "Púrpura"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("orange", "Naranja"),
                    ("red", "Rojo"),
                    ("gray", "Gris"),
                    ("yellow", "Amarillo"),
                    ("pink", "Rosa"),
                    ("indigo", "Índigo"),
                    ("teal", "Verde azulado"),
                ],
                help_text="Color del macroproceso/módulo (para visualización en UI)",
                max_length=20,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.CreateModel(
            name="ModuleTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tab (ej: identidad, plan_estrategico)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible del tab (ej: Identidad Corporativa)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de las funcionalidades del tab",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide (ej: Building2, Target, BarChart)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparición del tab",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Si el tab está activo en el sistema",
                        verbose_name="Habilitado",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Los tabs core no pueden desactivarse",
                        verbose_name="Es tab core",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="core.systemmodule",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tab de Módulo",
                "verbose_name_plural": "Tabs de Módulos",
                "db_table": "core_module_tab",
                "ordering": ["module", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TabSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la sección (ej: mision_vision, valores)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible de la sección (ej: Misión y Visión)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del contenido de la sección",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide (ej: Eye, Heart, FileText)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparición de la sección",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Si la sección está activa en el sistema",
                        verbose_name="Habilitado",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Las secciones core no pueden desactivarse",
                        verbose_name="Es sección core",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.moduletab",
                        verbose_name="Tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Tab",
                "verbose_name_plural": "Secciones de Tabs",
                "db_table": "core_tab_section",
                "ordering": ["tab", "order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="moduletab",
            index=models.Index(
                fields=["module", "is_enabled"], name="core_module_module__406458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduletab",
            index=models.Index(fields=["code"], name="core_module_code_75c27d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="moduletab",
            unique_together={("module", "code")},
        ),
        migrations.AddIndex(
            model_name="tabsection",
            index=models.Index(
                fields=["tab", "is_enabled"], name="core_tab_se_tab_id_c322f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tabsection",
            index=models.Index(fields=["code"], name="core_tab_se_code_60b1f1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tabsection",
            unique_together={("tab", "code")},
        ),
    ]
