# Generated by Django 5.0.9 on 2026-01-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cargosectionaccess',
            name='core_cargosc_lookup_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='core_userrole_user_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='cargo',
            new_name='core_cargo_area_id_e6c9e3_idx',
            old_name='core_cargo_area_idx',
        ),
    ]
