# Generated by Django 5.0.9 on 2026-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_route_to_modules_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargosectionaccess',
            name='can_create',
            field=models.BooleanField(default=False, help_text='Permite crear nuevos registros en esta sección', verbose_name='Puede crear'),
        ),
        migrations.AddField(
            model_name='cargosectionaccess',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Permite eliminar registros', verbose_name='Puede eliminar'),
        ),
        migrations.AddField(
            model_name='cargosectionaccess',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Permite modificar registros existentes', verbose_name='Puede editar'),
        ),
        migrations.AddField(
            model_name='cargosectionaccess',
            name='can_view',
            field=models.BooleanField(default=True, help_text='Permite ver/acceder a esta sección', verbose_name='Puede ver'),
        ),
    ]
