# Generated by Django 5.0.14 on 2026-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_groupsectionaccess"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="groupsectionaccess",
            new_name="core_group__group_i_4acad1_idx",
            old_name="core_group__group_i_idx",
        ),
        migrations.RenameIndex(
            model_name="groupsectionaccess",
            new_name="core_group__section_b0ed23_idx",
            old_name="core_group__sectio_idx",
        ),
        migrations.RenameIndex(
            model_name="roladicionalsectionaccess",
            new_name="core_rol_ad_rol_adi_0c1458_idx",
            old_name="core_rol_ad_rol_adi_idx",
        ),
        migrations.RenameIndex(
            model_name="roladicionalsectionaccess",
            new_name="core_rol_ad_section_63272b_idx",
            old_name="core_rol_ad_section_idx",
        ),
        migrations.AlterField(
            model_name="roladicionalsectionaccess",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
