# Generated by Django migration for ConsecutivoConfig enhancements

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migración para extender ConsecutivoConfig con nuevas funcionalidades:
    - include_day: Incluir día en formato YYYYMMDD
    - separator: Separador configurable (-, /, _, sin separador)
    - context_code: Código de área/proceso (SST, CAL, PROD, etc.)
    - include_context: Si incluir el contexto en el consecutivo
    - Actualización de DOCUMENT_TYPE_CHOICES con todos los tipos
    """

    dependencies = [
        ('core', '0009_add_missing_tabsections_gestion_estrategica'),
    ]

    operations = [
        # Agregar campo include_day
        migrations.AddField(
            model_name='consecutivoconfig',
            name='include_day',
            field=models.BooleanField(
                default=False,
                help_text='Si se incluye el día en el consecutivo (formato YYYYMMDD)',
                verbose_name='Incluir Día',
            ),
        ),
        # Agregar campo separator
        migrations.AddField(
            model_name='consecutivoconfig',
            name='separator',
            field=models.CharField(
                choices=[
                    ('-', 'Guión (-)'),
                    ('/', 'Diagonal (/)'),
                    ('_', 'Guión bajo (_)'),
                    ('', 'Sin separador'),
                ],
                default='-',
                help_text='Carácter separador entre partes del consecutivo',
                max_length=1,
                verbose_name='Separador',
            ),
        ),
        # Agregar campo context_code
        migrations.AddField(
            model_name='consecutivoconfig',
            name='context_code',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Sin contexto'),
                    ('SST', 'SST - Seguridad y Salud en el Trabajo'),
                    ('CAL', 'CAL - Calidad'),
                    ('AMB', 'AMB - Ambiental'),
                    ('PESV', 'PESV - Seguridad Vial'),
                    ('PROD', 'PROD - Producción'),
                    ('LOG', 'LOG - Logística'),
                    ('COM', 'COM - Comercial'),
                    ('ADM', 'ADM - Administrativo'),
                    ('FIN', 'FIN - Financiero'),
                    ('TH', 'TH - Talento Humano'),
                    ('MTO', 'MTO - Mantenimiento'),
                    ('TI', 'TI - Tecnología'),
                ],
                default='',
                help_text='Área o proceso (ej: SST, CAL, PROD)',
                max_length=10,
                verbose_name='Código de Contexto',
            ),
        ),
        # Agregar campo include_context
        migrations.AddField(
            model_name='consecutivoconfig',
            name='include_context',
            field=models.BooleanField(
                default=False,
                help_text='Si se incluye el código de área/proceso en el consecutivo',
                verbose_name='Incluir Contexto',
            ),
        ),
        # Actualizar choices de document_type para incluir nuevos tipos
        migrations.AlterField(
            model_name='consecutivoconfig',
            name='document_type',
            field=models.CharField(
                choices=[
                    # Operacionales
                    ('RECOLECCION', 'Recolección / Voucher'),
                    ('RECEPCION', 'Recepción de Materia Prima'),
                    ('LOTE', 'Lote de Producción'),
                    ('DESPACHO', 'Despacho'),
                    ('FACTURA', 'Factura'),
                    ('ORDEN_COMPRA', 'Orden de Compra'),
                    ('REQUISICION', 'Requisición'),
                    ('REMISION', 'Remisión'),
                    ('COTIZACION', 'Cotización'),
                    ('ORDEN_TRABAJO', 'Orden de Trabajo'),
                    ('ACTA_COMITE', 'Acta de Comité'),
                    # Sistema de Gestión
                    ('PROCEDIMIENTO', 'Procedimiento'),
                    ('INSTRUCTIVO', 'Instructivo'),
                    ('FORMATO', 'Formato'),
                    ('PROTOCOLO', 'Protocolo'),
                    ('MANUAL', 'Manual'),
                    ('PROGRAMA', 'Programa'),
                    ('PLAN', 'Plan'),
                    # Calidad y SST
                    ('NO_CONFORMIDAD', 'No Conformidad'),
                    ('ACCION_CORRECTIVA', 'Acción Correctiva'),
                    ('ACCION_PREVENTIVA', 'Acción Preventiva'),
                    ('ACCION_MEJORA', 'Acción de Mejora'),
                    ('INCIDENTE', 'Reporte de Incidente'),
                    ('ACCIDENTE', 'Reporte de Accidente'),
                    ('INVESTIGACION', 'Investigación'),
                    ('AUDITORIA', 'Auditoría'),
                    ('CAPACITACION', 'Capacitación'),
                    # Proveedores/Clientes
                    ('PROVEEDOR_MP', 'Código Proveedor Materia Prima'),
                    ('PROVEEDOR_PS', 'Código Proveedor Productos/Servicios'),
                    ('CLIENTE', 'Código Cliente'),
                    ('ECOALIADO', 'Código Ecoaliado'),
                    # Pruebas
                    ('PRUEBA_ACIDEZ', 'Prueba de Acidez'),
                    ('ANALISIS_CALIDAD', 'Análisis de Calidad'),
                ],
                max_length=30,
                unique=True,
                verbose_name='Tipo de Documento',
            ),
        ),
    ]
