# Generated by Django 5.0.9 on production

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reorder_talent_hub_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_setup_expires',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del token de configuración', null=True, verbose_name='Expiración token contraseña'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_setup_token',
            field=models.CharField(blank=True, help_text='Token único para configurar contraseña inicial', max_length=64, null=True, verbose_name='Token de configuración de contraseña'),
        ),
    ]
