# Generated by Django 5.0.9 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_password_setup_expires_and_more'),
        ('gestion_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proveedor',
            field=models.ForeignKey(
                blank=True,
                help_text='Solo para usuarios externos (consultores, auditores, proveedores de servicios)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuarios_vinculados',
                to='gestion_proveedores.proveedor',
                verbose_name='Proveedor vinculado',
            ),
        ),
    ]
