# Generated by Django migration for initial ConsecutivoConfig data

from django.db import migrations
from django.utils import timezone


def create_initial_consecutivos(apps, schema_editor):
    """
    Crea las configuraciones iniciales de consecutivos para los tipos
    de documento que ya están en uso en el sistema.

    Esto asegura que los modelos existentes (Recoleccion, Proveedor,
    RecepcionMateriaPrima, PruebaAcidez) puedan usar el servicio
    centralizado.
    """
    ConsecutivoConfig = apps.get_model('core', 'ConsecutivoConfig')
    today = timezone.now().date()

    # Configuraciones iniciales basadas en los formatos actuales del sistema
    initial_configs = [
        # === OPERACIONALES ===
        {
            'document_type': 'RECOLECCION',
            'prefix': 'REC',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': True,  # REC-YYYYMMDD-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'RECEPCION',
            'prefix': 'RMP',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': True,  # RMP-YYYYMMDD-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'FACTURA',
            'prefix': 'FAC',
            'padding': 6,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'ORDEN_COMPRA',
            'prefix': 'OC',
            'padding': 5,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'REQUISICION',
            'prefix': 'REQ',
            'padding': 5,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'REMISION',
            'prefix': 'REM',
            'padding': 5,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },

        # === PROVEEDORES/CLIENTES ===
        {
            'document_type': 'PROVEEDOR_MP',
            'prefix': 'MP',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': False,  # MP-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'PROVEEDOR_PS',
            'prefix': 'PS',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': False,  # PS-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'ECOALIADO',
            'prefix': 'ECO',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': False,  # ECO-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },

        # === PRUEBAS/ANÁLISIS ===
        {
            'document_type': 'PRUEBA_ACIDEZ',
            'prefix': 'ACID',
            'padding': 4,
            'include_year': False,
            'include_month': False,
            'include_day': True,  # ACID-YYYYMMDD-0001
            'separator': '-',
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },

        # === CALIDAD Y SST ===
        {
            'document_type': 'NO_CONFORMIDAD',
            'prefix': 'NC',
            'padding': 4,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': '',  # Se puede usar con SST, CAL, etc
            'include_context': True,
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'ACCION_CORRECTIVA',
            'prefix': 'AC',
            'padding': 4,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': '',
            'include_context': True,
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'INCIDENTE',
            'prefix': 'INC',
            'padding': 4,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': 'SST',
            'include_context': True,
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'ACCIDENTE',
            'prefix': 'ACC',
            'padding': 4,
            'include_year': True,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': 'SST',
            'include_context': True,
            'reset_yearly': True,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },

        # === DOCUMENTOS DE GESTIÓN ===
        {
            'document_type': 'PROCEDIMIENTO',
            'prefix': 'PROC',
            'padding': 3,
            'include_year': False,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': '',
            'include_context': True,  # PROC-SST-001, PROC-CAL-001
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'INSTRUCTIVO',
            'prefix': 'INST',
            'padding': 3,
            'include_year': False,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': '',
            'include_context': True,
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
        {
            'document_type': 'FORMATO',
            'prefix': 'FORM',
            'padding': 3,
            'include_year': False,
            'include_month': False,
            'include_day': False,
            'separator': '-',
            'context_code': '',
            'include_context': True,
            'reset_yearly': False,
            'reset_monthly': False,
            'is_active': True,
            'current_number': 0,
            'last_reset_date': today,
        },
    ]

    for config_data in initial_configs:
        # Solo crear si no existe
        if not ConsecutivoConfig.objects.filter(document_type=config_data['document_type']).exists():
            ConsecutivoConfig.objects.create(**config_data)


def reverse_initial_consecutivos(apps, schema_editor):
    """Elimina las configuraciones iniciales de consecutivos."""
    ConsecutivoConfig = apps.get_model('core', 'ConsecutivoConfig')

    initial_types = [
        'RECOLECCION', 'RECEPCION', 'FACTURA', 'ORDEN_COMPRA',
        'REQUISICION', 'REMISION', 'PROVEEDOR_MP', 'PROVEEDOR_PS',
        'ECOALIADO', 'PRUEBA_ACIDEZ', 'NO_CONFORMIDAD', 'ACCION_CORRECTIVA',
        'INCIDENTE', 'ACCIDENTE', 'PROCEDIMIENTO', 'INSTRUCTIVO', 'FORMATO',
    ]

    ConsecutivoConfig.objects.filter(document_type__in=initial_types).delete()


class Migration(migrations.Migration):
    """
    Migración de datos para crear configuraciones iniciales de consecutivos.
    """

    dependencies = [
        ('core', '0010_extend_consecutivo_config'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_consecutivos,
            reverse_initial_consecutivos,
        ),
    ]
