# Generated by Django 5.0.9 on 2026-01-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_cargosectionaccess_custom_actions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandingconfig",
            options={
                "verbose_name": "Configuracion de Branding",
                "verbose_name_plural": "Configuraciones de Branding",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["orden", "name"],
                "verbose_name": "Item de Menu",
                "verbose_name_plural": "Items de Menu",
            },
        ),
        migrations.AlterModelOptions(
            name="moduletab",
            options={
                "ordering": ["module", "orden", "name"],
                "verbose_name": "Tab de Modulo",
                "verbose_name_plural": "Tabs de Modulos",
            },
        ),
        migrations.AlterModelOptions(
            name="systemmodule",
            options={
                "ordering": ["category", "orden", "name"],
                "verbose_name": "Modulo del Sistema",
                "verbose_name_plural": "Modulos del Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="tabsection",
            options={
                "ordering": ["tab", "orden", "name"],
                "verbose_name": "Seccion de Tab",
                "verbose_name_plural": "Secciones de Tabs",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="sede_nombre",
        ),
        migrations.AlterField(
            model_name="brandingconfig",
            name="app_version",
            field=models.CharField(
                default="2.0.0",
                help_text="Version que se muestra en el login y footer",
                max_length=20,
                verbose_name="Version de la Aplicacion",
            ),
        ),
        migrations.AlterField(
            model_name="brandingconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="brandingconfig",
            name="login_background",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de fondo para la pagina de login (recomendado: 1920x1080)",
                null=True,
                upload_to="branding/backgrounds/",
                verbose_name="Imagen de Fondo Login",
            ),
        ),
        migrations.AlterField(
            model_name="brandingconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="allow_all",
            field=models.BooleanField(
                default=False,
                help_text="Si esta activo, todos los usuarios autenticados pueden ver este item",
                verbose_name="Permitir todos",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico del item de menu (ej: menu.econorte)",
                max_length=50,
                unique=True,
                verbose_name="Codigo",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("purple", "Purpura"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("orange", "Naranja"),
                    ("red", "Rojo"),
                    ("gray", "Gris"),
                ],
                help_text="Color del item (solo para items de nivel 0)",
                max_length=20,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_category",
            field=models.BooleanField(
                default=False,
                help_text="Si es una categoria (sin ruta)",
                verbose_name="Es categoria",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="macroprocess",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECCION_ESTRATEGICA", "Direccion Estrategica"),
                    ("GESTION_MISIONAL", "Gestion Misional"),
                    ("GESTION_APOYO", "Gestion de Apoyo"),
                    ("GESTION_INTEGRAL", "Gestion Integral"),
                ],
                db_index=True,
                help_text="Categoria del sistema a la que pertenece (solo para items de nivel 0 - Legacy: usar SystemModule.category)",
                max_length=30,
                null=True,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(
                help_text="Nombre visible en el menu",
                max_length=100,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="orden",
            field=models.IntegerField(
                default=0,
                help_text="Orden de aparicion en el menu",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de menu padre (para jerarquia)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.menuitem",
                verbose_name="Item padre",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico del tab (ej: identidad, plan_estrategico)",
                max_length=50,
                verbose_name="Codigo",
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripcion de las funcionalidades del tab",
                null=True,
                verbose_name="Descripcion",
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="is_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Si el tab esta activo en el sistema",
                verbose_name="Habilitado",
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="core.systemmodule",
                verbose_name="Modulo",
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="orden",
            field=models.PositiveIntegerField(
                default=0, help_text="Orden de aparicion del tab", verbose_name="Orden"
            ),
        ),
        migrations.AlterField(
            model_name="moduletab",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="category",
            field=models.CharField(
                choices=[
                    ("ESTRATEGICO", "Nivel Estrategico"),
                    ("MOTOR", "Motores del Sistema"),
                    ("INTEGRAL", "Gestion Integral"),
                    ("MISIONAL", "Nivel Misional"),
                    ("APOYO", "Nivel de Apoyo"),
                    ("INTELIGENCIA", "Inteligencia de Negocio"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico del modulo (ej: apps.supply_chain)",
                max_length=50,
                unique=True,
                verbose_name="Codigo",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("purple", "Purpura"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("orange", "Naranja"),
                    ("red", "Rojo"),
                    ("gray", "Gris"),
                    ("yellow", "Amarillo"),
                    ("pink", "Rosa"),
                    ("indigo", "Indigo"),
                    ("teal", "Verde azulado"),
                ],
                help_text="Color del modulo (para visualizacion en UI)",
                max_length=20,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modulos que deben estar activos para que este funcione",
                related_name="dependents",
                to="core.systemmodule",
                verbose_name="Dependencias",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripcion de las funcionalidades del modulo",
                null=True,
                verbose_name="Descripcion",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="is_core",
            field=models.BooleanField(
                default=False,
                help_text="Los modulos core no pueden desactivarse",
                verbose_name="Es modulo core",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="is_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Si el modulo esta activo en el sistema",
                verbose_name="Habilitado",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="license_expires_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de expiracion de licencia"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="name",
            field=models.CharField(
                help_text="Nombre del modulo", max_length=100, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="requires_license",
            field=models.BooleanField(
                default=False,
                help_text="Si el modulo requiere licencia adicional",
                verbose_name="Requiere licencia",
            ),
        ),
        migrations.AlterField(
            model_name="systemmodule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico de la seccion (ej: mision_vision, valores)",
                max_length=50,
                verbose_name="Codigo",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripcion del contenido de la seccion",
                null=True,
                verbose_name="Descripcion",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="is_core",
            field=models.BooleanField(
                default=False,
                help_text="Las secciones core no pueden desactivarse",
                verbose_name="Es seccion core",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="is_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Si la seccion esta activa en el sistema",
                verbose_name="Habilitado",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="name",
            field=models.CharField(
                help_text="Nombre visible de la seccion (ej: Mision y Vision)",
                max_length=100,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="orden",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Orden de aparicion de la seccion",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="supported_actions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de codigos de acciones extra soportadas (ej: ["enviar", "aprobar"])',
                verbose_name="Acciones soportadas",
            ),
        ),
        migrations.AlterField(
            model_name="tabsection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
    ]
