# Generated by Django 5.0.9 on 2026-01-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_brandingconfig_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_background_color',
            field=models.CharField(blank=True, help_text='Color de fondo del splash screen (formato HEX)', max_length=7, null=True, verbose_name='Color de Fondo PWA'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_description',
            field=models.TextField(blank=True, help_text='Descripcion de la aplicacion para manifest.json', null=True, verbose_name='Descripcion PWA'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_icon_192',
            field=models.ImageField(blank=True, help_text='Icono para manifest.json (192x192 px, PNG)', null=True, upload_to='branding/pwa/', verbose_name='Icono PWA 192x192'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_icon_512',
            field=models.ImageField(blank=True, help_text='Icono para manifest.json (512x512 px, PNG)', null=True, upload_to='branding/pwa/', verbose_name='Icono PWA 512x512'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_icon_maskable',
            field=models.ImageField(blank=True, help_text='Icono maskable para Android (512x512 px, PNG con padding)', null=True, upload_to='branding/pwa/', verbose_name='Icono Maskable PWA'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_name',
            field=models.CharField(blank=True, help_text='Nombre completo de la app para manifest.json', max_length=200, null=True, verbose_name='Nombre PWA'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_short_name',
            field=models.CharField(blank=True, help_text='Nombre corto para iconos de app (max 12 caracteres recomendado)', max_length=50, null=True, verbose_name='Nombre Corto PWA'),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='pwa_theme_color',
            field=models.CharField(blank=True, help_text='Color de la barra de titulo del navegador (formato HEX)', max_length=7, null=True, verbose_name='Color de Tema PWA'),
        ),
    ]
