# Generated by Django 5.0.14 on 2026-03-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_cliente_fk_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="dias_laborales",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Días de la semana laborables (ej: ["LUN","MAR","MIE","JUE","VIE"])',
                verbose_name="Días Laborales",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="horario_entrada",
            field=models.TimeField(
                blank=True,
                help_text="Hora de inicio de jornada (ej: 07:00)",
                null=True,
                verbose_name="Horario de Entrada",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="horario_salida",
            field=models.TimeField(
                blank=True,
                help_text="Hora de fin de jornada (ej: 17:00)",
                null=True,
                verbose_name="Horario de Salida",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="turno_trabajo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIURNO", "Diurno"),
                    ("NOCTURNO", "Nocturno"),
                    ("MIXTO", "Mixto"),
                    ("ROTATIVO", "Rotativo"),
                    ("FLEXIBLE", "Flexible"),
                ],
                default="DIURNO",
                help_text="Tipo de turno asignado al cargo",
                max_length=20,
                verbose_name="Turno de Trabajo",
            ),
        ),
    ]
