# Generated by Django 5.0.9 on 2025-12-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_extend_cargo_user_models"),
        ("organizacion", "0003_populate_tipos_documento"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cargo",
            name="core_cargo_is_acti_389961_idx",
        ),
        migrations.RenameIndex(
            model_name="riesgoocupacional",
            new_name="core_riesgo_code_352b47_idx",
            old_name="core_riesgo_code_idx",
        ),
        migrations.RenameIndex(
            model_name="riesgoocupacional",
            new_name="core_riesgo_clasifi_8abd41_idx",
            old_name="core_riesgo_clasif_idx",
        ),
        migrations.AlterField(
            model_name="cargo",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción general del cargo",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "Operativo"),
                    (1, "Supervisión"),
                    (2, "Coordinación"),
                    (3, "Dirección"),
                ],
                default=0,
                help_text="Nivel jerárquico legacy (0=Operativo, 3=Dirección)",
                verbose_name="Nivel (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="parent_cargo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo al que reporta (supervisor directo)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to="core.cargo",
                verbose_name="Reporta a",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["is_active", "nivel_jerarquico"],
                name="core_cargo_is_acti_d4c742_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["area"], name="core_cargo_area_id_e6c9e3_idx"),
        ),
    ]
