# Generated by Django 5.0.9 on 2025-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_fix_area_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="requiere_licencia_sst",
            field=models.BooleanField(
                default=False,
                help_text="Si el cargo requiere Licencia en Seguridad y Salud en el Trabajo",
                verbose_name="Requiere Licencia SST",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="requiere_tarjeta_abogado",
            field=models.BooleanField(
                default=False,
                help_text="Si el cargo requiere Tarjeta Profesional de Abogado",
                verbose_name="Requiere Tarjeta Profesional Abogado",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="requiere_tarjeta_contador",
            field=models.BooleanField(
                default=False,
                help_text="Si el cargo requiere Tarjeta Profesional de Contador Público",
                verbose_name="Requiere Tarjeta Profesional Contador",
            ),
        ),
    ]
