# Generated by Django 5.0.9 on 2026-01-20 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_userpreferences"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="twofactorauth",
            name="core_two_fa_user_enabled_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="core_user_s_user_id_3a83a6_idx",
            old_name="core_user_s_user_id_is_act_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="core_user_s_refresh_c1236b_idx",
            old_name="core_user_s_refresh_tok_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="core_user_s_expires_9b142f_idx",
            old_name="core_user_s_expires_at_idx",
        ),
    ]
