# Generated by Django 5.0.9 on 2025-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_roles_adicionales_rbac_hibrido"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="roladicional",
            new_name="core_rol_ad_code_67aa02_idx",
            old_name="core_rol_ad_code_idx",
        ),
        migrations.RenameIndex(
            model_name="roladicional",
            new_name="core_rol_ad_tipo_1f1d39_idx",
            old_name="core_rol_ad_tipo_active_idx",
        ),
        migrations.RenameIndex(
            model_name="roladicional",
            new_name="core_rol_ad_is_acti_6a830e_idx",
            old_name="core_rol_ad_active_idx",
        ),
        migrations.RenameIndex(
            model_name="userroladicional",
            new_name="core_user_r_user_id_39ff03_idx",
            old_name="core_user_r_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="userroladicional",
            new_name="core_user_r_expires_adac39_idx",
            old_name="core_user_r_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="userroladicional",
            new_name="core_user_r_certifi_c85d1a_idx",
            old_name="core_user_r_cert_exp_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="roles_adicionales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles especiales asignados además del cargo base (COPASST, Brigadista, etc.)",
                related_name="users",
                through="core.UserRolAdicional",
                to="core.roladicional",
                verbose_name="Roles Adicionales",
            ),
        ),
    ]
