# Generated by Django 5.0.9 on 2025-12-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_rename_order_to_orden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["orden", "name"],
                "verbose_name": "Item de Menú",
                "verbose_name_plural": "Items de Menú",
            },
        ),
        migrations.AlterModelOptions(
            name="moduletab",
            options={
                "ordering": ["module", "orden", "name"],
                "verbose_name": "Tab de Módulo",
                "verbose_name_plural": "Tabs de Módulos",
            },
        ),
        migrations.AlterModelOptions(
            name="systemmodule",
            options={
                "ordering": ["category", "orden", "name"],
                "verbose_name": "Módulo del Sistema",
                "verbose_name_plural": "Módulos del Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="tabsection",
            options={
                "ordering": ["tab", "orden", "name"],
                "verbose_name": "Sección de Tab",
                "verbose_name_plural": "Secciones de Tabs",
            },
        ),
        migrations.RemoveIndex(
            model_name="menuitem",
            name="core_menu_i_is_acti_f5145f_idx",
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_active", "orden"], name="core_menu_i_is_acti_19ecdb_idx"
            ),
        ),
    ]
