# Generated by Django 5.0.9 on 2026-01-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_menuitem_options_alter_moduletab_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingconfig",
            name="app_version",
            field=models.CharField(
                default="2.0.0",
                help_text="Versión que se muestra en el login y footer",
                max_length=20,
                verbose_name="Versión de la Aplicación",
            ),
        ),
        migrations.AddField(
            model_name="brandingconfig",
            name="login_background",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de fondo para la página de login (recomendado: 1920x1080)",
                null=True,
                upload_to="branding/backgrounds/",
                verbose_name="Imagen de Fondo Login",
            ),
        ),
    ]
