# Generated by Django 5.0.9 on 2025-11-20 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "proveedores",
            "0004_remove_proveedor_proveedores_subtipo_9348ba_idx_and_more",
        ),
    ]

    operations = [
        # RemoveIndex y RemoveField forma_pago comentados porque ya fueron eliminados
        # migrations.RemoveIndex(
        #     model_name="proveedor",
        #     name="proveedores_subtipo_9348ba_idx",
        # ),
        # migrations.RemoveField(
        #     model_name="proveedor",
        #     name="forma_pago",
        # ),
        migrations.RemoveField(
            model_name="proveedor",
            name="latitud",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="longitud",
        ),
    ]
