# Generated by Django 5.0.9 on 2025-11-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0013_create_prueba_acidez"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialprecioproveedor",
            name="tipo_materia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HUESO_CRUDO", "Hueso Crudo"),
                    ("HUESO_SECO", "Hueso Seco"),
                    ("HUESO_CALCINADO", "Hueso Calcinado"),
                    ("HUESO_CENIZA", "Hueso Ceniza"),
                    ("SEBO_CRUDO_CARNICERIA", "Sebo Crudo Carnicería"),
                    ("SEBO_CRUDO_MATADERO", "Sebo Crudo Matadero"),
                    ("SEBO_CUERO", "Sebo de Cuero"),
                    ("SEBO_CUERO_VIRIL", "Sebo de Cuero de Viril"),
                    ("SEBO_POLLO", "Sebo Pollo"),
                    ("SEBO_PROCESADO_A", "Sebo Procesado Tipo A (1-5% Acidez)"),
                    ("SEBO_PROCESADO_B", "Sebo Procesado Tipo B (5.1-8% Acidez)"),
                    ("SEBO_PROCESADO_B1", "Sebo Procesado Tipo B1 (8.1-10% Acidez)"),
                    ("SEBO_PROCESADO_B2", "Sebo Procesado Tipo B2 (10.1-15% Acidez)"),
                    ("SEBO_PROCESADO_B4", "Sebo Procesado Tipo B4 (15.1-20% Acidez)"),
                    ("SEBO_PROCESADO_C", "Sebo Procesado Tipo C (>20.1% Acidez)"),
                    ("CHICHARRON", "Chicharrón"),
                    ("CABEZAS", "Cabezas"),
                    ("ACU", "ACU - Aceite de Cocina Usado"),
                ],
                help_text="Código específico de materia prima (ej: HUESO_CRUDO, SEBO_PROCESADO_A)",
                max_length=25,
                null=True,
                verbose_name="Código de materia prima",
            ),
        ),
        migrations.AlterField(
            model_name="preciomateriaprima",
            name="tipo_materia",
            field=models.CharField(
                choices=[
                    ("HUESO_CRUDO", "Hueso Crudo"),
                    ("HUESO_SECO", "Hueso Seco"),
                    ("HUESO_CALCINADO", "Hueso Calcinado"),
                    ("HUESO_CENIZA", "Hueso Ceniza"),
                    ("SEBO_CRUDO_CARNICERIA", "Sebo Crudo Carnicería"),
                    ("SEBO_CRUDO_MATADERO", "Sebo Crudo Matadero"),
                    ("SEBO_CUERO", "Sebo de Cuero"),
                    ("SEBO_CUERO_VIRIL", "Sebo de Cuero de Viril"),
                    ("SEBO_POLLO", "Sebo Pollo"),
                    ("SEBO_PROCESADO_A", "Sebo Procesado Tipo A (1-5% Acidez)"),
                    ("SEBO_PROCESADO_B", "Sebo Procesado Tipo B (5.1-8% Acidez)"),
                    ("SEBO_PROCESADO_B1", "Sebo Procesado Tipo B1 (8.1-10% Acidez)"),
                    ("SEBO_PROCESADO_B2", "Sebo Procesado Tipo B2 (10.1-15% Acidez)"),
                    ("SEBO_PROCESADO_B4", "Sebo Procesado Tipo B4 (15.1-20% Acidez)"),
                    ("SEBO_PROCESADO_C", "Sebo Procesado Tipo C (>20.1% Acidez)"),
                    ("CHICHARRON", "Chicharrón"),
                    ("CABEZAS", "Cabezas"),
                    ("ACU", "ACU - Aceite de Cocina Usado"),
                ],
                help_text="Código específico de materia prima (ej: HUESO_CRUDO, SEBO_PROCESADO_A)",
                max_length=25,
                verbose_name="Código de materia prima",
            ),
        ),
    ]
