# Generated by Django 5.0.9 on 2025-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0016_update_codigo_interno_prefixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="codigo_interno",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Código único autogenerado (MP-0001 para materia prima, PS-0001 para productos/servicios)",
                max_length=20,
                unique=True,
                verbose_name="Código interno",
            ),
        ),
    ]
