# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptonomina",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del concepto (ej: SAL_BASICO, HE_DIURNA)",
                max_length=20,
                verbose_name="Código",
            ),
        ),
    ]
