# Generated by Django 5.0.9 on 2025-12-14 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0013_delete_consecutivoconfig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del plan estratégico (ej: Plan Estratégico 2024-2026)",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción y alcance del plan",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("ANUAL", "Anual"),
                            ("BIANUAL", "Bianual"),
                            ("TRIANUAL", "Trianual"),
                            ("QUINQUENAL", "Quinquenal"),
                        ],
                        default="ANUAL",
                        max_length=20,
                        verbose_name="Tipo de período",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Fecha de inicio del plan",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Fecha de finalización del plan",
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "strategic_map_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="strategic_plans/maps/",
                        verbose_name="Imagen del Mapa Estratégico",
                    ),
                ),
                (
                    "strategic_map_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción del Mapa Estratégico",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Estratégico",
                "verbose_name_plural": "Planes Estratégicos",
                "db_table": "planeacion_strategic_plan",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del objetivo (ej: OE-001)",
                        max_length=20,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del objetivo estratégico",
                        max_length=300,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del objetivo",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "bsc_perspective",
                    models.CharField(
                        choices=[
                            ("FINANCIERA", "Financiera"),
                            ("CLIENTES", "Clientes"),
                            ("PROCESOS", "Procesos Internos"),
                            ("APRENDIZAJE", "Aprendizaje y Crecimiento"),
                        ],
                        db_index=True,
                        help_text="Perspectiva del Balanced Scorecard",
                        max_length=20,
                        verbose_name="Perspectiva BSC",
                    ),
                ),
                (
                    "iso_standards",
                    models.JSONField(
                        default=list,
                        help_text="Lista de normas ISO vinculadas",
                        verbose_name="Normas ISO",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor meta del indicador",
                        max_digits=10,
                        null=True,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor actual del indicador",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Actual",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unidad de medida (%, $, unidades, etc.)",
                        max_length=20,
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        help_text="Porcentaje de avance (0-100)",
                        verbose_name="Progreso %",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                            ("RETRASADO", "Retrasado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "responsible_cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives_responsible",
                        to="core.cargo",
                        verbose_name="Cargo Responsable",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="planeacion.strategicplan",
                        verbose_name="Plan Estratégico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo Estratégico",
                "verbose_name_plural": "Objetivos Estratégicos",
                "db_table": "planeacion_strategic_objective",
                "ordering": ["bsc_perspective", "order", "code"],
                "unique_together": {("plan", "code")},
            },
        ),
    ]
