# Generated by Django 5.0.14 on 2026-02-05 22:35
# Agrega FK de StrategicObjective a EstrategiaTOWS (relación inversa)
# Esto elimina la dependencia circular: contexto ya no depende de planeacion

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estrategica_contexto', '0002_remove_circular_dependency'),
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='estrategia_origen',
            field=models.ForeignKey(
                blank=True,
                help_text='Estrategia TOWS de la que se derivó este objetivo',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='objetivos_derivados',
                to='gestion_estrategica_contexto.estrategiatows',
                verbose_name='Estrategia TOWS de Origen'
            ),
        ),
    ]
