# Generated by Django 5.0.9 on 2025-12-25 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planeacion", "0003_rename_order_to_orden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategicobjective",
            options={
                "ordering": ["bsc_perspective", "orden", "code"],
                "verbose_name": "Objetivo Estratégico",
                "verbose_name_plural": "Objetivos Estratégicos",
            },
        ),
    ]
