# Generated by Django 5.0.9 on 2026-01-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_dynamic_models_dia6'),
        ('gestion_clientes', '0001_initial'),
        ('pipeline_ventas', '0001_initial'),
        ('producto_terminado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(help_text='Producto cotizado', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_detalle', to='producto_terminado.productoterminado', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='etapaventa',
            index=models.Index(fields=['codigo'], name='pipeline_et_codigo_6c9fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='etapaventa',
            index=models.Index(fields=['orden', 'activo'], name='pipeline_et_orden_a58290_idx'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='cambiado_por',
            field=models.ForeignKey(help_text='Usuario que realizó el cambio', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_etapa_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='etapa_anterior',
            field=models.ForeignKey(help_text='Etapa desde la cual se movió', on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_anterior', to='pipeline_ventas.etapaventa', verbose_name='Etapa Anterior'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='etapa_nueva',
            field=models.ForeignKey(help_text='Etapa a la cual se movió', on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_nueva', to='pipeline_ventas.etapaventa', verbose_name='Etapa Nueva'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente asociado a la oportunidad', on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='gestion_clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etapa_actual',
            field=models.ForeignKey(help_text='Etapa actual en el pipeline', on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='pipeline_ventas.etapaventa', verbose_name='Etapa Actual'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='fuente',
            field=models.ForeignKey(help_text='Canal u origen de la oportunidad', on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='pipeline_ventas.fuenteoportunidad', verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='motivo_perdida',
            field=models.ForeignKey(blank=True, help_text='Motivo por el cual se perdió la oportunidad (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_perdidas', to='pipeline_ventas.motivoperdida', verbose_name='Motivo de Pérdida'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='vendedor',
            field=models.ForeignKey(help_text='Usuario responsable de la oportunidad', on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='oportunidad',
            field=models.ForeignKey(help_text='Oportunidad asociada', on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='pipeline_ventas.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='oportunidad',
            field=models.ForeignKey(blank=True, help_text='Oportunidad asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='pipeline_ventas.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AddField(
            model_name='seguimientooportunidad',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='seguimientooportunidad',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='seguimientooportunidad',
            name='oportunidad',
            field=models.ForeignKey(help_text='Oportunidad a la que pertenece el seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pipeline_ventas.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AddField(
            model_name='seguimientooportunidad',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que registró el seguimiento', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='seguimientooportunidad',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='detallecotizacion',
            index=models.Index(fields=['cotizacion', 'orden'], name='pipeline_de_cotizac_7f7a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['codigo'], name='pipeline_op_codigo_f90f49_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['empresa', 'etapa_actual'], name='pipeline_op_empresa_5dfca3_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['vendedor', 'etapa_actual'], name='pipeline_op_vendedo_afdefe_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['fecha_cierre_estimada'], name='pipeline_op_fecha_c_fc94c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oportunidad',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='historialetapa',
            index=models.Index(fields=['oportunidad', 'fecha_cambio'], name='pipeline_hi_oportun_d4639c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['codigo'], name='pipeline_co_codigo_685ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'estado'], name='pipeline_co_empresa_0dd367_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente', 'estado'], name='pipeline_co_cliente_57dc17_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_vencimiento'], name='pipeline_co_fecha_v_b6f5bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacion',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='seguimientooportunidad',
            index=models.Index(fields=['oportunidad', 'fecha'], name='pipeline_se_oportun_2e802f_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientooportunidad',
            index=models.Index(fields=['fecha_proxima'], name='pipeline_se_fecha_p_b607df_idx'),
        ),
    ]
