# Generated by Django 5.0.9 on 2026-01-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_contable', '0001_initial'),
        ('configuracion', '0003_dynamic_models_dia6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Informe')),
                ('tipo_informe', models.CharField(choices=[('balance_general', 'Balance General'), ('estado_resultados', 'Estado de Resultados (P&G)'), ('flujo_efectivo', 'Estado de Flujos de Efectivo'), ('cambios_patrimonio', 'Estado de Cambios en el Patrimonio'), ('auxiliar_cuentas', 'Auxiliar de Cuentas'), ('balance_prueba', 'Balance de Prueba'), ('personalizado', 'Informe Personalizado')], db_index=True, max_length=30, verbose_name='Tipo de Informe')),
                ('nivel_detalle', models.IntegerField(choices=[(1, 'Clase'), (2, 'Grupo'), (3, 'Cuenta'), (4, 'Subcuenta'), (5, 'Auxiliar')], default=3, verbose_name='Nivel de Detalle')),
                ('incluye_saldo_cero', models.BooleanField(default=False, verbose_name='Incluye Saldos en Cero')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Informe Contable',
                'verbose_name_plural': 'Informes Contables',
                'db_table': 'accounting_informe_contable',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='GeneracionInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('fecha_desde', models.DateField(db_index=True, verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(db_index=True, verbose_name='Fecha Hasta')),
                ('resultado_json', models.JSONField(default=dict, verbose_name='Resultado JSON')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contabilidad/informes/%Y/%m/', verbose_name='Archivo PDF')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='contabilidad/informes/%Y/%m/', verbose_name='Archivo Excel')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], db_index=True, default='generando', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_contable.centrocostocontable', verbose_name='Centro de Costo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones', to='informes_contables.informecontable', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Generación de Informe',
                'verbose_name_plural': 'Generaciones de Informes',
                'db_table': 'accounting_generacion_informe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField(verbose_name='Secuencia')),
                ('codigo_linea', models.CharField(max_length=20, verbose_name='Código de Línea')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo_linea', models.CharField(choices=[('cuenta', 'Cuenta Específica'), ('rango', 'Rango de Cuentas'), ('formula', 'Fórmula'), ('titulo', 'Título (no suma)'), ('subtotal', 'Subtotal'), ('total', 'Total')], max_length=20, verbose_name='Tipo de Línea')),
                ('formula', models.CharField(blank=True, help_text='Fórmula de cálculo (ej: A1 + A2 - A3)', max_length=500, verbose_name='Fórmula')),
                ('nivel_indentacion', models.IntegerField(default=0, verbose_name='Nivel de Indentación')),
                ('negrita', models.BooleanField(default=False, verbose_name='Negrita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_informe_desde', to='config_contable.cuentacontable', verbose_name='Cuenta Desde')),
                ('cuenta_hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_informe_hasta', to='config_contable.cuentacontable', verbose_name='Cuenta Hasta')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='informes_contables.informecontable', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Línea de Informe',
                'verbose_name_plural': 'Líneas de Informes',
                'db_table': 'accounting_linea_informe',
                'ordering': ['informe', 'secuencia'],
            },
        ),
        migrations.AddIndex(
            model_name='informecontable',
            index=models.Index(fields=['empresa', 'codigo'], name='accounting__empresa_6d5e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='informecontable',
            index=models.Index(fields=['tipo_informe'], name='accounting__tipo_in_b35d92_idx'),
        ),
        migrations.AddConstraint(
            model_name='informecontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_informe_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='generacioninforme',
            index=models.Index(fields=['empresa', 'informe', 'created_at'], name='accounting__empresa_614e80_idx'),
        ),
        migrations.AddIndex(
            model_name='generacioninforme',
            index=models.Index(fields=['fecha_desde', 'fecha_hasta'], name='accounting__fecha_d_6ce68c_idx'),
        ),
        migrations.AddIndex(
            model_name='lineainforme',
            index=models.Index(fields=['informe', 'secuencia'], name='accounting__informe_e50846_idx'),
        ),
    ]
