# Generated by Django 5.0.9 on 2026-01-05 19:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('configuracion', '0003_dynamic_models_dia6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del turno (Ej: T1, MAÑANA, NOCHE)', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Turno')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la jornada', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la jornada', verbose_name='Hora de Fin')),
                ('duracion_jornada', models.DecimalField(decimal_places=2, help_text='Horas totales de la jornada', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Duración de Jornada (horas)')),
                ('aplica_recargo_nocturno', models.BooleanField(default=False, help_text='Si el turno incluye horas nocturnas (10pm - 6am)', verbose_name='Aplica Recargo Nocturno')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días en que aplica el turno. Ej: ["lunes", "martes", ...]', verbose_name='Días de la Semana')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'talent_hub_turno',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha del registro de asistencia', verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('hora_entrada_almuerzo', models.TimeField(blank=True, null=True, verbose_name='Hora Entrada Almuerzo')),
                ('hora_salida_almuerzo', models.TimeField(blank=True, null=True, verbose_name='Hora Salida Almuerzo')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('permiso', 'Permiso'), ('incapacidad', 'Incapacidad'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia')], db_index=True, default='presente', max_length=15, verbose_name='Estado de Asistencia')),
                ('minutos_tardanza', models.PositiveIntegerField(default=0, help_text='Minutos de retraso (calculado automáticamente)', verbose_name='Minutos de Tardanza')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_asistencia', to='control_tiempo.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'talent_hub_registro_asistencia',
                'ordering': ['-fecha', 'colaborador'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual aplica el turno', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha hasta la cual aplica (null = indefinido)', null=True, verbose_name='Fecha de Fin')),
                ('es_rotativo', models.BooleanField(default=False, help_text='Si el turno rota con otros', verbose_name='Es Rotativo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='control_tiempo.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'db_table': 'talent_hub_asignacion_turno',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('dias_trabajados', models.PositiveIntegerField(default=0, verbose_name='Días Trabajados')),
                ('dias_ausente', models.PositiveIntegerField(default=0, verbose_name='Días Ausente')),
                ('dias_tardanza', models.PositiveIntegerField(default=0, verbose_name='Días con Tardanza')),
                ('total_horas_trabajadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total Horas Trabajadas')),
                ('total_horas_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total Horas Extras')),
                ('total_minutos_tardanza', models.PositiveIntegerField(default=0, verbose_name='Total Minutos de Tardanza')),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje de Asistencia')),
                ('cerrado', models.BooleanField(db_index=True, default=False, help_text='Si el consolidado está cerrado para modificaciones', verbose_name='Cerrado')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado Por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_asistencia', to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Consolidado de Asistencia',
                'verbose_name_plural': 'Consolidados de Asistencia',
                'db_table': 'talent_hub_consolidado_asistencia',
                'ordering': ['-anio', '-mes', 'colaborador'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='talent_hub__anio_784141_idx'), models.Index(fields=['colaborador', 'anio', 'mes'], name='talent_hub__colabor_ca1b86_idx'), models.Index(fields=['cerrado'], name='talent_hub__cerrado_9c83f9_idx'), models.Index(fields=['empresa', 'anio', 'mes'], name='talent_hub__empresa_f60fac_idx')],
                'unique_together': {('colaborador', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha en que se trabajaron las horas extras', verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('tipo', models.CharField(choices=[('diurna', 'Diurna - Recargo 25%'), ('nocturna', 'Nocturna - Recargo 75%'), ('dominical_diurna', 'Dominical Diurna - Recargo 75%'), ('dominical_nocturna', 'Dominical Nocturna - Recargo 110%'), ('festivo_diurna', 'Festivo Diurna - Recargo 75%'), ('festivo_nocturna', 'Festivo Nocturna - Recargo 110%')], db_index=True, max_length=25, verbose_name='Tipo de Hora Extra')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, help_text='Horas extras trabajadas (calculado automáticamente)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Horas Trabajadas')),
                ('factor_recargo', models.DecimalField(decimal_places=2, help_text='Multiplicador según tipo (1.25, 1.75, 2.10)', max_digits=4, verbose_name='Factor de Recargo')),
                ('justificacion', models.TextField(help_text='Motivo o actividad que justifica las horas extras', verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Hora Extra',
                'verbose_name_plural': 'Horas Extras',
                'db_table': 'talent_hub_hora_extra',
                'ordering': ['-fecha', 'colaborador'],
                'indexes': [models.Index(fields=['fecha'], name='talent_hub__fecha_1125d4_idx'), models.Index(fields=['colaborador', 'fecha'], name='talent_hub__colabor_1d9cda_idx'), models.Index(fields=['estado'], name='talent_hub__estado_3c4a23_idx'), models.Index(fields=['tipo'], name='talent_hub__tipo_86fc73_idx'), models.Index(fields=['empresa', 'fecha'], name='talent_hub__empresa_679c94_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'codigo'], name='talent_hub__empresa_ffd2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'is_active'], name='talent_hub__empresa_2bb62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['fecha'], name='talent_hub__fecha_e8225a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['colaborador', 'fecha'], name='talent_hub__colabor_347b18_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['estado'], name='talent_hub__estado_e7148b_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['empresa', 'fecha'], name='talent_hub__empresa_ac0a9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('colaborador', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='asignacionturno',
            index=models.Index(fields=['colaborador', 'fecha_inicio'], name='talent_hub__colabor_fae12e_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionturno',
            index=models.Index(fields=['turno'], name='talent_hub__turno_i_ef0bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionturno',
            index=models.Index(fields=['empresa', 'is_active'], name='talent_hub__empresa_05b1ee_idx'),
        ),
    ]
