# Generated by Django 5.0.14 on 2026-03-02 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_legacy_fields"),
        (
            "control_tiempo",
            "0006_turno_qr_token_marcajetiempo_registroasistencia_justificacion",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="marcajetiempo",
            new_name="talent_hub__colabor_4a363e_idx",
            old_name="talent_hub_marcaje_colab_fh_idx",
        ),
        migrations.RenameIndex(
            model_name="marcajetiempo",
            new_name="talent_hub__empresa_0bf0d3_idx",
            old_name="talent_hub_marcaje_emp_fh_idx",
        ),
        migrations.RenameIndex(
            model_name="marcajetiempo",
            new_name="talent_hub__tipo_be83f2_idx",
            old_name="talent_hub_marcaje_tipo_idx",
        ),
        migrations.AlterField(
            model_name="marcajetiempo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="marcajetiempo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="marcajetiempo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
    ]
