# Generated by Django 5.0.9 on 2026-01-25 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_proyectos", "0001_initial"),
        ("planeacion", "0002_strategicobjective_areas_responsables"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="origen_cambio",
            field=models.ForeignKey(
                blank=True,
                help_text="Cambio organizacional que originó este proyecto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_generados",
                to="planeacion.gestioncambio",
                verbose_name="Cambio de Origen",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="origen_objetivo",
            field=models.ForeignKey(
                blank=True,
                help_text="Objetivo estratégico al que contribuye este proyecto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_vinculados",
                to="planeacion.strategicobjective",
                verbose_name="Objetivo Estratégico",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo_origen",
            field=models.CharField(
                choices=[
                    ("manual", "Creación Manual"),
                    ("cambio", "Desde Gestión de Cambios"),
                    ("objetivo", "Desde Objetivo Estratégico"),
                    ("auditoria", "Desde Hallazgo de Auditoría"),
                    ("riesgo", "Desde Tratamiento de Riesgo"),
                    ("mejora", "Desde Acción de Mejora"),
                ],
                default="manual",
                help_text="Indica cómo se originó el proyecto",
                max_length=20,
                verbose_name="Tipo de Origen",
            ),
        ),
    ]
