# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_proyectos", "0003_actividadproyecto_kanban_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="actividadproyecto",
            new_name="gestion_pro_proyect_a4d0e4_idx",
            old_name="gestion_pro_proyect_kanban_idx",
        ),
    ]
