# Generated by Django 5.0.9 on 2026-01-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0002_initial"),
        ("organizacion", "0001_initial"),
        ("planeacion", "0002_strategicobjective_areas_responsables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoParteInteresada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("interna", "Interna"), ("externa", "Externa")],
                        default="externa",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de Parte Interesada",
                "verbose_name_plural": "Tipos de Partes Interesadas",
                "db_table": "contexto_tipo_parte_interesada",
                "ordering": ["orden", "categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AnalisisDOFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Análisis"
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 2025-Q1, 2025 Anual, Enero 2025",
                        max_length=50,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("vigente", "Vigente"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones y Conclusiones"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dofa_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dofa_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Análisis",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis DOFA",
                "verbose_name_plural": "Análisis DOFA",
                "db_table": "contexto_analisis_dofa",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="AnalisisPESTEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Análisis"
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 2025-Q1, 2025 Anual",
                        max_length=50,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("vigente", "Vigente"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "conclusiones",
                    models.TextField(blank=True, verbose_name="Conclusiones Generales"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pestel_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Análisis",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis PESTEL",
                "verbose_name_plural": "Análisis PESTEL",
                "db_table": "contexto_analisis_pestel",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="EstrategiaTOWS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fo", "FO - Fortalezas-Oportunidades (Ofensiva)"),
                            ("fa", "FA - Fortalezas-Amenazas (Defensiva)"),
                            ("do", "DO - Debilidades-Oportunidades (Adaptativa)"),
                            ("da", "DA - Debilidades-Amenazas (Supervivencia)"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de Estrategia",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción de la Estrategia"),
                ),
                ("objetivo", models.TextField(verbose_name="Objetivo Esperado")),
                (
                    "fecha_implementacion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha Planificada de Implementación",
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Límite"
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("propuesta", "Propuesta"),
                            ("aprobada", "Aprobada"),
                            ("en_ejecucion", "En Ejecución"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("suspendida", "Suspendida"),
                        ],
                        default="propuesta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(blank=True, verbose_name="Recursos Necesarios"),
                ),
                (
                    "indicadores_exito",
                    models.TextField(blank=True, verbose_name="Indicadores de Éxito"),
                ),
                (
                    "progreso_porcentaje",
                    models.PositiveIntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estrategias",
                        to="gestion_estrategica_contexto.analisisdofa",
                        verbose_name="Análisis DOFA",
                    ),
                ),
                (
                    "area_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estrategias_tows",
                        to="organizacion.area",
                        verbose_name="Área Responsable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "objetivo_estrategico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Objetivo estratégico creado a partir de esta estrategia TOWS",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estrategias_origen",
                        to="planeacion.strategicobjective",
                        verbose_name="Objetivo Estratégico Derivado",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estrategias_tows_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrategia TOWS",
                "verbose_name_plural": "Estrategias TOWS",
                "db_table": "contexto_estrategia_tows",
                "ordering": ["-prioridad", "fecha_limite"],
            },
        ),
        migrations.CreateModel(
            name="FactorDOFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fortaleza", "Fortaleza"),
                            ("oportunidad", "Oportunidad"),
                            ("debilidad", "Debilidad"),
                            ("amenaza", "Amenaza"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Factor",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Factor"),
                ),
                (
                    "area_afectada",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Área o Proceso Afectado (texto)",
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        default="medio",
                        max_length=10,
                        verbose_name="Nivel de Impacto",
                    ),
                ),
                (
                    "evidencias",
                    models.TextField(
                        blank=True, verbose_name="Evidencias o Sustentación"
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        default="manual",
                        help_text="manual, encuesta, importado",
                        max_length=50,
                        verbose_name="Fuente del Factor",
                    ),
                ),
                (
                    "votos_fortaleza",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos como Fortaleza"
                    ),
                ),
                (
                    "votos_debilidad",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos como Debilidad"
                    ),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factores",
                        to="gestion_estrategica_contexto.analisisdofa",
                        verbose_name="Análisis DOFA",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factores_dofa",
                        to="organizacion.area",
                        verbose_name="Área Organizacional",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factor DOFA",
                "verbose_name_plural": "Factores DOFA",
                "db_table": "contexto_factor_dofa",
                "ordering": ["analisis", "tipo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="FactorPESTEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("politico", "Político"),
                            ("economico", "Económico"),
                            ("social", "Social"),
                            ("tecnologico", "Tecnológico"),
                            ("ecologico", "Ecológico (Ambiental)"),
                            ("legal", "Legal (Regulatorio)"),
                        ],
                        max_length=15,
                        verbose_name="Dimensión PESTEL",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Factor"),
                ),
                (
                    "tendencia",
                    models.CharField(
                        choices=[
                            ("mejorando", "Mejorando (Favorable)"),
                            ("estable", "Estable (Sin cambios)"),
                            ("empeorando", "Empeorando (Desfavorable)"),
                        ],
                        default="estable",
                        max_length=15,
                        verbose_name="Tendencia del Factor",
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de Impacto en la Organización",
                    ),
                ),
                (
                    "probabilidad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        max_length=10,
                        verbose_name="Probabilidad de Ocurrencia/Permanencia",
                    ),
                ),
                (
                    "implicaciones",
                    models.TextField(
                        blank=True, verbose_name="Implicaciones para la Organización"
                    ),
                ),
                (
                    "fuentes",
                    models.TextField(blank=True, verbose_name="Fuentes de Información"),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factores",
                        to="gestion_estrategica_contexto.analisispestel",
                        verbose_name="Análisis PESTEL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factor PESTEL",
                "verbose_name_plural": "Factores PESTEL",
                "db_table": "contexto_factor_pestel",
                "ordering": ["analisis", "tipo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="FuerzaPorter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rivalidad", "1. Rivalidad entre Competidores Existentes"),
                            ("nuevos_entrantes", "2. Amenaza de Nuevos Entrantes"),
                            (
                                "sustitutos",
                                "3. Amenaza de Productos/Servicios Sustitutos",
                            ),
                            (
                                "poder_proveedores",
                                "4. Poder de Negociación de Proveedores",
                            ),
                            ("poder_clientes", "5. Poder de Negociación de Clientes"),
                        ],
                        max_length=20,
                        verbose_name="Fuerza de Porter",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("alto", "Alto (Desfavorable)"),
                            ("medio", "Medio (Moderado)"),
                            ("bajo", "Bajo (Favorable)"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de Intensidad de la Fuerza",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción y Análisis"),
                ),
                (
                    "factores",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Factores Clave"
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                ("periodo", models.CharField(max_length=50, verbose_name="Periodo")),
                (
                    "implicaciones_estrategicas",
                    models.TextField(
                        blank=True, verbose_name="Implicaciones Estratégicas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuerza de Porter",
                "verbose_name_plural": "Fuerzas de Porter",
                "db_table": "contexto_fuerza_porter",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="ParteInteresada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "representante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Representante"
                    ),
                ),
                (
                    "cargo_representante",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Cargo del Representante",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "nivel_influencia",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Nivel de Influencia",
                    ),
                ),
                (
                    "nivel_interes",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        default="medio",
                        max_length=10,
                        verbose_name="Nivel de Interés",
                    ),
                ),
                (
                    "relacionado_sst",
                    models.BooleanField(
                        default=False, verbose_name="Relacionado con SST (ISO 45001)"
                    ),
                ),
                (
                    "relacionado_ambiental",
                    models.BooleanField(
                        default=False,
                        verbose_name="Relacionado con Ambiental (ISO 14001)",
                    ),
                ),
                (
                    "relacionado_calidad",
                    models.BooleanField(
                        default=False, verbose_name="Relacionado con Calidad (ISO 9001)"
                    ),
                ),
                (
                    "relacionado_pesv",
                    models.BooleanField(
                        default=False, verbose_name="Relacionado con PESV"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partes_interesadas",
                        to="gestion_estrategica_contexto.tipoparteinteresada",
                        verbose_name="Tipo de Parte Interesada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte Interesada",
                "verbose_name_plural": "Partes Interesadas",
                "db_table": "contexto_parte_interesada",
                "ordering": ["-nivel_influencia", "-nivel_interes", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MatrizComunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("que_comunicar", models.TextField(verbose_name="Qué Comunicar")),
                (
                    "cuando_comunicar",
                    models.CharField(
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("quincenal", "Quincenal"),
                            ("mensual", "Mensual"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                            ("segun_necesidad", "Según Necesidad"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "como_comunicar",
                    models.CharField(
                        choices=[
                            ("email", "Correo Electrónico"),
                            ("reunion", "Reunión"),
                            ("informe", "Informe Escrito"),
                            ("cartelera", "Cartelera"),
                            ("intranet", "Intranet"),
                            ("telefono", "Teléfono"),
                            ("redes", "Redes Sociales"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Medio",
                    ),
                ),
                (
                    "registro_evidencia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Registro/Evidencia"
                    ),
                ),
                (
                    "aplica_sst",
                    models.BooleanField(default=False, verbose_name="Aplica a SST"),
                ),
                (
                    "aplica_ambiental",
                    models.BooleanField(
                        default=False, verbose_name="Aplica a Ambiental"
                    ),
                ),
                (
                    "aplica_calidad",
                    models.BooleanField(default=False, verbose_name="Aplica a Calidad"),
                ),
                (
                    "aplica_pesv",
                    models.BooleanField(default=False, verbose_name="Aplica a PESV"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicaciones_pi_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "parte_interesada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicaciones",
                        to="gestion_estrategica_contexto.parteinteresada",
                        verbose_name="Parte Interesada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación con Parte Interesada",
                "verbose_name_plural": "Matriz de Comunicaciones",
                "db_table": "contexto_matriz_comunicacion",
                "ordering": ["parte_interesada", "cuando_comunicar"],
            },
        ),
        migrations.CreateModel(
            name="RequisitoParteInteresada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("necesidad", "Necesidad"),
                            ("expectativa", "Expectativa"),
                            ("requisito_legal", "Requisito Legal"),
                            ("requisito_contractual", "Requisito Contractual"),
                        ],
                        default="expectativa",
                        max_length=25,
                        verbose_name="Tipo de Requisito",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "como_se_aborda",
                    models.TextField(blank=True, verbose_name="Cómo se Aborda"),
                ),
                (
                    "proceso_relacionado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Proceso Relacionado"
                    ),
                ),
                (
                    "indicador_seguimiento",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Indicador de Seguimiento",
                    ),
                ),
                ("cumple", models.BooleanField(default=False, verbose_name="Cumple")),
                (
                    "evidencia_cumplimiento",
                    models.TextField(
                        blank=True, verbose_name="Evidencia de Cumplimiento"
                    ),
                ),
                (
                    "fecha_ultima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Revisión"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "parte_interesada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos",
                        to="gestion_estrategica_contexto.parteinteresada",
                        verbose_name="Parte Interesada",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito de Parte Interesada",
                "verbose_name_plural": "Requisitos de Partes Interesadas",
                "db_table": "contexto_requisito_parte_interesada",
                "ordering": ["-prioridad", "tipo"],
            },
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["empresa", "periodo"], name="contexto_an_empresa_3ec38a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["empresa", "estado"], name="contexto_an_empresa_172343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["fecha_analisis"], name="contexto_an_fecha_a_51f587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisispestel",
            index=models.Index(
                fields=["empresa", "periodo"], name="contexto_an_empresa_20a01f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisispestel",
            index=models.Index(
                fields=["fecha_analisis"], name="contexto_an_fecha_a_664e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="contexto_es_empresa_21aeff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["estado", "prioridad"], name="contexto_es_estado_130645_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["fecha_limite"], name="contexto_es_fecha_l_5a7e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factordofa",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="contexto_fa_empresa_522d0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factordofa",
            index=models.Index(
                fields=["tipo", "impacto"], name="contexto_fa_tipo_926cf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorpestel",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="contexto_fa_empresa_8c791c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factorpestel",
            index=models.Index(
                fields=["tipo", "impacto", "probabilidad"],
                name="contexto_fa_tipo_b00192_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fuerzaporter",
            index=models.Index(
                fields=["empresa", "periodo"], name="contexto_fu_empresa_4ef035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuerzaporter",
            index=models.Index(
                fields=["tipo", "nivel"], name="contexto_fu_tipo_6314e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuerzaporter",
            constraint=models.UniqueConstraint(
                fields=("empresa", "tipo", "periodo"),
                name="unique_contexto_porter_empresa_periodo",
            ),
        ),
        migrations.AddIndex(
            model_name="matrizcomunicacion",
            index=models.Index(
                fields=["empresa", "parte_interesada"],
                name="contexto_ma_empresa_527495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matrizcomunicacion",
            index=models.Index(
                fields=["empresa", "cuando_comunicar"],
                name="contexto_ma_empresa_f1c3ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisitoparteinteresada",
            index=models.Index(
                fields=["empresa", "parte_interesada"],
                name="contexto_re_empresa_ac3e8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisitoparteinteresada",
            index=models.Index(
                fields=["empresa", "prioridad"], name="contexto_re_empresa_11a0c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parteinteresada",
            index=models.Index(
                fields=["empresa", "tipo"], name="contexto_pa_empresa_b26791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parteinteresada",
            index=models.Index(
                fields=["empresa", "nivel_influencia", "nivel_interes"],
                name="contexto_pa_empresa_f83578_idx",
            ),
        ),
    ]
