# Generated by Django 5.0.9 on 2026-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estrategica_contexto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteinteresada',
            name='canal_principal',
            field=models.CharField(choices=[('email', 'Correo Electrónico'), ('telefono', 'Teléfono'), ('reunion', 'Reunión Presencial'), ('videoconferencia', 'Videoconferencia'), ('whatsapp', 'WhatsApp'), ('portal_web', 'Portal Web'), ('redes_sociales', 'Redes Sociales'), ('correspondencia', 'Correspondencia Física'), ('otro', 'Otro')], default='email', help_text='Canal preferido para comunicarse con esta parte interesada', max_length=20, verbose_name='Canal de Comunicación Principal'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='es_requisito_legal',
            field=models.BooleanField(default=False, help_text='Indica si los requisitos de esta parte interesada son de carácter legal', verbose_name='Tiene Requisitos Legales'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='expectativas',
            field=models.TextField(blank=True, help_text='¿Qué espera esta parte interesada de la organización?', verbose_name='Expectativas'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='frecuencia_comunicacion',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('segun_necesidad', 'Según Necesidad')], default='mensual', help_text='Frecuencia recomendada de comunicación según matriz poder-interés', max_length=20, verbose_name='Frecuencia de Comunicación'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='necesidades',
            field=models.TextField(blank=True, help_text='¿Qué necesita esta parte interesada de la organización?', verbose_name='Necesidades'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='requisitos_pertinentes',
            field=models.TextField(blank=True, help_text='Requisitos que la organización debe cumplir para esta parte interesada', verbose_name='Requisitos Pertinentes'),
        ),
        migrations.AddField(
            model_name='parteinteresada',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL del sitio web de la parte interesada', max_length=500, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='parteinteresada',
            name='nivel_influencia',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Nivel de Influencia (Poder)'),
        ),
    ]
