# Generated by Django 5.0.9 on 2026-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estrategica_contexto', '0004_parteinteresada_canales_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordofa',
            name='votos_amenaza',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos como Amenaza'),
        ),
        migrations.AddField(
            model_name='factordofa',
            name='votos_oportunidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos como Oportunidad'),
        ),
    ]
