# Generated by Django 5.0.9 on 2026-01-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_estrategica_contexto", "0007_alter_estrategiatows_responsable"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="matrizcomunicacion",
            new_name="contexto_ma_empresa_0d87fa_idx",
            old_name="contexto_ma_empresa_b8c5f1_idx",
        ),
        migrations.AlterField(
            model_name="matrizcomunicacion",
            name="que_comunicar",
            field=models.TextField(
                help_text="Información o mensaje a comunicar",
                verbose_name="Qué Comunicar",
            ),
        ),
        migrations.AlterField(
            model_name="matrizcomunicacion",
            name="registro_evidencia",
            field=models.CharField(
                blank=True,
                help_text="Documento o registro donde queda evidencia de la comunicación",
                max_length=200,
                verbose_name="Registro/Evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisisdofa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisisdofa",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisisdofa",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisisdofa",
            name="orden",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Orden de visualización (menor número = primero)",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisisdofa",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisispestel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisispestel",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisispestel",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisispestel",
            name="orden",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Orden de visualización (menor número = primero)",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="tipoanalisispestel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
    ]
