# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config_contable", "0001_initial"),
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobanteContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Comprobante",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        db_index=True,
                        help_text="Formato YYYY-MM",
                        max_length=7,
                        verbose_name="Período Contable",
                    ),
                ),
                (
                    "fecha_comprobante",
                    models.DateField(
                        db_index=True, verbose_name="Fecha del Comprobante"
                    ),
                ),
                (
                    "fecha_elaboracion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Elaboración"
                    ),
                ),
                ("concepto", models.TextField(verbose_name="Concepto")),
                (
                    "total_debito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Total Débito",
                    ),
                ),
                (
                    "total_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Total Crédito",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pendiente_aprobacion", "Pendiente Aprobación"),
                            ("aprobado", "Aprobado"),
                            ("contabilizado", "Contabilizado"),
                            ("anulado", "Anulado"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "requiere_aprobacion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Aprobación"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "origen_automatico",
                    models.BooleanField(
                        default=False, verbose_name="Origen Automático"
                    ),
                ),
                (
                    "modulo_origen",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Módulo de Origen"
                    ),
                ),
                (
                    "documento_origen_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Documento Origen"
                    ),
                ),
                (
                    "fecha_anulacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Anulación"
                    ),
                ),
                (
                    "motivo_anulacion",
                    models.TextField(blank=True, verbose_name="Motivo de Anulación"),
                ),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="Notas Adicionales"),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes_anulados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anulado Por",
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado Por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes",
                        to="config_contable.tipodocumentocontable",
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante Contable",
                "verbose_name_plural": "Comprobantes Contables",
                "db_table": "accounting_comprobante_contable",
                "ordering": ["-fecha_comprobante", "-numero_comprobante"],
            },
        ),
        migrations.CreateModel(
            name="DetalleComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secuencia", models.IntegerField(verbose_name="Secuencia")),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "debito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Débito",
                    ),
                ),
                (
                    "credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Crédito",
                    ),
                ),
                (
                    "base_retencion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Base Retención",
                    ),
                ),
                (
                    "tipo_documento_soporte",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo Documento Soporte"
                    ),
                ),
                (
                    "numero_documento_soporte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número Documento Soporte",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centro_costo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="config_contable.centrocostocontable",
                        verbose_name="Centro de Costo",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="movimientos.comprobantecontable",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="config_contable.cuentacontable",
                        verbose_name="Cuenta Contable",
                    ),
                ),
                (
                    "tercero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="config_contable.tercero",
                        verbose_name="Tercero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Comprobante",
                "verbose_name_plural": "Detalles de Comprobantes",
                "db_table": "accounting_detalle_comprobante",
                "ordering": ["comprobante", "secuencia"],
            },
        ),
        migrations.CreateModel(
            name="SecuenciaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        db_index=True,
                        help_text="Formato YYYY-MM",
                        max_length=7,
                        verbose_name="Período",
                    ),
                ),
                (
                    "consecutivo_actual",
                    models.IntegerField(default=0, verbose_name="Consecutivo Actual"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secuencias",
                        to="config_contable.tipodocumentocontable",
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia de Documento",
                "verbose_name_plural": "Secuencias de Documentos",
                "db_table": "accounting_secuencia_documento",
                "ordering": ["tipo_documento", "periodo"],
            },
        ),
        migrations.CreateModel(
            name="AsientoPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Plantilla"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="Es Recurrente"),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("quincenal", "Quincenal"),
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "estructura_json",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura de las líneas del asiento",
                        verbose_name="Estructura JSON",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantillas",
                        to="config_contable.tipodocumentocontable",
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Asiento",
                "verbose_name_plural": "Plantillas de Asientos",
                "db_table": "accounting_asiento_plantilla",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "codigo"],
                        name="accounting__empresa_b791a9_idx",
                    ),
                    models.Index(
                        fields=["es_recurrente", "frecuencia"],
                        name="accounting__es_recu_c497f6_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="asientoplantilla",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="unique_plantilla_por_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="comprobantecontable",
            index=models.Index(
                fields=["empresa", "estado", "fecha_comprobante"],
                name="accounting__empresa_d3741c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comprobantecontable",
            index=models.Index(
                fields=["periodo", "tipo_documento"],
                name="accounting__periodo_a03d74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comprobantecontable",
            index=models.Index(
                fields=["numero_comprobante"], name="accounting__numero__4c87b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comprobantecontable",
            index=models.Index(
                fields=["modulo_origen", "documento_origen_id"],
                name="accounting__modulo__297e18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detallecomprobante",
            index=models.Index(
                fields=["comprobante", "secuencia"],
                name="accounting__comprob_a86922_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detallecomprobante",
            index=models.Index(
                fields=["cuenta"], name="accounting__cuenta__0ab00f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallecomprobante",
            index=models.Index(
                fields=["tercero"], name="accounting__tercero_63f438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallecomprobante",
            index=models.Index(
                fields=["centro_costo"], name="accounting__centro__6d28ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="secuenciadocumento",
            index=models.Index(
                fields=["empresa", "tipo_documento", "periodo"],
                name="accounting__empresa_584e4b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="secuenciadocumento",
            constraint=models.UniqueConstraint(
                fields=("empresa", "tipo_documento", "periodo"),
                name="unique_secuencia_por_periodo",
            ),
        ),
    ]
