# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisDOFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Análisis"
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 2025-Q1, 2025 Anual, Enero 2025",
                        max_length=50,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("vigente", "Vigente"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones y Conclusiones"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dofa_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dofa_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Análisis",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis DOFA",
                "verbose_name_plural": "Análisis DOFA",
                "db_table": "motor_riesgos_analisis_dofa",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="AnalisisPESTEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Análisis"
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 2025-Q1, 2025 Anual",
                        max_length=50,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("vigente", "Vigente"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "conclusiones",
                    models.TextField(blank=True, verbose_name="Conclusiones Generales"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pestel_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Análisis",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis PESTEL",
                "verbose_name_plural": "Análisis PESTEL",
                "db_table": "motor_riesgos_analisis_pestel",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="EstrategiaTOWS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fo", "FO - Fortalezas-Oportunidades (Ofensiva)"),
                            ("fa", "FA - Fortalezas-Amenazas (Defensiva)"),
                            ("do", "DO - Debilidades-Oportunidades (Adaptativa)"),
                            ("da", "DA - Debilidades-Amenazas (Supervivencia)"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de Estrategia",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción de la Estrategia"),
                ),
                ("objetivo", models.TextField(verbose_name="Objetivo Esperado")),
                (
                    "fecha_implementacion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha Planificada de Implementación",
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Límite"
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("propuesta", "Propuesta"),
                            ("aprobada", "Aprobada"),
                            ("en_ejecucion", "En Ejecución"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("suspendida", "Suspendida"),
                        ],
                        default="propuesta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(blank=True, verbose_name="Recursos Necesarios"),
                ),
                (
                    "indicadores_exito",
                    models.TextField(blank=True, verbose_name="Indicadores de Éxito"),
                ),
                (
                    "progreso_porcentaje",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Porcentaje de avance en la implementación",
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estrategias",
                        to="planeacion_contexto.analisisdofa",
                        verbose_name="Análisis DOFA",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estrategias_tows_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrategia TOWS",
                "verbose_name_plural": "Estrategias TOWS",
                "db_table": "motor_riesgos_estrategia_tows",
                "ordering": ["-prioridad", "fecha_limite"],
            },
        ),
        migrations.CreateModel(
            name="FactorDOFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fortaleza", "Fortaleza"),
                            ("oportunidad", "Oportunidad"),
                            ("debilidad", "Debilidad"),
                            ("amenaza", "Amenaza"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Factor",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Factor"),
                ),
                (
                    "area_afectada",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Área o Proceso Afectado",
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        default="medio",
                        max_length=10,
                        verbose_name="Nivel de Impacto",
                    ),
                ),
                (
                    "evidencias",
                    models.TextField(
                        blank=True, verbose_name="Evidencias o Sustentación"
                    ),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factores",
                        to="planeacion_contexto.analisisdofa",
                        verbose_name="Análisis DOFA",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factor DOFA",
                "verbose_name_plural": "Factores DOFA",
                "db_table": "motor_riesgos_factor_dofa",
                "ordering": ["analisis", "tipo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="FactorPESTEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("politico", "Político"),
                            ("economico", "Económico"),
                            ("social", "Social"),
                            ("tecnologico", "Tecnológico"),
                            ("ecologico", "Ecológico (Ambiental)"),
                            ("legal", "Legal (Regulatorio)"),
                        ],
                        max_length=15,
                        verbose_name="Dimensión PESTEL",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Factor"),
                ),
                (
                    "tendencia",
                    models.CharField(
                        choices=[
                            ("mejorando", "Mejorando (Favorable)"),
                            ("estable", "Estable (Sin cambios)"),
                            ("empeorando", "Empeorando (Desfavorable)"),
                        ],
                        default="estable",
                        max_length=15,
                        verbose_name="Tendencia del Factor",
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de Impacto en la Organización",
                    ),
                ),
                (
                    "probabilidad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        max_length=10,
                        verbose_name="Probabilidad de Ocurrencia/Permanencia",
                    ),
                ),
                (
                    "implicaciones",
                    models.TextField(
                        blank=True, verbose_name="Implicaciones para la Organización"
                    ),
                ),
                (
                    "fuentes",
                    models.TextField(
                        blank=True,
                        help_text="Referencias, estudios, informes consultados",
                        verbose_name="Fuentes de Información",
                    ),
                ),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factores",
                        to="planeacion_contexto.analisispestel",
                        verbose_name="Análisis PESTEL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factor PESTEL",
                "verbose_name_plural": "Factores PESTEL",
                "db_table": "motor_riesgos_factor_pestel",
                "ordering": ["analisis", "tipo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="FuerzaPorter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rivalidad", "1. Rivalidad entre Competidores Existentes"),
                            ("nuevos_entrantes", "2. Amenaza de Nuevos Entrantes"),
                            (
                                "sustitutos",
                                "3. Amenaza de Productos/Servicios Sustitutos",
                            ),
                            (
                                "poder_proveedores",
                                "4. Poder de Negociación de Proveedores",
                            ),
                            ("poder_clientes", "5. Poder de Negociación de Clientes"),
                        ],
                        max_length=20,
                        verbose_name="Fuerza de Porter",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("alto", "Alto (Desfavorable)"),
                            ("medio", "Medio (Moderado)"),
                            ("bajo", "Bajo (Favorable)"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de Intensidad de la Fuerza",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción y Análisis"),
                ),
                (
                    "factores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de factores que contribuyen a esta fuerza",
                        verbose_name="Factores Clave",
                    ),
                ),
                ("fecha_analisis", models.DateField(verbose_name="Fecha de Análisis")),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 2025-Q1, 2025 Anual",
                        max_length=50,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "implicaciones_estrategicas",
                    models.TextField(
                        blank=True,
                        help_text="Cómo esta fuerza afecta la estrategia competitiva",
                        verbose_name="Implicaciones Estratégicas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuerza de Porter",
                "verbose_name_plural": "Fuerzas de Porter",
                "db_table": "motor_riesgos_fuerza_porter",
                "ordering": ["tipo"],
            },
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["empresa", "periodo"], name="motor_riesg_empresa_d8913d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["empresa", "estado"], name="motor_riesg_empresa_5cea03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisisdofa",
            index=models.Index(
                fields=["fecha_analisis"], name="motor_riesg_fecha_a_46614c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisispestel",
            index=models.Index(
                fields=["empresa", "periodo"], name="motor_riesg_empresa_58b86f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisispestel",
            index=models.Index(
                fields=["fecha_analisis"], name="motor_riesg_fecha_a_b37817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="motor_riesg_empresa_bc81c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["estado", "prioridad"], name="motor_riesg_estado_be6c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estrategiatows",
            index=models.Index(
                fields=["fecha_limite"], name="motor_riesg_fecha_l_0b66bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factordofa",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="motor_riesg_empresa_38f09c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factordofa",
            index=models.Index(
                fields=["tipo", "impacto"], name="motor_riesg_tipo_7879e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorpestel",
            index=models.Index(
                fields=["empresa", "analisis", "tipo"],
                name="motor_riesg_empresa_785293_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factorpestel",
            index=models.Index(
                fields=["tipo", "impacto", "probabilidad"],
                name="motor_riesg_tipo_656ce9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fuerzaporter",
            index=models.Index(
                fields=["empresa", "periodo"], name="motor_riesg_empresa_4965dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuerzaporter",
            index=models.Index(
                fields=["tipo", "nivel"], name="motor_riesg_tipo_e4ffe2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuerzaporter",
            constraint=models.UniqueConstraint(
                fields=("empresa", "tipo", "periodo"),
                name="unique_porter_fuerza_empresa_periodo",
            ),
        ),
    ]
