# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "periodo_actual",
                    models.CharField(
                        help_text="Formato YYYY-MM",
                        max_length=7,
                        verbose_name="Período Actual",
                    ),
                ),
                (
                    "fecha_inicio_ejercicio",
                    models.DateField(verbose_name="Inicio Ejercicio Fiscal"),
                ),
                (
                    "fecha_fin_ejercicio",
                    models.DateField(verbose_name="Fin Ejercicio Fiscal"),
                ),
                (
                    "ultimo_periodo_cerrado",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Último Período Cerrado"
                    ),
                ),
                (
                    "permite_modificar_periodos_cerrados",
                    models.BooleanField(
                        default=False,
                        verbose_name="Permite Modificar Períodos Cerrados",
                    ),
                ),
                (
                    "contabiliza_automatico_pagos",
                    models.BooleanField(
                        default=True, verbose_name="Contabilizar Automático Pagos"
                    ),
                ),
                (
                    "contabiliza_automatico_recaudos",
                    models.BooleanField(
                        default=True, verbose_name="Contabilizar Automático Recaudos"
                    ),
                ),
                (
                    "contabiliza_automatico_nomina",
                    models.BooleanField(
                        default=True, verbose_name="Contabilizar Automático Nómina"
                    ),
                ),
                (
                    "contabiliza_automatico_inventarios",
                    models.BooleanField(
                        default=True, verbose_name="Contabilizar Automático Inventarios"
                    ),
                ),
                (
                    "decimales_moneda",
                    models.IntegerField(
                        choices=[(0, "0"), (2, "2"), (4, "4")],
                        default=2,
                        verbose_name="Decimales para Moneda",
                    ),
                ),
                (
                    "exige_cuadre_comprobantes",
                    models.BooleanField(
                        default=True, verbose_name="Exige Cuadre en Comprobantes"
                    ),
                ),
                (
                    "exige_centro_costo_gastos",
                    models.BooleanField(
                        default=True, verbose_name="Exige Centro Costo en Gastos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Módulo Contable",
                "verbose_name_plural": "Configuraciones Módulo Contable",
                "db_table": "accounting_configuracion_modulo",
            },
        ),
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código PUC"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Cuenta"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (1, "Clase (1 dígito)"),
                            (2, "Grupo (2 dígitos)"),
                            (3, "Cuenta (4 dígitos)"),
                            (4, "Subcuenta (6 dígitos)"),
                            (5, "Auxiliar (8+ dígitos)"),
                        ],
                        db_index=True,
                        verbose_name="Nivel de la Cuenta",
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("debito", "Débito"), ("credito", "Crédito")],
                        db_index=True,
                        max_length=10,
                        verbose_name="Naturaleza",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("detalle", "Cuenta de Detalle"),
                            ("titulo", "Cuenta Título"),
                        ],
                        db_index=True,
                        default="detalle",
                        max_length=20,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "clase_cuenta",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("pasivo", "Pasivo"),
                            ("patrimonio", "Patrimonio"),
                            ("ingreso", "Ingreso"),
                            ("gasto", "Gasto"),
                            ("costo", "Costo de Venta"),
                            ("orden", "Cuentas de Orden"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Clase de Cuenta",
                    ),
                ),
                (
                    "exige_tercero",
                    models.BooleanField(default=False, verbose_name="Exige Tercero"),
                ),
                (
                    "exige_centro_costo",
                    models.BooleanField(
                        default=False, verbose_name="Exige Centro de Costo"
                    ),
                ),
                (
                    "exige_base_retencion",
                    models.BooleanField(
                        default=False, verbose_name="Exige Base Retención"
                    ),
                ),
                (
                    "permite_saldo_negativo",
                    models.BooleanField(
                        default=False, verbose_name="Permite Saldo Negativo"
                    ),
                ),
                (
                    "saldo_debito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Saldo Débito",
                    ),
                ),
                (
                    "saldo_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Saldo Crédito",
                    ),
                ),
                (
                    "acepta_movimientos",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Acepta Movimientos"
                    ),
                ),
                (
                    "modulo_origen",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Módulo de Origen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "db_table": "accounting_cuenta_contable",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="PlanCuentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del plan de cuentas (ej: PUC NIIF PYMES 2025)",
                        max_length=200,
                        verbose_name="Nombre del Plan",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="Versión")),
                (
                    "tipo_plan",
                    models.CharField(
                        choices=[
                            ("comercial", "PUC Comercial"),
                            ("niif_pymes", "NIIF para PYMES"),
                            ("niif_plenas", "NIIF Plenas"),
                            ("simplificado", "Régimen Simplificado"),
                        ],
                        db_index=True,
                        default="niif_pymes",
                        max_length=30,
                        verbose_name="Tipo de Plan",
                    ),
                ),
                (
                    "fecha_inicio_vigencia",
                    models.DateField(
                        db_index=True, verbose_name="Fecha Inicio Vigencia"
                    ),
                ),
                (
                    "fecha_fin_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Fin Vigencia"
                    ),
                ),
                (
                    "es_activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Plan Activo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Plan de Cuentas",
                "verbose_name_plural": "Planes de Cuentas",
                "db_table": "accounting_plan_cuentas",
                "ordering": ["-fecha_inicio_vigencia"],
            },
        ),
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("nit", "NIT"),
                            ("cc", "Cédula de Ciudadanía"),
                            ("ce", "Cédula de Extranjería"),
                            ("pasaporte", "Pasaporte"),
                            ("rut", "RUT"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Identificación",
                    ),
                ),
                (
                    "numero_identificacion",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        verbose_name="Número de Identificación",
                    ),
                ),
                (
                    "digito_verificacion",
                    models.CharField(
                        blank=True, max_length=1, verbose_name="Dígito de Verificación"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        max_length=200, verbose_name="Razón Social / Nombre Completo"
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Comercial"
                    ),
                ),
                (
                    "tipo_tercero",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("proveedor", "Proveedor"),
                            ("empleado", "Empleado"),
                            ("accionista", "Accionista"),
                            ("gobierno", "Entidad Gubernamental"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Tercero",
                    ),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[
                            ("juridica", "Persona Jurídica"),
                            ("natural", "Persona Natural"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Persona",
                    ),
                ),
                (
                    "responsable_iva",
                    models.BooleanField(
                        default=False, verbose_name="Responsable de IVA"
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("comun", "Régimen Común"),
                            ("simplificado", "Régimen Simplificado"),
                            ("especial", "Régimen Especial"),
                            ("no_responsable", "No Responsable"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Régimen Tributario",
                    ),
                ),
                (
                    "gran_contribuyente",
                    models.BooleanField(
                        default=False, verbose_name="Gran Contribuyente"
                    ),
                ),
                (
                    "autoretenedor",
                    models.BooleanField(default=False, verbose_name="Autoretenedor"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Tercero Contable",
                "verbose_name_plural": "Terceros Contables",
                "db_table": "accounting_tercero",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "clase_documento",
                    models.CharField(
                        choices=[
                            ("diario", "Comprobante de Diario"),
                            ("egreso", "Comprobante de Egreso"),
                            ("ingreso", "Comprobante de Ingreso"),
                            ("ajuste", "Comprobante de Ajuste"),
                            ("cierre", "Comprobante de Cierre"),
                            ("apertura", "Comprobante de Apertura"),
                            ("nota", "Nota Contable"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Clase de Documento",
                    ),
                ),
                ("prefijo", models.CharField(max_length=10, verbose_name="Prefijo")),
                (
                    "consecutivo_actual",
                    models.IntegerField(default=0, verbose_name="Consecutivo Actual"),
                ),
                (
                    "usa_periodo_numeracion",
                    models.BooleanField(
                        default=True, verbose_name="Usa Período en Numeración"
                    ),
                ),
                (
                    "requiere_aprobacion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Aprobación"
                    ),
                ),
                (
                    "afecta_contabilidad",
                    models.BooleanField(
                        default=True, verbose_name="Afecta Contabilidad"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento Contable",
                "verbose_name_plural": "Tipos de Documentos Contables",
                "db_table": "accounting_tipo_documento_contable",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CentroCostoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Centro de Costo"
                    ),
                ),
                (
                    "tipo_centro",
                    models.CharField(
                        choices=[
                            ("produccion", "Centro de Producción"),
                            ("servicio", "Centro de Servicio"),
                            ("administrativo", "Centro Administrativo"),
                            ("ventas", "Centro de Ventas"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Centro de Costo",
                    ),
                ),
                (
                    "presupuesto_anual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Presupuesto Anual",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "centro_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcentros",
                        to="config_contable.centrocostocontable",
                        verbose_name="Centro Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Costo Contable",
                "verbose_name_plural": "Centros de Costo Contables",
                "db_table": "accounting_centro_costo",
                "ordering": ["codigo"],
            },
        ),
    ]
