# Generated by Django 5.0.14 on 2026-02-22 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivoInformacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Codigo"),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HARDWARE", "Hardware"),
                            ("SOFTWARE", "Software"),
                            ("INFORMACION", "Informacion"),
                            ("SERVICIOS", "Servicios"),
                            ("PERSONAS", "Personas"),
                            ("INTANGIBLES", "Intangibles"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ubicacion"
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("PUBLICA", "Publica"),
                            ("INTERNA", "Interna"),
                            ("CONFIDENCIAL", "Confidencial"),
                            ("SECRETA", "Secreta"),
                        ],
                        default="INTERNA",
                        max_length=20,
                        verbose_name="Clasificacion",
                    ),
                ),
                (
                    "valor_confidencialidad",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Valor Confidencialidad",
                    ),
                ),
                (
                    "valor_integridad",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Valor Integridad",
                    ),
                ),
                (
                    "valor_disponibilidad",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Valor Disponibilidad",
                    ),
                ),
                (
                    "criticidad",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Criticidad"
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(verbose_name="Empresa ID"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "custodio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activos_custodio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Custodio",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activos_propietario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo de Informacion",
                "verbose_name_plural": "Activos de Informacion",
                "db_table": "motor_riesgos_activo_informacion",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Amenaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Codigo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NATURAL", "Natural"),
                            ("HUMANA_INTENCIONAL", "Humana Intencional"),
                            ("HUMANA_NO_INTENCIONAL", "Humana No Intencional"),
                            ("TECNICA", "Tecnica"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "probabilidad_ocurrencia",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Probabilidad de Ocurrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenaza",
                "verbose_name_plural": "Amenazas",
                "db_table": "motor_riesgos_amenaza",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "is_active"], name="motor_riesg_tipo_5150bb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidenteSeguridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(verbose_name="Fecha de Deteccion"),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del Incidente"),
                ),
                (
                    "tipo_incidente",
                    models.CharField(
                        choices=[
                            ("ACCESO_NO_AUTORIZADO", "Acceso No Autorizado"),
                            ("MALWARE", "Malware/Virus"),
                            ("FUGA_INFORMACION", "Fuga de Informacion"),
                            ("PHISHING", "Phishing"),
                            ("DENEGACION_SERVICIO", "Denegacion de Servicio"),
                            ("PERDIDA_DATOS", "Perdida de Datos"),
                            ("ROBO_EQUIPOS", "Robo de Equipos"),
                            ("INGENIERIA_SOCIAL", "Ingenieria Social"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de Incidente",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Critica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "impacto_real",
                    models.TextField(blank=True, verbose_name="Impacto Real"),
                ),
                (
                    "acciones_contencion",
                    models.TextField(blank=True, verbose_name="Acciones de Contencion"),
                ),
                (
                    "acciones_erradicacion",
                    models.TextField(
                        blank=True, verbose_name="Acciones de Erradicacion"
                    ),
                ),
                (
                    "lecciones_aprendidas",
                    models.TextField(blank=True, verbose_name="Lecciones Aprendidas"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REPORTADO", "Reportado"),
                            ("EN_INVESTIGACION", "En Investigacion"),
                            ("CONTENIDO", "Contenido"),
                            ("ERRADICADO", "Erradicado"),
                            ("RECUPERADO", "Recuperado"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="REPORTADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "activos_afectados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incidentes",
                        to="seguridad_informacion.activoinformacion",
                        verbose_name="Activos Afectados",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_reportados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reportado Por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente de Seguridad",
                "verbose_name_plural": "Incidentes de Seguridad",
                "db_table": "motor_riesgos_incidente_seguridad",
                "ordering": ["-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="RiesgoSeguridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "escenario_riesgo",
                    models.TextField(
                        help_text="Descripcion del escenario de riesgo",
                        verbose_name="Escenario de Riesgo",
                    ),
                ),
                (
                    "probabilidad",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Muy Baja"),
                            (2, "Baja"),
                            (3, "Media"),
                            (4, "Alta"),
                            (5, "Muy Alta"),
                        ],
                        default=3,
                        verbose_name="Probabilidad",
                    ),
                ),
                (
                    "impacto",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Insignificante"),
                            (2, "Menor"),
                            (3, "Moderado"),
                            (4, "Mayor"),
                            (5, "Catastrofico"),
                        ],
                        default=3,
                        verbose_name="Impacto",
                    ),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Critico"),
                        ],
                        editable=False,
                        max_length=10,
                        verbose_name="Nivel de Riesgo",
                    ),
                ),
                (
                    "controles_existentes",
                    models.TextField(blank=True, verbose_name="Controles Existentes"),
                ),
                (
                    "probabilidad_residual",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Muy Baja"),
                            (2, "Baja"),
                            (3, "Media"),
                            (4, "Alta"),
                            (5, "Muy Alta"),
                        ],
                        null=True,
                        verbose_name="Probabilidad Residual",
                    ),
                ),
                (
                    "impacto_residual",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Insignificante"),
                            (2, "Menor"),
                            (3, "Moderado"),
                            (4, "Mayor"),
                            (5, "Catastrofico"),
                        ],
                        null=True,
                        verbose_name="Impacto Residual",
                    ),
                ),
                (
                    "nivel_residual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Critico"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de Riesgo Residual",
                    ),
                ),
                (
                    "aceptabilidad",
                    models.CharField(
                        choices=[
                            ("ACEPTABLE", "Aceptable"),
                            ("TOLERABLE", "Tolerable"),
                            ("INACEPTABLE", "Inaceptable"),
                        ],
                        default="INACEPTABLE",
                        max_length=15,
                        verbose_name="Aceptabilidad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("IDENTIFICADO", "Identificado"),
                            ("EN_EVALUACION", "En Evaluacion"),
                            ("EN_TRATAMIENTO", "En Tratamiento"),
                            ("CONTROLADO", "Controlado"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="IDENTIFICADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riesgos",
                        to="seguridad_informacion.activoinformacion",
                        verbose_name="Activo de Informacion",
                    ),
                ),
                (
                    "amenaza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riesgos",
                        to="seguridad_informacion.amenaza",
                        verbose_name="Amenaza",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable_tratamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="riesgos_seguridad_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Tratamiento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riesgo de Seguridad",
                "verbose_name_plural": "Riesgos de Seguridad",
                "db_table": "motor_riesgos_riesgo_seguridad",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlSeguridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "control_iso",
                    models.CharField(
                        help_text="Ej: A.5.1.1, A.6.1.1",
                        max_length=20,
                        verbose_name="Control ISO 27001",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del Control"),
                ),
                (
                    "tipo_control",
                    models.CharField(
                        choices=[
                            ("PREVENTIVO", "Preventivo"),
                            ("DETECTIVO", "Detectivo"),
                            ("CORRECTIVO", "Correctivo"),
                        ],
                        default="PREVENTIVO",
                        max_length=15,
                        verbose_name="Tipo de Control",
                    ),
                ),
                (
                    "estado_implementacion",
                    models.CharField(
                        choices=[
                            ("NO_IMPLEMENTADO", "No Implementado"),
                            ("EN_IMPLEMENTACION", "En Implementacion"),
                            ("IMPLEMENTADO", "Implementado"),
                            ("OPTIMIZADO", "Optimizado"),
                        ],
                        default="NO_IMPLEMENTADO",
                        max_length=20,
                        verbose_name="Estado de Implementacion",
                    ),
                ),
                (
                    "efectividad",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Efectividad (%)",
                    ),
                ),
                (
                    "fecha_implementacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Implementacion"
                    ),
                ),
                ("evidencia", models.TextField(blank=True, verbose_name="Evidencia")),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles_seguridad_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "riesgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="seguridad_informacion.riesgoseguridad",
                        verbose_name="Riesgo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Seguridad",
                "verbose_name_plural": "Controles de Seguridad",
                "db_table": "motor_riesgos_control_seguridad",
                "ordering": ["control_iso"],
            },
        ),
        migrations.CreateModel(
            name="Vulnerabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Codigo")),
                ("descripcion", models.TextField(verbose_name="Descripcion")),
                (
                    "facilidad_explotacion",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Facilidad de Explotacion",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(verbose_name="Empresa ID"),
                ),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilidades",
                        to="seguridad_informacion.activoinformacion",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerabilidad",
                "verbose_name_plural": "Vulnerabilidades",
                "db_table": "motor_riesgos_vulnerabilidad",
                "ordering": ["activo", "codigo"],
            },
        ),
        migrations.AddField(
            model_name="riesgoseguridad",
            name="vulnerabilidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="riesgos",
                to="seguridad_informacion.vulnerabilidad",
                verbose_name="Vulnerabilidad",
            ),
        ),
        migrations.AddIndex(
            model_name="activoinformacion",
            index=models.Index(
                fields=["empresa_id", "is_active"],
                name="motor_riesg_empresa_252a98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activoinformacion",
            index=models.Index(fields=["tipo"], name="motor_riesg_tipo_032fac_idx"),
        ),
        migrations.AddIndex(
            model_name="activoinformacion",
            index=models.Index(
                fields=["clasificacion"], name="motor_riesg_clasifi_145f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenteseguridad",
            index=models.Index(
                fields=["empresa_id", "estado"], name="motor_riesg_empresa_9cf1be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenteseguridad",
            index=models.Index(
                fields=["severidad"], name="motor_riesg_severid_290488_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidenteseguridad",
            index=models.Index(
                fields=["tipo_incidente"], name="motor_riesg_tipo_in_e33404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilidad",
            index=models.Index(
                fields=["empresa_id", "is_active"],
                name="motor_riesg_empresa_c89549_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilidad",
            unique_together={("activo", "codigo")},
        ),
        migrations.AddIndex(
            model_name="riesgoseguridad",
            index=models.Index(
                fields=["empresa_id", "estado"], name="motor_riesg_empresa_40bc89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riesgoseguridad",
            index=models.Index(
                fields=["nivel_riesgo"], name="motor_riesg_nivel_r_0e0c74_idx"
            ),
        ),
    ]
