# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "numero_identificacion",
                    models.CharField(
                        db_index=True,
                        help_text="Número de documento de identidad único",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo se permiten números, letras y guiones",
                                regex="^[a-zA-Z0-9-]+$",
                            )
                        ],
                        verbose_name="Número de Identificación",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PA", "Pasaporte"),
                            ("PEP", "Permiso Especial de Permanencia"),
                            ("PPT", "Permiso de Protección Temporal"),
                        ],
                        default="CC",
                        max_length=5,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=50, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo Nombre"
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=50, verbose_name="Primer Apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo Apellido"
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(db_index=True, verbose_name="Fecha de Ingreso"),
                ),
                (
                    "fecha_retiro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Retiro"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                            ("retirado", "Retirado"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=15,
                        verbose_name="Estado Laboral",
                    ),
                ),
                (
                    "motivo_retiro",
                    models.TextField(blank=True, verbose_name="Motivo de Retiro"),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("indefinido", "Término Indefinido"),
                            ("fijo", "Término Fijo"),
                            ("obra_labor", "Obra o Labor"),
                            ("aprendizaje", "Aprendizaje"),
                            ("prestacion_servicios", "Prestación de Servicios"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "fecha_fin_contrato",
                    models.DateField(
                        blank=True,
                        help_text="Solo para contratos a término fijo u obra/labor",
                        null=True,
                        verbose_name="Fecha Fin de Contrato",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salario mensual en COP",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salario Actual",
                    ),
                ),
                (
                    "auxilio_transporte",
                    models.BooleanField(
                        default=True, verbose_name="Recibe Auxilio de Transporte"
                    ),
                ),
                (
                    "horas_semanales",
                    models.PositiveIntegerField(
                        default=48,
                        help_text="Horas laborales por semana (default: 48)",
                        verbose_name="Horas Semanales",
                    ),
                ),
                (
                    "email_personal",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Personal"
                    ),
                ),
                (
                    "telefono_movil",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono Móvil"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="colaboradores/fotos/",
                        verbose_name="Foto del Colaborador",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Generales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "db_table": "talent_hub_colaborador",
                "ordering": ["-fecha_ingreso", "primer_apellido", "primer_nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("contratacion", "Contratación"),
                            ("ascenso", "Ascenso"),
                            ("traslado", "Traslado"),
                            ("cambio_salario", "Cambio de Salario"),
                            ("cambio_cargo", "Cambio de Cargo"),
                            ("cambio_contrato", "Cambio de Contrato"),
                            ("suspension", "Suspensión"),
                            ("reactivacion", "Reactivación"),
                            ("retiro", "Retiro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "fecha_movimiento",
                    models.DateField(
                        db_index=True, verbose_name="Fecha del Movimiento"
                    ),
                ),
                (
                    "fecha_efectiva",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que el cambio entra en vigencia (si es diferente)",
                        null=True,
                        verbose_name="Fecha Efectiva",
                    ),
                ),
                (
                    "salario_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salario Anterior",
                    ),
                ),
                (
                    "salario_nuevo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salario Nuevo",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo del Movimiento")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "documento_soporte",
                    models.FileField(
                        blank=True,
                        help_text="Carta de ascenso, memorando, etc.",
                        null=True,
                        upload_to="colaboradores/historial/",
                        verbose_name="Documento de Soporte",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Laboral",
                "verbose_name_plural": "Historial Laboral",
                "db_table": "talent_hub_historial_laboral",
                "ordering": ["-fecha_movimiento", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HojaVida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nivel_estudio_maximo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primaria", "Primaria"),
                            ("bachillerato", "Bachillerato"),
                            ("tecnico", "Técnico"),
                            ("tecnologo", "Tecnólogo"),
                            ("profesional", "Profesional"),
                            ("especializacion", "Especialización"),
                            ("maestria", "Maestría"),
                            ("doctorado", "Doctorado"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Estudio Máximo",
                    ),
                ),
                (
                    "titulo_academico",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título Académico"
                    ),
                ),
                (
                    "institucion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Institución Educativa"
                    ),
                ),
                (
                    "anio_graduacion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Graduación"
                    ),
                ),
                (
                    "estudios_adicionales",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de estudios complementarios en formato JSON",
                        verbose_name="Estudios Adicionales",
                    ),
                ),
                (
                    "certificaciones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de certificaciones en formato JSON",
                        verbose_name="Certificaciones",
                    ),
                ),
                (
                    "experiencia_previa",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de empleos anteriores en formato JSON",
                        verbose_name="Experiencia Laboral Previa",
                    ),
                ),
                (
                    "idiomas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de idiomas con nivel en formato JSON. Ejemplo: [{"idioma": "Inglés", "nivel": "intermedio"}]',
                        verbose_name="Idiomas",
                    ),
                ),
                (
                    "habilidades",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de habilidades técnicas",
                        verbose_name="Habilidades Técnicas",
                    ),
                ),
                (
                    "competencias_blandas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de competencias blandas (liderazgo, trabajo en equipo, etc.)",
                        verbose_name="Competencias Blandas",
                    ),
                ),
                (
                    "referencias_laborales",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de referencias laborales en formato JSON",
                        verbose_name="Referencias Laborales",
                    ),
                ),
                (
                    "cv_documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="colaboradores/cv/",
                        verbose_name="CV en PDF",
                    ),
                ),
                (
                    "certificados_estudios",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="colaboradores/certificados/",
                        verbose_name="Certificados de Estudios",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de la Hoja de Vida"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoja de Vida",
                "verbose_name_plural": "Hojas de Vida",
                "db_table": "talent_hub_hoja_vida",
            },
        ),
        migrations.CreateModel(
            name="InfoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiere no decir"),
                        ],
                        max_length=10,
                        verbose_name="Género",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soltero", "Soltero/a"),
                            ("casado", "Casado/a"),
                            ("union_libre", "Unión Libre"),
                            ("divorciado", "Divorciado/a"),
                            ("viudo", "Viudo/a"),
                        ],
                        max_length=15,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Dirección de Residencia",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "telefono_fijo",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono Fijo"
                    ),
                ),
                (
                    "nombre_contacto_emergencia",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nombre Contacto de Emergencia",
                    ),
                ),
                (
                    "parentesco_contacto_emergencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Parentesco"
                    ),
                ),
                (
                    "telefono_contacto_emergencia",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono de Emergencia"
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bancolombia", "Bancolombia"),
                            ("banco_bogota", "Banco de Bogotá"),
                            ("davivienda", "Davivienda"),
                            ("bbva", "BBVA"),
                            ("banco_popular", "Banco Popular"),
                            ("banco_occidente", "Banco de Occidente"),
                            ("banco_caja_social", "Banco Caja Social"),
                            ("colpatria", "Colpatria"),
                            ("av_villas", "AV Villas"),
                            ("nequi", "Nequi"),
                            ("daviplata", "Daviplata"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Banco",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[("ahorros", "Ahorros"), ("corriente", "Corriente")],
                        max_length=10,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True,
                        help_text="Información sensible - encriptar en producción",
                        max_length=20,
                        verbose_name="Número de Cuenta",
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de Sangre",
                    ),
                ),
                (
                    "alergias",
                    models.TextField(blank=True, verbose_name="Alergias Conocidas"),
                ),
                (
                    "medicamentos_permanentes",
                    models.TextField(
                        blank=True, verbose_name="Medicamentos de Uso Permanente"
                    ),
                ),
                (
                    "condiciones_medicas",
                    models.TextField(
                        blank=True, verbose_name="Condiciones Médicas Relevantes"
                    ),
                ),
                (
                    "eps",
                    models.CharField(blank=True, max_length=100, verbose_name="EPS"),
                ),
                (
                    "arl",
                    models.CharField(blank=True, max_length=100, verbose_name="ARL"),
                ),
                (
                    "fondo_pensiones",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fondo de Pensiones"
                    ),
                ),
                (
                    "caja_compensacion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Caja de Compensación"
                    ),
                ),
                (
                    "talla_camisa",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla Camisa/Camiseta"
                    ),
                ),
                (
                    "talla_pantalon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla Pantalón"
                    ),
                ),
                (
                    "talla_zapatos",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla Zapatos"
                    ),
                ),
                (
                    "talla_overol",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla Overol"
                    ),
                ),
                (
                    "numero_hijos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Hijos"
                    ),
                ),
                (
                    "personas_a_cargo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Personas a Cargo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Información Personal",
                "verbose_name_plural": "Información Personal",
                "db_table": "talent_hub_info_personal",
            },
        ),
    ]
