# Generated by Django 5.0.14 on 2026-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_gerencial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistadashboard',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único de la vista (ej: DASH-FINANCIERO)', max_length=50, verbose_name='Código'),
        ),
    ]
