# Generated by Django 5.0.14 on 2026-04-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo_productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoEspecCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "acidez_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rango inferior de acidez aceptable",
                        max_digits=5,
                        verbose_name="Acidez mínima (%)",
                    ),
                ),
                (
                    "acidez_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rango superior de acidez aceptable",
                        max_digits=5,
                        verbose_name="Acidez máxima (%)",
                    ),
                ),
                (
                    "requiere_prueba_acidez",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, toda recepción debe registrar una prueba de acidez",
                        verbose_name="Requiere prueba de acidez",
                    ),
                ),
                (
                    "parametros_adicionales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible para otros parámetros por industria (pH, humedad, etc.)",
                        verbose_name="Parámetros adicionales de calidad",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espec_calidad",
                        to="catalogo_productos.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especificación de calidad",
                "verbose_name_plural": "Especificaciones de calidad",
            },
        ),
        migrations.AddConstraint(
            model_name="productoespeccalidad",
            constraint=models.CheckConstraint(
                check=models.Q(("acidez_max__gte", models.F("acidez_min"))),
                name="ck_espec_calidad_rango_acidez_valido",
            ),
        ),
    ]
