# Generated by Django 5.0.14 on 2026-04-20 00:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogo_productos",
            "0004_alter_producto_precio_referencia_alter_producto_sku",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadmedida",
            name="decimales_display",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Cantidad de decimales al mostrar (0-6)",
                verbose_name="Decimales para display",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="descripcion",
            field=models.TextField(blank=True, default="", verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="nombre_plural",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Ej: Kilogramos. Si se deja vacío, se agrega "s" al nombre.',
                max_length=100,
                verbose_name="Nombre plural",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="prefiere_notacion_cientifica",
            field=models.BooleanField(
                default=False,
                help_text="Usar notación científica para valores muy grandes/pequeños",
                verbose_name="Notación científica",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="simbolo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Símbolo corto (ej: m³, hrs). Si vacío, se usa abreviatura.",
                max_length=10,
                verbose_name="Símbolo",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="unidad_base",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad base para conversión (ej: kg es base de ton)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades_derivadas",
                to="catalogo_productos.unidadmedida",
                verbose_name="Unidad base",
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="usar_separador_miles",
            field=models.BooleanField(
                default=True,
                help_text="Formatear con separador de miles (1,200 vs 1200)",
                verbose_name="Usar separador de miles",
            ),
        ),
        migrations.AlterField(
            model_name="unidadmedida",
            name="factor_conversion",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=Decimal("1.0"),
                help_text="Factor para convertir a unidad base (ej: 1 ton = 1000 kg → factor: 1000)",
                max_digits=20,
                null=True,
                verbose_name="Factor de conversión",
            ),
        ),
        migrations.AlterField(
            model_name="unidadmedida",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PESO", "Peso"),
                    ("VOLUMEN", "Volumen"),
                    ("LONGITUD", "Longitud"),
                    ("AREA", "Área"),
                    ("UNIDAD", "Unidad"),
                    ("TIEMPO", "Tiempo"),
                    ("CONTENEDOR", "Contenedor / Embalaje"),
                    ("OTRO", "Otro"),
                ],
                default="UNIDAD",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
