# Generated by Django 5.0.14 on 2026-04-23 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo_productos", "0015_tipo_proveedor_tipos_productos_permitidos"),
        ("gestion_proveedores", "0008_preciomateriaprima_modalidad_logistica"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="modalidad_logistica",
            field=models.ForeignKey(
                blank=True,
                help_text="Forma de entrega habitual del proveedor (entrega en planta / recolección en punto).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proveedores_ct",
                to="gestion_proveedores.modalidadlogistica",
                verbose_name="Modalidad logística",
            ),
        ),
    ]
