# Generated by Django 5.0.14 on 2026-04-27 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo_productos", "0020_proveedor_drop_sede_empresa_origen"),
        ("catalogos", "0010_modo_directa_y_quitar_frecuencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="ruta_origen",
            field=models.OneToOneField(
                blank=True,
                help_text="DEPRECATED H-SC-RUTA-02. No usar en código nuevo. Drop pendiente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proveedor_espejo",
                to="catalogos.rutarecoleccion",
                verbose_name="[DEPRECATED] Ruta de origen",
            ),
        ),
    ]
