# Generated by Django 5.0.14 on 2026-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo_productos", "0021_alter_proveedor_ruta_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="frecuencia_pago",
            field=models.CharField(
                choices=[
                    ("INMEDIATA", "Inmediata (por entrega)"),
                    ("SEMANAL", "Semanal"),
                    ("QUINCENAL", "Quincenal"),
                    ("MENSUAL", "Mensual"),
                ],
                default="INMEDIATA",
                help_text="Frecuencia con la que se acumulan entregas para liquidación.",
                max_length=20,
            ),
        ),
    ]
