# Generated by Django 5.0.9 on 2025-12-22 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActaRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_acta", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("lugar", models.CharField(max_length=200)),
                (
                    "introduccion",
                    models.TextField(
                        blank=True, help_text="Introducción y objetivos de la reunión"
                    ),
                ),
                ("orden_del_dia", models.TextField(blank=True)),
                (
                    "conclusiones_generales",
                    models.TextField(
                        blank=True, help_text="Conclusiones generales de la revisión"
                    ),
                ),
                (
                    "decisiones_mejora",
                    models.TextField(
                        blank=True, help_text="Oportunidades de mejora identificadas"
                    ),
                ),
                (
                    "necesidad_cambios",
                    models.TextField(
                        blank=True, help_text="Necesidad de cambios en el SG"
                    ),
                ),
                (
                    "necesidad_recursos",
                    models.TextField(blank=True, help_text="Necesidades de recursos"),
                ),
                (
                    "evaluacion_sistema",
                    models.CharField(
                        choices=[
                            ("adecuado", "Adecuado"),
                            ("parcialmente_adecuado", "Parcialmente Adecuado"),
                            ("no_adecuado", "No Adecuado"),
                        ],
                        default="adecuado",
                        max_length=50,
                    ),
                ),
                ("observaciones_evaluacion", models.TextField(blank=True)),
                ("fecha_elaboracion", models.DateField(blank=True, null=True)),
                ("fecha_revision", models.DateField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateField(blank=True, null=True)),
                (
                    "documento_acta",
                    models.FileField(
                        blank=True, null=True, upload_to="revisiones/actas/"
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_revision_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elaborado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_revision_elaboradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_revision_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de Revisión",
                "verbose_name_plural": "Actas de Revisión",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CompromisoRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consecutivo", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("accion_correctiva", "Acción Correctiva"),
                            ("accion_preventiva", "Acción Preventiva"),
                            ("mejora", "Oportunidad de Mejora"),
                            ("decision", "Decisión Directiva"),
                            ("asignacion_recurso", "Asignación de Recurso"),
                            ("cambio_sg", "Cambio en el Sistema de Gestión"),
                            ("otro", "Otro"),
                        ],
                        default="mejora",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("resultado_esperado", models.TextField(blank=True)),
                (
                    "fecha_compromiso",
                    models.DateField(help_text="Fecha límite de cumplimiento"),
                ),
                ("fecha_cumplimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En Progreso"),
                            ("completado", "Completado"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("evidencia_cumplimiento", models.TextField(blank=True)),
                (
                    "documento_evidencia",
                    models.FileField(
                        blank=True, null=True, upload_to="revisiones/evidencias/"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compromisos",
                        to="revision_direccion.actarevision",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compromisos_revision_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromiso de Revisión",
                "verbose_name_plural": "Compromisos de Revisión",
                "ordering": ["-prioridad", "fecha_compromiso"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(db_index=True, default=1),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(help_text="Año del programa"),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Ej: 'Primer Semestre 2025'", max_length=50
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("cuatrimestral", "Cuatrimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        default="semestral",
                        max_length=20,
                    ),
                ),
                ("fecha_programada", models.DateField()),
                ("fecha_realizada", models.DateField(blank=True, null=True)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                (
                    "duracion_estimada_horas",
                    models.DecimalField(decimal_places=1, default=2.0, max_digits=4),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, help_text="Lugar o sala de reunión", max_length=200
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(blank=True, default="presencial", max_length=50),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("convocada", "Convocada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("reprogramada", "Reprogramada"),
                        ],
                        db_index=True,
                        default="programada",
                        max_length=20,
                    ),
                ),
                (
                    "incluye_calidad",
                    models.BooleanField(default=True, verbose_name="ISO 9001"),
                ),
                (
                    "incluye_sst",
                    models.BooleanField(default=True, verbose_name="ISO 45001/SST"),
                ),
                (
                    "incluye_ambiental",
                    models.BooleanField(default=True, verbose_name="ISO 14001"),
                ),
                (
                    "incluye_pesv",
                    models.BooleanField(default=False, verbose_name="PESV"),
                ),
                (
                    "incluye_seguridad_info",
                    models.BooleanField(default=False, verbose_name="ISO 27001"),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programas_revision_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable_convocatoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisiones_convocadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Revisión",
                "verbose_name_plural": "Programas de Revisión",
                "ordering": ["-anio", "fecha_programada"],
                "unique_together": {("empresa_id", "anio", "periodo")},
            },
        ),
        migrations.AddField(
            model_name="actarevision",
            name="programa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acta",
                to="revision_direccion.programarevision",
            ),
        ),
        migrations.CreateModel(
            name="SeguimientoCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "porcentaje_avance",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("descripcion_avance", models.TextField()),
                (
                    "evidencia",
                    models.FileField(
                        blank=True, null=True, upload_to="revisiones/seguimientos/"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compromiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="revision_direccion.compromisorevision",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_compromiso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Compromiso",
                "verbose_name_plural": "Seguimientos de Compromisos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="TemaRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            (
                                "estado_acciones",
                                "Estado de acciones de revisiones previas",
                            ),
                            (
                                "cambios_contexto",
                                "Cambios en cuestiones externas e internas",
                            ),
                            ("info_desempeno", "Información sobre el desempeño del SG"),
                            ("satisfaccion_cliente", "Satisfacción del cliente y PI"),
                            ("objetivos", "Grado de cumplimiento de objetivos"),
                            (
                                "no_conformidades",
                                "No conformidades y acciones correctivas",
                            ),
                            ("auditorias", "Resultados de auditorías"),
                            ("proveedores", "Desempeño de proveedores externos"),
                            ("adecuacion_recursos", "Adecuación de recursos"),
                            ("eficacia_acciones", "Eficacia de acciones de riesgos"),
                            ("oportunidades_mejora", "Oportunidades de mejora"),
                            (
                                "incidentes",
                                "Incidentes, no conformidades, acciones correctivas",
                            ),
                            ("participacion", "Consulta y participación trabajadores"),
                            ("requisitos_legales", "Cumplimiento requisitos legales"),
                            ("otro", "Otro tema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "documento_soporte",
                    models.FileField(
                        blank=True, null=True, upload_to="revisiones/documentos/"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=1)),
                ("fue_presentado", models.BooleanField(default=False)),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas",
                        to="revision_direccion.programarevision",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temas_revision_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema de Revisión",
                "verbose_name_plural": "Temas de Revisión",
                "ordering": ["programa", "orden"],
            },
        ),
        migrations.AddField(
            model_name="compromisorevision",
            name="tema_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compromisos",
                to="revision_direccion.temarevision",
            ),
        ),
        migrations.CreateModel(
            name="ParticipanteRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("direccion", "Alta Dirección"),
                            ("lider_proceso", "Líder de Proceso"),
                            ("responsable_sg", "Responsable SG"),
                            ("invitado", "Invitado"),
                            ("secretario", "Secretario"),
                        ],
                        default="invitado",
                        max_length=20,
                    ),
                ),
                ("es_obligatorio", models.BooleanField(default=True)),
                ("confirmo_asistencia", models.BooleanField(default=False)),
                ("asistio", models.BooleanField(default=False)),
                ("observaciones", models.CharField(blank=True, max_length=300)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones_revision",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="revision_direccion.programarevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante de Revisión",
                "verbose_name_plural": "Participantes de Revisión",
                "unique_together": {("programa", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="AnalisisTemaActa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resumen_presentacion",
                    models.TextField(help_text="Resumen de la presentación"),
                ),
                (
                    "hallazgos",
                    models.TextField(blank=True, help_text="Hallazgos principales"),
                ),
                (
                    "decisiones",
                    models.TextField(blank=True, help_text="Decisiones tomadas"),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_temas",
                        to="revision_direccion.actarevision",
                    ),
                ),
                (
                    "presentado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis",
                        to="revision_direccion.temarevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de Tema",
                "verbose_name_plural": "Análisis de Temas",
                "unique_together": {("acta", "tema")},
            },
        ),
    ]
