# Generated by Django 5.0.9 on 2025-12-25 19:35
# Modified to use SeparateDatabaseAndState for existing DB structure

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0006_sedeempresa_updated_by_and_more"),
        ("revision_direccion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Usar SeparateDatabaseAndState para manejar la diferencia entre
        # el estado de Django y la realidad de la base de datos
        migrations.SeparateDatabaseAndState(
            # DATABASE OPERATIONS: lo que realmente se ejecuta en la BD
            database_operations=[
                # La FK empresa_id ya existe en la BD apuntando a configuracion_empresa
                # Solo necesitamos crear el índice único
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE revision_direccion_programarevision
                    ADD UNIQUE INDEX revision_direccion_programarevision_empresa_id_anio_periodo_uniq
                    (empresa_id, anio, periodo)
                    """,
                    reverse_sql="""
                    ALTER TABLE revision_direccion_programarevision
                    DROP INDEX revision_direccion_programarevision_empresa_id_anio_periodo_uniq
                    """,
                ),
            ],
            # STATE OPERATIONS: actualizar el estado de Django para que coincida con models.py
            state_operations=[
                # Eliminar el unique_together inexistente
                migrations.AlterUniqueTogether(
                    name="programarevision",
                    unique_together=set(),
                ),
                # Remover el campo empresa_id del estado
                migrations.RemoveField(
                    model_name="programarevision",
                    name="empresa_id",
                ),
                # Agregar el campo empresa como FK (solo en estado de Django)
                migrations.AddField(
                    model_name="programarevision",
                    name="empresa",
                    field=models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                        db_column="empresa_id",  # Usar la columna existente
                    ),
                ),
                # Establecer el nuevo unique_together con empresa (FK)
                migrations.AlterUniqueTogether(
                    name="programarevision",
                    unique_together={("empresa", "anio", "periodo")},
                ),
            ],
        ),
        # Resto de campos para otros modelos (estos se ejecutan normalmente)
        migrations.AddField(
            model_name="actarevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="actarevision",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="actarevision",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="compromisorevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="compromisorevision",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="compromisorevision",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="programarevision",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="programarevision",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="seguimientocompromiso",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="actarevision",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="actarevision",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="actarevision",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="compromisorevision",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="compromisorevision",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="compromisorevision",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="programarevision",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="programarevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="programarevision",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="programarevision",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="seguimientocompromiso",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
    ]
