# Generated by Django 5.0.9 on 2025-12-25 19:56
# Modified: Solo actualiza estado de Django, no toca BD

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0006_sedeempresa_updated_by_and_more"),
        ("revision_direccion", "0002_alter_programarevision_unique_together_and_more"),
    ]

    operations = [
        # Solo actualizamos el estado de Django (sin db_column explícito)
        # La BD no cambia, solo removemos el db_column="empresa_id" del estado
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacemos nada en la BD, la columna ya existe correctamente
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="programarevision",
                    name="empresa",
                    field=models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
            ],
        ),
    ]
