# Generated by Django 5.0.14 on 2026-03-19 22:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaboradores", "0001_initial"),
        ("configuracion", "0003_unify_sede_unidadnegocio"),
        (
            "core",
            "0005_rename_core_email__user_id_purpose_idx_core_email__user_id_5f5ad3_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código del Item"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=300, verbose_name="Descripción del Item"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("documentos", "Documentación"),
                            ("afiliaciones", "Afiliaciones"),
                            ("equipos", "Equipos y Herramientas"),
                            ("accesos", "Accesos y Credenciales"),
                            ("capacitacion", "Capacitación"),
                            ("otros", "Otros"),
                        ],
                        default="documentos",
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "requiere_adjunto",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Archivo Adjunto"
                    ),
                ),
                (
                    "requiere_fecha",
                    models.BooleanField(default=False, verbose_name="Requiere Fecha"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "aplica_a_todos",
                    models.BooleanField(
                        default=True, verbose_name="Aplica a Todos los Cargos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Checklist",
                "verbose_name_plural": "Items de Checklist",
                "db_table": "mi_equipo_item_checklist",
                "ordering": ["categoria", "orden"],
            },
        ),
        migrations.CreateModel(
            name="ModuloInduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Código único del módulo (ej: IND-001)",
                        max_length=20,
                        verbose_name="Código del Módulo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Módulo"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_modulo",
                    models.CharField(
                        choices=[
                            ("induccion_general", "Inducción General"),
                            ("induccion_especifica", "Inducción Específica"),
                            ("reinduccion", "Reinducción"),
                            ("sst", "Seguridad y Salud en el Trabajo"),
                            ("calidad", "Sistema de Calidad"),
                            ("ambiente", "Gestión Ambiental"),
                            ("etica", "Código de Ética"),
                            ("pesv", "Seguridad Vial"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="induccion_general",
                        max_length=20,
                        verbose_name="Tipo de Módulo",
                    ),
                ),
                (
                    "formato_contenido",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("presentacion", "Presentación"),
                            ("documento", "Documento PDF"),
                            ("quiz", "Cuestionario"),
                            ("actividad", "Actividad Práctica"),
                            ("presencial", "Sesión Presencial"),
                            ("mixto", "Mixto"),
                        ],
                        default="presentacion",
                        max_length=20,
                        verbose_name="Formato del Contenido",
                    ),
                ),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Tiempo estimado para completar el módulo",
                        verbose_name="Duración (minutos)",
                    ),
                ),
                (
                    "requiere_evaluacion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Evaluación"
                    ),
                ),
                (
                    "nota_minima_aprobacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("70.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nota Mínima Aprobación (%)",
                    ),
                ),
                (
                    "intentos_permitidos",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Intentos Permitidos"
                    ),
                ),
                (
                    "contenido_url",
                    models.URLField(
                        blank=True,
                        help_text="Enlace al video o recurso externo",
                        verbose_name="URL del Contenido",
                    ),
                ),
                (
                    "archivo_contenido",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/modulos/",
                        verbose_name="Archivo de Contenido",
                    ),
                ),
                (
                    "preguntas_evaluacion",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de preguntas en formato JSON",
                        verbose_name="Preguntas de Evaluación",
                    ),
                ),
                (
                    "fecha_vigencia_desde",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente Desde"
                    ),
                ),
                (
                    "fecha_vigencia_hasta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente Hasta"
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de Ejecución"
                    ),
                ),
                (
                    "es_obligatorio",
                    models.BooleanField(default=True, verbose_name="Es Obligatorio"),
                ),
            ],
            options={
                "verbose_name": "Módulo de Inducción",
                "verbose_name_plural": "Módulos de Inducción",
                "db_table": "mi_equipo_modulo_induccion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionPorCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "es_obligatorio",
                    models.BooleanField(
                        default=True, verbose_name="Es Obligatorio para este Cargo"
                    ),
                ),
                (
                    "dias_para_completar",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días desde el ingreso para completar el módulo",
                        verbose_name="Días para Completar",
                    ),
                ),
                (
                    "orden_ejecucion",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de Ejecución"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_induccion",
                        to="core.cargo",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación por Cargo",
                "verbose_name_plural": "Asignaciones por Cargo",
                "db_table": "mi_equipo_asignacion_cargo_modulo",
                "ordering": ["cargo", "orden_ejecucion"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("cumplido", "Cumplido"),
                            ("no_aplica", "No Aplica"),
                            ("incompleto", "Incompleto"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_cumplimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Cumplimiento"
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/checklist/",
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_ingreso",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_verificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist de Ingreso",
                "verbose_name_plural": "Checklists de Ingreso",
                "db_table": "mi_equipo_checklist_ingreso",
                "ordering": ["colaborador", "item__orden"],
            },
        ),
        migrations.CreateModel(
            name="EjecucionIntegral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En Progreso"),
                            ("completado", "Completado"),
                            ("reprobado", "Reprobado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                ("fecha_limite", models.DateField(verbose_name="Fecha Límite")),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "progreso_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "tiempo_dedicado_minutos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo Dedicado (min)"
                    ),
                ),
                (
                    "nota_obtenida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nota Obtenida",
                    ),
                ),
                (
                    "intentos_realizados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos Realizados"
                    ),
                ),
                (
                    "respuestas_evaluacion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Respuestas de Evaluación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "retroalimentacion_colaborador",
                    models.TextField(
                        blank=True, verbose_name="Retroalimentación del Colaborador"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejecuciones_induccion",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "facilitador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inducciones_facilitadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Facilitador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Inducción",
                "verbose_name_plural": "Ejecuciones de Inducción",
                "db_table": "mi_equipo_ejecucion_integral",
                "ordering": ["colaborador", "modulo__orden"],
            },
        ),
        migrations.CreateModel(
            name="EntregaActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_activo",
                    models.CharField(
                        choices=[
                            ("computador", "Computador"),
                            ("celular", "Celular Corporativo"),
                            ("radio", "Radio de Comunicación"),
                            ("vehiculo", "Vehículo"),
                            ("herramienta", "Herramienta"),
                            ("uniforme", "Uniforme"),
                            ("carnet", "Carnet/Credencial"),
                            ("llaves", "Llaves"),
                            ("tarjeta_acceso", "Tarjeta de Acceso"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Activo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=200, verbose_name="Descripción del Activo"
                    ),
                ),
                (
                    "codigo_activo",
                    models.CharField(
                        blank=True,
                        help_text="Código de inventario interno",
                        max_length=50,
                        verbose_name="Código del Activo",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Serie"
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "valor_activo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor del Activo (COP)",
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(db_index=True, verbose_name="Fecha de Entrega"),
                ),
                (
                    "fecha_devolucion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Devolución"
                    ),
                ),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("buen_estado", "Buen Estado"),
                            ("uso_normal", "Uso Normal"),
                            ("desgastado", "Desgastado"),
                        ],
                        default="nuevo",
                        max_length=20,
                        verbose_name="Estado al Entregar",
                    ),
                ),
                (
                    "estado_devolucion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buen_estado", "Buen Estado"),
                            ("uso_normal", "Uso Normal"),
                            ("desgastado", "Desgastado"),
                            ("danado", "Dañado"),
                            ("perdido", "Perdido"),
                        ],
                        max_length=20,
                        verbose_name="Estado al Devolver",
                    ),
                ),
                (
                    "recibido_conforme",
                    models.BooleanField(default=True, verbose_name="Recibido Conforme"),
                ),
                (
                    "devuelto",
                    models.BooleanField(default=False, verbose_name="Devuelto"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "acta_entrega",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/actas_activos/",
                        verbose_name="Acta de Entrega",
                    ),
                ),
                (
                    "acta_devolucion",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/actas_activos/",
                        verbose_name="Acta de Devolución",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_activos",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos_entregados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregado Por",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos_recibidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido Por (Devolución)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Activo",
                "verbose_name_plural": "Entregas de Activos",
                "db_table": "mi_equipo_entrega_activo",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="EntregaEPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_epp",
                    models.CharField(
                        choices=[
                            ("casco", "Casco de Seguridad"),
                            ("gafas", "Gafas de Protección"),
                            ("guantes", "Guantes"),
                            ("botas", "Botas de Seguridad"),
                            ("overol", "Overol"),
                            ("protector_auditivo", "Protector Auditivo"),
                            ("mascarilla", "Mascarilla/Respirador"),
                            ("arnes", "Arnés de Seguridad"),
                            ("chaleco", "Chaleco Reflectivo"),
                            ("otro", "Otro"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de EPP",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=200, verbose_name="Descripción del EPP"
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia/Modelo"
                    ),
                ),
                (
                    "talla",
                    models.CharField(blank=True, max_length=20, verbose_name="Talla"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(db_index=True, verbose_name="Fecha de Entrega"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Vencimiento/Reposición",
                    ),
                ),
                (
                    "recibido_conforme",
                    models.BooleanField(default=True, verbose_name="Recibido Conforme"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "acta_entrega",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/actas_epp/",
                        verbose_name="Acta de Entrega Firmada",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_epp",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epp_entregados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregado Por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de EPP",
                "verbose_name_plural": "Entregas de EPP",
                "db_table": "mi_equipo_entrega_epp",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="FirmaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato de Trabajo"),
                            ("reglamento_interno", "Reglamento Interno de Trabajo"),
                            ("politica_datos", "Política de Tratamiento de Datos"),
                            ("politica_sst", "Política SST"),
                            ("acuerdo_confidencialidad", "Acuerdo de Confidencialidad"),
                            ("autorizacion_descuento", "Autorización de Descuentos"),
                            ("compromiso_cumplimiento", "Compromiso de Cumplimiento"),
                            ("otro", "Otro Documento"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Versión del Documento"
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/documentos/",
                        verbose_name="Documento Original",
                    ),
                ),
                (
                    "documento_firmado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/documentos_firmados/",
                        verbose_name="Documento Firmado",
                    ),
                ),
                (
                    "fecha_firma",
                    models.DateField(db_index=True, verbose_name="Fecha de Firma"),
                ),
                ("firmado", models.BooleanField(default=False, verbose_name="Firmado")),
                (
                    "metodo_firma",
                    models.CharField(
                        choices=[
                            ("fisico", "Firma Física"),
                            ("digital", "Firma Digital"),
                            ("electronica", "Firma Electrónica"),
                        ],
                        default="fisico",
                        max_length=20,
                        verbose_name="Método de Firma",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmas_documentos",
                        to="colaboradores.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma de Documento",
                "verbose_name_plural": "Firmas de Documentos",
                "db_table": "mi_equipo_firma_documento",
                "ordering": ["-fecha_firma"],
            },
        ),
    ]
