# Generated by Django 5.0.14 on 2026-02-22 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAspecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Codigo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EMISION", "Emisiones a la Atmosfera"),
                            ("VERTIMIENTO", "Vertimientos al Agua"),
                            ("RESIDUO", "Generacion de Residuos"),
                            ("CONSUMO_RECURSO", "Consumo de Recursos"),
                            ("CONTAMINACION_SUELO", "Contaminacion del Suelo"),
                            ("RUIDO_VIBRACION", "Ruido y Vibraciones"),
                            ("BIODIVERSIDAD", "Afectacion a Biodiversidad"),
                            ("ENERGIA", "Uso de Energia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Aspecto",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "impactos_asociados",
                    models.TextField(
                        blank=True,
                        help_text="Posibles impactos que puede generar este tipo de aspecto",
                        verbose_name="Impactos Ambientales Asociados",
                    ),
                ),
                (
                    "requisitos_legales",
                    models.TextField(
                        blank=True,
                        help_text="Normatividad colombiana aplicable (ej: Decreto 1076/2015)",
                        verbose_name="Requisitos Legales Aplicables",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Aspecto Ambiental",
                "verbose_name_plural": "Categorias de Aspectos Ambientales",
                "db_table": "aspectos_amb_categoria",
                "ordering": ["tipo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="AspectoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico del aspecto",
                        max_length=50,
                        verbose_name="Codigo",
                    ),
                ),
                (
                    "proceso",
                    models.CharField(
                        help_text="Proceso donde se identifica el aspecto",
                        max_length=200,
                        verbose_name="Proceso",
                    ),
                ),
                (
                    "actividad",
                    models.CharField(max_length=300, verbose_name="Actividad"),
                ),
                (
                    "descripcion_aspecto",
                    models.TextField(
                        help_text="Elemento de las actividades que puede interactuar con el ambiente",
                        verbose_name="Descripcion del Aspecto Ambiental",
                    ),
                ),
                (
                    "condicion_operacion",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Operacion Normal"),
                            ("ANORMAL", "Operacion Anormal"),
                            ("EMERGENCIA", "Situacion de Emergencia"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Condicion de Operacion",
                    ),
                ),
                (
                    "tiempo_verbo",
                    models.CharField(
                        choices=[
                            ("PASADO", "Pasado"),
                            ("PRESENTE", "Presente"),
                            ("FUTURO", "Futuro"),
                        ],
                        default="PRESENTE",
                        help_text="Cuando ocurre el aspecto?",
                        max_length=20,
                        verbose_name="Temporalidad",
                    ),
                ),
                (
                    "frecuencia",
                    models.PositiveSmallIntegerField(
                        help_text="1=Muy Baja, 2=Baja, 3=Media, 4=Alta, 5=Muy Alta",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "severidad",
                    models.PositiveSmallIntegerField(
                        help_text="1=Muy Baja, 2=Baja, 3=Media, 4=Alta, 5=Muy Alta",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Severidad del Impacto",
                    ),
                ),
                (
                    "probabilidad",
                    models.PositiveSmallIntegerField(
                        help_text="1=Muy Baja, 2=Baja, 3=Media, 4=Alta, 5=Muy Alta",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Probabilidad de Ocurrencia",
                    ),
                ),
                (
                    "alcance",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Area afectada: 1=Puntual, 5=Regional",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Alcance/Extension",
                    ),
                ),
                (
                    "reversibilidad",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Capacidad de recuperacion: 1=Totalmente reversible, 5=Irreversible",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reversibilidad",
                    ),
                ),
                (
                    "cumplimiento_legal",
                    models.BooleanField(
                        default=True,
                        help_text="Se cumple la normatividad aplicable?",
                        verbose_name="Cumplimiento Legal",
                    ),
                ),
                (
                    "quejas_comunidad",
                    models.BooleanField(
                        default=False,
                        help_text="Ha generado quejas de partes interesadas?",
                        verbose_name="Quejas de la Comunidad",
                    ),
                ),
                (
                    "valor_significancia",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Frecuencia x Severidad x Probabilidad",
                        verbose_name="Valor de Significancia",
                    ),
                ),
                (
                    "significancia",
                    models.CharField(
                        choices=[
                            ("NO_SIGNIFICATIVO", "No Significativo"),
                            ("SIGNIFICATIVO", "Significativo"),
                            ("CRITICO", "Critico"),
                        ],
                        editable=False,
                        max_length=20,
                        verbose_name="Significancia",
                    ),
                ),
                (
                    "descripcion_impacto",
                    models.TextField(
                        help_text="Cambio en el medio ambiente como resultado del aspecto",
                        verbose_name="Descripcion del Impacto Ambiental",
                    ),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("NEGATIVO", "Negativo"), ("POSITIVO", "Positivo")],
                        default="NEGATIVO",
                        max_length=20,
                        verbose_name="Tipo de Impacto",
                    ),
                ),
                (
                    "controles_actuales",
                    models.TextField(
                        blank=True,
                        help_text="Medidas de control implementadas actualmente",
                        verbose_name="Controles Actuales",
                    ),
                ),
                (
                    "procedimientos_asociados",
                    models.TextField(
                        blank=True,
                        help_text="Procedimientos operacionales que controlan el aspecto",
                        verbose_name="Procedimientos Asociados",
                    ),
                ),
                (
                    "areas_afectadas",
                    models.TextField(
                        blank=True,
                        help_text="Ubicaciones donde se presenta el aspecto",
                        verbose_name="Areas Afectadas",
                    ),
                ),
                (
                    "requisito_legal_aplicable",
                    models.TextField(
                        blank=True,
                        help_text="Normatividad colombiana especifica (Decretos, Resoluciones)",
                        verbose_name="Requisito Legal Aplicable",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("VIGENTE", "Vigente"),
                            ("EN_REVISION", "En Revision"),
                            ("OBSOLETO", "Obsoleto"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_identificacion",
                    models.DateField(verbose_name="Fecha de Identificacion"),
                ),
                (
                    "proxima_evaluacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Proxima Evaluacion"
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aspectos",
                        to="aspectos_ambientales.categoriaaspecto",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aspecto Ambiental",
                "verbose_name_plural": "Aspectos Ambientales",
                "db_table": "aspectos_amb_aspecto",
                "ordering": ["-valor_significancia", "proceso"],
            },
        ),
        migrations.CreateModel(
            name="ImpactoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Codigo del Impacto"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del Impacto"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Cambio ambiental resultante del aspecto",
                        verbose_name="Descripcion del Impacto",
                    ),
                ),
                (
                    "componente_ambiental",
                    models.CharField(
                        choices=[
                            ("AIRE", "Aire"),
                            ("AGUA", "Agua"),
                            ("SUELO", "Suelo"),
                            ("FLORA", "Flora"),
                            ("FAUNA", "Fauna"),
                            ("PAISAJE", "Paisaje"),
                            ("SOCIAL", "Social"),
                            ("ECONOMICO", "Economico"),
                        ],
                        max_length=20,
                        verbose_name="Componente Ambiental Afectado",
                    ),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("NEGATIVO", "Negativo"), ("POSITIVO", "Positivo")],
                        default="NEGATIVO",
                        max_length=20,
                        verbose_name="Tipo de Impacto",
                    ),
                ),
                (
                    "magnitud",
                    models.CharField(
                        choices=[
                            ("MUY_BAJA", "Muy Baja"),
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("MUY_ALTA", "Muy Alta"),
                        ],
                        max_length=20,
                        verbose_name="Magnitud del Impacto",
                    ),
                ),
                (
                    "duracion",
                    models.CharField(
                        choices=[
                            ("TEMPORAL", "Temporal (< 1 anio)"),
                            ("MEDIO_PLAZO", "Medio Plazo (1-5 anios)"),
                            ("PERMANENTE", "Permanente (> 5 anios)"),
                        ],
                        max_length=20,
                        verbose_name="Duracion",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        choices=[
                            ("PUNTUAL", "Puntual"),
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                        ],
                        max_length=20,
                        verbose_name="Extension",
                    ),
                ),
                (
                    "valor_cuantitativo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ej: kg CO2, m3 agua, tons residuos",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Cuantitativo",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidad de Medida"
                    ),
                ),
                (
                    "medidas_control",
                    models.TextField(
                        blank=True,
                        help_text="Acciones para prevenir, mitigar o compensar el impacto",
                        verbose_name="Medidas de Control",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "aspecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impactos",
                        to="aspectos_ambientales.aspectoambiental",
                        verbose_name="Aspecto Ambiental",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impacto Ambiental",
                "verbose_name_plural": "Impactos Ambientales",
                "db_table": "aspectos_amb_impacto",
                "ordering": ["aspecto", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Codigo del Programa"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Programa"
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        help_text="Que se pretende lograr con este programa",
                        verbose_name="Objetivo del Programa",
                    ),
                ),
                (
                    "tipo_programa",
                    models.CharField(
                        choices=[
                            ("PREVENCION", "Prevencion"),
                            ("MITIGACION", "Mitigacion"),
                            ("COMPENSACION", "Compensacion"),
                            ("MEJORAMIENTO", "Mejoramiento Continuo"),
                            ("CUMPLIMIENTO", "Cumplimiento Legal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Programa",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Fecha de Inicio Planificada"),
                ),
                (
                    "fecha_fin",
                    models.DateField(verbose_name="Fecha de Fin Planificada"),
                ),
                (
                    "actividades",
                    models.TextField(
                        help_text="Descripcion detallada de actividades a ejecutar",
                        verbose_name="Actividades del Programa",
                    ),
                ),
                (
                    "metas",
                    models.TextField(
                        help_text="Metas especificas, medibles y con plazo",
                        verbose_name="Metas",
                    ),
                ),
                (
                    "indicadores_medicion",
                    models.TextField(
                        blank=True,
                        help_text="Como se medira el progreso y cumplimiento",
                        verbose_name="Indicadores de Medicion",
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto Asignado",
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(
                        blank=True,
                        help_text="Recursos humanos, tecnicos, financieros",
                        verbose_name="Recursos Necesarios",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecucion"),
                            ("COMPLETADO", "Completado"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANIFICADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de Avance",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_completado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Completacion Real"
                    ),
                ),
                (
                    "resultados_obtenidos",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion de logros y resultados al finalizar",
                        verbose_name="Resultados Obtenidos",
                    ),
                ),
                (
                    "eficacia",
                    models.CharField(
                        choices=[
                            ("NO_EVALUADO", "No Evaluado"),
                            ("EFICAZ", "Eficaz"),
                            ("PARCIALMENTE_EFICAZ", "Parcialmente Eficaz"),
                            ("NO_EFICAZ", "No Eficaz"),
                        ],
                        default="NO_EVALUADO",
                        max_length=20,
                        verbose_name="Eficacia del Programa",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "aspectos_relacionados",
                    models.ManyToManyField(
                        help_text="Aspectos que este programa busca controlar",
                        related_name="programas",
                        to="aspectos_ambientales.aspectoambiental",
                        verbose_name="Aspectos Ambientales Relacionados",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "equipo_apoyo",
                    models.ManyToManyField(
                        blank=True,
                        related_name="programas_ambientales_equipo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Equipo de Apoyo",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programas_ambientales_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Programa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa Ambiental",
                "verbose_name_plural": "Programas Ambientales",
                "db_table": "aspectos_amb_programa",
                "ordering": ["-fecha_inicio", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="MonitoreoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Codigo de Monitoreo"),
                ),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("EMISION_ATMOSFERICA", "Emision Atmosferica"),
                            ("CALIDAD_AGUA", "Calidad del Agua"),
                            ("VERTIMIENTO", "Vertimiento"),
                            ("RUIDO", "Ruido Ambiental"),
                            ("RESIDUOS", "Gestion de Residuos"),
                            ("CONSUMO_AGUA", "Consumo de Agua"),
                            ("CONSUMO_ENERGIA", "Consumo de Energia"),
                            ("CONSUMO_COMBUSTIBLE", "Consumo de Combustible"),
                            ("BIODIVERSIDAD", "Biodiversidad"),
                            ("SUELO", "Calidad del Suelo"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Monitoreo",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        max_length=200, verbose_name="Ubicacion del Monitoreo"
                    ),
                ),
                (
                    "fecha_monitoreo",
                    models.DateField(verbose_name="Fecha del Monitoreo"),
                ),
                (
                    "hora_monitoreo",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora del Monitoreo"
                    ),
                ),
                (
                    "frecuencia_requerida",
                    models.CharField(
                        choices=[
                            ("DIARIA", "Diaria"),
                            ("SEMANAL", "Semanal"),
                            ("MENSUAL", "Mensual"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("SEMESTRAL", "Semestral"),
                            ("ANUAL", "Anual"),
                            ("EVENTUAL", "Eventual"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia Requerida",
                    ),
                ),
                (
                    "parametro_medido",
                    models.CharField(
                        help_text="Ej: pH, DBO, Material Particulado, dB(A), kWh",
                        max_length=200,
                        verbose_name="Parametro Medido",
                    ),
                ),
                (
                    "valor_medido",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Valor Medido"
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=50, verbose_name="Unidad de Medida"),
                ),
                (
                    "valor_referencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Limite legal o meta establecida",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor de Referencia/Limite",
                    ),
                ),
                (
                    "cumplimiento",
                    models.CharField(
                        choices=[
                            ("CUMPLE", "Cumple"),
                            ("NO_CUMPLE", "No Cumple"),
                            ("NO_APLICA", "No Aplica"),
                        ],
                        max_length=20,
                        verbose_name="Cumplimiento",
                    ),
                ),
                (
                    "normatividad_aplicable",
                    models.CharField(
                        blank=True,
                        help_text="Resolucion, Decreto o norma que establece el limite",
                        max_length=255,
                        verbose_name="Normatividad Aplicable",
                    ),
                ),
                (
                    "metodo_medicion",
                    models.CharField(
                        blank=True,
                        help_text="Metodo o norma tecnica utilizada",
                        max_length=200,
                        verbose_name="Metodo de Medicion",
                    ),
                ),
                (
                    "equipo_utilizado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Equipo Utilizado"
                    ),
                ),
                (
                    "laboratorio_externo",
                    models.CharField(
                        blank=True,
                        help_text="Si fue realizado por laboratorio acreditado",
                        max_length=200,
                        verbose_name="Laboratorio Externo",
                    ),
                ),
                (
                    "numero_informe",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numero de Informe de Laboratorio",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "acciones_tomadas",
                    models.TextField(
                        blank=True,
                        help_text="Acciones correctivas si no cumple",
                        verbose_name="Acciones Tomadas",
                    ),
                ),
                (
                    "evidencia_fotografica",
                    models.TextField(
                        blank=True,
                        help_text="URLs o referencias a fotografias",
                        verbose_name="Evidencia Fotografica",
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del informe o certificado",
                        max_length=500,
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "aspecto_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoreos",
                        to="aspectos_ambientales.aspectoambiental",
                        verbose_name="Aspecto Ambiental Relacionado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable_medicion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoreos_ambientales_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de la Medicion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "programa_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoreos",
                        to="aspectos_ambientales.programaambiental",
                        verbose_name="Programa Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoreo Ambiental",
                "verbose_name_plural": "Monitoreos Ambientales",
                "db_table": "aspectos_amb_monitoreo",
                "ordering": ["-fecha_monitoreo", "tipo_monitoreo"],
            },
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "estado"], name="aspectos_am_empresa_f166a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "significancia"],
                name="aspectos_am_empresa_641c4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "proceso"], name="aspectos_am_empresa_427393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["categoria", "significancia"],
                name="aspectos_am_categor_9c32d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aspectoambiental",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AddIndex(
            model_name="impactoambiental",
            index=models.Index(
                fields=["empresa_id", "componente_ambiental"],
                name="aspectos_am_empresa_af217f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impactoambiental",
            index=models.Index(
                fields=["tipo_impacto", "magnitud"],
                name="aspectos_am_tipo_im_687f9a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="impactoambiental",
            unique_together={("aspecto", "codigo")},
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["empresa_id", "estado"], name="aspectos_am_empresa_c8607b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["responsable", "estado"], name="aspectos_am_respons_22a42b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="aspectos_am_fecha_i_23af46_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programaambiental",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["empresa_id", "tipo_monitoreo"],
                name="aspectos_am_empresa_c85e43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["empresa_id", "fecha_monitoreo"],
                name="aspectos_am_empresa_f0e977_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["aspecto_relacionado", "fecha_monitoreo"],
                name="aspectos_am_aspecto_e34896_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["cumplimiento"], name="aspectos_am_cumplim_59a01e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monitoreoambiental",
            unique_together={("empresa_id", "codigo")},
        ),
    ]
