# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aspectos_ambientales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aspectoambiental",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aspectos_ambientales_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="aspectoambiental",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aspectos",
                to="aspectos_ambientales.categoriaaspecto",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="impactoambiental",
            name="aspecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impactos",
                to="aspectos_ambientales.aspectoambiental",
                verbose_name="Aspecto Ambiental",
            ),
        ),
        migrations.AddField(
            model_name="impactoambiental",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impactos_ambientales_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="monitoreoambiental",
            name="aspecto_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoreos",
                to="aspectos_ambientales.aspectoambiental",
                verbose_name="Aspecto Ambiental Relacionado",
            ),
        ),
        migrations.AddField(
            model_name="monitoreoambiental",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoreos_ambientales_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="monitoreoambiental",
            name="responsable_medicion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoreos_ambientales_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable de la Medición",
            ),
        ),
        migrations.AddField(
            model_name="programaambiental",
            name="aspectos_relacionados",
            field=models.ManyToManyField(
                help_text="Aspectos que este programa busca controlar",
                related_name="programas",
                to="aspectos_ambientales.aspectoambiental",
                verbose_name="Aspectos Ambientales Relacionados",
            ),
        ),
        migrations.AddField(
            model_name="programaambiental",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programas_ambientales_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="programaambiental",
            name="equipo_apoyo",
            field=models.ManyToManyField(
                blank=True,
                related_name="programas_ambientales_equipo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Equipo de Apoyo",
            ),
        ),
        migrations.AddField(
            model_name="programaambiental",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programas_ambientales_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable del Programa",
            ),
        ),
        migrations.AddField(
            model_name="monitoreoambiental",
            name="programa_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoreos",
                to="aspectos_ambientales.programaambiental",
                verbose_name="Programa Relacionado",
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "estado"], name="aspectos_am_empresa_f166a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "significancia"],
                name="aspectos_am_empresa_641c4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["empresa_id", "proceso"], name="aspectos_am_empresa_427393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aspectoambiental",
            index=models.Index(
                fields=["categoria", "significancia"],
                name="aspectos_am_categor_9c32d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aspectoambiental",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AddIndex(
            model_name="impactoambiental",
            index=models.Index(
                fields=["empresa_id", "componente_ambiental"],
                name="aspectos_am_empresa_af217f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impactoambiental",
            index=models.Index(
                fields=["tipo_impacto", "magnitud"],
                name="aspectos_am_tipo_im_687f9a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="impactoambiental",
            unique_together={("aspecto", "codigo")},
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["empresa_id", "estado"], name="aspectos_am_empresa_c8607b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["responsable", "estado"], name="aspectos_am_respons_22a42b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programaambiental",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="aspectos_am_fecha_i_23af46_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programaambiental",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["empresa_id", "tipo_monitoreo"],
                name="aspectos_am_empresa_c85e43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["empresa_id", "fecha_monitoreo"],
                name="aspectos_am_empresa_f0e977_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["aspecto_relacionado", "fecha_monitoreo"],
                name="aspectos_am_aspecto_e34896_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoreoambiental",
            index=models.Index(
                fields=["cumplimiento"], name="aspectos_am_cumplim_59a01e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monitoreoambiental",
            unique_together={("empresa_id", "codigo")},
        ),
    ]
