# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanalVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del canal (ej: DIRECTO, ECOMMERCE)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del canal de venta",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del canal de venta",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "aplica_comision",
                    models.BooleanField(
                        default=False,
                        help_text="¿Este canal aplica comisión de ventas?",
                        verbose_name="Aplica Comisión",
                    ),
                ),
                (
                    "porcentaje_comision",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de comisión (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje Comisión",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="¿Canal activo?",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canal de Venta",
                "verbose_name_plural": "Canales de Venta",
                "db_table": "sales_crm_canal_venta",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="sales_crm_c_codigo_007d69_idx"
                    ),
                    models.Index(
                        fields=["activo", "orden"], name="sales_crm_c_activo_e85565_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del estado (ej: ACTIVO, BLOQUEADO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del estado",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color para representación visual (success, warning, danger, info, gray)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del estado",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "permite_ventas",
                    models.BooleanField(
                        default=True,
                        help_text="¿El cliente en este estado puede realizar compras?",
                        verbose_name="Permite Ventas",
                    ),
                ),
                (
                    "requiere_aprobacion",
                    models.BooleanField(
                        default=False,
                        help_text="¿Requiere aprobación previa para ventas?",
                        verbose_name="Requiere Aprobación",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="¿Estado activo?",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Cliente",
                "verbose_name_plural": "Estados de Cliente",
                "db_table": "sales_crm_estado_cliente",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="sales_crm_e_codigo_176e13_idx"
                    ),
                    models.Index(
                        fields=["activo", "orden"], name="sales_crm_e_activo_951792_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo_cliente",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del cliente (auto-generado: CLI-XXXXX)",
                        max_length=50,
                        verbose_name="Código Cliente",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("NIT", "NIT"),
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        help_text="Tipo de documento de identificación",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="Número de documento de identificación",
                        max_length=20,
                        verbose_name="Número de Documento",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Nombre legal del cliente",
                        max_length=255,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True,
                        help_text="Nombre comercial o marca del cliente",
                        max_length=255,
                        verbose_name="Nombre Comercial",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email principal",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                        help_text="Dirección completa",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad donde se encuentra el cliente",
                        max_length=100,
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True,
                        help_text="Departamento/Estado donde se encuentra",
                        max_length=100,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Colombia",
                        help_text="País donde se encuentra el cliente",
                        max_length=100,
                        verbose_name="País",
                    ),
                ),
                (
                    "plazo_pago_dias",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días de plazo para pago de facturas",
                        verbose_name="Plazo de Pago (días)",
                    ),
                ),
                (
                    "cupo_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cupo máximo de crédito aprobado",
                        max_digits=15,
                        verbose_name="Cupo de Crédito",
                    ),
                ),
                (
                    "descuento_comercial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de descuento comercial (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Descuento Comercial %",
                    ),
                ),
                (
                    "fecha_primera_compra",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la primera compra realizada",
                        null=True,
                        verbose_name="Fecha Primera Compra",
                    ),
                ),
                (
                    "ultima_compra",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la última compra realizada",
                        null=True,
                        verbose_name="Última Compra",
                    ),
                ),
                (
                    "total_compras_acumulado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto total de todas las compras del cliente",
                        max_digits=15,
                        verbose_name="Total Compras Acumulado",
                    ),
                ),
                (
                    "cantidad_pedidos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de pedidos realizados",
                        verbose_name="Cantidad de Pedidos",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales sobre el cliente",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "canal_venta",
                    models.ForeignKey(
                        help_text="Canal por el que se obtuvo el cliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clientes",
                        to="gestion_clientes.canalventa",
                        verbose_name="Canal de Venta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "vendedor_asignado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendedor responsable del cliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clientes_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor Asignado",
                    ),
                ),
                (
                    "estado_cliente",
                    models.ForeignKey(
                        help_text="Estado actual del cliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clientes",
                        to="gestion_clientes.estadocliente",
                        verbose_name="Estado del Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "sales_crm_cliente",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="SegmentoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del segmento (ej: VIP, CORPORATIVO)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del segmento",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del segmento y sus criterios",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "criterios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Criterios dinámicos para asignación automática (JSON)",
                        verbose_name="Criterios de Segmentación",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        help_text="Color para representación visual",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmento de Cliente",
                "verbose_name_plural": "Segmentos de Cliente",
                "db_table": "sales_crm_segmento_cliente",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClienteSegmento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha en que se asignó el cliente al segmento",
                        verbose_name="Fecha de Asignación",
                    ),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        help_text="Usuario que realizó la asignación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_segmento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente asignado al segmento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentos",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "segmento",
                    models.ForeignKey(
                        help_text="Segmento al que pertenece el cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="gestion_clientes.segmentocliente",
                        verbose_name="Segmento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Cliente-Segmento",
                "verbose_name_plural": "Asignaciones Cliente-Segmento",
                "db_table": "sales_crm_cliente_segmento",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="TipoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo de cliente (ej: EMPRESA, PERSONA_NATURAL)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de cliente",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del tipo de cliente",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="¿Tipo de cliente activo?",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Cliente",
                "verbose_name_plural": "Tipos de Cliente",
                "db_table": "sales_crm_tipo_cliente",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="sales_crm_t_codigo_2d3d4e_idx"
                    ),
                    models.Index(
                        fields=["activo", "orden"], name="sales_crm_t_activo_3874ee_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.ForeignKey(
                help_text="Tipo al que pertenece este cliente",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="gestion_clientes.tipocliente",
                verbose_name="Tipo de Cliente",
            ),
        ),
        migrations.CreateModel(
            name="ContactoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre completo del contacto",
                        max_length=255,
                        verbose_name="Nombre Completo",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        help_text="Cargo o posición en la empresa",
                        max_length=100,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Correo electrónico",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="¿Es el contacto principal del cliente?",
                        verbose_name="Contacto Principal",
                    ),
                ),
                (
                    "fecha_cumpleanos",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de cumpleaños del contacto",
                        null=True,
                        verbose_name="Fecha de Cumpleaños",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el contacto",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente al que pertenece el contacto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de Cliente",
                "verbose_name_plural": "Contactos de Cliente",
                "db_table": "sales_crm_contacto_cliente",
                "ordering": ["-es_principal", "nombre_completo"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "is_active"],
                        name="sales_crm_c_empresa_43230e_idx",
                    ),
                    models.Index(
                        fields=["cliente", "es_principal"],
                        name="sales_crm_c_cliente_28cd06_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InteraccionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_interaccion",
                    models.CharField(
                        choices=[
                            ("LLAMADA", "Llamada Telefónica"),
                            ("EMAIL", "Email"),
                            ("VISITA", "Visita al Cliente"),
                            ("REUNION", "Reunión"),
                            ("WHATSAPP", "WhatsApp"),
                            ("VIDEOLLAMADA", "Videollamada"),
                            ("OTRO", "Otro"),
                        ],
                        db_index=True,
                        help_text="Tipo de interacción realizada",
                        max_length=50,
                        verbose_name="Tipo de Interacción",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de la interacción",
                        verbose_name="Fecha y Hora",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la interacción",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "resultado",
                    models.TextField(
                        blank=True,
                        help_text="Resultado u outcome de la interacción",
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "proxima_accion",
                    models.TextField(
                        blank=True,
                        help_text="Acción de seguimiento pendiente",
                        verbose_name="Próxima Acción",
                    ),
                ),
                (
                    "fecha_proxima_accion",
                    models.DateField(
                        blank=True,
                        help_text="Fecha programada para el seguimiento",
                        null=True,
                        verbose_name="Fecha Próxima Acción",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente con el que se tuvo la interacción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacciones",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        help_text="Usuario que registró la interacción",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interacciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción con Cliente",
                "verbose_name_plural": "Interacciones con Cliente",
                "db_table": "sales_crm_interaccion_cliente",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "is_active"],
                        name="sales_crm_i_empresa_d7ea73_idx",
                    ),
                    models.Index(
                        fields=["cliente", "fecha"],
                        name="sales_crm_i_cliente_2aabb8_idx",
                    ),
                    models.Index(
                        fields=["tipo_interaccion", "fecha"],
                        name="sales_crm_i_tipo_in_fda195_idx",
                    ),
                    models.Index(
                        fields=["fecha_proxima_accion"],
                        name="sales_crm_i_fecha_p_79c39e_idx",
                    ),
                    models.Index(
                        fields=["registrado_por"], name="sales_crm_i_registr_92d107_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoringCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación total del cliente (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Puntuación Total",
                    ),
                ),
                (
                    "frecuencia_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación por frecuencia de compra (0-25)",
                        max_digits=5,
                        verbose_name="Score Frecuencia de Compra",
                    ),
                ),
                (
                    "volumen_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación por volumen total comprado (0-25)",
                        max_digits=5,
                        verbose_name="Score Volumen de Compra",
                    ),
                ),
                (
                    "puntualidad_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación por puntualidad en pagos (0-30)",
                        max_digits=5,
                        verbose_name="Score Puntualidad de Pago",
                    ),
                ),
                (
                    "antiguedad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Puntuación por tiempo como cliente (0-20)",
                        max_digits=5,
                        verbose_name="Score Antigüedad",
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de la última actualización del scoring",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "historial_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Historial de puntuaciones anteriores [{fecha, puntuacion}]",
                        verbose_name="Historial de Scores",
                    ),
                ),
                (
                    "cliente",
                    models.OneToOneField(
                        help_text="Cliente al que pertenece el scoring",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring",
                        to="gestion_clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring de Cliente",
                "verbose_name_plural": "Scorings de Cliente",
                "db_table": "sales_crm_scoring_cliente",
                "ordering": ["-puntuacion_total"],
                "indexes": [
                    models.Index(
                        fields=["puntuacion_total"],
                        name="sales_crm_s_puntuac_b79619_idx",
                    ),
                    models.Index(
                        fields=["ultima_actualizacion"],
                        name="sales_crm_s_ultima__0c7925_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="segmentocliente",
            index=models.Index(
                fields=["empresa", "is_active"], name="sales_crm_s_empresa_dfd5ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segmentocliente",
            index=models.Index(fields=["codigo"], name="sales_crm_s_codigo_4accae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="segmentocliente",
            unique_together={("empresa", "codigo")},
        ),
        migrations.AddIndex(
            model_name="clientesegmento",
            index=models.Index(
                fields=["empresa", "is_active"], name="sales_crm_c_empresa_c95515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientesegmento",
            index=models.Index(
                fields=["cliente", "segmento"], name="sales_crm_c_cliente_014550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientesegmento",
            index=models.Index(
                fields=["fecha_asignacion"], name="sales_crm_c_fecha_a_8e5460_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientesegmento",
            unique_together={("cliente", "segmento")},
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["empresa", "is_active"], name="sales_crm_c_empresa_a46d7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["codigo_cliente"], name="sales_crm_c_codigo__83f1c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["numero_documento"], name="sales_crm_c_numero__aa6f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["tipo_cliente", "estado_cliente"],
                name="sales_crm_c_tipo_cl_530173_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["vendedor_asignado"], name="sales_crm_c_vendedo_590355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["ultima_compra"], name="sales_crm_c_ultima__a8c4f5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={
                ("empresa", "codigo_cliente"),
                ("empresa", "numero_documento"),
            },
        ),
    ]
