# Generated by Django 5.0.9 on 2026-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parte_interesada_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID de la Parte Interesada vinculada (gestion_estrategica.ParteInteresada)', null=True, verbose_name='ID Parte Interesada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parte_interesada_nombre',
            field=models.CharField(blank=True, help_text='Cache: nombre de la parte interesada vinculada', max_length=200, verbose_name='Nombre Parte Interesada'),
        ),
    ]
