# Generated by Django 5.0.9 on 2026-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0003_onboarding_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico del suscriptor",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Nombre"
                    ),
                ),
                (
                    "categorias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de categorías de recursos de interés",
                        verbose_name="Categorias de Interes",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="recursos",
                        help_text="Desde donde se suscribió (recursos, newsletter, contacto)",
                        max_length=50,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, no recibe emails",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscriptor Newsletter",
                "verbose_name_plural": "Suscriptores Newsletter",
                "db_table": "platform_newsletter_subscriber",
                "ordering": ["-created_at"],
            },
        ),
    ]
