# Generated by Django 5.0.9 on 2026-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenant_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de expiracion del token de reset', null=True, verbose_name='Expiracion del token'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Token temporal para restablecer contraseña', max_length=64, null=True, verbose_name='Token de reset'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='DEPRECATED: Usar campo "logo" en su lugar', verbose_name='URL del logo (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='tenantuseraccess',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si False, el usuario no puede acceder a este tenant', verbose_name='Acceso activo'),
        ),
        migrations.AlterField(
            model_name='tenantuseraccess',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario'), ('readonly', 'Solo lectura')], default='user', help_text='Campo deprecado. Usar cargo del User dentro del tenant.', max_length=20, verbose_name='Rol (DEPRECATED)'),
        ),
    ]
