# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccidenteTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "codigo_at",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del accidente (ej: AT-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código AT",
                    ),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(
                        help_text="Fecha y hora exacta del accidente",
                        verbose_name="Fecha y Hora del Evento",
                    ),
                ),
                (
                    "lugar_evento",
                    models.CharField(
                        help_text="Ubicación específica donde ocurrió el accidente",
                        max_length=255,
                        verbose_name="Lugar del Evento",
                    ),
                ),
                (
                    "descripcion_evento",
                    models.TextField(
                        help_text="Descripción detallada de cómo ocurrió el accidente",
                        verbose_name="Descripción del Evento",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("CAIDA_MISMO_NIVEL", "Caída a nivel"),
                            ("CAIDA_DISTINTO_NIVEL", "Caída a distinto nivel"),
                            ("GOLPE_OBJETO", "Golpe por objeto"),
                            ("ATRAPAMIENTO", "Atrapamiento"),
                            ("SOBREESFUERZO", "Sobreesfuerzo"),
                            ("EXPOSICION_SUSTANCIA", "Exposición a sustancia"),
                            ("CONTACTO_ELECTRICO", "Contacto eléctrico"),
                            (
                                "CONTACTO_TEMPERATURA",
                                "Contacto con temperatura extrema",
                            ),
                            ("ACCIDENTE_TRANSITO", "Accidente de tránsito en misión"),
                            ("VIOLENCIA", "Violencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "cargo_trabajador",
                    models.CharField(
                        help_text="Cargo del trabajador al momento del accidente",
                        max_length=100,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "tipo_lesion",
                    models.CharField(
                        choices=[
                            ("CONTUSION", "Contusión"),
                            ("CORTE", "Corte/Laceración"),
                            ("FRACTURA", "Fractura"),
                            ("QUEMADURA", "Quemadura"),
                            ("AMPUTACION", "Amputación"),
                            ("ESGUINCE", "Esguince"),
                            ("LUXACION", "Luxación"),
                            ("TRAUMA_CRANEO", "Trauma Craneoencefálico"),
                            ("HERIDA", "Herida"),
                            ("PICADURA", "Picadura/Mordedura"),
                            ("INTOXICACION", "Intoxicación"),
                            ("ASFIXIA", "Asfixia"),
                            ("QUEMADURA_QUIMICA", "Quemadura Química"),
                            ("ELECTROCUCION", "Electrocución"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Lesión",
                    ),
                ),
                (
                    "parte_cuerpo",
                    models.CharField(
                        choices=[
                            ("CABEZA", "Cabeza"),
                            ("OJO_DERECHO", "Ojo Derecho"),
                            ("OJO_IZQUIERDO", "Ojo Izquierdo"),
                            ("OIDO_DERECHO", "Oído Derecho"),
                            ("OIDO_IZQUIERDO", "Oído Izquierdo"),
                            ("CARA", "Cara"),
                            ("CUELLO", "Cuello"),
                            ("TORAX", "Tórax"),
                            ("ABDOMEN", "Abdomen"),
                            ("ESPALDA_SUPERIOR", "Espalda Superior"),
                            ("ESPALDA_INFERIOR", "Espalda Inferior/Lumbar"),
                            ("HOMBRO_DERECHO", "Hombro Derecho"),
                            ("HOMBRO_IZQUIERDO", "Hombro Izquierdo"),
                            ("BRAZO_DERECHO", "Brazo Derecho"),
                            ("BRAZO_IZQUIERDO", "Brazo Izquierdo"),
                            ("CODO_DERECHO", "Codo Derecho"),
                            ("CODO_IZQUIERDO", "Codo Izquierdo"),
                            ("ANTEBRAZO_DERECHO", "Antebrazo Derecho"),
                            ("ANTEBRAZO_IZQUIERDO", "Antebrazo Izquierdo"),
                            ("MUNECA_DERECHA", "Muñeca Derecha"),
                            ("MUNECA_IZQUIERDA", "Muñeca Izquierda"),
                            ("MANO_DERECHA", "Mano Derecha"),
                            ("MANO_IZQUIERDA", "Mano Izquierda"),
                            ("DEDOS_MANO_DERECHA", "Dedos Mano Derecha"),
                            ("DEDOS_MANO_IZQUIERDA", "Dedos Mano Izquierda"),
                            ("CADERA", "Cadera"),
                            ("PELVIS", "Pelvis"),
                            ("MUSLO_DERECHO", "Muslo Derecho"),
                            ("MUSLO_IZQUIERDO", "Muslo Izquierdo"),
                            ("RODILLA_DERECHA", "Rodilla Derecha"),
                            ("RODILLA_IZQUIERDA", "Rodilla Izquierda"),
                            ("PIERNA_DERECHA", "Pierna Derecha"),
                            ("PIERNA_IZQUIERDA", "Pierna Izquierda"),
                            ("TOBILLO_DERECHO", "Tobillo Derecho"),
                            ("TOBILLO_IZQUIERDO", "Tobillo Izquierdo"),
                            ("PIE_DERECHO", "Pie Derecho"),
                            ("PIE_IZQUIERDO", "Pie Izquierdo"),
                            ("DEDOS_PIE_DERECHO", "Dedos Pie Derecho"),
                            ("DEDOS_PIE_IZQUIERDO", "Dedos Pie Izquierdo"),
                            ("MULTIPLES", "Múltiples Partes"),
                            ("SISTEMICO", "Sistémico/Interno"),
                        ],
                        max_length=50,
                        verbose_name="Parte del Cuerpo Afectada",
                    ),
                ),
                (
                    "descripcion_lesion",
                    models.TextField(
                        help_text="Descripción médica de la lesión",
                        verbose_name="Descripción de la Lesión",
                    ),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve - Sin incapacidad o < 10 días"),
                            ("MODERADO", "Moderado - 10 a 30 días"),
                            ("GRAVE", "Grave - > 30 días o secuela"),
                            ("MORTAL", "Mortal"),
                        ],
                        max_length=20,
                        verbose_name="Gravedad",
                    ),
                ),
                (
                    "dias_incapacidad",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Días de incapacidad laboral",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Días de Incapacidad",
                    ),
                ),
                (
                    "mortal",
                    models.BooleanField(
                        default=False,
                        help_text="¿El accidente resultó en muerte?",
                        verbose_name="Mortal",
                    ),
                ),
                (
                    "fecha_muerte",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de muerte (si aplica)",
                        null=True,
                        verbose_name="Fecha de Muerte",
                    ),
                ),
                (
                    "centro_atencion",
                    models.CharField(
                        help_text="IPS o centro médico donde fue atendido",
                        max_length=255,
                        verbose_name="Centro de Atención Médica",
                    ),
                ),
                (
                    "diagnostico_medico",
                    models.TextField(
                        help_text="Diagnóstico oficial del médico tratante",
                        verbose_name="Diagnóstico Médico",
                    ),
                ),
                (
                    "reportado_arl",
                    models.BooleanField(
                        default=False,
                        help_text="¿Fue reportado a la ARL?",
                        verbose_name="Reportado a ARL",
                    ),
                ),
                (
                    "fecha_reporte_arl",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Reporte ARL"
                    ),
                ),
                (
                    "numero_caso_arl",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Caso ARL"
                    ),
                ),
                (
                    "calificacion_origen",
                    models.CharField(
                        blank=True,
                        help_text="Calificación por Junta de Calificación",
                        max_length=50,
                        verbose_name="Calificación de Origen",
                    ),
                ),
                (
                    "testigos",
                    models.TextField(
                        blank=True,
                        help_text="Nombres de testigos presenciales",
                        verbose_name="Testigos",
                    ),
                ),
                (
                    "requiere_investigacion",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Investigación"
                    ),
                ),
                (
                    "fecha_reporte_interno",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Reporte Interno"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Accidente de Trabajo",
                "verbose_name_plural": "Accidentes de Trabajo",
                "db_table": "hseq_accidentes_trabajo",
                "ordering": ["-fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="AccionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Orden de ejecución dentro del plan",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("ELIMINACION", "Eliminación del Peligro"),
                            ("SUSTITUCION", "Sustitución"),
                            ("CONTROL_INGENIERIA", "Control de Ingeniería"),
                            ("CONTROL_ADMINISTRATIVO", "Control Administrativo"),
                            ("EPP", "Equipos de Protección Personal"),
                            ("CAPACITACION", "Capacitación/Formación"),
                            ("PROCEDIMIENTO", "Revisión de Procedimiento"),
                            ("SENALIZACION", "Señalización"),
                            ("INSPECCION", "Inspección/Mantenimiento"),
                            ("OTRA", "Otra"),
                        ],
                        help_text="Jerarquía de controles según ISO 45001",
                        max_length=50,
                        verbose_name="Tipo de Acción",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Qué se va a hacer",
                        verbose_name="Descripción de la Acción",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_compromiso",
                    models.DateField(
                        help_text="Fecha comprometida para completar esta acción",
                        verbose_name="Fecha Compromiso",
                    ),
                ),
                (
                    "fecha_completada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Completada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("VERIFICADA", "Verificada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recursos",
                    models.TextField(
                        blank=True,
                        help_text="Recursos específicos para esta acción",
                        verbose_name="Recursos",
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo Estimado",
                    ),
                ),
                (
                    "evidencia_implementacion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de evidencias (fotos, documentos, etc.)",
                        verbose_name="Evidencia de Implementación",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "fecha_verificacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                (
                    "observaciones_verificacion",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de Verificación"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción del Plan",
                "verbose_name_plural": "Acciones del Plan",
                "db_table": "hseq_acciones_plan",
                "ordering": ["plan_accion", "orden"],
            },
        ),
        migrations.CreateModel(
            name="CausaRaiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "tipo_causa",
                    models.CharField(
                        choices=[
                            ("INMEDIATA_ACTO", "Causa Inmediata - Acto Inseguro"),
                            (
                                "INMEDIATA_CONDICION",
                                "Causa Inmediata - Condición Insegura",
                            ),
                            ("BASICA_PERSONAL", "Causa Básica - Factores Personales"),
                            ("BASICA_TRABAJO", "Causa Básica - Factores del Trabajo"),
                            ("ORGANIZACIONAL", "Causa Organizacional"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Causa",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la causa identificada",
                        verbose_name="Descripción de la Causa",
                    ),
                ),
                (
                    "evidencia",
                    models.TextField(
                        blank=True,
                        help_text="Evidencia que soporta esta causa",
                        verbose_name="Evidencia",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        default=1,
                        help_text="1 = Más importante, 5 = Menos importante",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Causa Raíz",
                "verbose_name_plural": "Causas Raíz",
                "db_table": "hseq_causas_raiz",
                "ordering": ["investigacion", "prioridad"],
            },
        ),
        migrations.CreateModel(
            name="EnfermedadLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo_el",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código EL",
                    ),
                ),
                (
                    "cargo_trabajador",
                    models.CharField(max_length=100, verbose_name="Cargo"),
                ),
                (
                    "fecha_diagnostico",
                    models.DateField(verbose_name="Fecha de Diagnóstico"),
                ),
                (
                    "tipo_enfermedad",
                    models.CharField(
                        choices=[
                            ("RESPIRATORIA", "Enfermedad Respiratoria"),
                            ("PIEL", "Enfermedad de la Piel"),
                            ("AUDITIVA", "Enfermedad Auditiva"),
                            ("VISUAL", "Enfermedad Visual"),
                            ("MUSCULOESQUELETICA", "Enfermedad Musculoesquelética"),
                            ("NEUROLOGICA", "Enfermedad Neurológica"),
                            ("MENTAL", "Enfermedad Mental"),
                            ("CARDIOVASCULAR", "Enfermedad Cardiovascular"),
                            ("INTOXICACION_CRONICA", "Intoxicación Crónica"),
                            ("CANCER_OCUPACIONAL", "Cáncer Ocupacional"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Enfermedad",
                    ),
                ),
                (
                    "diagnostico_cie10",
                    models.CharField(
                        help_text="Código de diagnóstico CIE-10",
                        max_length=20,
                        verbose_name="Código CIE-10",
                    ),
                ),
                (
                    "diagnostico_descripcion",
                    models.TextField(verbose_name="Descripción del Diagnóstico"),
                ),
                (
                    "factor_riesgo",
                    models.TextField(
                        help_text="Factor de riesgo al cual estuvo expuesto",
                        verbose_name="Factor de Riesgo",
                    ),
                ),
                (
                    "tiempo_exposicion",
                    models.CharField(
                        help_text="Tiempo estimado de exposición al riesgo",
                        max_length=100,
                        verbose_name="Tiempo de Exposición",
                    ),
                ),
                (
                    "descripcion_exposicion",
                    models.TextField(
                        help_text="Detalle de las condiciones de exposición",
                        verbose_name="Descripción de la Exposición",
                    ),
                ),
                (
                    "estado_calificacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Calificación"),
                            ("PROVISIONAL", "Calificación Provisional"),
                            ("DEFINITIVA_LABORAL", "Definitiva - Origen Laboral"),
                            ("DEFINITIVA_COMUN", "Definitiva - Origen Común"),
                            ("EN_CONTROVERSIA", "En Controversia"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                        verbose_name="Estado de Calificación",
                    ),
                ),
                (
                    "fecha_calificacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Calificación"
                    ),
                ),
                (
                    "porcentaje_pcl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de pérdida de capacidad laboral",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje PCL (Pérdida Capacidad Laboral)",
                    ),
                ),
                (
                    "entidad_calificadora",
                    models.CharField(
                        blank=True,
                        help_text="ARL, EPS o Junta de Calificación",
                        max_length=255,
                        verbose_name="Entidad Calificadora",
                    ),
                ),
                (
                    "numero_dictamen",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Dictamen"
                    ),
                ),
                (
                    "reportado_arl",
                    models.BooleanField(default=False, verbose_name="Reportado a ARL"),
                ),
                (
                    "fecha_reporte_arl",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Reporte ARL"
                    ),
                ),
                (
                    "numero_caso_arl",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Caso ARL"
                    ),
                ),
                (
                    "requiere_investigacion",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Investigación"
                    ),
                ),
                (
                    "fecha_reporte_interno",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Reporte Interno"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfermedad Laboral",
                "verbose_name_plural": "Enfermedades Laborales",
                "db_table": "hseq_enfermedades_laborales",
                "ordering": ["-fecha_diagnostico"],
            },
        ),
        migrations.CreateModel(
            name="IncidenteTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo_incidente",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código Incidente",
                    ),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(verbose_name="Fecha y Hora del Evento"),
                ),
                (
                    "lugar_evento",
                    models.CharField(max_length=255, verbose_name="Lugar del Evento"),
                ),
                (
                    "tipo_incidente",
                    models.CharField(
                        choices=[
                            ("CASI_ACCIDENTE", "Casi Accidente"),
                            ("CONDICION_INSEGURA", "Condición Insegura"),
                            ("ACTO_INSEGURO", "Acto Inseguro"),
                            ("DANO_PROPIEDAD", "Daño a Propiedad"),
                            ("DERRAME", "Derrame de Sustancia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Incidente",
                    ),
                ),
                (
                    "descripcion_evento",
                    models.TextField(verbose_name="Descripción del Evento"),
                ),
                (
                    "potencial_gravedad",
                    models.CharField(
                        choices=[
                            ("BAJO", "Potencial Bajo"),
                            ("MEDIO", "Potencial Medio"),
                            ("ALTO", "Potencial Alto"),
                            ("CRITICO", "Potencial Crítico"),
                        ],
                        help_text="Gravedad potencial si hubiera ocurrido lesión",
                        max_length=20,
                        verbose_name="Potencial de Gravedad",
                    ),
                ),
                (
                    "consecuencias_potenciales",
                    models.TextField(
                        help_text="Qué pudo haber pasado",
                        verbose_name="Consecuencias Potenciales",
                    ),
                ),
                (
                    "personas_involucradas",
                    models.TextField(
                        blank=True,
                        help_text="Trabajadores que presenciaron o estuvieron cerca",
                        verbose_name="Personas Involucradas",
                    ),
                ),
                (
                    "hubo_danos_materiales",
                    models.BooleanField(
                        default=False, verbose_name="¿Hubo Daños Materiales?"
                    ),
                ),
                (
                    "descripcion_danos",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de daños a equipos, instalaciones, etc.",
                        verbose_name="Descripción de Daños",
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo estimado de daños materiales",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo Estimado",
                    ),
                ),
                (
                    "requiere_investigacion",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Investigación"
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Reporte"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente de Trabajo",
                "verbose_name_plural": "Incidentes de Trabajo",
                "db_table": "hseq_incidentes_trabajo",
                "ordering": ["-fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="InvestigacionATEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo_investigacion",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código de Investigación",
                    ),
                ),
                (
                    "metodologia",
                    models.CharField(
                        choices=[
                            ("ARBOL_CAUSAS", "Árbol de Causas"),
                            ("CINCO_PORQUES", "5 Porqués"),
                            ("ISHIKAWA", "Diagrama de Ishikawa (Espina de Pescado)"),
                            ("TAPROOT", "TapRoot"),
                            ("OTRA", "Otra Metodología"),
                        ],
                        max_length=50,
                        verbose_name="Metodología de Investigación",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True,
                        help_text="Fecha límite para completar la investigación",
                        null=True,
                        verbose_name="Fecha Límite",
                    ),
                ),
                (
                    "fecha_completada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Completada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INICIADA", "Iniciada"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("CERRADA", "Cerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="INICIADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "descripcion_hechos",
                    models.TextField(
                        help_text="Reconstrucción detallada de lo ocurrido",
                        verbose_name="Descripción de los Hechos",
                    ),
                ),
                (
                    "analisis_datos",
                    models.JSONField(
                        blank=True,
                        help_text="JSON con estructura del análisis (árbol, 5 porqués, etc.)",
                        null=True,
                        verbose_name="Datos de Análisis",
                    ),
                ),
                (
                    "conclusiones",
                    models.TextField(
                        blank=True,
                        help_text="Conclusiones de la investigación",
                        verbose_name="Conclusiones",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones generales",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "aprobada",
                    models.BooleanField(default=False, verbose_name="Aprobada"),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Investigación ATEL",
                "verbose_name_plural": "Investigaciones ATEL",
                "db_table": "hseq_investigaciones_atel",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="LeccionAprendida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo_leccion",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código de Lección",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TECNICA", "Técnica/Operativa"),
                            ("COMPORTAMENTAL", "Comportamental"),
                            ("ORGANIZACIONAL", "Organizacional"),
                            ("COMUNICACION", "Comunicación"),
                            ("CAPACITACION", "Capacitación"),
                            ("EQUIPOS", "Equipos y Herramientas"),
                            ("PROCEDIMIENTOS", "Procedimientos"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título descriptivo de la lección",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "situacion",
                    models.TextField(help_text="¿Qué pasó?", verbose_name="Situación"),
                ),
                (
                    "causa",
                    models.TextField(help_text="¿Por qué pasó?", verbose_name="Causa"),
                ),
                (
                    "leccion",
                    models.TextField(
                        help_text="¿Qué aprendimos?", verbose_name="Lección"
                    ),
                ),
                (
                    "recomendacion",
                    models.TextField(
                        help_text="¿Qué debemos hacer diferente?",
                        verbose_name="Recomendación",
                    ),
                ),
                (
                    "areas_aplicables",
                    models.TextField(
                        help_text="Áreas o departamentos donde aplica esta lección",
                        verbose_name="Áreas Aplicables",
                    ),
                ),
                (
                    "puestos_trabajo_aplicables",
                    models.TextField(
                        blank=True, verbose_name="Puestos de Trabajo Aplicables"
                    ),
                ),
                (
                    "estado_divulgacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Divulgación"),
                            ("PROGRAMADA", "Divulgación Programada"),
                            ("DIVULGADA", "Divulgada"),
                            ("ARCHIVADA", "Archivada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de Divulgación",
                    ),
                ),
                (
                    "fecha_divulgacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Divulgación"
                    ),
                ),
                (
                    "metodo_divulgacion",
                    models.CharField(
                        blank=True,
                        help_text="Charla, correo, cartelera, capacitación, etc.",
                        max_length=255,
                        verbose_name="Método de Divulgación",
                    ),
                ),
                (
                    "personas_divulgadas",
                    models.TextField(
                        blank=True,
                        help_text="Listado o descripción de personas que recibieron la divulgación",
                        verbose_name="Personas Divulgadas",
                    ),
                ),
                (
                    "evidencia_divulgacion",
                    models.TextField(
                        blank=True,
                        help_text="Referencias a documentos, fotos, listas de asistencia, etc.",
                        verbose_name="Evidencia de Divulgación",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección Aprendida",
                "verbose_name_plural": "Lecciones Aprendidas",
                "db_table": "hseq_lecciones_aprendidas",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PlanAccionATEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo_plan",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código del Plan",
                    ),
                ),
                (
                    "nombre_plan",
                    models.CharField(
                        help_text="Título descriptivo del plan de acción",
                        max_length=255,
                        verbose_name="Nombre del Plan",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        help_text="Objetivo del plan de acción", verbose_name="Objetivo"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_compromiso",
                    models.DateField(
                        help_text="Fecha comprometida para completar todas las acciones",
                        verbose_name="Fecha Compromiso",
                    ),
                ),
                (
                    "fecha_completado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecución"),
                            ("COMPLETADO", "Completado"),
                            ("VERIFICADO", "Verificado"),
                            ("CERRADO", "Cerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANIFICADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(
                        blank=True,
                        help_text="Recursos humanos, materiales, financieros necesarios",
                        verbose_name="Recursos Necesarios",
                    ),
                ),
                (
                    "presupuesto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presupuesto Estimado",
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.IntegerField(
                        default=0,
                        help_text="Porcentaje de avance del plan",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de Avance",
                    ),
                ),
                (
                    "observaciones_seguimiento",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de Seguimiento"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "fecha_verificacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                (
                    "efectividad",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de la efectividad de las acciones",
                        max_length=50,
                        verbose_name="Evaluación de Efectividad",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Acción ATEL",
                "verbose_name_plural": "Planes de Acción ATEL",
                "db_table": "hseq_planes_accion_atel",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
