# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accidentalidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentetrabajo",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accidentes_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="accidentetrabajo",
            name="reportado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accidentes_reportados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reportado Por",
            ),
        ),
        migrations.AddField(
            model_name="accidentetrabajo",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accidentes_trabajo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Trabajador Afectado",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_actualizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acciones_plan_atel_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="verificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_verificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verificado Por",
            ),
        ),
        migrations.AddField(
            model_name="causaraiz",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="causa_raiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones",
                to="accidentalidad.causaraiz",
                verbose_name="Causa Raíz que Atiende",
            ),
        ),
        migrations.AddField(
            model_name="enfermedadlaboral",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enfermedades_actualizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="enfermedadlaboral",
            name="reportado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enfermedades_reportadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reportado Por",
            ),
        ),
        migrations.AddField(
            model_name="enfermedadlaboral",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enfermedades_laborales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Trabajador Afectado",
            ),
        ),
        migrations.AddField(
            model_name="incidentetrabajo",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidentes_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="incidentetrabajo",
            name="reportado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidentes_trabajo_reportados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reportado Por",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="accidente_trabajo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigacion",
                to="accidentalidad.accidentetrabajo",
                verbose_name="Accidente de Trabajo",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigaciones_actualizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="aprobada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigaciones_aprobadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobada Por",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigaciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="enfermedad_laboral",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigacion",
                to="accidentalidad.enfermedadlaboral",
                verbose_name="Enfermedad Laboral",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="equipo_investigacion",
            field=models.ManyToManyField(
                help_text="Miembros del equipo investigador",
                related_name="investigaciones_participadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Equipo de Investigación",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="incidente_trabajo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigacion",
                to="accidentalidad.incidentetrabajo",
                verbose_name="Incidente de Trabajo",
            ),
        ),
        migrations.AddField(
            model_name="investigacionatel",
            name="lider_investigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investigaciones_lideradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Líder de Investigación",
            ),
        ),
        migrations.AddField(
            model_name="causaraiz",
            name="investigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="causas_raiz",
                to="accidentalidad.investigacionatel",
                verbose_name="Investigación",
            ),
        ),
        migrations.AddField(
            model_name="leccionaprendida",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecciones_actualizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="leccionaprendida",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="leccionaprendida",
            name="divulgado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecciones_divulgadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Divulgado Por",
            ),
        ),
        migrations.AddField(
            model_name="leccionaprendida",
            name="investigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecciones_aprendidas",
                to="accidentalidad.investigacionatel",
                verbose_name="Investigación",
            ),
        ),
        migrations.AddField(
            model_name="planaccionatel",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planes_accion_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AddField(
            model_name="planaccionatel",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planes_accion_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="planaccionatel",
            name="investigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_accion",
                to="accidentalidad.investigacionatel",
                verbose_name="Investigación",
            ),
        ),
        migrations.AddField(
            model_name="planaccionatel",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planes_accion_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable del Plan",
            ),
        ),
        migrations.AddField(
            model_name="planaccionatel",
            name="verificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planes_accion_verificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verificado Por",
            ),
        ),
        migrations.AddField(
            model_name="accionplan",
            name="plan_accion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones",
                to="accidentalidad.planaccionatel",
                verbose_name="Plan de Acción",
            ),
        ),
        migrations.AddIndex(
            model_name="accidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "fecha_evento"],
                name="hseq_accide_empresa_763375_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "gravedad"], name="hseq_accide_empresa_ac0b51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "mortal"], name="hseq_accide_empresa_d0a949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accidentetrabajo",
            index=models.Index(
                fields=["trabajador", "fecha_evento"],
                name="hseq_accide_trabaja_f9fb88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accidentetrabajo",
            index=models.Index(
                fields=["codigo_at"], name="hseq_accide_codigo__5216a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enfermedadlaboral",
            index=models.Index(
                fields=["empresa_id", "fecha_diagnostico"],
                name="hseq_enferm_empresa_8c8c3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enfermedadlaboral",
            index=models.Index(
                fields=["empresa_id", "estado_calificacion"],
                name="hseq_enferm_empresa_1a4003_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enfermedadlaboral",
            index=models.Index(
                fields=["trabajador", "fecha_diagnostico"],
                name="hseq_enferm_trabaja_18361f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "fecha_evento"],
                name="hseq_incide_empresa_c8c957_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "tipo_incidente"],
                name="hseq_incide_empresa_174737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentetrabajo",
            index=models.Index(
                fields=["empresa_id", "potencial_gravedad"],
                name="hseq_incide_empresa_7c6347_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investigacionatel",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_invest_empresa_69f142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigacionatel",
            index=models.Index(
                fields=["empresa_id", "fecha_inicio"],
                name="hseq_invest_empresa_5bdef1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investigacionatel",
            index=models.Index(
                fields=["lider_investigacion", "estado"],
                name="hseq_invest_lider_i_3db024_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="causaraiz",
            index=models.Index(
                fields=["empresa_id", "investigacion"],
                name="hseq_causas_empresa_5d2a75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="causaraiz",
            index=models.Index(
                fields=["investigacion", "tipo_causa"],
                name="hseq_causas_investi_eebc78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leccionaprendida",
            index=models.Index(
                fields=["empresa_id", "estado_divulgacion"],
                name="hseq_leccio_empresa_382881_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leccionaprendida",
            index=models.Index(
                fields=["empresa_id", "categoria"],
                name="hseq_leccio_empresa_fa0ad8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leccionaprendida",
            index=models.Index(
                fields=["investigacion"], name="hseq_leccio_investi_f36573_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionatel",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_planes_empresa_3fe928_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionatel",
            index=models.Index(
                fields=["empresa_id", "fecha_compromiso"],
                name="hseq_planes_empresa_e14d40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionatel",
            index=models.Index(
                fields=["investigacion"], name="hseq_planes_investi_7f1e35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionatel",
            index=models.Index(
                fields=["responsable", "estado"], name="hseq_planes_respons_eb351c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accionplan",
            index=models.Index(
                fields=["empresa_id", "plan_accion"],
                name="hseq_accion_empresa_80abda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accionplan",
            index=models.Index(
                fields=["empresa_id", "estado"], name="hseq_accion_empresa_c08175_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accionplan",
            index=models.Index(
                fields=["responsable", "estado"], name="hseq_accion_respons_462fec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accionplan",
            index=models.Index(
                fields=["plan_accion", "orden"], name="hseq_accion_plan_ac_f3427b_idx"
            ),
        ),
    ]
