# Generated by Django 5.0.9 on 2026-01-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_dynamic_models_dia6'),
        ('gestion_flota', '0001_initial'),
        ('gestion_transporte', '0001_initial'),
        ('producto_terminado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledespacho',
            name='stock_producto',
            field=models.ForeignKey(blank=True, help_text='Producto de stock asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_despacho', to='producto_terminado.stockproducto', verbose_name='Stock producto'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='estado_despacho',
            field=models.ForeignKey(help_text='Estado actual del despacho', on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='gestion_transporte.estadodespacho', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='generado_por',
            field=models.ForeignKey(help_text='Usuario que generó el manifiesto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifiestos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='conductor',
            field=models.ForeignKey(help_text='Conductor asignado', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion_transporte.conductor', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='programado_por',
            field=models.ForeignKey(help_text='Usuario que programó el viaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_rutas', to=settings.AUTH_USER_MODEL, verbose_name='Programado por'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo asignado a la ruta', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_ruta', to='gestion_flota.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='programacion_ruta',
            field=models.ForeignKey(help_text='Programación de ruta asociada', on_delete=django.db.models.deletion.PROTECT, related_name='manifiestos', to='gestion_transporte.programacionruta', verbose_name='Programación ruta'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='programacion_ruta',
            field=models.ForeignKey(help_text='Programación de ruta asociada', on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='gestion_transporte.programacionruta', verbose_name='Programación ruta'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='programacionruta',
            name='ruta',
            field=models.ForeignKey(help_text='Ruta a ejecutar', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion_transporte.ruta', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_ruta',
            field=models.ForeignKey(help_text='Tipo de ruta (recolección, entrega, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='gestion_transporte.tiporuta', verbose_name='Tipo de ruta'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['empresa', 'is_active'], name='transporte__empresa_97ac4c_idx'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['documento_identidad'], name='transporte__documen_85d605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conductor',
            unique_together={('empresa', 'documento_identidad')},
        ),
        migrations.AddIndex(
            model_name='manifiesto',
            index=models.Index(fields=['empresa', 'fecha_expedicion'], name='transporte__empresa_50bf4a_idx'),
        ),
        migrations.AddIndex(
            model_name='manifiesto',
            index=models.Index(fields=['numero_manifiesto'], name='transporte__numero__06f3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['empresa', 'estado_despacho'], name='transporte__empresa_90ec91_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['codigo'], name='transporte__codigo_d0972d_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['fecha_entrega_estimada'], name='transporte__fecha_e_0820ed_idx'),
        ),
        migrations.AddIndex(
            model_name='programacionruta',
            index=models.Index(fields=['empresa', 'estado', 'fecha_programada'], name='transporte__empresa_010d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='programacionruta',
            index=models.Index(fields=['codigo'], name='transporte__codigo_b7dded_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('empresa', 'codigo')},
        ),
    ]
