# Generated by Django 5.0.14 on 2026-03-16 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único del proceso (ej: GER, OPE, ADM)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del proceso",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de las funciones del proceso",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ESTRATEGICO", "Estratégico"),
                            ("MISIONAL", "Misional"),
                            ("APOYO", "Apoyo"),
                            ("EVALUACION", "Evaluación"),
                        ],
                        db_index=True,
                        default="APOYO",
                        help_text="Clasificación según ISO 9001:2015 (estratégico, misional, apoyo, evaluación)",
                        max_length=15,
                        verbose_name="Tipo de proceso",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Objetivo que persigue este proceso dentro del SGI",
                        verbose_name="Objetivo del proceso",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True,
                        help_text="Código del centro de costo asociado",
                        max_length=50,
                        null=True,
                        verbose_name="Centro de Costo",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Building2",
                        help_text="Nombre del icono Lucide (ej: Building2, Users, Briefcase)",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="purple",
                        help_text="Color del proceso (ej: purple, blue, green, red, amber, gray)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cargo responsable del proceso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas_responsable",
                        to="core.cargo",
                        verbose_name="Cargo Responsable",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proceso superior en la jerarquía",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="organizacion.area",
                        verbose_name="Proceso Padre",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "db_table": "organizacion_area",
                "ordering": ["orden", "name"],
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Versión de la ficha de caracterización",
                        verbose_name="Versión",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("VIGENTE", "Vigente"),
                            ("EN_REVISION", "En Revisión"),
                            ("OBSOLETO", "Obsoleto"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        blank=True,
                        help_text="Propósito y razón de ser del proceso",
                        verbose_name="Objetivo del Proceso",
                    ),
                ),
                (
                    "alcance",
                    models.TextField(
                        blank=True,
                        help_text="Límites del proceso: dónde inicia y dónde termina",
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "proveedores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"nombre": "...", "tipo": "interno|externo"}]',
                        verbose_name="Proveedores (S)",
                    ),
                ),
                (
                    "entradas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"descripcion": "...", "origen": "..."}]',
                        verbose_name="Entradas (I)",
                    ),
                ),
                (
                    "actividades_clave",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"descripcion": "...", "responsable": "..."}]',
                        verbose_name="Actividades Clave (P)",
                    ),
                ),
                (
                    "salidas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"descripcion": "...", "destino": "..."}]',
                        verbose_name="Salidas (O)",
                    ),
                ),
                (
                    "clientes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"nombre": "...", "tipo": "interno|externo"}]',
                        verbose_name="Clientes (C)",
                    ),
                ),
                (
                    "recursos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"tipo": "humano|tecnologico|fisico|financiero", "descripcion": "..."}]',
                        verbose_name="Recursos",
                    ),
                ),
                (
                    "indicadores_vinculados",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"nombre": "...", "formula": "...", "meta": "..."}]',
                        verbose_name="Indicadores Vinculados",
                    ),
                ),
                (
                    "riesgos_asociados",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"descripcion": "...", "nivel": "alto|medio|bajo", "tratamiento": "..."}]',
                        verbose_name="Riesgos Asociados",
                    ),
                ),
                (
                    "documentos_referencia",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"codigo": "...", "nombre": "..."}]',
                        verbose_name="Documentos de Referencia",
                    ),
                ),
                (
                    "requisitos_normativos",
                    models.TextField(
                        blank=True,
                        help_text="Requisitos ISO, legales u otros aplicables al proceso",
                        verbose_name="Requisitos Normativos",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "area",
                    models.OneToOneField(
                        help_text="Proceso o área que se caracteriza",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracterizacion",
                        to="organizacion.area",
                        verbose_name="Proceso / Área",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "lider_proceso",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cargo responsable del proceso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos_liderados",
                        to="core.cargo",
                        verbose_name="Líder del Proceso",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caracterización de Proceso",
                "verbose_name_plural": "Caracterizaciones de Procesos",
                "db_table": "organizacion_caracterizacion_proceso",
                "ordering": ["area__name"],
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionIndicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("formula", models.CharField(blank=True, max_length=500)),
                ("meta", models.CharField(blank=True, max_length=255)),
                (
                    "indicador_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Indicador (Analytics)",
                    ),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador Vinculado",
                "db_table": "organizacion_caract_indicador",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descripcion", models.CharField(max_length=500)),
                ("origen", models.CharField(blank=True, max_length=255)),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada SIPOC",
                "db_table": "organizacion_caract_entrada",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "documento_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Documento (Gestión Documental)",
                    ),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Referencia",
                "db_table": "organizacion_caract_documento",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("interno", "Interno"), ("externo", "Externo")],
                        default="externo",
                        max_length=10,
                    ),
                ),
                (
                    "parte_interesada_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Parte Interesada",
                    ),
                ),
                (
                    "parte_interesada_nombre",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente SIPOC",
                "db_table": "organizacion_caract_cliente",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descripcion", models.CharField(max_length=500)),
                ("responsable", models.CharField(blank=True, max_length=255)),
                (
                    "responsable_cargo_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Cargo Responsable",
                    ),
                ),
                (
                    "responsable_cargo_nombre",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad SIPOC",
                "db_table": "organizacion_caract_actividad",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("interno", "Interno"), ("externo", "Externo")],
                        default="externo",
                        max_length=10,
                    ),
                ),
                (
                    "parte_interesada_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Parte Interesada",
                    ),
                ),
                (
                    "parte_interesada_nombre",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor SIPOC",
                "db_table": "organizacion_caract_proveedor",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("humano", "Humano"),
                            ("tecnologico", "Tecnológico"),
                            ("fisico", "Físico"),
                            ("financiero", "Financiero"),
                        ],
                        default="humano",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "db_table": "organizacion_caract_recurso",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("alto", "Alto"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        default="medio",
                        max_length=10,
                    ),
                ),
                ("tratamiento", models.CharField(blank=True, max_length=500)),
                (
                    "riesgo_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Riesgo (Motor Riesgos)",
                    ),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riesgo Asociado",
                "db_table": "organizacion_caract_riesgo",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionSalida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descripcion", models.CharField(max_length=500)),
                ("destino", models.CharField(blank=True, max_length=255)),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizacion.caracterizacionproceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salida SIPOC",
                "db_table": "organizacion_caract_salida",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsecutivoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del consecutivo (ej: FACTURA, OC, REQ)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del consecutivo",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del uso de este consecutivo",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("DOCUMENTOS", "Documentos"),
                            ("COMPRAS", "Compras"),
                            ("VENTAS", "Ventas"),
                            ("INVENTARIO", "Inventario"),
                            ("CONTABILIDAD", "Contabilidad"),
                            ("PRODUCCION", "Producción"),
                            ("CALIDAD", "Calidad"),
                            ("RRHH", "Recursos Humanos"),
                            ("SST", "Seguridad y Salud"),
                            ("AMBIENTAL", "Gestión Ambiental"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Categoría para agrupar consecutivos",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Prefijo del consecutivo (ej: FAC, OC, REQ)",
                        max_length=20,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sufijo opcional al final (ej: CO, -A)",
                        max_length=20,
                        verbose_name="Sufijo",
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        choices=[
                            ("-", "Guión (-)"),
                            ("/", "Diagonal (/)"),
                            ("_", "Guión bajo (_)"),
                            (".", "Punto (.)"),
                            ("", "Sin separador"),
                        ],
                        default="-",
                        help_text="Caracter separador entre componentes",
                        max_length=1,
                        verbose_name="Separador",
                    ),
                ),
                (
                    "current_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Último número generado",
                        verbose_name="Número Actual",
                    ),
                ),
                (
                    "padding",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Cantidad de dígitos con ceros a la izquierda (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Dígitos de Relleno",
                    ),
                ),
                (
                    "numero_inicial",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número desde el cual inicia la secuencia",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número Inicial",
                    ),
                ),
                (
                    "include_year",
                    models.BooleanField(
                        default=True,
                        help_text="Incluir el año en formato YYYY",
                        verbose_name="Incluir Año",
                    ),
                ),
                (
                    "include_month",
                    models.BooleanField(
                        default=False,
                        help_text="Incluir el mes en formato MM (requiere año o produce YYYYMM)",
                        verbose_name="Incluir Mes",
                    ),
                ),
                (
                    "include_day",
                    models.BooleanField(
                        default=False,
                        help_text="Incluir el día en formato DD (requiere mes o produce YYYYMMDD)",
                        verbose_name="Incluir Día",
                    ),
                ),
                (
                    "reset_yearly",
                    models.BooleanField(
                        default=True,
                        help_text="Reiniciar la numeración cada año",
                        verbose_name="Reinicio Anual",
                    ),
                ),
                (
                    "reset_monthly",
                    models.BooleanField(
                        default=False,
                        help_text="Reiniciar la numeración cada mes",
                        verbose_name="Reinicio Mensual",
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha del último reinicio de la secuencia",
                        null=True,
                        verbose_name="Última Fecha de Reinicio",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es un consecutivo del sistema (no editable)",
                        verbose_name="Es del Sistema",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Consecutivo",
                "verbose_name_plural": "Configuraciones de Consecutivos",
                "db_table": "configuracion_consecutivo",
                "ordering": ["categoria", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="OrganigramaNodePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[("cargo", "Cargo"), ("area", "Área")], max_length=10
                    ),
                ),
                ("node_id", models.IntegerField()),
                ("view_mode", models.CharField(max_length=10)),
                ("direction", models.CharField(default="TB", max_length=2)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Posición de Nodo",
                "verbose_name_plural": "Posiciones de Nodos",
                "db_table": "organizacion_node_position",
                "unique_together": {("node_type", "node_id", "view_mode", "direction")},
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la unidad (ej: KG, TON, M3, UND)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo de la unidad (ej: Kilogramo, Tonelada)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "nombre_plural",
                    models.CharField(
                        blank=True,
                        help_text='Nombre en plural (ej: Kilogramos, Toneladas). Si vacío, se agrega "s"',
                        max_length=100,
                        verbose_name="Nombre Plural",
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(
                        help_text="Símbolo o abreviatura (ej: kg, ton, m³, hrs)",
                        max_length=10,
                        verbose_name="Símbolo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MASA", "Masa / Peso"),
                            ("VOLUMEN", "Volumen"),
                            ("LONGITUD", "Longitud"),
                            ("AREA", "Área"),
                            ("CANTIDAD", "Cantidad / Unidades"),
                            ("TIEMPO", "Tiempo"),
                            ("CONTENEDOR", "Contenedores / Embalaje"),
                            ("OTRO", "Otro"),
                        ],
                        db_index=True,
                        help_text="Categoría de la unidad de medida",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "factor_conversion",
                    models.DecimalField(
                        decimal_places=10,
                        default=Decimal("1.0"),
                        help_text="Factor para convertir a unidad base (ej: 1 ton = 1000 kg → factor: 1000)",
                        max_digits=20,
                        verbose_name="Factor de Conversión",
                    ),
                ),
                (
                    "decimales_display",
                    models.IntegerField(
                        default=2,
                        help_text="Cantidad de decimales para mostrar (0-6)",
                        verbose_name="Decimales para Display",
                    ),
                ),
                (
                    "prefiere_notacion_cientifica",
                    models.BooleanField(
                        default=False,
                        help_text="Usar notación científica para valores muy grandes/pequeños",
                        verbose_name="Notación Científica",
                    ),
                ),
                (
                    "usar_separador_miles",
                    models.BooleanField(
                        default=True,
                        help_text="Formatear con separador de miles (ej: 1,200 vs 1200)",
                        verbose_name="Usar Separador de Miles",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción o notas sobre la unidad",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Unidad precargada del sistema (no editable por usuarios)",
                        verbose_name="Es del Sistema",
                    ),
                ),
                (
                    "orden_display",
                    models.IntegerField(
                        default=0,
                        help_text="Orden para mostrar en listas (menor primero)",
                        verbose_name="Orden de Visualización",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "unidad_base",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidad base para conversión (ej: kg es base de ton)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_derivadas",
                        to="organizacion.unidadmedida",
                        verbose_name="Unidad Base",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "configuracion_unidad_medida",
                "ordering": ["categoria", "orden_display", "nombre"],
            },
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["code"], name="organizacio_code_21ad20_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["is_active"], name="organizacio_is_acti_0dfc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["parent"], name="organizacio_parent__957c96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caracterizacionproceso",
            index=models.Index(fields=["estado"], name="organizacio_estado_6c5e7f_idx"),
        ),
        migrations.AddIndex(
            model_name="consecutivoconfig",
            index=models.Index(
                fields=["empresa_id", "categoria"],
                name="configuraci_empresa_f91ac4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consecutivoconfig",
            index=models.Index(
                fields=["empresa_id", "is_active"],
                name="configuraci_empresa_430db3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consecutivoconfig",
            index=models.Index(fields=["codigo"], name="configuraci_codigo_12fa09_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="consecutivoconfig",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AddIndex(
            model_name="unidadmedida",
            index=models.Index(fields=["codigo"], name="configuraci_codigo_8119eb_idx"),
        ),
        migrations.AddIndex(
            model_name="unidadmedida",
            index=models.Index(
                fields=["categoria", "is_active"], name="configuraci_categor_e3a235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadmedida",
            index=models.Index(
                fields=["es_sistema"], name="configuraci_es_sist_055dfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadmedida",
            index=models.Index(
                fields=["deleted_at"], name="configuraci_deleted_89a48c_idx"
            ),
        ),
    ]
