# Generated by Django 5.0.9 on 2026-01-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='color',
            field=models.CharField(default='purple', help_text='Color del área (ej: purple, blue, green, red, amber, gray)', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='area',
            name='icon',
            field=models.CharField(default='Building2', help_text='Nombre del icono Lucide (ej: Building2, Users, Briefcase)', max_length=50, verbose_name='Icono'),
        ),
    ]
