# Generated by Django 5.0.9 on 2026-01-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_add_icon_color_to_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='consecutivoconfig',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CategoriaDocumento',
        ),
        migrations.DeleteModel(
            name='ConsecutivoConfig',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
