# Generated by Django 5.0.9 on 2026-03-12 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_caracterizacionproceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caracterizacionproceso',
            new_name='organizacio_estado_6c5e7f_idx',
            old_name='organizacio_estado_idx',
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='caracterizacionproceso',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
