# Generated by Django 5.0.14 on 2026-03-16 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0005_caracterizacion_relacional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracterizacionactividad",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacioncliente",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizaciondocumento",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionentrada",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionindicador",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionproveedor",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionrecurso",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionriesgo",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacionsalida",
            name="caracterizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizacion.caracterizacionproceso",
            ),
        ),
    ]
