# Generated by Django 5.0.14 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0006_alter_caracterizacionactividad_caracterizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ESTRATEGICO", "Estratégico"),
                    ("MISIONAL", "Misional"),
                    ("APOYO", "Apoyo"),
                    ("EVALUACION", "Evaluación"),
                ],
                db_index=True,
                default="APOYO",
                help_text="Clasificación según ISO 9001:2015 (estratégico, misional, apoyo, evaluación)",
                max_length=15,
                verbose_name="Tipo de proceso",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="objetivo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Objetivo que persigue este proceso dentro del SGI",
                verbose_name="Objetivo del proceso",
            ),
        ),
    ]
