# Generated by Django 5.0.9 on 2025-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recolecciones", "0002_certificadorecoleccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="recoleccion",
            name="calidad",
            field=models.CharField(
                blank=True,
                help_text="Calidad determinada por acidez: A (1-5%), B (5.1-8%), B1 (8.1-10%), B2 (10.1-15%), B4 (15.1-20%), C (>20%)",
                max_length=10,
                null=True,
                verbose_name="Calidad",
            ),
        ),
        migrations.AddField(
            model_name="recoleccion",
            name="porcentaje_acidez",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de acidez del ACU/Sebo (0-100%)",
                max_digits=5,
                null=True,
                verbose_name="Porcentaje de acidez (%)",
            ),
        ),
        migrations.AddField(
            model_name="recoleccion",
            name="requiere_prueba_acidez",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la recoleccion requiere prueba de acidez (ACU y Sebo Procesado)",
                verbose_name="Requiere prueba de acidez",
            ),
        ),
    ]
