# Generated by Django 5.0.14 on 2026-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_catalogo_productos", "0006_migrar_unidades_desde_legacy"),
        ("gestion_proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="productos_suministrados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Productos del catálogo maestro que el proveedor suministra",
                related_name="proveedores",
                to="infra_catalogo_productos.producto",
                verbose_name="Productos que suministra",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="tipos_materia_prima",
            field=models.ManyToManyField(
                blank=True,
                related_name="proveedores",
                to="gestion_proveedores.tipomateriaprima",
                verbose_name="Tipos de materia prima (legacy)",
            ),
        ),
    ]
