# Generated by Django 5.0.9 on 2026-01-17 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_proveedores", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ciudad",
            name="idx_ciudad_depto",
        ),
        migrations.RemoveIndex(
            model_name="evaluacionproveedor",
            name="idx_eval_prov_fecha",
        ),
        migrations.RemoveIndex(
            model_name="proveedor",
            name="idx_prov_depto_tipo_act",
        ),
        migrations.RemoveIndex(
            model_name="proveedor",
            name="idx_prov_modal_activo",
        ),
        migrations.RemoveIndex(
            model_name="proveedor",
            name="idx_prov_unidad_activo",
        ),
        migrations.RemoveIndex(
            model_name="pruebaacidez",
            name="idx_acidez_prov_cal",
        ),
        migrations.RemoveIndex(
            model_name="pruebaacidez",
            name="idx_acidez_tipo_fecha",
        ),
        migrations.RemoveIndex(
            model_name="tipomateriaprima",
            name="idx_tipomp_categoria",
        ),
        migrations.RemoveIndex(
            model_name="unidadnegocio",
            name="idx_unidad_tipo",
        ),
    ]
