# Generated by Django 5.0.14 on 2026-04-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "compras",
            "0003_alter_contrato_proveedor_alter_cotizacion_proveedor_and_more",
        ),
        (
            "gestion_proveedores",
            "0006_remove_criterioevaluacion_aplica_a_tipo_and_more",
        ),
        ("sc_recepcion", "0002_alter_voucherrecepcion_proveedor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Proveedor",
        ),
    ]
