# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mejora_continua", "0002_expand_auditoria_tipos_hallazgo_impacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoria",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="evaluacioncumplimiento",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hallazgo",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="programaauditoria",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="auditoria",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="evaluacioncumplimiento",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="hallazgo",
            unique_together={("empresa_id", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="programaauditoria",
            unique_together={("empresa_id", "codigo")},
        ),
    ]
