# Generated by Django 5.0.9 on 2026-03-12 17:41

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejora_continua', '0003_alter_auditoria_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditoria',
            name='hseq_audito_empresa_ffba4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='evaluacioncumplimiento',
            name='hseq_evalua_empresa_4579d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallazgo',
            name='hseq_hallaz_empresa_0d3338_idx',
        ),
        migrations.RemoveIndex(
            model_name='programaauditoria',
            name='hseq_progra_empresa_1e3729_idx',
        ),
        # SeparateDatabaseAndState: elimina unique_together solo si existe
        # (tenant schemas pueden no tener la constraint si fueron creados via syncdb)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='auditoria', unique_together=set()),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$ DECLARE v_con TEXT;
BEGIN
    SELECT tc.constraint_name INTO v_con
    FROM information_schema.table_constraints tc
    WHERE tc.table_name = 'hseq_auditoria'
      AND tc.constraint_type = 'UNIQUE'
      AND tc.table_schema = current_schema()
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'empresa_id')
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'codigo')
    LIMIT 1;
    IF v_con IS NOT NULL THEN
        EXECUTE format('ALTER TABLE hseq_auditoria DROP CONSTRAINT %I', v_con);
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='evaluacioncumplimiento', unique_together=set()),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$ DECLARE v_con TEXT;
BEGIN
    SELECT tc.constraint_name INTO v_con
    FROM information_schema.table_constraints tc
    WHERE tc.table_name = 'hseq_evaluacion_cumplimiento'
      AND tc.constraint_type = 'UNIQUE'
      AND tc.table_schema = current_schema()
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'empresa_id')
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'codigo')
    LIMIT 1;
    IF v_con IS NOT NULL THEN
        EXECUTE format('ALTER TABLE hseq_evaluacion_cumplimiento DROP CONSTRAINT %I', v_con);
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='hallazgo', unique_together=set()),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$ DECLARE v_con TEXT;
BEGIN
    SELECT tc.constraint_name INTO v_con
    FROM information_schema.table_constraints tc
    WHERE tc.table_name = 'hseq_hallazgo_auditoria'
      AND tc.constraint_type = 'UNIQUE'
      AND tc.table_schema = current_schema()
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'empresa_id')
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'codigo')
    LIMIT 1;
    IF v_con IS NOT NULL THEN
        EXECUTE format('ALTER TABLE hseq_hallazgo_auditoria DROP CONSTRAINT %I', v_con);
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='programaauditoria', unique_together=set()),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$ DECLARE v_con TEXT;
BEGIN
    SELECT tc.constraint_name INTO v_con
    FROM information_schema.table_constraints tc
    WHERE tc.table_name = 'hseq_programa_auditoria'
      AND tc.constraint_type = 'UNIQUE'
      AND tc.table_schema = current_schema()
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'empresa_id')
      AND EXISTS (SELECT 1 FROM information_schema.key_column_usage kcu
                  WHERE kcu.constraint_name = tc.constraint_name AND kcu.column_name = 'codigo')
    LIMIT 1;
    IF v_con IS NOT NULL THEN
        EXECUTE format('ALTER TABLE hseq_programa_auditoria DROP CONSTRAINT %I', v_con);
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='requisito_legal_id',
            field=models.PositiveBigIntegerField(blank=True, db_column='requisito_legal_ext_id', db_index=True, help_text='ID del RequisitoLegal en módulo Motor de Cumplimiento', null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='requisito_legal_nombre',
            field=models.CharField(blank=True, help_text='Nombre cache del requisito legal vinculado', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacioncumplimiento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='no_conformidad_codigo',
            field=models.CharField(blank=True, help_text='Código cache de la NoConformidad vinculada', max_length=50),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='no_conformidad_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID de la NoConformidad generada en módulo Calidad', null=True),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='estado',
            field=django_fsm.FSMField(choices=[('PROGRAMADA', 'Programada'), ('PLANIFICADA', 'Planificada'), ('EN_EJECUCION', 'En Ejecución'), ('INFORME_PENDIENTE', 'Informe Pendiente'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='evaluacioncumplimiento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncumplimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='evaluacioncumplimiento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='evaluacioncumplimiento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='estado',
            field=django_fsm.FSMField(choices=[('IDENTIFICADO', 'Identificado'), ('COMUNICADO', 'Comunicado'), ('EN_TRATAMIENTO', 'En Tratamiento'), ('VERIFICADO', 'Verificado'), ('CERRADO', 'Cerrado')], db_index=True, default='IDENTIFICADO', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='programaauditoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='programaauditoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='programaauditoria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='programaauditoria',
            name='estado',
            field=django_fsm.FSMField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En Ejecución'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='programaauditoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='empresa_id',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='evaluacioncumplimiento',
            name='empresa_id',
        ),
        migrations.RemoveField(
            model_name='evaluacioncumplimiento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='evaluacioncumplimiento',
            name='requisito_legal',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='empresa_id',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='no_conformidad_generada',
        ),
        migrations.RemoveField(
            model_name='programaauditoria',
            name='empresa_id',
        ),
        migrations.RemoveField(
            model_name='programaauditoria',
            name='is_active',
        ),
    ]
