# Generated by Django 5.0.9 on 2026-02-01 04:26

import apps.gestion_estrategica.configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificadoDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Nombre descriptivo del certificado (ej: "Certificado DIAN 2025")',
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            (
                                "P12",
                                "PKCS#12 (.p12/.pfx) - Certificado con clave privada",
                            ),
                            ("PEM", "PEM (.pem/.crt) - Certificado X.509"),
                            ("DER", "DER (.der/.cer) - Certificado binario"),
                            ("JKS", "Java KeyStore (.jks) - Almacén Java"),
                            ("PFX", "PFX (.pfx) - Personal Information Exchange"),
                        ],
                        default="P12",
                        max_length=10,
                        verbose_name="Tipo de Certificado",
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        choices=[
                            ("FACTURACION_DIAN", "Facturación Electrónica DIAN"),
                            ("NOMINA_ELECTRONICA", "Nómina Electrónica"),
                            ("FIRMA_DIGITAL", "Firma Digital de Documentos"),
                            ("TLS_CLIENT", "Autenticación TLS/SSL Client"),
                            ("WEB_SERVICE", "Web Services (SOAP/REST)"),
                            ("OTRO", "Otro uso"),
                        ],
                        default="FACTURACION_DIAN",
                        max_length=30,
                        verbose_name="Uso del Certificado",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Archivo .p12, .pfx, .pem, .crt, etc.",
                        upload_to=apps.gestion_estrategica.configuracion.models.certificado_upload_path,
                        verbose_name="Archivo del Certificado",
                    ),
                ),
                (
                    "_password_encrypted",
                    models.TextField(
                        blank=True,
                        db_column="password_encrypted",
                        help_text="Contraseña del certificado (almacenada encriptada)",
                        null=True,
                        verbose_name="Contraseña (Encriptada)",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de serie del certificado (extraído automáticamente)",
                        max_length=100,
                        null=True,
                        verbose_name="Número de Serie",
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True,
                        help_text="Common Name del sujeto del certificado",
                        max_length=250,
                        null=True,
                        verbose_name="Subject (CN)",
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True,
                        help_text="Common Name del emisor del certificado",
                        max_length=250,
                        null=True,
                        verbose_name="Emisor (CN)",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha desde la cual el certificado es válido",
                        null=True,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha hasta la cual el certificado es válido",
                        null=True,
                        verbose_name="Fecha de Expiración",
                    ),
                ),
                (
                    "huella_digital",
                    models.CharField(
                        blank=True,
                        help_text="Fingerprint SHA-256 del certificado",
                        max_length=100,
                        null=True,
                        verbose_name="Huella Digital (SHA-256)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PROXIMO_VENCER", "Próximo a Vencer"),
                            ("VENCIDO", "Vencido"),
                            ("REVOCADO", "Revocado"),
                            ("PENDIENTE", "Pendiente de Validación"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "dias_alerta_vencimiento",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días antes del vencimiento para generar alerta",
                        verbose_name="Días para Alerta",
                    ),
                ),
                (
                    "ultima_validacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de la última validación del certificado",
                        null=True,
                        verbose_name="Última Validación",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el certificado",
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Digital",
                "verbose_name_plural": "Certificados Digitales",
                "db_table": "configuracion_certificado_digital",
                "ordering": ["-fecha_expiracion", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="Número de Identificación Tributaria (ej: 900123456-7)",
                        max_length=20,
                        unique=True,
                        validators=[
                            apps.gestion_estrategica.configuracion.models.validar_nit_colombiano
                        ],
                        verbose_name="NIT",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Nombre legal completo de la empresa",
                        max_length=250,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True,
                        help_text="Nombre comercial o de fantasía (opcional)",
                        max_length=200,
                        null=True,
                        verbose_name="Nombre Comercial",
                    ),
                ),
                (
                    "representante_legal",
                    models.CharField(
                        help_text="Nombre completo del representante legal",
                        max_length=200,
                        verbose_name="Representante Legal",
                    ),
                ),
                (
                    "cedula_representante",
                    models.CharField(
                        blank=True,
                        help_text="Número de cédula del representante legal",
                        max_length=20,
                        null=True,
                        verbose_name="Cédula del Representante",
                    ),
                ),
                (
                    "tipo_sociedad",
                    models.CharField(
                        choices=[
                            ("SAS", "Sociedad por Acciones Simplificada (S.A.S.)"),
                            ("SA", "Sociedad Anónima (S.A.)"),
                            ("LTDA", "Sociedad Limitada (Ltda.)"),
                            ("SCA", "Sociedad en Comandita por Acciones"),
                            ("SC", "Sociedad en Comandita Simple"),
                            ("COLECTIVA", "Sociedad Colectiva"),
                            ("ESAL", "Entidad Sin Ánimo de Lucro"),
                            ("PERSONA_NATURAL", "Persona Natural"),
                            ("SUCURSAL_EXTRANJERA", "Sucursal de Sociedad Extranjera"),
                            ("OTRO", "Otro"),
                        ],
                        default="SAS",
                        help_text="Tipo de persona jurídica",
                        max_length=30,
                        verbose_name="Tipo de Sociedad",
                    ),
                ),
                (
                    "actividad_economica",
                    models.CharField(
                        blank=True,
                        help_text="Código de Clasificación Industrial Internacional Uniforme",
                        max_length=10,
                        null=True,
                        verbose_name="Actividad Económica (CIIU)",
                    ),
                ),
                (
                    "descripcion_actividad",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de la actividad económica principal",
                        max_length=300,
                        null=True,
                        verbose_name="Descripción de Actividad",
                    ),
                ),
                (
                    "regimen_tributario",
                    models.CharField(
                        choices=[
                            ("COMUN", "Régimen Común (Responsable de IVA)"),
                            ("SIMPLE", "Régimen Simple de Tributación (RST)"),
                            ("NO_RESPONSABLE", "No Responsable de IVA"),
                            ("ESPECIAL", "Régimen Tributario Especial"),
                            ("GRAN_CONTRIBUYENTE", "Gran Contribuyente"),
                        ],
                        default="COMUN",
                        help_text="Régimen tributario de la empresa",
                        max_length=30,
                        verbose_name="Régimen Tributario",
                    ),
                ),
                (
                    "direccion_fiscal",
                    models.TextField(
                        help_text="Dirección fiscal completa",
                        verbose_name="Dirección Fiscal",
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("AMAZONAS", "Amazonas"),
                            ("ANTIOQUIA", "Antioquia"),
                            ("ARAUCA", "Arauca"),
                            ("ATLANTICO", "Atlántico"),
                            ("BOLIVAR", "Bolívar"),
                            ("BOYACA", "Boyacá"),
                            ("CALDAS", "Caldas"),
                            ("CAQUETA", "Caquetá"),
                            ("CASANARE", "Casanare"),
                            ("CAUCA", "Cauca"),
                            ("CESAR", "Cesar"),
                            ("CHOCO", "Chocó"),
                            ("CORDOBA", "Córdoba"),
                            ("CUNDINAMARCA", "Cundinamarca"),
                            ("GUAINIA", "Guainía"),
                            ("GUAVIARE", "Guaviare"),
                            ("HUILA", "Huila"),
                            ("LA_GUAJIRA", "La Guajira"),
                            ("MAGDALENA", "Magdalena"),
                            ("META", "Meta"),
                            ("NARINO", "Nariño"),
                            ("NORTE_DE_SANTANDER", "Norte de Santander"),
                            ("PUTUMAYO", "Putumayo"),
                            ("QUINDIO", "Quindío"),
                            ("RISARALDA", "Risaralda"),
                            ("SAN_ANDRES", "San Andrés y Providencia"),
                            ("SANTANDER", "Santander"),
                            ("SUCRE", "Sucre"),
                            ("TOLIMA", "Tolima"),
                            ("VALLE_DEL_CAUCA", "Valle del Cauca"),
                            ("VAUPES", "Vaupés"),
                            ("VICHADA", "Vichada"),
                        ],
                        max_length=50,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Colombia", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código Postal",
                    ),
                ),
                (
                    "telefono_principal",
                    models.CharField(
                        help_text="Teléfono fijo o móvil principal",
                        max_length=20,
                        verbose_name="Teléfono Principal",
                    ),
                ),
                (
                    "telefono_secundario",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono Secundario",
                    ),
                ),
                (
                    "email_corporativo",
                    models.EmailField(
                        help_text="Email institucional de la empresa",
                        max_length=254,
                        verbose_name="Email Corporativo",
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "matricula_mercantil",
                    models.CharField(
                        blank=True,
                        help_text="Número de matrícula en Cámara de Comercio",
                        max_length=50,
                        null=True,
                        verbose_name="Matrícula Mercantil",
                    ),
                ),
                (
                    "camara_comercio",
                    models.CharField(
                        blank=True,
                        help_text="Cámara de Comercio donde está registrada",
                        max_length=100,
                        null=True,
                        verbose_name="Cámara de Comercio",
                    ),
                ),
                (
                    "fecha_constitucion",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de constitución de la sociedad",
                        null=True,
                        verbose_name="Fecha de Constitución",
                    ),
                ),
                (
                    "fecha_inscripcion_registro",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de inscripción en el registro mercantil",
                        null=True,
                        verbose_name="Fecha de Inscripción en Registro",
                    ),
                ),
                (
                    "zona_horaria",
                    models.CharField(
                        choices=[
                            ("America/Bogota", "Colombia (America/Bogota)"),
                            ("America/New_York", "Este EEUU (America/New_York)"),
                            (
                                "America/Los_Angeles",
                                "Pacífico EEUU (America/Los_Angeles)",
                            ),
                            ("America/Mexico_City", "México (America/Mexico_City)"),
                            ("Europe/Madrid", "España (Europe/Madrid)"),
                            ("UTC", "UTC"),
                        ],
                        default="America/Bogota",
                        max_length=50,
                        verbose_name="Zona Horaria",
                    ),
                ),
                (
                    "formato_fecha",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY (31/12/2024)"),
                            ("MM/DD/YYYY", "MM/DD/YYYY (12/31/2024)"),
                            ("YYYY-MM-DD", "YYYY-MM-DD (2024-12-31)"),
                            ("DD-MM-YYYY", "DD-MM-YYYY (31-12-2024)"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                        verbose_name="Formato de Fecha",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("COP", "Peso Colombiano (COP)"),
                            ("USD", "Dólar Estadounidense (USD)"),
                            ("EUR", "Euro (EUR)"),
                        ],
                        default="COP",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "simbolo_moneda",
                    models.CharField(
                        default="$", max_length=5, verbose_name="Símbolo de Moneda"
                    ),
                ),
                (
                    "separador_miles",
                    models.CharField(
                        default=".",
                        help_text="Carácter para separar miles (. o ,)",
                        max_length=1,
                        verbose_name="Separador de Miles",
                    ),
                ),
                (
                    "separador_decimales",
                    models.CharField(
                        default=",",
                        help_text="Carácter para separar decimales (. o ,)",
                        max_length=1,
                        verbose_name="Separador de Decimales",
                    ),
                ),
                (
                    "mostrar_powered_by",
                    models.BooleanField(
                        default=True,
                        help_text="Muestra el crédito de StrateKaz en el footer",
                        verbose_name='Mostrar "Powered by StrateKaz"',
                    ),
                ),
                (
                    "texto_footer",
                    models.CharField(
                        blank=True,
                        help_text="Texto personalizado para el pie de página",
                        max_length=200,
                        null=True,
                        verbose_name="Texto del Footer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Empresa",
                "verbose_name_plural": "Configuración de Empresa",
                "db_table": "configuracion_empresa",
            },
        ),
        migrations.CreateModel(
            name="IconRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre exacto del icono en Lucide (ej: Heart, Shield, Star)",
                        max_length=50,
                        verbose_name="Nombre del Icono",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nombre amigable para mostrar al usuario (ej: Corazon, Escudo)",
                        max_length=100,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VALORES", "Valores Corporativos"),
                            ("NORMAS", "Normas y Sistemas"),
                            ("ACCIONES", "Acciones y Botones"),
                            ("ESTADOS", "Estados y Status"),
                            ("NAVEGACION", "Navegacion"),
                            ("DOCUMENTOS", "Documentos"),
                            ("COMUNICACION", "Comunicacion"),
                            ("PERSONAS", "Personas y Equipos"),
                            ("FINANZAS", "Finanzas"),
                            ("RIESGOS", "Riesgos y Alertas"),
                            ("GENERAL", "Uso General"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        help_text="Categoria para agrupar iconos en el selector",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Descripcion o contexto de uso del icono",
                        max_length=200,
                        null=True,
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Palabras clave para busqueda (separadas por coma)",
                        max_length=200,
                        null=True,
                        verbose_name="Palabras Clave",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparicion en el selector",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Iconos precargados del sistema (no eliminables)",
                        verbose_name="Es del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Icono del Sistema",
                "verbose_name_plural": "Iconos del Sistema",
                "db_table": "configuracion_icon_registry",
                "ordering": ["category", "orden", "label"],
            },
        ),
        migrations.CreateModel(
            name="IntegracionExterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Nombre descriptivo de la integración (ej: "Email Corporativo Gmail")',
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "tipo_servicio_legacy",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="[DEPRECATED] Tipo Servicio (texto)",
                    ),
                ),
                (
                    "proveedor_legacy",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="[DEPRECATED] Proveedor (texto)",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del propósito de la integración",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="URL base de la API del servicio (ej: https://api.servicio.com/v1)",
                        max_length=500,
                        null=True,
                        verbose_name="URL del Endpoint",
                    ),
                ),
                (
                    "metodo_autenticacion",
                    models.CharField(
                        choices=[
                            ("API_KEY", "API Key"),
                            ("BEARER_TOKEN", "Bearer Token"),
                            ("OAUTH2", "OAuth 2.0"),
                            ("OAUTH1", "OAuth 1.0"),
                            ("BASIC_AUTH", "Basic Authentication (Usuario/Contraseña)"),
                            ("JWT", "JSON Web Token (JWT)"),
                            ("SERVICE_ACCOUNT", "Service Account (Cuenta de Servicio)"),
                            (
                                "CERTIFICATE",
                                "Certificado Digital (TLS/SSL Client Certificate)",
                            ),
                            ("HMAC", "HMAC Signature"),
                            ("CUSTOM", "Autenticación Personalizada"),
                        ],
                        default="API_KEY",
                        help_text="Tipo de autenticación utilizado",
                        max_length=30,
                        verbose_name="Método de Autenticación",
                    ),
                ),
                (
                    "_credenciales_encrypted",
                    models.TextField(
                        blank=True,
                        db_column="credenciales_encrypted",
                        help_text="Almacena credenciales encriptadas (API keys, tokens, passwords, etc.)",
                        null=True,
                        verbose_name="Credenciales (Encriptadas)",
                    ),
                ),
                (
                    "configuracion_adicional",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parámetros específicos del servicio (timeouts, límites, etc.)",
                        verbose_name="Configuración Adicional",
                    ),
                ),
                (
                    "ambiente",
                    models.CharField(
                        choices=[
                            ("PRODUCCION", "Producción"),
                            ("SANDBOX", "Sandbox / Pruebas"),
                            ("DESARROLLO", "Desarrollo"),
                        ],
                        default="PRODUCCION",
                        help_text="Ambiente de la integración",
                        max_length=20,
                        verbose_name="Ambiente",
                    ),
                ),
                (
                    "ultima_conexion_exitosa",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la última conexión exitosa",
                        null=True,
                        verbose_name="Última Conexión Exitosa",
                    ),
                ),
                (
                    "ultima_falla",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la última falla de conexión",
                        null=True,
                        verbose_name="Última Falla",
                    ),
                ),
                (
                    "contador_llamadas",
                    models.IntegerField(
                        default=0,
                        help_text="Total de llamadas realizadas (para rate limiting)",
                        verbose_name="Contador de Llamadas",
                    ),
                ),
                (
                    "errores_recientes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de los últimos 10 errores con timestamp y detalle",
                        verbose_name="Errores Recientes",
                    ),
                ),
                (
                    "limite_llamadas_dia",
                    models.IntegerField(
                        blank=True,
                        help_text="Límite máximo de llamadas permitidas por día (null = sin límite)",
                        null=True,
                        verbose_name="Límite de Llamadas por Día",
                    ),
                ),
                (
                    "alerta_porcentaje_limite",
                    models.IntegerField(
                        default=80,
                        help_text="Porcentaje del límite para enviar alerta (ej: 80 = alerta al 80%)",
                        verbose_name="% para Alerta de Límite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integración Externa",
                "verbose_name_plural": "Integraciones Externas",
                "db_table": "configuracion_integracion_externa",
                "ordering": ["tipo_servicio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="NormaISO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la norma (ej: ISO_9001, PESV)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo de la norma",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre abreviado (ej: Calidad, SST)",
                        max_length=50,
                        null=True,
                        verbose_name="Nombre Corto",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de clasificación (ej: Calidad, Ambiental, SST)",
                        max_length=50,
                        null=True,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Versión o año de la norma (ej: 2015, 2018)",
                        max_length=20,
                        null=True,
                        verbose_name="Versión/Año",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono Lucide",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Color"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Normas precargadas del sistema (no eliminables)",
                        verbose_name="Es del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Norma ISO / Sistema de Gestión",
                "verbose_name_plural": "Normas ISO / Sistemas de Gestión",
                "db_table": "configuracion_norma_iso",
                "ordering": ["orden", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProveedorIntegracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del proveedor (ej: GMAIL, TWILIO, AWS_S3)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del proveedor",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de Documentación"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del archivo de logo o URL",
                        max_length=100,
                        null=True,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "pais_origen",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="País de Origen",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_sistema",
                    models.BooleanField(default=False, verbose_name="Es del Sistema"),
                ),
            ],
            options={
                "verbose_name": "Proveedor de Integración",
                "verbose_name_plural": "Proveedores de Integración",
                "db_table": "configuracion_proveedor_integracion",
                "ordering": ["orden", "name"],
            },
        ),
        migrations.CreateModel(
            name="SedeEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la sede (ej: SEDE-001, PLANTA-BOG)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la sede",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "tipo_sede_legacy",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="[DEPRECATED] Tipo Sede (texto)",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la sede",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        help_text="Dirección física de la sede",
                        verbose_name="Dirección",
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("AMAZONAS", "Amazonas"),
                            ("ANTIOQUIA", "Antioquia"),
                            ("ARAUCA", "Arauca"),
                            ("ATLANTICO", "Atlántico"),
                            ("BOLIVAR", "Bolívar"),
                            ("BOYACA", "Boyacá"),
                            ("CALDAS", "Caldas"),
                            ("CAQUETA", "Caquetá"),
                            ("CASANARE", "Casanare"),
                            ("CAUCA", "Cauca"),
                            ("CESAR", "Cesar"),
                            ("CHOCO", "Chocó"),
                            ("CORDOBA", "Córdoba"),
                            ("CUNDINAMARCA", "Cundinamarca"),
                            ("GUAINIA", "Guainía"),
                            ("GUAVIARE", "Guaviare"),
                            ("HUILA", "Huila"),
                            ("LA_GUAJIRA", "La Guajira"),
                            ("MAGDALENA", "Magdalena"),
                            ("META", "Meta"),
                            ("NARINO", "Nariño"),
                            ("NORTE_DE_SANTANDER", "Norte de Santander"),
                            ("PUTUMAYO", "Putumayo"),
                            ("QUINDIO", "Quindío"),
                            ("RISARALDA", "Risaralda"),
                            ("SAN_ANDRES", "San Andrés y Providencia"),
                            ("SANTANDER", "Santander"),
                            ("SUCRE", "Sucre"),
                            ("TOLIMA", "Tolima"),
                            ("VALLE_DEL_CAUCA", "Valle del Cauca"),
                            ("VAUPES", "Vaupés"),
                            ("VICHADA", "Vichada"),
                        ],
                        max_length=50,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código Postal",
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Coordenada de latitud GPS (ej: 4.60971)",
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Coordenada de longitud GPS (ej: -74.08175)",
                        max_digits=11,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto de la sede",
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto de la sede",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "es_sede_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Solo puede haber una sede principal",
                        verbose_name="Es Sede Principal",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de apertura o inicio de operaciones",
                        null=True,
                        verbose_name="Fecha de Apertura",
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de cierre (si aplica)",
                        null=True,
                        verbose_name="Fecha de Cierre",
                    ),
                ),
                (
                    "capacidad_almacenamiento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacidad máxima de almacenamiento (cantidad numérica)",
                        max_digits=12,
                        null=True,
                        verbose_name="Capacidad de Almacenamiento",
                    ),
                ),
                (
                    "capacidad_almacenamiento_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="DEPRECATED: Use capacidad_almacenamiento + unidad_capacidad",
                        max_digits=12,
                        null=True,
                        verbose_name="[DEPRECATED] Capacidad de Almacenamiento (kg)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede de la Empresa",
                "verbose_name_plural": "Sedes de la Empresa",
                "db_table": "configuracion_sede_empresa",
                "ordering": ["-es_sede_principal", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: ESTRATEGICO, PROCESO)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de cambio",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono Lucide",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Color"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Tipos precargados del sistema (no eliminables)",
                        verbose_name="Es del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Cambio",
                "verbose_name_plural": "Tipos de Cambio",
                "db_table": "configuracion_tipo_cambio",
                "ordering": ["orden", "name"],
            },
        ),
        migrations.CreateModel(
            name="TipoSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: PLANTA, ALMACEN, SUCURSAL)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de sede",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono Lucide (ej: Building, Factory, Warehouse)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color para identificación visual",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Tipos precargados del sistema (no eliminables)",
                        verbose_name="Es del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Sede",
                "verbose_name_plural": "Tipos de Sede",
                "db_table": "configuracion_tipo_sede",
                "ordering": ["orden", "name"],
            },
        ),
        migrations.CreateModel(
            name="TipoServicioIntegracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: EMAIL, FACTURACION, PAGOS)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de servicio",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de clasificación (ej: Comunicación, Financiero, Almacenamiento)",
                        max_length=50,
                        null=True,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono Lucide",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_sistema",
                    models.BooleanField(default=False, verbose_name="Es del Sistema"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Servicio de Integración",
                "verbose_name_plural": "Tipos de Servicio de Integración",
                "db_table": "configuracion_tipo_servicio_integracion",
                "ordering": ["orden", "name"],
            },
        ),
    ]
