# Generated by Django migration generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Datos de Identificación Fiscal
                ('nit', models.CharField(
                    max_length=20,
                    unique=True,
                    verbose_name='NIT',
                    help_text='Número de Identificación Tributaria (ej: 900123456-7)'
                )),
                ('razon_social', models.CharField(
                    max_length=250,
                    verbose_name='Razón Social',
                    help_text='Nombre legal completo de la empresa'
                )),
                ('nombre_comercial', models.CharField(
                    max_length=200,
                    blank=True,
                    null=True,
                    verbose_name='Nombre Comercial',
                    help_text='Nombre comercial o de fantasía (opcional)'
                )),
                ('representante_legal', models.CharField(
                    max_length=200,
                    verbose_name='Representante Legal',
                    help_text='Nombre completo del representante legal'
                )),
                ('cedula_representante', models.CharField(
                    max_length=20,
                    blank=True,
                    null=True,
                    verbose_name='Cédula del Representante',
                    help_text='Número de cédula del representante legal'
                )),
                ('tipo_sociedad', models.CharField(
                    max_length=30,
                    choices=[
                        ('SAS', 'Sociedad por Acciones Simplificada (S.A.S.)'),
                        ('SA', 'Sociedad Anónima (S.A.)'),
                        ('LTDA', 'Sociedad Limitada (Ltda.)'),
                        ('SCA', 'Sociedad en Comandita por Acciones'),
                        ('SC', 'Sociedad en Comandita Simple'),
                        ('COLECTIVA', 'Sociedad Colectiva'),
                        ('ESAL', 'Entidad Sin Ánimo de Lucro'),
                        ('PERSONA_NATURAL', 'Persona Natural'),
                        ('SUCURSAL_EXTRANJERA', 'Sucursal de Sociedad Extranjera'),
                        ('OTRO', 'Otro'),
                    ],
                    default='SAS',
                    verbose_name='Tipo de Sociedad',
                    help_text='Tipo de persona jurídica'
                )),
                ('actividad_economica', models.CharField(
                    max_length=10,
                    blank=True,
                    null=True,
                    verbose_name='Actividad Económica (CIIU)',
                    help_text='Código de Clasificación Industrial Internacional Uniforme'
                )),
                ('descripcion_actividad', models.CharField(
                    max_length=300,
                    blank=True,
                    null=True,
                    verbose_name='Descripción de Actividad',
                    help_text='Descripción de la actividad económica principal'
                )),
                ('regimen_tributario', models.CharField(
                    max_length=30,
                    choices=[
                        ('COMUN', 'Régimen Común (Responsable de IVA)'),
                        ('SIMPLE', 'Régimen Simple de Tributación (RST)'),
                        ('NO_RESPONSABLE', 'No Responsable de IVA'),
                        ('ESPECIAL', 'Régimen Tributario Especial'),
                        ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'),
                    ],
                    default='COMUN',
                    verbose_name='Régimen Tributario',
                    help_text='Régimen tributario de la empresa'
                )),
                # Datos de Contacto Oficial
                ('direccion_fiscal', models.TextField(
                    verbose_name='Dirección Fiscal',
                    help_text='Dirección fiscal completa'
                )),
                ('ciudad', models.CharField(
                    max_length=100,
                    verbose_name='Ciudad'
                )),
                ('departamento', models.CharField(
                    max_length=50,
                    choices=[
                        ('AMAZONAS', 'Amazonas'),
                        ('ANTIOQUIA', 'Antioquia'),
                        ('ARAUCA', 'Arauca'),
                        ('ATLANTICO', 'Atlántico'),
                        ('BOLIVAR', 'Bolívar'),
                        ('BOYACA', 'Boyacá'),
                        ('CALDAS', 'Caldas'),
                        ('CAQUETA', 'Caquetá'),
                        ('CASANARE', 'Casanare'),
                        ('CAUCA', 'Cauca'),
                        ('CESAR', 'Cesar'),
                        ('CHOCO', 'Chocó'),
                        ('CORDOBA', 'Córdoba'),
                        ('CUNDINAMARCA', 'Cundinamarca'),
                        ('GUAINIA', 'Guainía'),
                        ('GUAVIARE', 'Guaviare'),
                        ('HUILA', 'Huila'),
                        ('LA_GUAJIRA', 'La Guajira'),
                        ('MAGDALENA', 'Magdalena'),
                        ('META', 'Meta'),
                        ('NARINO', 'Nariño'),
                        ('NORTE_DE_SANTANDER', 'Norte de Santander'),
                        ('PUTUMAYO', 'Putumayo'),
                        ('QUINDIO', 'Quindío'),
                        ('RISARALDA', 'Risaralda'),
                        ('SAN_ANDRES', 'San Andrés y Providencia'),
                        ('SANTANDER', 'Santander'),
                        ('SUCRE', 'Sucre'),
                        ('TOLIMA', 'Tolima'),
                        ('VALLE_DEL_CAUCA', 'Valle del Cauca'),
                        ('VAUPES', 'Vaupés'),
                        ('VICHADA', 'Vichada'),
                    ],
                    verbose_name='Departamento'
                )),
                ('pais', models.CharField(
                    max_length=100,
                    default='Colombia',
                    verbose_name='País'
                )),
                ('codigo_postal', models.CharField(
                    max_length=10,
                    blank=True,
                    null=True,
                    verbose_name='Código Postal'
                )),
                ('telefono_principal', models.CharField(
                    max_length=20,
                    verbose_name='Teléfono Principal',
                    help_text='Teléfono fijo o móvil principal'
                )),
                ('telefono_secundario', models.CharField(
                    max_length=20,
                    blank=True,
                    null=True,
                    verbose_name='Teléfono Secundario'
                )),
                ('email_corporativo', models.EmailField(
                    max_length=254,
                    verbose_name='Email Corporativo',
                    help_text='Email institucional de la empresa'
                )),
                ('sitio_web', models.URLField(
                    blank=True,
                    null=True,
                    verbose_name='Sitio Web'
                )),
                # Datos de Registro
                ('matricula_mercantil', models.CharField(
                    max_length=50,
                    blank=True,
                    null=True,
                    verbose_name='Matrícula Mercantil',
                    help_text='Número de matrícula en Cámara de Comercio'
                )),
                ('camara_comercio', models.CharField(
                    max_length=100,
                    blank=True,
                    null=True,
                    verbose_name='Cámara de Comercio',
                    help_text='Cámara de Comercio donde está registrada'
                )),
                ('fecha_constitucion', models.DateField(
                    blank=True,
                    null=True,
                    verbose_name='Fecha de Constitución',
                    help_text='Fecha de constitución de la sociedad'
                )),
                ('fecha_inscripcion_registro', models.DateField(
                    blank=True,
                    null=True,
                    verbose_name='Fecha de Inscripción en Registro',
                    help_text='Fecha de inscripción en el registro mercantil'
                )),
                # Configuración Regional
                ('zona_horaria', models.CharField(
                    max_length=50,
                    choices=[
                        ('America/Bogota', 'Colombia (America/Bogota)'),
                        ('America/New_York', 'Este EEUU (America/New_York)'),
                        ('America/Los_Angeles', 'Pacífico EEUU (America/Los_Angeles)'),
                        ('America/Mexico_City', 'México (America/Mexico_City)'),
                        ('Europe/Madrid', 'España (Europe/Madrid)'),
                        ('UTC', 'UTC'),
                    ],
                    default='America/Bogota',
                    verbose_name='Zona Horaria'
                )),
                ('formato_fecha', models.CharField(
                    max_length=20,
                    choices=[
                        ('DD/MM/YYYY', 'DD/MM/YYYY (31/12/2024)'),
                        ('MM/DD/YYYY', 'MM/DD/YYYY (12/31/2024)'),
                        ('YYYY-MM-DD', 'YYYY-MM-DD (2024-12-31)'),
                        ('DD-MM-YYYY', 'DD-MM-YYYY (31-12-2024)'),
                    ],
                    default='DD/MM/YYYY',
                    verbose_name='Formato de Fecha'
                )),
                ('moneda', models.CharField(
                    max_length=3,
                    choices=[
                        ('COP', 'Peso Colombiano (COP)'),
                        ('USD', 'Dólar Estadounidense (USD)'),
                        ('EUR', 'Euro (EUR)'),
                    ],
                    default='COP',
                    verbose_name='Moneda'
                )),
                ('simbolo_moneda', models.CharField(
                    max_length=5,
                    default='$',
                    verbose_name='Símbolo de Moneda'
                )),
                ('separador_miles', models.CharField(
                    max_length=1,
                    default='.',
                    verbose_name='Separador de Miles',
                    help_text='Carácter para separar miles (. o ,)'
                )),
                ('separador_decimales', models.CharField(
                    max_length=1,
                    default=',',
                    verbose_name='Separador de Decimales',
                    help_text='Carácter para separar decimales (. o ,)'
                )),
                # Auditoría
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Fecha de Creación'
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Última Actualización'
                )),
                ('updated_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='empresa_config_updates',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Actualizado por',
                    help_text='Usuario que realizó la última actualización'
                )),
            ],
            options={
                'db_table': 'configuracion_empresa',
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
