# Generated by Django 5.0.9 on 2026-02-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        ("organizacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificadodigital",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="certificadodigital",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="empresaconfig",
            name="unidad_capacidad_default",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad de medida predeterminada para capacidad de almacenamiento (ej: kg, ton, m³)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas_capacidad_default",
                to="organizacion.unidadmedida",
                verbose_name="Unidad de Capacidad por Defecto",
            ),
        ),
        migrations.AddField(
            model_name="empresaconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresa_config_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="iconregistry",
            index=models.Index(
                fields=["category", "orden"], name="configuraci_categor_b8a64d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="iconregistry",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_icon_per_category"
            ),
        ),
        migrations.AddField(
            model_name="integracionexterna",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="integracionexterna",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="certificadodigital",
            name="integracion",
            field=models.ForeignKey(
                help_text="Integración externa a la que pertenece este certificado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificados",
                to="configuracion.integracionexterna",
                verbose_name="Integración",
            ),
        ),
        migrations.AddField(
            model_name="integracionexterna",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor del servicio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="integraciones",
                to="configuracion.proveedorintegracion",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="sedeempresa",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="sedeempresa",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable de la sede",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sedes_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="sedeempresa",
            name="unidad_capacidad",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad de medida de la capacidad (ej: kg, ton, m³, pallets)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sedes_capacidad",
                to="organizacion.unidadmedida",
                verbose_name="Unidad de Capacidad",
            ),
        ),
        migrations.AddField(
            model_name="sedeempresa",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="sedeempresa",
            name="tipo_sede",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de sede o ubicación",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sedes",
                to="configuracion.tiposede",
                verbose_name="Tipo de Sede",
            ),
        ),
        migrations.AddField(
            model_name="proveedorintegracion",
            name="tipo_servicio",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de servicio principal que ofrece",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proveedores",
                to="configuracion.tiposerviciointegracion",
                verbose_name="Tipo de Servicio Principal",
            ),
        ),
        migrations.AddField(
            model_name="integracionexterna",
            name="tipo_servicio",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría del servicio externo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="integraciones",
                to="configuracion.tiposerviciointegracion",
                verbose_name="Tipo de Servicio",
            ),
        ),
        migrations.AddIndex(
            model_name="certificadodigital",
            index=models.Index(
                fields=["integracion", "is_active"],
                name="configuraci_integra_08f72d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificadodigital",
            index=models.Index(
                fields=["estado", "fecha_expiracion"],
                name="configuraci_estado_e7d8e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificadodigital",
            index=models.Index(fields=["uso"], name="configuraci_uso_c31bb7_idx"),
        ),
        migrations.AddIndex(
            model_name="sedeempresa",
            index=models.Index(fields=["codigo"], name="configuraci_codigo_00b2bd_idx"),
        ),
        migrations.AddIndex(
            model_name="sedeempresa",
            index=models.Index(
                fields=["is_active", "tipo_sede"], name="configuraci_is_acti_d232b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sedeempresa",
            index=models.Index(
                fields=["departamento", "ciudad"], name="configuraci_departa_dacde3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sedeempresa",
            index=models.Index(
                fields=["deleted_at"], name="configuraci_deleted_93031c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionexterna",
            index=models.Index(
                fields=["tipo_servicio", "is_active"],
                name="configuraci_tipo_se_dc6d8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integracionexterna",
            index=models.Index(
                fields=["proveedor", "is_active"], name="configuraci_proveed_c7de6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionexterna",
            index=models.Index(
                fields=["ambiente"], name="configuraci_ambient_264ab5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionexterna",
            index=models.Index(
                fields=["deleted_at"], name="configuraci_deleted_a59a98_idx"
            ),
        ),
    ]
