# Generated by Django 5.0.9 on 2026-01-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(db_index=True, help_text='Código único del proveedor (ej: GMAIL, TWILIO, AWS_S3)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del proveedor', max_length=100, verbose_name='Nombre')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('documentation_url', models.URLField(blank=True, null=True, verbose_name='URL de Documentación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('logo', models.CharField(blank=True, help_text='Nombre del archivo de logo o URL', max_length=100, null=True, verbose_name='Logo')),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True, verbose_name='País de Origen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es del Sistema')),
            ],
            options={
                'verbose_name': 'Proveedor de Integración',
                'verbose_name_plural': 'Proveedores de Integración',
                'db_table': 'configuracion_proveedor_integracion',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TipoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(db_index=True, help_text='Código único del tipo (ej: PLANTA, ALMACEN, SUCURSAL)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del tipo de sede', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Lucide (ej: Building, Factory, Warehouse)', max_length=50, null=True, verbose_name='Icono')),
                ('color', models.CharField(default='gray', help_text='Color para identificación visual', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_sistema', models.BooleanField(default=False, help_text='Tipos precargados del sistema (no eliminables)', verbose_name='Es del Sistema')),
            ],
            options={
                'verbose_name': 'Tipo de Sede',
                'verbose_name_plural': 'Tipos de Sede',
                'db_table': 'configuracion_tipo_sede',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicioIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(db_index=True, help_text='Código único del tipo (ej: EMAIL, FACTURACION, PAGOS)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del tipo de servicio', max_length=100, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, help_text='Grupo de clasificación (ej: Comunicación, Financiero, Almacenamiento)', max_length=50, null=True, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Lucide', max_length=50, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es del Sistema')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio de Integración',
                'verbose_name_plural': 'Tipos de Servicio de Integración',
                'db_table': 'configuracion_tipo_servicio_integracion',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='integracionexterna',
            new_name='configuraci_tipo_se_dc6d8f_idx',
            old_name='configuraci_tipo_se_a20d70_idx',
        ),
        migrations.RenameIndex(
            model_name='integracionexterna',
            new_name='configuraci_proveed_c7de6f_idx',
            old_name='configuraci_proveed_03e16b_idx',
        ),
        migrations.RenameIndex(
            model_name='sedeempresa',
            new_name='configuraci_is_acti_d232b9_idx',
            old_name='configuraci_is_acti_452daa_idx',
        ),
        migrations.AddField(
            model_name='integracionexterna',
            name='proveedor_legacy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='[DEPRECATED] Proveedor (texto)'),
        ),
        migrations.AddField(
            model_name='integracionexterna',
            name='tipo_servicio_legacy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='[DEPRECATED] Tipo Servicio (texto)'),
        ),
        migrations.AddField(
            model_name='sedeempresa',
            name='tipo_sede_legacy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='[DEPRECATED] Tipo Sede (texto)'),
        ),
        migrations.AlterField(
            model_name='integracionexterna',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del servicio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integraciones', to='configuracion.proveedorintegracion', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='sedeempresa',
            name='tipo_sede',
            field=models.ForeignKey(blank=True, help_text='Tipo de sede o ubicación', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='configuracion.tiposede', verbose_name='Tipo de Sede'),
        ),
        migrations.AddField(
            model_name='proveedorintegracion',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, help_text='Tipo de servicio principal que ofrece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='configuracion.tiposerviciointegracion', verbose_name='Tipo de Servicio Principal'),
        ),
        migrations.AlterField(
            model_name='integracionexterna',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, help_text='Categoría del servicio externo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integraciones', to='configuracion.tiposerviciointegracion', verbose_name='Tipo de Servicio'),
        ),
    ]
