# Generated by Django 5.0.9 on 2025-12-14 03:57

import apps.gestion_estrategica.configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0004_add_integracion_externa"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="integracionexterna",
            new_name="configuraci_tipo_se_a20d70_idx",
            old_name="config_tipo_active_idx",
        ),
        migrations.RenameIndex(
            model_name="integracionexterna",
            new_name="configuraci_proveed_03e16b_idx",
            old_name="config_prov_active_idx",
        ),
        migrations.RenameIndex(
            model_name="integracionexterna",
            new_name="configuraci_ambient_264ab5_idx",
            old_name="config_ambiente_idx",
        ),
        migrations.RenameIndex(
            model_name="integracionexterna",
            new_name="configuraci_deleted_a59a98_idx",
            old_name="config_deleted_integ_idx",
        ),
        migrations.RenameIndex(
            model_name="sedeempresa",
            new_name="configuraci_codigo_00b2bd_idx",
            old_name="configuraci_codigo_sede_idx",
        ),
        migrations.RenameIndex(
            model_name="sedeempresa",
            new_name="configuraci_is_acti_452daa_idx",
            old_name="configuraci_active_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="sedeempresa",
            new_name="configuraci_departa_dacde3_idx",
            old_name="configuraci_depto_ciudad_idx",
        ),
        migrations.RenameIndex(
            model_name="sedeempresa",
            new_name="configuraci_deleted_93031c_idx",
            old_name="configuraci_deleted_sede_idx",
        ),
        migrations.AlterField(
            model_name="empresaconfig",
            name="nit",
            field=models.CharField(
                help_text="Número de Identificación Tributaria (ej: 900123456-7)",
                max_length=20,
                unique=True,
                validators=[
                    apps.gestion_estrategica.configuracion.models.validar_nit_colombiano
                ],
                verbose_name="NIT",
            ),
        ),
    ]
