# Generated by Django 5.0.14 on 2026-03-16 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_legacy_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TERMINO_FIJO", "Contrato a Término Fijo"),
                            ("INDEFINIDO", "Contrato a Término Indefinido"),
                            ("OBRA_LABOR", "Contrato por Obra o Labor"),
                            ("PRESTACION_SERVICIOS", "Prestación de Servicios"),
                            ("APRENDIZAJE", "Contrato de Aprendizaje"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "clausulas_principales",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de cláusulas tipo del contrato (JSON array)",
                        verbose_name="Cláusulas Principales",
                    ),
                ),
                (
                    "duracion_default_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración estándar del contrato en días. Null para indefinido.",
                        null=True,
                        verbose_name="Duración por Defecto (días)",
                    ),
                ),
                (
                    "periodo_prueba_dias",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="CST Art. 76-80. Máximo 2 meses.",
                        verbose_name="Período de Prueba (días)",
                    ),
                ),
                (
                    "requiere_poliza",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el contrato requiere póliza de cumplimiento",
                        verbose_name="Requiere Póliza",
                    ),
                ),
                (
                    "plantilla_documento",
                    models.FileField(
                        blank=True,
                        help_text="Archivo Word/PDF con la plantilla del contrato",
                        null=True,
                        upload_to="contratos/plantillas/",
                        verbose_name="Plantilla del Documento",
                    ),
                ),
                (
                    "notas_legales",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones legales o normativas aplicables",
                        verbose_name="Notas Legales",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "db_table": "gestion_estrategica_tipocontrato",
                "ordering": ["empresa", "orden", "nombre"],
                "unique_together": {("empresa", "tipo", "nombre")},
            },
        ),
    ]
