# Generated by Django 5.0.14 on 2026-03-16
# Creates UnidadNegocio in Fundación (configuracion app).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0005_tipo_contrato"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # --- TimestampedModel (via AuditModel) ---
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                # --- AuditModel ---
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                # --- SoftDeleteModel ---
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                # --- Model's own fields ---
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la unidad de negocio (ej: PLANTA-BOG-01)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre"),
                ),
                (
                    "tipo_unidad",
                    models.CharField(
                        choices=[
                            ("SEDE", "Sede Administrativa"),
                            ("SUCURSAL", "Sucursal"),
                            ("PLANTA", "Planta de Producción"),
                            ("CENTRO_ACOPIO", "Centro de Acopio"),
                            ("ALMACEN", "Almacén"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de unidad",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, default="", verbose_name="Dirección"
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades_negocio",
                        to="core.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades_negocio_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                # is_active overrides SoftDeleteModel's version (no verbose_name/help_text)
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
            ],
            options={
                "verbose_name": "Unidad de Negocio",
                "verbose_name_plural": "Unidades de Negocio",
                "db_table": "fundacion_unidad_negocio",
                "ordering": ["codigo"],
            },
        ),
    ]
