# Generated by Django 5.0.9 on 2025-12-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "configuracion",
            "0005_rename_config_tipo_active_idx_configuraci_tipo_se_a20d70_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sedeempresa",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="empresaconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="empresaconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="integracionexterna",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="sedeempresa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="sedeempresa",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="sedeempresa",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AlterField(
            model_name="sedeempresa",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="sedeempresa",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
    ]
