# Generated by Django 5.0.9 on 2026-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_add_icon_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='color_fondo_showcase',
            field=models.CharField(blank=True, help_text='Color de fondo para presentaciones (ej: #1F2937)', max_length=7, null=True, verbose_name='Color Fondo Showcase'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='color_primario',
            field=models.CharField(blank=True, help_text='Color principal de la marca en formato HEX (ej: #3B82F6)', max_length=7, null=True, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='color_secundario',
            field=models.CharField(blank=True, help_text='Color secundario/acento en formato HEX (ej: #10B981)', max_length=7, null=True, verbose_name='Color Secundario'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icono pequeño para pestañas del navegador (32x32 o 64x64 px)', null=True, upload_to='empresa/favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='gradiente_mision',
            field=models.CharField(blank=True, help_text='Clases Tailwind para el gradiente de la slide de Misión', max_length=100, null=True, verbose_name='Gradiente Misión'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='gradiente_politica',
            field=models.CharField(blank=True, help_text='Clases Tailwind para el gradiente de la slide de Política', max_length=100, null=True, verbose_name='Gradiente Política'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='gradiente_valores',
            field=models.JSONField(blank=True, help_text='Lista de gradientes Tailwind para carrusel de valores', null=True, verbose_name='Gradientes Valores'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='gradiente_vision',
            field=models.CharField(blank=True, help_text='Clases Tailwind para el gradiente de la slide de Visión', max_length=100, null=True, verbose_name='Gradiente Visión'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa en formato PNG o SVG (recomendado fondo transparente)', null=True, upload_to='empresa/logos/', verbose_name='Logo Principal'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Versión del logo para fondos oscuros (opcional)', null=True, upload_to='empresa/logos/', verbose_name='Logo para Modo Oscuro'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='slogan',
            field=models.CharField(blank=True, help_text='Frase corta que identifica a la empresa', max_length=200, null=True, verbose_name='Slogan'),
        ),
    ]
