# Generated by Django 5.0.9 on 2026-01-20 02:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_empresaconfig_color_fondo_showcase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(help_text='Código único del consecutivo (ej: FACTURA, OC, REQ)', max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del consecutivo', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del uso de este consecutivo', null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('DOCUMENTOS', 'Documentos'), ('COMPRAS', 'Compras'), ('VENTAS', 'Ventas'), ('INVENTARIO', 'Inventario'), ('CONTABILIDAD', 'Contabilidad'), ('PRODUCCION', 'Producción'), ('CALIDAD', 'Calidad'), ('RRHH', 'Recursos Humanos'), ('SST', 'Seguridad y Salud'), ('AMBIENTAL', 'Gestión Ambiental'), ('GENERAL', 'General')], default='GENERAL', help_text='Categoría para agrupar consecutivos', max_length=20, verbose_name='Categoría')),
                ('prefix', models.CharField(help_text='Prefijo del consecutivo (ej: FAC, OC, REQ)', max_length=20, verbose_name='Prefijo')),
                ('suffix', models.CharField(blank=True, default='', help_text='Sufijo opcional al final (ej: CO, -A)', max_length=20, verbose_name='Sufijo')),
                ('separator', models.CharField(choices=[('-', 'Guión (-)'), ('/', 'Diagonal (/)'), ('_', 'Guión bajo (_)'), ('.', 'Punto (.)'), ('', 'Sin separador')], default='-', help_text='Caracter separador entre componentes', max_length=1, verbose_name='Separador')),
                ('current_number', models.PositiveIntegerField(default=0, help_text='Último número generado', verbose_name='Número Actual')),
                ('padding', models.PositiveSmallIntegerField(default=5, help_text='Cantidad de dígitos con ceros a la izquierda (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Dígitos de Relleno')),
                ('numero_inicial', models.PositiveIntegerField(default=1, help_text='Número desde el cual inicia la secuencia', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número Inicial')),
                ('include_year', models.BooleanField(default=True, help_text='Incluir el año en formato YYYY', verbose_name='Incluir Año')),
                ('include_month', models.BooleanField(default=False, help_text='Incluir el mes en formato MM (requiere año o produce YYYYMM)', verbose_name='Incluir Mes')),
                ('include_day', models.BooleanField(default=False, help_text='Incluir el día en formato DD (requiere mes o produce YYYYMMDD)', verbose_name='Incluir Día')),
                ('reset_yearly', models.BooleanField(default=True, help_text='Reiniciar la numeración cada año', verbose_name='Reinicio Anual')),
                ('reset_monthly', models.BooleanField(default=False, help_text='Reiniciar la numeración cada mes', verbose_name='Reinicio Mensual')),
                ('last_reset_date', models.DateField(blank=True, help_text='Fecha del último reinicio de la secuencia', null=True, verbose_name='Última Fecha de Reinicio')),
                ('es_sistema', models.BooleanField(default=False, help_text='Indica si es un consecutivo del sistema (no editable)', verbose_name='Es del Sistema')),
                ('empresa_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Empresa ID')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Consecutivo',
                'verbose_name_plural': 'Configuraciones de Consecutivos',
                'db_table': 'configuracion_consecutivo',
                'ordering': ['categoria', 'codigo'],
                'indexes': [models.Index(fields=['empresa_id', 'categoria'], name='configuraci_empresa_f91ac4_idx'), models.Index(fields=['empresa_id', 'is_active'], name='configuraci_empresa_430db3_idx'), models.Index(fields=['codigo'], name='configuraci_codigo_12fa09_idx')],
                'unique_together': {('empresa_id', 'codigo')},
            },
        ),
    ]
