# Generated by Django 5.0.9 on 2026-01-17 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('disenador_flujos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoformulario',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto corto'), ('TEXTAREA', 'Texto largo'), ('NUMBER', 'Número'), ('EMAIL', 'Correo electrónico'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y hora'), ('SELECT', 'Lista desplegable'), ('MULTISELECT', 'Selección múltiple'), ('CHECKBOX', 'Casilla de verificación'), ('RADIO', 'Botones de radio'), ('FILE', 'Archivo adjunto'), ('SIGNATURE', 'Firma Digital')], help_text='Tipo de dato que acepta el campo', max_length=20, verbose_name='Tipo de campo'),
        ),
        migrations.CreateModel(
            name='FormularioDiligenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveBigIntegerField(db_index=True, help_text='ID de la empresa (multi-tenant)', verbose_name='Empresa ID')),
                ('numero_formulario', models.CharField(help_text='Código único generado automáticamente (ej: FRM-2026-0001)', max_length=50, unique=True, verbose_name='Número de Formulario')),
                ('titulo', models.CharField(help_text='Título descriptivo del formulario diligenciado', max_length=255, verbose_name='Título')),
                ('fecha_diligenciamiento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Diligenciamiento')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='ID de Entidad Relacionada')),
                ('datos_formulario', models.JSONField(default=dict, help_text='Datos capturados en formato JSON estructurado', verbose_name='Datos del Formulario')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], db_index=True, default='EN_PROGRESO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Entidad Relacionada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_diligenciados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('diligenciado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_diligenciados', to=settings.AUTH_USER_MODEL, verbose_name='Diligenciado Por')),
                ('plantilla_flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_diligenciados', to='disenador_flujos.plantillaflujo', verbose_name='Plantilla de Formulario')),
            ],
            options={
                'verbose_name': 'Formulario Diligenciado',
                'verbose_name_plural': 'Formularios Diligenciados',
                'db_table': 'workflow_formulario_diligenciado',
                'ordering': ['-fecha_diligenciamiento'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveBigIntegerField(db_index=True, help_text='ID de la empresa (multi-tenant)', verbose_name='Empresa ID')),
                ('area_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID del área para asignaciones masivas', null=True, verbose_name='ID Área')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Asignación')),
                ('fecha_limite', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridad')),
                ('titulo', models.CharField(help_text='Título descriptivo de la asignación', max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones o contexto para el usuario', verbose_name='Descripción')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('dias_recordatorio', models.PositiveIntegerField(default=3, help_text='Días antes de la fecha límite para enviar recordatorio', verbose_name='Días de Recordatorio')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_formularios_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('plantilla_flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='disenador_flujos.plantillaflujo', verbose_name='Plantilla de Formulario')),
                ('formulario_diligenciado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignacion_origen', to='disenador_flujos.formulariodiligenciado', verbose_name='Formulario Diligenciado')),
            ],
            options={
                'verbose_name': 'Asignación de Formulario',
                'verbose_name_plural': 'Asignaciones de Formularios',
                'db_table': 'workflow_asignacion_formulario',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(help_text='Valor capturado (texto, número, fecha, archivo, firma, etc.)', verbose_name='Valor de la Respuesta')),
                ('firma_base64', models.TextField(blank=True, help_text='Imagen de firma capturada desde canvas signature', null=True, verbose_name='Firma en Base64')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('es_valido', models.BooleanField(default=True, verbose_name='Es Válido')),
                ('mensaje_validacion', models.CharField(blank=True, max_length=500, verbose_name='Mensaje de Validación')),
                ('version', models.PositiveIntegerField(default=1, help_text='Contador de modificaciones', verbose_name='Versión')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Valor previo antes de la modificación', null=True, verbose_name='Valor Anterior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('campo_formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='disenador_flujos.campoformulario', verbose_name='Campo de Formulario')),
                ('formulario_diligenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='disenador_flujos.formulariodiligenciado', verbose_name='Formulario Diligenciado')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Respuesta de Campo',
                'verbose_name_plural': 'Respuestas de Campos',
                'db_table': 'workflow_respuesta_campo',
                'ordering': ['campo_formulario__orden'],
            },
        ),
        migrations.AddIndex(
            model_name='formulariodiligenciado',
            index=models.Index(fields=['empresa_id', 'estado'], name='workflow_fo_empresa_8468e3_idx'),
        ),
        migrations.AddIndex(
            model_name='formulariodiligenciado',
            index=models.Index(fields=['plantilla_flujo', 'estado'], name='workflow_fo_plantil_7599ad_idx'),
        ),
        migrations.AddIndex(
            model_name='formulariodiligenciado',
            index=models.Index(fields=['diligenciado_por', '-fecha_diligenciamiento'], name='workflow_fo_diligen_c08a20_idx'),
        ),
        migrations.AddIndex(
            model_name='formulariodiligenciado',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_fo_content_6647fa_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionformulario',
            index=models.Index(fields=['empresa_id', 'estado'], name='workflow_as_empresa_c7a281_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionformulario',
            index=models.Index(fields=['asignado_a', 'estado'], name='workflow_as_asignad_baaa05_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionformulario',
            index=models.Index(fields=['fecha_limite'], name='workflow_as_fecha_l_c88ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionformulario',
            index=models.Index(fields=['area_id', 'estado'], name='workflow_as_area_id_43323d_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestacampo',
            index=models.Index(fields=['formulario_diligenciado', 'campo_formulario'], name='workflow_re_formula_972bff_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestacampo',
            index=models.Index(fields=['modificado_por', '-fecha_modificacion'], name='workflow_re_modific_42257c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestacampo',
            unique_together={('formulario_diligenciado', 'campo_formulario')},
        ),
    ]
