# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disenador_flujos", "0001_initial"),
        ("ejecucion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaFlujo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("retraso", "Retraso"),
                            ("escalamiento", "Escalamiento"),
                            ("error", "Error"),
                            ("vencimiento", "Vencimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("acciones_tomadas", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("atendida", "Atendida"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("empresa_id", models.PositiveBigIntegerField()),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_alertas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instancia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="ejecucion.instanciaflujo",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas",
                        to="ejecucion.tareaactiva",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_alerta_flujo",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_widget",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI"),
                            ("grafico", "Gráfico"),
                            ("lista", "Lista"),
                            ("tabla", "Tabla"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("configuracion", models.JSONField(default=dict)),
                ("posicion_x", models.IntegerField(default=0)),
                ("posicion_y", models.IntegerField(default=0)),
                ("ancho", models.IntegerField(default=4)),
                ("alto", models.IntegerField(default=4)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_dashboard_widget",
            },
        ),
        migrations.CreateModel(
            name="ReglaSLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("tiempo_limite_horas", models.IntegerField()),
                ("tiempo_alerta_horas", models.IntegerField()),
                (
                    "accion_vencimiento",
                    models.CharField(
                        choices=[
                            ("notificar", "Notificar"),
                            ("escalar", "Escalar"),
                            ("reasignar", "Reasignar"),
                        ],
                        default="notificar",
                        max_length=20,
                    ),
                ),
                ("destinatarios_alerta", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("empresa_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_sla",
                        to="disenador_flujos.nodoflujo",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_sla",
                        to="disenador_flujos.plantillaflujo",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_regla_sla",
            },
        ),
        migrations.CreateModel(
            name="ReporteAutomatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destinatarios", models.TextField()),
                (
                    "formato",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                    ),
                ),
                ("ultimo_envio", models.DateTimeField(blank=True, null=True)),
                ("proximo_envio", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("empresa_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plantillas_incluidas",
                    models.ManyToManyField(
                        related_name="reportes_automaticos",
                        to="disenador_flujos.plantillaflujo",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_reporte_automatico",
            },
        ),
        migrations.CreateModel(
            name="MetricaFlujo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("total_instancias", models.IntegerField(default=0)),
                ("instancias_completadas", models.IntegerField(default=0)),
                ("instancias_canceladas", models.IntegerField(default=0)),
                (
                    "tiempo_promedio_dias",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tareas_totales", models.IntegerField(default=0)),
                ("tareas_completadas", models.IntegerField(default=0)),
                ("tareas_rechazadas", models.IntegerField(default=0)),
                ("cuellos_botella", models.JSONField(default=dict)),
                ("empresa_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="disenador_flujos.plantillaflujo",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_metrica_flujo",
                "unique_together": {
                    ("plantilla", "periodo", "fecha_inicio", "empresa_id")
                },
            },
        ),
    ]
