# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_legacy_fields"),
        ("organizacion", "0002_organigramanodeposition"),
        ("presupuesto", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="presupuestoporarea",
            unique_together={("empresa", "area", "centro_costo", "rubro", "anio")},
        ),
        migrations.AlterField(
            model_name="centrocosto",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del centro de costo (ej: CC-001)",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="ejecucion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único de la ejecución (auto-generado: EJE-YYYY-####)",
                max_length=50,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="presupuestoporarea",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del presupuesto (auto-generado: PRE-YYYY-####)",
                max_length=50,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="rubro",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del rubro (auto-generado: RUB-###)",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centrocosto",
            unique_together={("empresa", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="ejecucion",
            unique_together={("empresa", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="presupuestoporarea",
            unique_together={
                ("empresa", "area", "centro_costo", "rubro", "anio"),
                ("empresa", "codigo"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="rubro",
            unique_together={("empresa", "codigo")},
        ),
    ]
