# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activos_fijos", "0001_initial"),
        ("configuracion", "0001_initial"),
        ("organizacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activofijo",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Área organizacional responsable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos_fijos",
                to="organizacion.area",
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable del activo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="baja",
            name="activo",
            field=models.OneToOneField(
                help_text="Activo a dar de baja",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baja",
                to="activos_fijos.activofijo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="baja",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que aprueba la baja",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bajas_aprobadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado Por",
            ),
        ),
        migrations.AddField(
            model_name="baja",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="baja",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="baja",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="categoriaactivo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="activofijo",
            name="categoria",
            field=models.ForeignKey(
                help_text="Categoría del activo",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos",
                to="activos_fijos.categoriaactivo",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="depreciacion",
            name="activo",
            field=models.ForeignKey(
                help_text="Activo a depreciar",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depreciaciones",
                to="activos_fijos.activofijo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="depreciacion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="depreciacion",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="depreciacion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="hojavidaactivo",
            name="activo",
            field=models.ForeignKey(
                help_text="Activo al que corresponde el evento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hojas_vida",
                to="activos_fijos.activofijo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="hojavidaactivo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="hojavidaactivo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="hojavidaactivo",
            name="realizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó o registró el evento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hojas_vida_realizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Realizado Por",
            ),
        ),
        migrations.AddField(
            model_name="hojavidaactivo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="programamantenimiento",
            name="activo",
            field=models.ForeignKey(
                help_text="Activo a mantener",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programas_mantenimiento",
                to="activos_fijos.activofijo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="programamantenimiento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="programamantenimiento",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="programamantenimiento",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable del mantenimiento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programas_mantenimiento",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="programamantenimiento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="baja",
            index=models.Index(
                fields=["empresa", "fecha_baja"], name="admin_finan_empresa_6cd06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baja",
            index=models.Index(
                fields=["activo"], name="admin_finan_activo__0c3b47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baja",
            index=models.Index(
                fields=["fecha_baja"], name="admin_finan_fecha_b_25409b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoriaactivo",
            index=models.Index(
                fields=["empresa", "is_active"], name="admin_finan_empresa_d2ba1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoriaactivo",
            index=models.Index(fields=["codigo"], name="admin_finan_codigo_605759_idx"),
        ),
        migrations.AddIndex(
            model_name="activofijo",
            index=models.Index(
                fields=["empresa", "estado"], name="admin_finan_empresa_de368b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activofijo",
            index=models.Index(fields=["codigo"], name="admin_finan_codigo_82f394_idx"),
        ),
        migrations.AddIndex(
            model_name="activofijo",
            index=models.Index(
                fields=["categoria", "estado"], name="admin_finan_categor_dcbefe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activofijo",
            index=models.Index(fields=["area"], name="admin_finan_area_id_393028_idx"),
        ),
        migrations.AddIndex(
            model_name="activofijo",
            index=models.Index(
                fields=["fecha_adquisicion"], name="admin_finan_fecha_a_db7c42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciacion",
            index=models.Index(
                fields=["empresa", "periodo_anio", "periodo_mes"],
                name="admin_finan_empresa_898a69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="depreciacion",
            index=models.Index(
                fields=["activo", "periodo_anio", "periodo_mes"],
                name="admin_finan_activo__568a70_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="depreciacion",
            unique_together={("activo", "periodo_mes", "periodo_anio")},
        ),
        migrations.AddIndex(
            model_name="hojavidaactivo",
            index=models.Index(
                fields=["empresa", "activo", "fecha"],
                name="admin_finan_empresa_c98e4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hojavidaactivo",
            index=models.Index(fields=["codigo"], name="admin_finan_codigo_0d4e54_idx"),
        ),
        migrations.AddIndex(
            model_name="hojavidaactivo",
            index=models.Index(
                fields=["activo", "tipo_evento"], name="admin_finan_activo__b3ab79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hojavidaactivo",
            index=models.Index(fields=["fecha"], name="admin_finan_fecha_f0ec58_idx"),
        ),
        migrations.AddIndex(
            model_name="programamantenimiento",
            index=models.Index(
                fields=["empresa", "estado"], name="admin_finan_empresa_fad399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programamantenimiento",
            index=models.Index(
                fields=["activo", "estado"], name="admin_finan_activo__b615c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programamantenimiento",
            index=models.Index(
                fields=["proxima_fecha"], name="admin_finan_proxima_436c3b_idx"
            ),
        ),
    ]
