# Generated by Django 5.0.14 on 2026-04-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liquidaciones", "0001_initial"),
        ("sc_recepcion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="voucher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidacion",
                to="sc_recepcion.voucherrecepcion",
                verbose_name="Voucher de recepción",
            ),
        ),
        migrations.AddIndex(
            model_name="liquidacion",
            index=models.Index(
                fields=["estado", "-created_at"], name="supply_chai_estado_41a0db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liquidacion",
            index=models.Index(
                fields=["voucher"], name="supply_chai_voucher_2c5b60_idx"
            ),
        ),
    ]
