# Generated by Django 5.0.14 on 2026-04-27 04:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0005_liquidacion_header_lineas"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="liquidacion",
            new_name="supply_chai_estado_fcfe27_idx",
            old_name="sc_liquida_estado_idx",
        ),
        migrations.AlterField(
            model_name="liquidacion",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Suma de monto_base de las líneas.",
                max_digits=14,
                verbose_name="Subtotal",
            ),
        ),
    ]
