# Generated by Django 5.0.14 on 2026-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0008_h_sc_02_estados_historial_gd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionlinea",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Peso neto de la línea del voucher (kg, 1 decimal).",
                max_digits=14,
                verbose_name="Cantidad",
            ),
        ),
    ]
