# Generated by Django 5.0.14 on 2026-03-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_firma_digital", "0003_firmadigital_hash_verificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmadigital",
            name="configuracion_flujo",
            field=models.ForeignKey(
                blank=True,
                help_text="Null cuando se auto-asigna desde plantilla sin flujo formal",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="firmas",
                to="infra_firma_digital.configuracionflujofirma",
                verbose_name="Configuración de Flujo",
            ),
        ),
    ]
