# Generated by Django 5.0.9 on 2026-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalisisKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "periodo_analisis",
                    models.DateField(
                        help_text="Fecha del período que se está analizando",
                        verbose_name="Período de Análisis",
                    ),
                ),
                (
                    "tipo_analisis",
                    models.CharField(
                        choices=[
                            ("periodo_anterior", "Período Anterior"),
                            (
                                "mismo_periodo_año_anterior",
                                "Mismo Período Año Anterior",
                            ),
                            ("promedio_historico", "Promedio Histórico"),
                            ("meta", "vs Meta"),
                        ],
                        help_text="Tipo de comparación realizada",
                        max_length=40,
                        verbose_name="Tipo de Análisis",
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor del KPI en el período analizado",
                        max_digits=15,
                        verbose_name="Valor Actual",
                    ),
                ),
                (
                    "valor_comparacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor contra el que se compara (período anterior, meta, etc.)",
                        max_digits=15,
                        verbose_name="Valor de Comparación",
                    ),
                ),
                (
                    "variacion_absoluta",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Diferencia absoluta entre valor actual y comparación",
                        max_digits=15,
                        verbose_name="Variación Absoluta",
                    ),
                ),
                (
                    "variacion_porcentual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variación porcentual respecto al valor de comparación",
                        max_digits=10,
                        verbose_name="Variación Porcentual",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[
                            ("mejora", "Mejora"),
                            ("deterioro", "Deterioro"),
                            ("estable", "Estable"),
                        ],
                        help_text="Si la variación representa mejora, deterioro o estabilidad",
                        max_length=15,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios sobre el análisis",
                        verbose_name="Observaciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis KPI",
                "verbose_name_plural": "Análisis de KPIs",
                "db_table": "analytics_analisis_kpi",
                "ordering": ["-periodo_analisis", "kpi"],
            },
        ),
        migrations.CreateModel(
            name="AnomaliaDetectada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo_anomalia",
                    models.CharField(
                        choices=[
                            ("valor_extremo_superior", "Valor Extremo Superior"),
                            ("valor_extremo_inferior", "Valor Extremo Inferior"),
                            ("cambio_abrupto", "Cambio Abrupto"),
                            ("patron_inusual", "Patrón Inusual"),
                        ],
                        help_text="Clasificación de la anomalía detectada",
                        max_length=30,
                        verbose_name="Tipo de Anomalía",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        help_text="Nivel de criticidad de la anomalía",
                        max_length=10,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "valor_detectado",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor anómalo que disparó la alerta",
                        max_digits=15,
                        verbose_name="Valor Detectado",
                    ),
                ),
                (
                    "valor_esperado",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor que se esperaba según el patrón histórico",
                        max_digits=15,
                        verbose_name="Valor Esperado",
                    ),
                ),
                (
                    "desviacion_std",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cuántas desviaciones estándar se desvía del promedio",
                        max_digits=10,
                        verbose_name="Desviación Estándar",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Cuándo se detectó la anomalía",
                        verbose_name="Fecha de Detección",
                    ),
                ),
                (
                    "esta_revisada",
                    models.BooleanField(
                        default=False,
                        help_text="Si la anomalía ha sido revisada por un usuario",
                        verbose_name="Revisada",
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se revisó la anomalía",
                        null=True,
                        verbose_name="Fecha de Revisión",
                    ),
                ),
                (
                    "accion_tomada",
                    models.TextField(
                        blank=True,
                        help_text="Qué acción se tomó al revisar la anomalía",
                        verbose_name="Acción Tomada",
                    ),
                ),
                (
                    "es_falso_positivo",
                    models.BooleanField(
                        default=False,
                        help_text="Si la anomalía fue determinada como falso positivo",
                        verbose_name="Falso Positivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomalía Detectada",
                "verbose_name_plural": "Anomalías Detectadas",
                "db_table": "analytics_anomalia_detectada",
                "ordering": ["-fecha_deteccion", "-severidad"],
            },
        ),
        migrations.CreateModel(
            name="TendenciaKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del rango analizado",
                        verbose_name="Inicio del Período",
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        help_text="Fecha de fin del rango analizado",
                        verbose_name="Fin del Período",
                    ),
                ),
                (
                    "tipo_tendencia",
                    models.CharField(
                        choices=[
                            ("creciente", "Creciente"),
                            ("decreciente", "Decreciente"),
                            ("estable", "Estable"),
                            ("volatil", "Volátil"),
                        ],
                        help_text="Clasificación de la tendencia observada",
                        max_length=15,
                        verbose_name="Tipo de Tendencia",
                    ),
                ),
                (
                    "coeficiente_correlacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Coeficiente de correlación de Pearson (-1 a 1)",
                        max_digits=5,
                        verbose_name="Coeficiente de Correlación (r)",
                    ),
                ),
                (
                    "r_cuadrado",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Proporción de varianza explicada por el modelo (0 a 1)",
                        max_digits=5,
                        verbose_name="R² (Coeficiente de Determinación)",
                    ),
                ),
                (
                    "pendiente",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Pendiente de la recta de regresión",
                        max_digits=15,
                        verbose_name="Pendiente",
                    ),
                ),
                (
                    "intercepto",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Intercepto de la recta de regresión",
                        max_digits=15,
                        verbose_name="Intercepto",
                    ),
                ),
                (
                    "proyeccion_3_meses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor proyectado para dentro de 3 meses",
                        max_digits=15,
                        null=True,
                        verbose_name="Proyección 3 Meses",
                    ),
                ),
                (
                    "proyeccion_6_meses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor proyectado para dentro de 6 meses",
                        max_digits=15,
                        null=True,
                        verbose_name="Proyección 6 Meses",
                    ),
                ),
                (
                    "proyeccion_12_meses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor proyectado para dentro de 12 meses",
                        max_digits=15,
                        null=True,
                        verbose_name="Proyección 12 Meses",
                    ),
                ),
                (
                    "datos_historicos",
                    models.JSONField(
                        default=list,
                        help_text="Array de {fecha, valor} utilizados en el análisis",
                        verbose_name="Datos Históricos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tendencia KPI",
                "verbose_name_plural": "Tendencias de KPIs",
                "db_table": "analytics_tendencia_kpi",
                "ordering": ["-periodo_fin", "kpi"],
            },
        ),
    ]
