# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analisis_tendencias", "0001_initial"),
        ("config_indicadores", "0001_initial"),
        ("configuracion", "0001_initial"),
        ("indicadores_area", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analisiskpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="analisiskpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="analisiskpi",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analisis",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="analisiskpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="anomaliadetectada",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="anomaliadetectada",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="anomaliadetectada",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="anomaliadetectada",
            name="usuario_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalias_revisadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que Revisó",
            ),
        ),
        migrations.AddField(
            model_name="anomaliadetectada",
            name="valor_kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalias",
                to="indicadores_area.valorkpi",
                verbose_name="Valor KPI",
            ),
        ),
        migrations.AddField(
            model_name="tendenciakpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="tendenciakpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="tendenciakpi",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tendencias",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="tendenciakpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="analisiskpi",
            index=models.Index(
                fields=["empresa", "kpi"], name="analytics_a_empresa_33954b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisiskpi",
            index=models.Index(
                fields=["periodo_analisis"], name="analytics_a_periodo_78a3f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisiskpi",
            index=models.Index(
                fields=["tipo_analisis"], name="analytics_a_tipo_an_dfb255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analisiskpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_a_empresa_0babb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaliadetectada",
            index=models.Index(
                fields=["empresa", "valor_kpi"], name="analytics_a_empresa_740eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaliadetectada",
            index=models.Index(
                fields=["fecha_deteccion"], name="analytics_a_fecha_d_9b3ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaliadetectada",
            index=models.Index(
                fields=["severidad", "esta_revisada"],
                name="analytics_a_severid_2efc12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomaliadetectada",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_a_empresa_60c5ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tendenciakpi",
            index=models.Index(
                fields=["empresa", "kpi"], name="analytics_t_empresa_2acdad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tendenciakpi",
            index=models.Index(
                fields=["periodo_inicio", "periodo_fin"],
                name="analytics_t_periodo_70db56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tendenciakpi",
            index=models.Index(
                fields=["tipo_tendencia"], name="analytics_t_tipo_te_87fc8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tendenciakpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_t_empresa_21fbde_idx"
            ),
        ),
    ]
