# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        ("gestion_proveedores", "0001_initial"),
        ("programacion_abastecimiento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6C757D",
                        help_text="Color para visualización (ej: #28A745 para verde)",
                        max_length=7,
                        verbose_name="Color (HEX)",
                    ),
                ),
                (
                    "es_inicial",
                    models.BooleanField(
                        default=False,
                        help_text="Estado por defecto para nuevas recepciones",
                        verbose_name="Es estado inicial",
                    ),
                ),
                (
                    "es_final",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que la recepción ha terminado (completada, rechazada o cancelada)",
                        verbose_name="Es estado final",
                    ),
                ),
                (
                    "permite_edicion",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la recepción puede editarse en este estado",
                        verbose_name="Permite edición",
                    ),
                ),
                (
                    "genera_inventario",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si al llegar a este estado se debe actualizar el inventario",
                        verbose_name="Genera inventario",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Recepción",
                "verbose_name_plural": "Estados de Recepción",
                "db_table": "production_ops_estado_recepcion",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="production__codigo_9e2aa5_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="production__is_acti_54d4ed_idx"
                    ),
                    models.Index(
                        fields=["es_inicial"], name="production__es_inic_d16d2c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PuntoRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del punto de recepción",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de la ubicación dentro de la planta",
                        max_length=200,
                        null=True,
                        verbose_name="Ubicación física",
                    ),
                ),
                (
                    "capacidad_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacidad máxima de recepción en kilogramos",
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidad en KG",
                    ),
                ),
                (
                    "bascula_asignada",
                    models.CharField(
                        blank=True,
                        help_text="Identificación de la báscula asociada a este punto",
                        max_length=100,
                        null=True,
                        verbose_name="Báscula asignada",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de Recepción",
                "verbose_name_plural": "Puntos de Recepción",
                "db_table": "production_ops_punto_recepcion",
                "ordering": ["empresa", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Recepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Código autogenerado de la recepción",
                        max_length=50,
                        unique=True,
                        verbose_name="Código de recepción",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha de la recepción",
                        verbose_name="Fecha de recepción",
                    ),
                ),
                (
                    "hora_llegada",
                    models.TimeField(
                        blank=True,
                        help_text="Hora en que llegó el vehículo a la planta",
                        null=True,
                        verbose_name="Hora de llegada",
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True,
                        help_text="Hora en que salió el vehículo de la planta",
                        null=True,
                        verbose_name="Hora de salida",
                    ),
                ),
                (
                    "vehiculo_proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Placa o identificación del vehículo (ej: ABC123)",
                        max_length=50,
                        null=True,
                        verbose_name="Vehículo del proveedor",
                    ),
                ),
                (
                    "conductor_proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del conductor que entrega la materia prima",
                        max_length=200,
                        null=True,
                        verbose_name="Conductor del proveedor",
                    ),
                ),
                (
                    "peso_bruto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso del vehículo cargado",
                        max_digits=10,
                        null=True,
                        verbose_name="Peso bruto (KG)",
                    ),
                ),
                (
                    "peso_tara",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso del vehículo vacío",
                        max_digits=10,
                        null=True,
                        verbose_name="Tara (KG)",
                    ),
                ),
                (
                    "peso_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente: peso_bruto - peso_tara",
                        max_digits=10,
                        null=True,
                        verbose_name="Peso neto (KG)",
                    ),
                ),
                (
                    "temperatura_llegada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperatura de la materia prima al momento de recepción",
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura de llegada (°C)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones generales"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones",
                        to="recepcion.estadorecepcion",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "programacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programación de abastecimiento asociada (si aplica)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recepciones",
                        to="programacion_abastecimiento.programacion",
                        verbose_name="Programación asociada",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        help_text="Proveedor que entrega la materia prima",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones_materia_prima",
                        to="gestion_proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "punto_recepcion",
                    models.ForeignKey(
                        help_text="Ubicación física donde se realiza la recepción",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones",
                        to="recepcion.puntorecepcion",
                        verbose_name="Punto de recepción",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        help_text="Usuario que registró la recepción",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción de Materia Prima",
                "verbose_name_plural": "Recepciones de Materia Prima",
                "db_table": "production_ops_recepcion",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetalleRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad recibida de este tipo de materia prima",
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        default="KG",
                        help_text="Unidad de medida (KG, TON, LT, etc.)",
                        max_length=20,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "acidez_medida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de acidez medido (solo para sebo procesado)",
                        max_digits=5,
                        null=True,
                        verbose_name="Acidez medida (%)",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperatura específica de este lote",
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio por unidad de medida",
                        max_digits=12,
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente: cantidad * precio_unitario",
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "lote_asignado",
                    models.CharField(
                        blank=True,
                        help_text="Código de lote para trazabilidad",
                        max_length=50,
                        null=True,
                        verbose_name="Lote asignado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones del detalle"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_recepcion",
                        to="gestion_proveedores.tipomateriaprima",
                        verbose_name="Tipo de materia prima",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="recepcion.recepcion",
                        verbose_name="Recepción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Recepción",
                "verbose_name_plural": "Detalles de Recepción",
                "db_table": "production_ops_detalle_recepcion",
                "ordering": ["recepcion", "id"],
            },
        ),
        migrations.CreateModel(
            name="ControlCalidadRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parametro",
                    models.CharField(
                        help_text="Parámetro evaluado (ej: acidez, temperatura, color, olor, impurezas, humedad)",
                        max_length=100,
                        verbose_name="Parámetro de control",
                    ),
                ),
                (
                    "valor_esperado",
                    models.CharField(
                        help_text="Valor o rango esperado del parámetro",
                        max_length=200,
                        verbose_name="Valor esperado",
                    ),
                ),
                (
                    "valor_obtenido",
                    models.CharField(
                        help_text="Valor real medido u observado",
                        max_length=200,
                        verbose_name="Valor obtenido",
                    ),
                ),
                (
                    "cumple",
                    models.BooleanField(
                        help_text="Indica si el valor obtenido cumple con lo esperado",
                        verbose_name="Cumple especificación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones del control"
                    ),
                ),
                (
                    "fecha_verificacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de verificación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verificado_por",
                    models.ForeignKey(
                        help_text="Usuario que realizó la verificación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controles_calidad_verificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_calidad",
                        to="recepcion.recepcion",
                        verbose_name="Recepción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Calidad de Recepción",
                "verbose_name_plural": "Controles de Calidad de Recepción",
                "db_table": "production_ops_control_calidad_recepcion",
                "ordering": ["recepcion", "fecha_verificacion"],
            },
        ),
        migrations.CreateModel(
            name="TipoRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo de recepción (ej: RECEPCION_HUESO_CRUDO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de recepción",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_pesaje",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este tipo requiere registro de peso bruto/neto/tara",
                        verbose_name="Requiere pesaje",
                    ),
                ),
                (
                    "requiere_acidez",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo requiere prueba de acidez (sebo procesado)",
                        verbose_name="Requiere medición de acidez",
                    ),
                ),
                (
                    "requiere_temperatura",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo requiere registro de temperatura",
                        verbose_name="Requiere medición de temperatura",
                    ),
                ),
                (
                    "requiere_control_calidad",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este tipo requiere controles de calidad adicionales",
                        verbose_name="Requiere control de calidad",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Recepción",
                "verbose_name_plural": "Tipos de Recepción",
                "db_table": "production_ops_tipo_recepcion",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="production__codigo_6d1042_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="production__is_acti_cf3637_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="recepcion",
            name="tipo_recepcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recepciones",
                to="recepcion.tiporecepcion",
                verbose_name="Tipo de recepción",
            ),
        ),
        migrations.AddIndex(
            model_name="puntorecepcion",
            index=models.Index(
                fields=["empresa", "codigo"], name="production__empresa_7f5de5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntorecepcion",
            index=models.Index(
                fields=["empresa", "is_active"], name="production__empresa_9a6d85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallerecepcion",
            index=models.Index(
                fields=["recepcion"], name="production__recepci_679349_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallerecepcion",
            index=models.Index(
                fields=["tipo_materia_prima"], name="production__tipo_ma_3b1b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallerecepcion",
            index=models.Index(
                fields=["lote_asignado"], name="production__lote_as_0bf05c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlcalidadrecepcion",
            index=models.Index(
                fields=["recepcion"], name="production__recepci_844203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlcalidadrecepcion",
            index=models.Index(
                fields=["parametro"], name="production__paramet_2e247d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlcalidadrecepcion",
            index=models.Index(fields=["cumple"], name="production__cumple_a93387_idx"),
        ),
        migrations.AddIndex(
            model_name="controlcalidadrecepcion",
            index=models.Index(
                fields=["fecha_verificacion"], name="production__fecha_v_8c236d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["empresa", "codigo"], name="production__empresa_724db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["empresa", "fecha"], name="production__empresa_4fead3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["proveedor", "fecha"], name="production__proveed_431b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["estado"], name="production__estado__821c7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["programacion"], name="production__program_2614c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recepcion",
            index=models.Index(
                fields=["is_active"], name="production__is_acti_692416_idx"
            ),
        ),
    ]
