# Generated by Django 5.0.9 on 2026-03-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_prueba_acidez_from_supply_chain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pruebaacidez',
            index=models.Index(fields=['proveedor_id', '-fecha_prueba'], name='supply_chai_proveed_e84b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='pruebaacidez',
            index=models.Index(fields=['calidad_resultante', '-fecha_prueba'], name='supply_chai_calidad_de6ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='pruebaacidez',
            index=models.Index(fields=['codigo_voucher'], name='supply_chai_codigo__f6d6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pruebaacidez',
            index=models.Index(fields=['deleted_at'], name='supply_chai_deleted_0f7643_idx'),
        ),
    ]
