# Generated by Django 5.0.14 on 2026-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertaGenerada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("titulo", models.CharField(max_length=500)),
                ("mensaje", models.TextField()),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("danger", "Peligro"),
                            ("critical", "Crítico"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                ("esta_atendida", models.BooleanField(db_index=True, default=False)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("accion_tomada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Alerta Generada",
                "verbose_name_plural": "Alertas Generadas",
                "db_table": "alertas_alerta_generada",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "condicion",
                    models.JSONField(
                        help_text="Condición de activación en formato JSON"
                    ),
                ),
                (
                    "dias_anticipacion",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "frecuencia_verificacion",
                    models.CharField(
                        choices=[
                            ("cada_hora", "Cada Hora"),
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                        ],
                        default="diario",
                        max_length=20,
                    ),
                ),
                (
                    "notificar_a",
                    models.CharField(
                        choices=[
                            ("responsable", "Responsable"),
                            ("jefe", "Jefe Inmediato"),
                            ("area", "Área"),
                            ("rol_especifico", "Rol Específico"),
                            ("usuarios_especificos", "Usuarios Específicos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("crear_tarea", models.BooleanField(default=False)),
                ("enviar_email", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración de Alerta",
                "verbose_name_plural": "Configuraciones de Alertas",
                "db_table": "alertas_configuracion_alerta",
            },
        ),
        migrations.CreateModel(
            name="EscalamientoAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("nivel", models.PositiveIntegerField()),
                ("horas_espera", models.PositiveIntegerField()),
                (
                    "notificar_a",
                    models.CharField(
                        choices=[
                            ("jefe_inmediato", "Jefe Inmediato"),
                            ("gerente_area", "Gerente de Área"),
                            ("gerente_general", "Gerente General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("mensaje_escalamiento", models.TextField()),
            ],
            options={
                "verbose_name": "Escalamiento de Alerta",
                "verbose_name_plural": "Escalamientos de Alertas",
                "db_table": "alertas_escalamiento_alerta",
                "ordering": ["configuracion_alerta", "nivel"],
            },
        ),
        migrations.CreateModel(
            name="TipoAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("vencimiento", "Vencimiento"),
                            ("umbral", "Umbral"),
                            ("evento", "Evento"),
                            ("inactividad", "Inactividad"),
                            ("cumplimiento", "Cumplimiento"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severidad_default",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("danger", "Peligro"),
                            ("critical", "Crítico"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("modulo_origen", models.CharField(max_length=100)),
                (
                    "modelo_origen",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Alerta",
                "verbose_name_plural": "Tipos de Alerta",
                "db_table": "alertas_tipo_alerta",
            },
        ),
    ]
