# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config_alertas", "0001_initial"),
        ("configuracion", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertagenerada",
            name="atendida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_atendidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertagenerada",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="configuraciones_alerta", to="core.cargo"
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="configuraciones_alerta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertagenerada",
            name="configuracion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas_generadas",
                to="config_alertas.configuracionalerta",
            ),
        ),
        migrations.AddField(
            model_name="escalamientoalerta",
            name="configuracion_alerta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalamientos",
                to="config_alertas.configuracionalerta",
            ),
        ),
        migrations.AddField(
            model_name="escalamientoalerta",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="escalamientoalerta",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="escalamientoalerta",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="escalamientoalerta",
            name="usuarios_adicionales",
            field=models.ManyToManyField(
                blank=True,
                related_name="escalamientos_alerta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tipoalerta",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="tipoalerta",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="tipoalerta",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionalerta",
            name="tipo_alerta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuraciones",
                to="config_alertas.tipoalerta",
            ),
        ),
    ]
