# Generated by Django 5.0.9 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_industrial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepp',
            name='cargo_id_ref',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID del cargo en core.Cargo al momento de la entrega', null=True, verbose_name='Cargo (referencia)'),
        ),
        migrations.AddField(
            model_name='entregaepp',
            name='cargo_nombre',
            field=models.CharField(blank=True, help_text='Nombre del cargo (cache para display sin join)', max_length=200, verbose_name='Cargo (nombre)'),
        ),
    ]
