# Generated by Django 5.0.9 on 2025-12-14 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        help_text="Declaración de misión de la organización",
                        verbose_name="Misión",
                    ),
                ),
                (
                    "vision",
                    models.TextField(
                        help_text="Declaración de visión de la organización",
                        verbose_name="Visión",
                    ),
                ),
                (
                    "integral_policy",
                    models.TextField(
                        help_text="Política integral del sistema de gestión (Calidad, SST, Ambiental)",
                        verbose_name="Política Integral",
                    ),
                ),
                (
                    "policy_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la firma digital",
                        null=True,
                        verbose_name="Fecha de firma",
                    ),
                ),
                (
                    "policy_signature_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 de la firma digital",
                        max_length=255,
                        null=True,
                        verbose_name="Hash de firma",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Fecha desde la cual esta identidad está vigente",
                        verbose_name="Fecha de vigencia",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Versión del documento (ej: 1.0, 2.1)",
                        max_length=20,
                        verbose_name="Versión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Solo una identidad puede estar activa",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identities_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "policy_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que firmó digitalmente la política",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_signed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identidad Corporativa",
                "verbose_name_plural": "Identidades Corporativas",
                "db_table": "identidad_corporate_identity",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="CorporateValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del valor (ej: Integridad, Compromiso)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del valor",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono de Lucide (ej: Heart, Shield)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de aparición", verbose_name="Orden"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="identidad.corporateidentity",
                        verbose_name="Identidad Corporativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor Corporativo",
                "verbose_name_plural": "Valores Corporativos",
                "db_table": "identidad_corporate_value",
                "ordering": ["order", "name"],
            },
        ),
    ]
