# Generated by Django 5.0.9 on 2026-02-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identidad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliticaEspecifica',
        ),
    ]
