# Generated by Django 5.0.9 on 2026-01-24 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identidad", "0002_add_procesos_cubiertos_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporateidentity",
            name="integral_policy",
        ),
        migrations.RemoveField(
            model_name="corporateidentity",
            name="policy_signature_hash",
        ),
        migrations.RemoveField(
            model_name="corporateidentity",
            name="policy_signed_at",
        ),
        migrations.RemoveField(
            model_name="corporateidentity",
            name="policy_signed_by",
        ),
    ]
