# Generated by Django 5.0.9 on 2026-01-09 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_add_icon_registry'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_add_review_date_to_politica_integral'),
        ('identidad', '0002_valores_vividos'),
        ('organizacion', '0003_add_review_date_to_politica_integral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Documento')),
                ('frecuencia', models.CharField(choices=[('ANUAL', 'Anual - 12 meses'), ('SEMESTRAL', 'Semestral - 6 meses'), ('TRIMESTRAL', 'Trimestral - 3 meses'), ('BIANUAL', 'Bianual - 24 meses'), ('PERSONALIZADO', 'Personalizado')], db_index=True, default='ANUAL', max_length=20, verbose_name='Frecuencia de Revisión')),
                ('dias_personalizados', models.PositiveIntegerField(blank=True, help_text='Número de días para frecuencia personalizada', null=True, verbose_name='Días (Personalizado)')),
                ('tipo_revision', models.CharField(choices=[('RENOVACION', 'Renovación'), ('NUEVA_VERSION', 'Nueva Versión'), ('REVISION_MAYOR', 'Revisión Mayor')], default='RENOVACION', help_text='Si crea nueva versión o solo renueva vigencia', max_length=20, verbose_name='Tipo de Revisión')),
                ('auto_renovar', models.BooleanField(default=False, help_text='Renovar automáticamente si no hay cambios', verbose_name='Auto-renovar')),
                ('alertas_dias_previos', models.JSONField(default=list, help_text='Lista de días antes del vencimiento para enviar alertas. Ej: [30, 15, 7]', verbose_name='Alertas (días previos)')),
                ('alertar_creador', models.BooleanField(default=True, verbose_name='Alertar a Creador')),
                ('alertar_responsable', models.BooleanField(default=True, verbose_name='Alertar a Responsable')),
                ('ultima_revision', models.DateField(blank=True, db_index=True, null=True, verbose_name='Última Revisión')),
                ('proxima_revision', models.DateField(db_index=True, help_text='Fecha programada para la próxima revisión', verbose_name='Próxima Revisión')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('PROXIMO_VENCIMIENTO', 'Próximo a Vencer'), ('VENCIDA', 'Vencida'), ('EN_REVISION', 'En Revisión')], db_index=True, default='VIGENTE', max_length=30, verbose_name='Estado')),
                ('habilitado', models.BooleanField(default=True, help_text='Si la revisión periódica está activa', verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Configuración de Revisión',
                'verbose_name_plural': 'Configuraciones de Revisión',
                'db_table': 'identidad_configuracion_revision',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionWorkflowFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Workflow Política SST, Workflow Política Calidad)', max_length=100, unique=True, verbose_name='Nombre del Workflow')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_politica', models.CharField(blank=True, db_index=True, help_text='Tipo de política (INTEGRAL, ESPECIFICA, etc.)', max_length=50, null=True, verbose_name='Tipo de Política')),
                ('tipo_orden', models.CharField(choices=[('SECUENCIAL', 'Secuencial'), ('PARALELO', 'Paralelo')], default='SECUENCIAL', max_length=20, verbose_name='Tipo de Orden')),
                ('dias_para_firmar', models.PositiveSmallIntegerField(default=5, help_text='Días máximos para completar la firma', verbose_name='Días para Firmar')),
                ('permitir_delegacion', models.BooleanField(default=True, verbose_name='Permitir Delegación')),
                ('roles_config', models.JSONField(default=list, help_text='\n        Lista de roles de firma con configuración:\n        [\n            {\n                "rol": "ELABORO",\n                "nombre": "Elaboró",\n                "orden": 1,\n                "obligatorio": true,\n                "cargo_id": null,\n                "usuario_id": null\n            },\n            ...\n        ]\n        ', verbose_name='Configuración de Roles')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de Workflow de Firma',
                'verbose_name_plural': 'Configuraciones de Workflow de Firma',
                'db_table': 'identidad_config_workflow_firma',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Documento')),
                ('rol_firma', models.CharField(choices=[('ELABORO', 'Elaboró'), ('REVISO', 'Revisó'), ('APROBO', 'Aprobó'), ('VALIDO', 'Validó'), ('AUTORIZO', 'Autorizó')], db_index=True, help_text='Rol del firmante (Elaboró, Revisó, Aprobó)', max_length=20, verbose_name='Rol en la Firma')),
                ('orden_firma', models.PositiveSmallIntegerField(default=1, help_text='Orden en que debe firmar (1=primero). 0 si es paralelo', verbose_name='Orden de Firma')),
                ('firma_manuscrita', models.TextField(blank=True, help_text='Firma en formato base64 (canvas signature)', null=True, verbose_name='Firma Manuscrita')),
                ('firma_hash', models.CharField(db_index=True, help_text='Hash de verificación de integridad', max_length=64, unique=True, verbose_name='Hash SHA-256')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FIRMADO', 'Firmado'), ('RECHAZADO', 'Rechazado'), ('DELEGADO', 'Delegado'), ('VENCIDO', 'Vencido')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_firma', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Firma')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite para firmar', null=True, verbose_name='Fecha de Vencimiento')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios del firmante', null=True, verbose_name='Observaciones')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón del rechazo (si aplica)', null=True, verbose_name='Motivo de Rechazo')),
                ('fecha_delegacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Delegación')),
                ('motivo_delegacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Delegación')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se firmó', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador', null=True, verbose_name='Navegador')),
                ('geolocation', models.JSONField(blank=True, default=dict, help_text='Coordenadas GPS si están disponibles', verbose_name='Geolocalización')),
            ],
            options={
                'verbose_name': 'Firma Digital',
                'verbose_name_plural': 'Firmas Digitales',
                'db_table': 'identidad_firma_digital',
                'ordering': ['orden_firma', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Documento')),
                ('version_numero', models.CharField(db_index=True, help_text='Versión semántica (ej: 1.0, 1.1, 2.0)', max_length=20, verbose_name='Número de Versión')),
                ('version_anterior', models.CharField(blank=True, help_text='Número de la versión anterior', max_length=20, null=True, verbose_name='Versión Anterior')),
                ('snapshot_data', models.JSONField(help_text='Copia completa de los datos de la política en esta versión', verbose_name='Snapshot de Datos')),
                ('tipo_cambio', models.CharField(db_index=True, help_text='Tipo de cambio realizado (CREACION, MODIFICACION, REVISION, RENOVACION, etc.)', max_length=50, verbose_name='Tipo de Cambio')),
                ('descripcion_cambio', models.TextField(help_text='Descripción detallada de los cambios realizados', verbose_name='Descripción del Cambio')),
                ('cambios_diff', models.JSONField(blank=True, default=dict, help_text='Diff detallado de cambios campo por campo', verbose_name='Diferencias')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador')),
                ('version_hash', models.CharField(db_index=True, help_text='Hash SHA-256 del snapshot', max_length=64, unique=True, verbose_name='Hash de Versión')),
            ],
            options={
                'verbose_name': 'Historial de Versión',
                'verbose_name_plural': 'Historiales de Versiones',
                'db_table': 'identidad_historial_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracionmetricavalor',
            options={'verbose_name': 'Configuración de Métrica de Valor', 'verbose_name_plural': 'Configuraciones de Métricas de Valores'},
        ),
        migrations.AlterModelOptions(
            name='valorvivido',
            options={'ordering': ['-fecha_vinculacion', '-created_at'], 'verbose_name': 'Valor Vivido', 'verbose_name_plural': 'Valores Vividos'},
        ),
        migrations.RemoveConstraint(
            model_name='valorvivido',
            name='unique_valor_accion_active',
        ),
        migrations.RemoveIndex(
            model_name='valorvivido',
            name='valor_vivido_val_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='valorvivido',
            name='valor_vivido_fecha_imp_idx',
        ),
        migrations.RemoveIndex(
            model_name='valorvivido',
            name='valor_vivido_verif_act_idx',
        ),
        migrations.RenameIndex(
            model_name='valorvivido',
            new_name='valor_vivido_content_idx',
            old_name='valor_vivido_ct_obj_idx',
        ),
        migrations.AlterUniqueTogether(
            name='configuracionmetricavalor',
            unique_together={('empresa',)},
        ),
        migrations.AddField(
            model_name='politicaintegral',
            name='review_date',
            field=models.DateField(blank=True, help_text='Próxima fecha de revisión programada', null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='acciones_minimas_mensual',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad mínima de acciones esperadas por valor por mes', verbose_name='Acciones Mínimas por Mes'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='alertar_valores_bajos',
            field=models.BooleanField(default=True, help_text='Enviar alertas cuando un valor tiene pocas acciones', verbose_name='Alertar Valores Bajos'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='categorias_prioritarias',
            field=models.JSONField(default=list, help_text='Lista de categorías de acciones que tienen mayor peso', verbose_name='Categorías Prioritarias'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_valores', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='meses_analisis',
            field=models.PositiveSmallIntegerField(default=12, help_text='Cantidad de meses a considerar para tendencias', verbose_name='Meses de Análisis'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='pesos_tipo_vinculo',
            field=models.JSONField(default=dict, help_text='Multiplicadores por tipo de vínculo (ej: {"REFLEJA": 1.0, "PROMUEVE": 0.8})', verbose_name='Pesos por Tipo de Vínculo'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='puntaje_minimo_promedio',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Puntaje promedio mínimo esperado (1-10)', max_digits=4, verbose_name='Puntaje Mínimo Promedio'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='umbral_alerta_acciones',
            field=models.PositiveIntegerField(default=3, help_text='Enviar alerta si un valor tiene menos de N acciones en el mes', verbose_name='Umbral de Alerta (acciones)'),
        ),
        migrations.AlterField(
            model_name='configuracionmetricavalor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='valores_vividos/evidencias/%Y/%m/', verbose_name='Archivo de Evidencia'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área responsable de la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_vividos', to='organizacion.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='categoria_accion',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto'), ('OBJETIVO', 'Objetivo Estratégico'), ('INICIATIVA', 'Iniciativa'), ('ACCION_CORRECTIVA', 'Acción Correctiva'), ('ACCION_PREVENTIVA', 'Acción Preventiva'), ('ACCION_MEJORA', 'Acción de Mejora'), ('OPORTUNIDAD_MEJORA', 'Oportunidad de Mejora'), ('GESTION_CAMBIO', 'Gestión del Cambio'), ('INVESTIGACION_INCIDENTE', 'Investigación de Incidente'), ('INSPECCION', 'Inspección'), ('HALLAZGO_AUDITORIA', 'Hallazgo de Auditoría'), ('NO_CONFORMIDAD', 'No Conformidad'), ('ACCION_PESV', 'Acción PESV'), ('OTRO', 'Otro')], db_index=True, default='OTRO', help_text='Categoría de la acción vinculada para reportes', max_length=30, verbose_name='Categoría de Acción'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='content_type',
            field=models.ForeignKey(help_text='Modelo de la acción vinculada (Proyecto, AccionCorrectiva, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Acción'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='evidencia',
            field=models.TextField(blank=True, help_text='Descripción de la evidencia que soporta el vínculo', null=True, verbose_name='Evidencia'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='fecha_vinculacion',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha en que se realizó la vinculación', verbose_name='Fecha de Vinculación'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='impacto',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('MUY_ALTO', 'Muy Alto')], db_index=True, default='MEDIO', help_text='Qué tan significativo es el impacto en el valor', max_length=20, verbose_name='Nivel de Impacto'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='justificacion',
            field=models.TextField(help_text='Por qué esta acción refleja/promueve este valor', verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales para reportes (título acción, código, etc.)', verbose_name='Metadatos'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID de la Acción'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='puntaje',
            field=models.PositiveSmallIntegerField(default=1, help_text='Puntaje de 1-10 para cálculos de BI', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='tipo_vinculo',
            field=models.CharField(choices=[('REFLEJA', 'Refleja el valor'), ('PROMUEVE', 'Promueve el valor'), ('RESULTADO', 'Resultado del valor'), ('MEJORA', 'Mejora el valor')], default='REFLEJA', help_text='Cómo se relaciona la acción con el valor', max_length=20, verbose_name='Tipo de Vínculo'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Si el vínculo ha sido verificado por un supervisor', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='valorvivido',
            name='vinculado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_vinculados', to=settings.AUTH_USER_MODEL, verbose_name='Vinculado por'),
        ),
        migrations.AlterUniqueTogether(
            name='valorvivido',
            unique_together={('valor', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='valorvivido',
            index=models.Index(fields=['valor', 'fecha_vinculacion'], name='valor_vivido_valor_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='valorvivido',
            index=models.Index(fields=['categoria_accion', 'impacto'], name='valor_vivido_cat_imp_idx'),
        ),
        migrations.AddIndex(
            model_name='valorvivido',
            index=models.Index(fields=['area', 'fecha_vinculacion'], name='valor_vivido_area_fecha_idx'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='cargo_responsable',
            field=models.ForeignKey(blank=True, help_text='Cargo responsable de la revisión (si no hay persona asignada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cargo', to='core.cargo', verbose_name='Cargo Responsable'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='destinatarios_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Usuarios adicionales que recibirán alertas', related_name='revisiones_alertas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios Adicionales'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='responsable_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Revisión'),
        ),
        migrations.AddField(
            model_name='configuracionrevision',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='configuracionworkflowfirma',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='configuracionworkflowfirma',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='cargo',
            field=models.ForeignKey(blank=True, help_text='Cargo que tenía el firmante al momento de firmar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_cargo', to='core.cargo', verbose_name='Cargo al momento de firmar'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='content_type',
            field=models.ForeignKey(help_text='Tipo de documento firmado (PoliticaIntegral, PoliticaEspecifica, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='delegado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que delegó la firma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegaciones_otorgadas', to=settings.AUTH_USER_MODEL, verbose_name='Delegado por'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='firmante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_identidad', to=settings.AUTH_USER_MODEL, verbose_name='Firmante'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='historialversion',
            name='cargo_usuario',
            field=models.ForeignKey(blank=True, help_text='Cargo que tenía el usuario al momento del cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios_identidad', to='core.cargo', verbose_name='Cargo del Usuario'),
        ),
        migrations.AddField(
            model_name='historialversion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='historialversion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_politicas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RemoveField(
            model_name='configuracionmetricavalor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configuracionmetricavalor',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='configuracionmetricavalor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='configuracionmetricavalor',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='configuracionrevision',
            index=models.Index(fields=['content_type', 'object_id'], name='config_rev_content_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionrevision',
            index=models.Index(fields=['estado', 'proxima_revision'], name='config_rev_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionrevision',
            index=models.Index(fields=['habilitado', 'proxima_revision'], name='config_rev_habilitado_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionrevision',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='configuracionworkflowfirma',
            index=models.Index(fields=['tipo_politica', 'activo'], name='config_wf_tipo_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['content_type', 'object_id'], name='firma_content_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['firmante', 'status'], name='firma_firmante_status_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['status', 'fecha_vencimiento'], name='firma_vencimiento_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='firmadigital',
            unique_together={('content_type', 'object_id', 'firmante', 'rol_firma')},
        ),
        migrations.AddIndex(
            model_name='historialversion',
            index=models.Index(fields=['content_type', 'object_id', 'version_numero'], name='hist_ver_content_idx'),
        ),
        migrations.AddIndex(
            model_name='historialversion',
            index=models.Index(fields=['tipo_cambio', 'created_at'], name='hist_ver_tipo_fecha_idx'),
        ),
    ]
