# Generated by Django 5.0.9 on 2026-01-25 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("identidad", "0003_remove_legacy_policy_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmaPolitica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "rol_firma",
                    models.CharField(
                        choices=[
                            ("ELABORO", "Elaboró"),
                            ("REVISO", "Revisó"),
                            ("APROBO", "Aprobó"),
                        ],
                        max_length=20,
                        verbose_name="Rol de Firma",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden en el flujo secuencial (1=ELABORO, 2=REVISO, 3=APROBO)",
                        verbose_name="Orden de Firma",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("FIRMADO", "Firmado"),
                            ("RECHAZADO", "Rechazado"),
                            ("EXPIRADO", "Expirado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "firma_imagen",
                    models.TextField(
                        blank=True,
                        help_text="Imagen de la firma en formato Base64 desde canvas",
                        null=True,
                        verbose_name="Firma Imagen (Base64)",
                    ),
                ),
                (
                    "documento_hash",
                    models.CharField(
                        help_text="SHA-256 hash del contenido al momento de crear la firma",
                        max_length=64,
                        verbose_name="Hash del Documento",
                    ),
                ),
                (
                    "firma_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash de la firma completa para verificación",
                        max_length=64,
                        null=True,
                        verbose_name="Hash de la Firma",
                    ),
                ),
                (
                    "fecha_firma",
                    models.DateTimeField(
                        blank=True,
                        help_text="Se completa cuando el usuario firma",
                        null=True,
                        verbose_name="Fecha y Hora de Firma",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "comentarios",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del firmante o motivo de rechazo",
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firmas_politicas",
                        to="core.cargo",
                        verbose_name="Cargo Firmante",
                    ),
                ),
                (
                    "politica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmas",
                        to="identidad.politicaespecifica",
                        verbose_name="Política",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se completa cuando el usuario firma",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmas_politicas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Firmó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma de Política",
                "verbose_name_plural": "Firmas de Políticas",
                "db_table": "identidad_firma_politica",
                "ordering": ["orden", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["politica", "estado"], name="firma_pol_estado_idx"
                    ),
                    models.Index(
                        fields=["cargo", "estado"], name="firma_cargo_estado_idx"
                    ),
                ],
            },
        ),
    ]
