# Generated by Django 5.0.9 on 2026-01-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    # Permitir DDL fuera de transacción para MySQL
    atomic = False

    dependencies = [
        ("identidad", "0004_add_firma_politica_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politicaespecifica",
            name="status",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EN_GESTION", "En Gestión"),
                    ("VIGENTE", "Vigente"),
                    ("OBSOLETO", "Obsoleto"),
                ],
                db_index=True,
                default="BORRADOR",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        # Eliminar tabla de historial que tiene FK hacia FirmaPolitica
        migrations.RunSQL(
            sql=[
                "SET FOREIGN_KEY_CHECKS = 0;",
                "DROP TABLE IF EXISTS identidad_historial_firma_politica;",
                "SET FOREIGN_KEY_CHECKS = 1;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="FirmaPolitica",
        ),
    ]
