# Generated by Django 5.0.9 on 2026-01-10 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidad', '0004_corporateidentity_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateidentity',
            name='integral_policy',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Usar modelo PoliticaIntegral. Campo legacy para migración.', verbose_name='[DEPRECATED] Política Integral'),
        ),
        migrations.AlterField(
            model_name='corporateidentity',
            name='policy_signature_hash',
            field=models.CharField(blank=True, help_text='DEPRECATED: Usar PoliticaIntegral.signature_hash', max_length=255, null=True, verbose_name='[DEPRECATED] Hash de firma'),
        ),
        migrations.AlterField(
            model_name='corporateidentity',
            name='policy_signed_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Usar PoliticaIntegral.signed_at', null=True, verbose_name='[DEPRECATED] Fecha de firma'),
        ),
        migrations.AlterField(
            model_name='corporateidentity',
            name='policy_signed_by',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Usar PoliticaIntegral.signed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_signed', to=settings.AUTH_USER_MODEL, verbose_name='[DEPRECATED] Firmada por'),
        ),
    ]
