# Generated by Django 5.0.9 on 2026-01-17 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0006_empresaconfig_color_fondo_showcase_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0012_alter_brandingconfig_options_alter_menuitem_options_and_more"),
        ("identidad", "0011_add_alcance_sig_fields"),
        ("organizacion", "0003_add_review_date_to_politica_integral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="procesofirmapolitica",
            name="identidad_p_tipo_po_d454e4_idx",
        ),
        migrations.AddField(
            model_name="politicaespecifica",
            name="change_reason",
            field=models.TextField(
                blank=True,
                help_text="Razón del cambio respecto a la versión anterior",
                null=True,
                verbose_name="Motivo del Cambio",
            ),
        ),
        migrations.AddField(
            model_name="politicaespecifica",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que la política deja de estar vigente",
                null=True,
                verbose_name="Fecha de Vencimiento",
            ),
        ),
        migrations.AddField(
            model_name="politicaespecifica",
            name="is_integral_policy",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indica si es la política integral del sistema de gestión",
                verbose_name="Es Política Integral",
            ),
        ),
        migrations.AddField(
            model_name="politicaespecifica",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash SHA-256 de la firma digital",
                max_length=255,
                null=True,
                verbose_name="Hash de Firma",
            ),
        ),
        migrations.AlterField(
            model_name="corporateidentity",
            name="integral_policy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="DEPRECATED v3.1: Usar PoliticaEspecifica con is_integral_policy=True.",
                verbose_name="[DEPRECATED] Política Integral",
            ),
        ),
        migrations.AlterField(
            model_name="corporateidentity",
            name="policy_signature_hash",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED v3.1: Usar PoliticaEspecifica.signature_hash",
                max_length=255,
                null=True,
                verbose_name="[DEPRECATED] Hash de firma",
            ),
        ),
        migrations.AlterField(
            model_name="corporateidentity",
            name="policy_signed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="DEPRECATED v3.1: Usar PoliticaEspecifica.approved_at",
                null=True,
                verbose_name="[DEPRECATED] Fecha de firma",
            ),
        ),
        migrations.AlterField(
            model_name="corporateidentity",
            name="policy_signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED v3.1: Usar PoliticaEspecifica.approved_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies_signed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="[DEPRECATED] Firmada por",
            ),
        ),
        migrations.AlterField(
            model_name="firmadigital",
            name="content_type",
            field=models.ForeignKey(
                help_text="Tipo de documento firmado (PoliticaEspecifica, etc.)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="procesofirmapolitica",
            name="politica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procesos_firma",
                to="identidad.politicaespecifica",
                verbose_name="Política",
            ),
        ),
        migrations.AddIndex(
            model_name="politicaespecifica",
            index=models.Index(
                fields=["is_integral_policy", "status"],
                name="pol_esp_integral_status_idx",
            ),
        ),
    ]
