# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacenamiento", "0002_initial"),
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertastock",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alertas_stock",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
    ]
