# Generated by Django 5.0.9 on 2026-01-17 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almacenamiento", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alertastock",
            name="idx_alerta_emp_tipo",
        ),
        migrations.RemoveIndex(
            model_name="alertastock",
            name="idx_alerta_pend_fecha",
        ),
        migrations.RemoveIndex(
            model_name="configuracionstock",
            name="idx_confstock_emp_alm",
        ),
        migrations.RemoveIndex(
            model_name="inventario",
            name="idx_inv_alm_prod_estado",
        ),
        migrations.RemoveIndex(
            model_name="inventario",
            name="idx_inv_tipo_alm_estado",
        ),
        migrations.RemoveIndex(
            model_name="inventario",
            name="idx_inv_venc_estado",
        ),
        migrations.RemoveIndex(
            model_name="movimientoinventario",
            name="idx_mov_kardex",
        ),
        migrations.RemoveIndex(
            model_name="movimientoinventario",
            name="idx_mov_doc_fecha",
        ),
        migrations.RemoveIndex(
            model_name="movimientoinventario",
            name="idx_mov_emp_tipo_fecha",
        ),
    ]
