# Generated by Django 5.0.9 on 2025-12-29 04:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0007_alter_integracionexterna_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                            ("TI", "Tarjeta de Identidad"),
                        ],
                        default="CC",
                        max_length=10,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Número de documento"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono alternativo",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        max_length=100, verbose_name="Ciudad de residencia"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "nivel_educativo",
                    models.CharField(
                        choices=[
                            ("bachiller", "Bachiller"),
                            ("tecnico", "Técnico"),
                            ("tecnologo", "Tecnólogo"),
                            ("profesional", "Profesional"),
                            ("especializacion", "Especialización"),
                            ("maestria", "Maestría"),
                            ("doctorado", "Doctorado"),
                        ],
                        max_length=50,
                        verbose_name="Nivel educativo",
                    ),
                ),
                (
                    "titulo_obtenido",
                    models.CharField(
                        blank=True,
                        help_text="Título profesional o técnico obtenido",
                        max_length=200,
                        null=True,
                        verbose_name="Título obtenido",
                    ),
                ),
                (
                    "anos_experiencia",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Años de experiencia laboral total",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Años de experiencia",
                    ),
                ),
                (
                    "anos_experiencia_cargo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Años de experiencia específica en cargos similares",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Años de experiencia en el cargo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("postulado", "Postulado"),
                            ("preseleccionado", "Preseleccionado"),
                            ("en_evaluacion", "En Evaluación"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("contratado", "Contratado"),
                        ],
                        db_index=True,
                        default="postulado",
                        max_length=20,
                        verbose_name="Estado en el proceso",
                    ),
                ),
                (
                    "origen_postulacion",
                    models.CharField(
                        choices=[
                            ("portal_empleo", "Portal de empleo"),
                            ("referido", "Referido"),
                            ("redes_sociales", "Redes sociales"),
                            ("base_datos", "Base de datos"),
                            ("agencia", "Agencia de empleo"),
                            ("universidad", "Universidad"),
                            ("otro", "Otro"),
                        ],
                        default="portal_empleo",
                        max_length=30,
                        verbose_name="Origen de postulación",
                    ),
                ),
                (
                    "fecha_postulacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de postulación",
                    ),
                ),
                (
                    "fecha_ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización de estado"
                    ),
                ),
                (
                    "hoja_vida",
                    models.FileField(
                        help_text="Archivo PDF o Word con la hoja de vida",
                        upload_to="talent_hub/candidatos/hojas_vida/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Hoja de vida (CV)",
                    ),
                ),
                (
                    "carta_presentacion",
                    models.FileField(
                        blank=True,
                        help_text="Carta de presentación (opcional)",
                        null=True,
                        upload_to="talent_hub/candidatos/cartas/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Carta de presentación",
                    ),
                ),
                (
                    "pretension_salarial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pretensión salarial del candidato (COP)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Pretensión salarial",
                    ),
                ),
                (
                    "fecha_disponibilidad",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la cual puede iniciar labores",
                        null=True,
                        verbose_name="Fecha de disponibilidad",
                    ),
                ),
                (
                    "requiere_reubicacion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el candidato requiere reubicarse para el cargo",
                        verbose_name="Requiere reubicación",
                    ),
                ),
                (
                    "disponibilidad_viajes",
                    models.BooleanField(
                        default=False, verbose_name="Disponibilidad para viajar"
                    ),
                ),
                (
                    "referido_por",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la persona que refirió al candidato",
                        max_length=200,
                        null=True,
                        verbose_name="Referido por",
                    ),
                ),
                (
                    "calificacion_general",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calificación general del proceso (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "fortalezas",
                    models.TextField(
                        blank=True,
                        help_text="Fortalezas principales del candidato",
                        null=True,
                        verbose_name="Fortalezas identificadas",
                    ),
                ),
                (
                    "debilidades",
                    models.TextField(
                        blank=True,
                        help_text="Aspectos a mejorar o debilidades",
                        null=True,
                        verbose_name="Debilidades identificadas",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del proceso de selección",
                        null=True,
                        verbose_name="Observaciones generales",
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True,
                        help_text="Razón por la cual se rechazó al candidato",
                        null=True,
                        verbose_name="Motivo de rechazo",
                    ),
                ),
                (
                    "fecha_contratacion",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en la que fue contratado el candidato",
                        null=True,
                        verbose_name="Fecha de contratación",
                    ),
                ),
                (
                    "salario_ofrecido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salario ofrecido al momento de contratación (COP)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salario ofrecido",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidato",
                "verbose_name_plural": "Candidatos",
                "db_table": "talent_hub_candidato",
                "ordering": ["-fecha_postulacion"],
            },
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo de contrato (ej: INDEFINIDO, FIJO, OBRA)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del tipo de contrato",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción y características del tipo de contrato",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "requiere_duracion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si requiere especificar duración (término fijo, obra/labor)",
                        verbose_name="Requiere duración",
                    ),
                ),
                (
                    "requiere_objeto",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si requiere especificar objeto del contrato (obra/labor, servicios)",
                        verbose_name="Requiere objeto contractual",
                    ),
                ),
                (
                    "color_badge",
                    models.CharField(
                        default="blue",
                        help_text="Color para mostrar en el frontend (blue, green, yellow, red, gray)",
                        max_length=20,
                        verbose_name="Color del badge",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "db_table": "talent_hub_tipo_contrato",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="talent_hub__codigo_7dc07e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="talent_hub__is_acti_1c5093_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TipoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único (EPS, ARL, AFP, CCF)",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del tipo de entidad",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "es_obligatorio",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la afiliación a este tipo de entidad es obligatoria",
                        verbose_name="Es obligatorio",
                    ),
                ),
                (
                    "color_badge",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Color del badge"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Entidad",
                "verbose_name_plural": "Tipos de Entidad",
                "db_table": "talent_hub_tipo_entidad",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="talent_hub__codigo_42ff9e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="talent_hub__is_acti_23476d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntidadSeguridadSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la entidad",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre comercial de la entidad",
                        max_length=150,
                        verbose_name="Nombre comercial",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón social"),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="NIT de la entidad", max_length=20, verbose_name="NIT"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio web"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidades",
                        to="seleccion_contratacion.tipoentidad",
                        verbose_name="Tipo de entidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad de Seguridad Social",
                "verbose_name_plural": "Entidades de Seguridad Social",
                "db_table": "talent_hub_entidad_seguridad_social",
                "ordering": ["tipo_entidad__orden", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo de prueba",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del tipo de prueba",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_calificacion",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la prueba tiene una calificación numérica (ej: 0-100)",
                        verbose_name="Permite calificación numérica",
                    ),
                ),
                (
                    "requiere_archivo",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se requiere adjuntar archivo de resultado",
                        verbose_name="Requiere adjuntar archivo",
                    ),
                ),
                (
                    "duracion_estimada_minutos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración estimada de la prueba en minutos",
                        null=True,
                        verbose_name="Duración estimada (minutos)",
                    ),
                ),
                (
                    "color_badge",
                    models.CharField(
                        default="purple", max_length=20, verbose_name="Color del badge"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Prueba",
                "verbose_name_plural": "Tipos de Prueba",
                "db_table": "talent_hub_tipo_prueba",
                "ordering": ["orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="talent_hub__codigo_82d13c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="talent_hub__is_acti_a69a0c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(verbose_name="Fecha y hora programada"),
                ),
                (
                    "fecha_realizacion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y hora de realización",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Lugar donde se realizará la prueba",
                        max_length=200,
                        null=True,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "proveedor_externo",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la empresa o institución que aplica la prueba",
                        max_length=200,
                        null=True,
                        verbose_name="Proveedor externo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("realizada", "Realizada"),
                            ("calificada", "Calificada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="programada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calificación obtenida (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        blank=True,
                        help_text="Indica si el candidato aprobó la prueba",
                        null=True,
                        verbose_name="Aprobado",
                    ),
                ),
                (
                    "puntaje_minimo_aprobacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Puntaje mínimo requerido para aprobar",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Puntaje mínimo de aprobación",
                    ),
                ),
                (
                    "archivo_prueba",
                    models.FileField(
                        blank=True,
                        help_text="Archivo con la prueba o plantilla",
                        null=True,
                        upload_to="talent_hub/pruebas/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "xlsx", "jpg", "png"]
                            )
                        ],
                        verbose_name="Archivo de la prueba",
                    ),
                ),
                (
                    "archivo_resultado",
                    models.FileField(
                        blank=True,
                        help_text="Archivo con los resultados de la prueba",
                        null=True,
                        upload_to="talent_hub/pruebas/resultados/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "xlsx", "jpg", "png"]
                            )
                        ],
                        verbose_name="Archivo de resultado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones sobre la prueba o resultados",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones derivadas de los resultados",
                        null=True,
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de cancelación"
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo de aplicación de la prueba (COP)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Costo",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruebas",
                        to="seleccion_contratacion.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Usuario responsable de coordinar la prueba",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pruebas_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "tipo_prueba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pruebas",
                        to="seleccion_contratacion.tipoprueba",
                        verbose_name="Tipo de prueba",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba",
                "verbose_name_plural": "Pruebas",
                "db_table": "talent_hub_prueba",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="VacanteActiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo_vacante",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la vacante (ej: VAC-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código de vacante",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título descriptivo de la posición",
                        max_length=200,
                        verbose_name="Título de la vacante",
                    ),
                ),
                (
                    "cargo_requerido",
                    models.CharField(
                        help_text="Nombre del cargo a cubrir",
                        max_length=200,
                        verbose_name="Cargo requerido",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        help_text="Área o departamento donde se encuentra la vacante",
                        max_length=100,
                        verbose_name="Área",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción completa de la posición y responsabilidades",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "requisitos_minimos",
                    models.TextField(
                        help_text="Requisitos mínimos indispensables (educación, experiencia, certificaciones)",
                        verbose_name="Requisitos mínimos",
                    ),
                ),
                (
                    "requisitos_deseables",
                    models.TextField(
                        blank=True,
                        help_text="Requisitos deseables pero no excluyentes",
                        null=True,
                        verbose_name="Requisitos deseables",
                    ),
                ),
                (
                    "funciones_principales",
                    models.TextField(
                        help_text="Principales funciones y responsabilidades del cargo",
                        verbose_name="Funciones principales",
                    ),
                ),
                (
                    "competencias_requeridas",
                    models.TextField(
                        blank=True,
                        help_text="Competencias técnicas y blandas requeridas",
                        null=True,
                        verbose_name="Competencias requeridas",
                    ),
                ),
                (
                    "salario_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salario mínimo ofrecido (COP)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salario mínimo",
                    ),
                ),
                (
                    "salario_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salario máximo ofrecido (COP)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salario máximo",
                    ),
                ),
                (
                    "salario_oculto",
                    models.BooleanField(
                        default=False,
                        help_text="No mostrar el salario en la publicación externa",
                        verbose_name="Salario oculto en publicación",
                    ),
                ),
                (
                    "beneficios",
                    models.TextField(
                        blank=True,
                        help_text="Beneficios adicionales al salario",
                        null=True,
                        verbose_name="Beneficios adicionales",
                    ),
                ),
                (
                    "horario",
                    models.CharField(
                        help_text="Horario de trabajo (ej: Lun-Vie 8:00-17:00)",
                        max_length=200,
                        verbose_name="Horario",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("hibrido", "Híbrido"),
                            ("remoto", "Remoto"),
                        ],
                        default="presencial",
                        max_length=20,
                        verbose_name="Modalidad de trabajo",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Ubicación física del trabajo (ciudad, dirección)",
                        max_length=200,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "numero_posiciones",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cantidad de personas a contratar para esta vacante",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de posiciones",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_proceso", "En Proceso"),
                            ("cerrada", "Cerrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="abierta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de apertura",
                    ),
                ),
                (
                    "fecha_cierre_esperada",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada para cerrar el proceso",
                        null=True,
                        verbose_name="Fecha de cierre esperada",
                    ),
                ),
                (
                    "fecha_cierre_real",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en la que efectivamente se cerró la vacante",
                        null=True,
                        verbose_name="Fecha de cierre real",
                    ),
                ),
                (
                    "publicada_externamente",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la vacante está publicada en portales externos",
                        verbose_name="Publicada externamente",
                    ),
                ),
                (
                    "url_publicacion",
                    models.URLField(
                        blank=True,
                        help_text="URL de la publicación externa si aplica",
                        null=True,
                        verbose_name="URL de publicación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones internas del proceso",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "motivo_cierre",
                    models.TextField(
                        blank=True,
                        help_text="Motivo del cierre o cancelación de la vacante",
                        null=True,
                        verbose_name="Motivo de cierre",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "reclutador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario asignado para el reclutamiento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacantes_reclutamiento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reclutador asignado",
                    ),
                ),
                (
                    "responsable_proceso",
                    models.ForeignKey(
                        help_text="Usuario responsable de gestionar el proceso de selección",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacantes_activas_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del proceso",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacantes",
                        to="seleccion_contratacion.tipocontrato",
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacante Activa",
                "verbose_name_plural": "Vacantes Activas",
                "db_table": "talent_hub_vacante_activa",
                "ordering": ["-fecha_apertura", "-prioridad"],
            },
        ),
        migrations.AddField(
            model_name="candidato",
            name="vacante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidatos",
                to="seleccion_contratacion.vacanteactiva",
                verbose_name="Vacante",
            ),
        ),
        migrations.CreateModel(
            name="AfiliacionSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de solicitud",
                    ),
                ),
                (
                    "fecha_afiliacion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de afiliación efectiva",
                    ),
                ),
                (
                    "numero_afiliacion",
                    models.CharField(
                        blank=True,
                        help_text="Número de afiliado o carnet",
                        max_length=50,
                        null=True,
                        verbose_name="Número de afiliación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En proceso"),
                            ("afiliado", "Afiliado"),
                            ("rechazado", "Rechazado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado de la afiliación",
                    ),
                ),
                (
                    "documento_afiliacion",
                    models.FileField(
                        blank=True,
                        help_text="Certificado o documento que acredita la afiliación",
                        null=True,
                        upload_to="talent_hub/afiliaciones/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "png"]
                            )
                        ],
                        verbose_name="Documento de afiliación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del proceso de afiliación",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True,
                        help_text="Razón por la cual se rechazó la afiliación",
                        null=True,
                        verbose_name="Motivo de rechazo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsable_tramite",
                    models.ForeignKey(
                        help_text="Usuario responsable de gestionar la afiliación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="afiliaciones_gestionadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del trámite",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        help_text="Candidato al que se le gestionan las afiliaciones",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afiliaciones_ss",
                        to="seleccion_contratacion.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="afiliaciones",
                        to="seleccion_contratacion.entidadseguridadsocial",
                        verbose_name="Entidad de seguridad social",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afiliación a Seguridad Social",
                "verbose_name_plural": "Afiliaciones a Seguridad Social",
                "db_table": "talent_hub_afiliacion_ss",
                "ordering": ["-fecha_solicitud"],
                "indexes": [
                    models.Index(
                        fields=["candidato", "entidad"],
                        name="talent_hub__candida_b16d6c_idx",
                    ),
                    models.Index(
                        fields=["estado", "is_active"],
                        name="talent_hub__estado_5948ea_idx",
                    ),
                    models.Index(
                        fields=["fecha_solicitud"],
                        name="talent_hub__fecha_s_41a146_idx",
                    ),
                    models.Index(
                        fields=["empresa", "estado"],
                        name="talent_hub__empresa_33f3f0_idx",
                    ),
                ],
                "unique_together": {("candidato", "entidad")},
            },
        ),
        migrations.CreateModel(
            name="Entrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "numero_entrevista",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número secuencial de la entrevista para este candidato",
                        verbose_name="Número de entrevista",
                    ),
                ),
                (
                    "tipo_entrevista",
                    models.CharField(
                        choices=[
                            ("telefonica", "Telefónica"),
                            ("presencial", "Presencial"),
                            ("virtual", "Virtual"),
                            ("grupal", "Grupal"),
                            ("panel", "Panel"),
                        ],
                        default="presencial",
                        max_length=20,
                        verbose_name="Tipo de entrevista",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(verbose_name="Fecha y hora programada"),
                ),
                (
                    "duracion_estimada_minutos",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(15)],
                        verbose_name="Duración estimada (minutos)",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Dirección física o enlace de videollamada",
                        max_length=200,
                        null=True,
                        verbose_name="Ubicación o enlace",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("reprogramada", "Reprogramada"),
                        ],
                        db_index=True,
                        default="programada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_realizacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que efectivamente se realizó la entrevista",
                        null=True,
                        verbose_name="Fecha y hora de realización",
                    ),
                ),
                (
                    "duracion_real_minutos",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duración real (minutos)",
                    ),
                ),
                (
                    "asistio_candidato",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el candidato asistió a la entrevista",
                        verbose_name="Candidato asistió",
                    ),
                ),
                (
                    "calificacion_tecnica",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Evaluación de conocimientos técnicos",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Calificación técnica (0-100)",
                    ),
                ),
                (
                    "calificacion_competencias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Evaluación de competencias blandas y actitudinales",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Calificación competencias (0-100)",
                    ),
                ),
                (
                    "calificacion_general",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calificación global de la entrevista",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Calificación general (0-100)",
                    ),
                ),
                (
                    "fortalezas_identificadas",
                    models.TextField(
                        blank=True,
                        help_text="Principales fortalezas observadas durante la entrevista",
                        null=True,
                        verbose_name="Fortalezas identificadas",
                    ),
                ),
                (
                    "aspectos_mejorar",
                    models.TextField(
                        blank=True,
                        help_text="Aspectos que el candidato debe mejorar",
                        null=True,
                        verbose_name="Aspectos a mejorar",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones generales de la entrevista",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "recomendacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contratar", "Recomendado para contratar"),
                            ("segunda_entrevista", "Segunda entrevista"),
                            ("rechazar", "No recomendado"),
                            ("pendiente", "Decisión pendiente"),
                        ],
                        help_text="Recomendación del entrevistador",
                        max_length=20,
                        null=True,
                        verbose_name="Recomendación",
                    ),
                ),
                (
                    "notas_entrevista",
                    models.FileField(
                        blank=True,
                        help_text="Archivo con notas detalladas de la entrevista",
                        null=True,
                        upload_to="talent_hub/entrevistas/notas/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Notas de la entrevista",
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(
                        blank=True,
                        help_text="Razón de la cancelación o reprogramación",
                        null=True,
                        verbose_name="Motivo de cancelación",
                    ),
                ),
                (
                    "fecha_reprogramada",
                    models.DateTimeField(
                        blank=True,
                        help_text="Nueva fecha si fue reprogramada",
                        null=True,
                        verbose_name="Fecha reprogramada",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrevistas",
                        to="seleccion_contratacion.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "entrevistador_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrevistas_principal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrevistador principal",
                    ),
                ),
                (
                    "entrevistadores_adicionales",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Otros entrevistadores participantes (para entrevistas panel)",
                        related_name="entrevistas_adicionales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrevistadores adicionales",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrevista",
                "verbose_name_plural": "Entrevistas",
                "db_table": "talent_hub_entrevista",
                "ordering": ["-fecha_programada"],
                "indexes": [
                    models.Index(
                        fields=["candidato", "estado"],
                        name="talent_hub__candida_b45b76_idx",
                    ),
                    models.Index(
                        fields=["fecha_programada"],
                        name="talent_hub__fecha_p_200dac_idx",
                    ),
                    models.Index(
                        fields=["entrevistador_principal"],
                        name="talent_hub__entrevi_89f96b_idx",
                    ),
                    models.Index(
                        fields=["estado", "is_active"],
                        name="talent_hub__estado_b9c9c6_idx",
                    ),
                    models.Index(
                        fields=["empresa", "fecha_programada"],
                        name="talent_hub__empresa_257e58_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entidadseguridadsocial",
            index=models.Index(fields=["codigo"], name="talent_hub__codigo_a4c921_idx"),
        ),
        migrations.AddIndex(
            model_name="entidadseguridadsocial",
            index=models.Index(fields=["nit"], name="talent_hub__nit_b00191_idx"),
        ),
        migrations.AddIndex(
            model_name="entidadseguridadsocial",
            index=models.Index(
                fields=["tipo_entidad", "is_active"],
                name="talent_hub__tipo_en_22ad0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prueba",
            index=models.Index(
                fields=["candidato", "estado"], name="talent_hub__candida_cb9680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prueba",
            index=models.Index(
                fields=["tipo_prueba"], name="talent_hub__tipo_pr_b7ed19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prueba",
            index=models.Index(
                fields=["fecha_programada"], name="talent_hub__fecha_p_e85c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prueba",
            index=models.Index(
                fields=["estado", "is_active"], name="talent_hub__estado_8a3418_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prueba",
            index=models.Index(
                fields=["empresa", "tipo_prueba"], name="talent_hub__empresa_97c516_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacanteactiva",
            index=models.Index(
                fields=["codigo_vacante"], name="talent_hub__codigo__13ce19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacanteactiva",
            index=models.Index(
                fields=["estado", "is_active"], name="talent_hub__estado_d949ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacanteactiva",
            index=models.Index(
                fields=["fecha_apertura"], name="talent_hub__fecha_a_d67c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacanteactiva",
            index=models.Index(
                fields=["empresa", "estado"], name="talent_hub__empresa_7e79e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacanteactiva",
            index=models.Index(
                fields=["responsable_proceso"], name="talent_hub__respons_143f20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["vacante", "estado"], name="talent_hub__vacante_d49a9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["numero_documento"], name="talent_hub__numero__f16607_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(fields=["email"], name="talent_hub__email_14effc_idx"),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["estado", "is_active"], name="talent_hub__estado_20925f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["fecha_postulacion"], name="talent_hub__fecha_p_7413a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["empresa", "vacante"], name="talent_hub__empresa_3c9b20_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidato",
            unique_together={("vacante", "numero_documento")},
        ),
    ]
