# Generated by Django 5.0.9 on 2026-02-13 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_initial'),
        ('seleccion_contratacion', '0002_historial_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPruebaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('token', models.CharField(db_index=True, help_text='Token único para acceso público sin autenticación', max_length=64, unique=True, verbose_name='Token de Acceso')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('calificada', 'Calificada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Si se pasa esta fecha, la prueba queda vencida', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Momento en que el candidato abrió la prueba', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('respuestas', models.JSONField(blank=True, default=dict, help_text='Respuestas del candidato: {nombre_campo: valor}', verbose_name='Respuestas')),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje Obtenido')),
                ('puntaje_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje Máximo')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje (%)')),
                ('aprobado', models.BooleanField(blank=True, null=True, verbose_name='Aprobado')),
                ('detalle_calificacion', models.JSONField(blank=True, default=dict, help_text='Detalle por pregunta: {nombre_campo: {correcto, puntaje, respuesta_correcta, respuesta_candidato}}', verbose_name='Detalle de Calificación')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Candidato')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
            ],
            options={
                'verbose_name': 'Asignación de Prueba Dinámica',
                'verbose_name_plural': 'Asignaciones de Pruebas Dinámicas',
                'db_table': 'seleccion_asignacion_prueba_dinamica',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPruebaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(help_text='Ej: Prueba de Conducción Preventiva, Test Excel Avanzado', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Instrucciones generales para el candidato', verbose_name='Descripción')),
                ('instrucciones', models.TextField(blank=True, default='', help_text='Instrucciones detalladas que verá el candidato antes de iniciar', verbose_name='Instrucciones')),
                ('campos', models.JSONField(default=list, help_text='Array de campos con estructura CampoFormulario: [{nombre_campo, etiqueta, tipo_campo, opciones, es_obligatorio, respuesta_correcta, puntaje, orden, ...}]', verbose_name='Campos del Formulario')),
                ('scoring_config', models.JSONField(blank=True, default=dict, help_text='Configuración de calificación automática: {puntaje_maximo, puntaje_aprobacion, penalizar_incorrectas}', verbose_name='Configuración de Scoring')),
                ('tipo_scoring', models.CharField(choices=[('manual', 'Calificación Manual'), ('automatico', 'Scoring Automático'), ('mixto', 'Mixto (Auto + Manual)')], default='manual', max_length=15, verbose_name='Tipo de Scoring')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(default=30, help_text='Tiempo estimado para completar la prueba', verbose_name='Duración Estimada (minutos)')),
                ('tiempo_limite_minutos', models.PositiveIntegerField(blank=True, help_text='Tiempo máximo (si se aplica). Null = sin límite.', null=True, verbose_name='Tiempo Límite (minutos)')),
                ('categoria', models.CharField(blank=True, default='', help_text='Ej: Técnica, Conocimiento, Habilidad, Conducción, SST', max_length=100, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Las plantillas inactivas no pueden asignarse', verbose_name='Activa')),
                ('total_asignaciones', models.PositiveIntegerField(default=0, help_text='Contador de veces que se ha asignado esta plantilla', verbose_name='Total Asignaciones')),
            ],
            options={
                'verbose_name': 'Plantilla de Prueba Dinámica',
                'verbose_name_plural': 'Plantillas de Pruebas Dinámicas',
                'db_table': 'seleccion_plantilla_prueba_dinamica',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='historialcontrato',
            new_name='talent_hub__empresa_abe16c_idx',
            old_name='th_hist_cont_emp_col_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcontrato',
            new_name='talent_hub__fecha_i_3b9031_idx',
            old_name='th_hist_cont_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcontrato',
            new_name='talent_hub__tipo_mo_ea34c4_idx',
            old_name='th_hist_cont_tipo_mov_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcontrato',
            new_name='talent_hub__numero__629e02_idx',
            old_name='th_hist_cont_num_idx',
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='historialcontrato',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_dinamicas', to='seleccion_contratacion.candidato', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='vacante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_dinamicas', to='seleccion_contratacion.vacanteactiva', verbose_name='Vacante'),
        ),
        migrations.AddField(
            model_name='plantillapruebadinamica',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_prueba_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='plantillapruebadinamica',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='plantillapruebadinamica',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignacionpruebadinamica',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='seleccion_contratacion.plantillapruebadinamica', verbose_name='Plantilla'),
        ),
        migrations.AddIndex(
            model_name='plantillapruebadinamica',
            index=models.Index(fields=['empresa', 'is_active'], name='seleccion_p_empresa_b1e28c_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillapruebadinamica',
            index=models.Index(fields=['empresa', 'categoria'], name='seleccion_p_empresa_17716a_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionpruebadinamica',
            index=models.Index(fields=['empresa', 'estado'], name='seleccion_a_empresa_f497be_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionpruebadinamica',
            index=models.Index(fields=['candidato', 'estado'], name='seleccion_a_candida_6e4daf_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionpruebadinamica',
            index=models.Index(fields=['token'], name='seleccion_a_token_f49a2b_idx'),
        ),
    ]
