# Generated by Django 5.0.9 on 2026-02-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_empresaconfig_options_and_more'),
        ('seleccion_contratacion', '0004_add_entrevista_asincronica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entrevistaasincronica',
            new_name='talent_hub__candida_b32fc1_idx',
            old_name='talent_hub__candidat_async_idx',
        ),
        migrations.RenameIndex(
            model_name='entrevistaasincronica',
            new_name='talent_hub__token_a2db28_idx',
            old_name='talent_hub__token_async_idx',
        ),
        migrations.RenameIndex(
            model_name='entrevistaasincronica',
            new_name='talent_hub__estado_cfc834_idx',
            old_name='talent_hub__estado_async_idx',
        ),
        migrations.RenameIndex(
            model_name='entrevistaasincronica',
            new_name='talent_hub__empresa_4fca89_idx',
            old_name='talent_hub__empresa_async_idx',
        ),
        migrations.RenameIndex(
            model_name='entrevistaasincronica',
            new_name='talent_hub__fecha_v_f90a51_idx',
            old_name='talent_hub__venci_async_idx',
        ),
        migrations.AddField(
            model_name='entrevistaasincronica',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='entrevistaasincronica',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
