# Generated by Django 5.0.9 on 2026-02-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reorder_talent_hub_sidebar'),
        ('seleccion_contratacion', '0005_rename_talent_hub__candidat_async_idx_talent_hub__candida_b32fc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanteactiva',
            name='cargo',
            field=models.ForeignKey(blank=True, help_text='Cargo del organigrama asociado a la vacante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacantes_activas', to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='vacanteactiva',
            name='posiciones_cubiertas',
            field=models.PositiveIntegerField(default=0, help_text='Número de posiciones ya cubiertas por contratación', verbose_name='Posiciones cubiertas'),
        ),
        migrations.AlterField(
            model_name='vacanteactiva',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Área organizacional (auto-poblada desde cargo.area)', max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='vacanteactiva',
            name='cargo_requerido',
            field=models.CharField(blank=True, default='', help_text='Nombre del cargo (auto-poblado desde FK cargo)', max_length=200, verbose_name='Cargo requerido'),
        ),
    ]
