# Generated by Django 5.0.14 on 2026-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared_library", "0002_add_tipo_plantilla_campos_formulario"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliotecaplantilla",
            name="firmantes_por_defecto",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON: [{"rol_firma": "ELABORO", "cargo_code": "COORD_HSEQ", "orden": 1, "es_requerido": true}]',
                verbose_name="Firmantes por Defecto",
            ),
        ),
    ]
