# Generated by Django 5.0.14 on 2026-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogoKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del indicador (ej: SST-001, FIN-002)",
                        max_length=50,
                        verbose_name="Código KPI",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del indicador",
                        max_length=255,
                        verbose_name="Nombre del KPI",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del indicador",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "tipo_indicador",
                    models.CharField(
                        choices=[
                            ("eficiencia", "Eficiencia"),
                            ("eficacia", "Eficacia"),
                            ("efectividad", "Efectividad"),
                        ],
                        help_text="Clasificación según su propósito",
                        max_length=20,
                        verbose_name="Tipo de Indicador",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sst", "SST - Seguridad y Salud en el Trabajo"),
                            ("pesv", "PESV - Plan Estratégico de Seguridad Vial"),
                            ("ambiental", "Ambiental"),
                            ("calidad", "Calidad"),
                            ("financiero", "Financiero"),
                            ("operacional", "Operacional"),
                            ("rrhh", "Recursos Humanos"),
                            ("comercial", "Comercial"),
                        ],
                        help_text="Área o módulo al que pertenece",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "frecuencia_medicion",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("quincenal", "Quincenal"),
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        help_text="Con qué frecuencia se debe medir",
                        max_length=20,
                        verbose_name="Frecuencia de Medición",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        help_text="Unidad en que se expresa (%, $, unidades, días, etc.)",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "es_mayor_mejor",
                    models.BooleanField(
                        default=True,
                        help_text="True si valores altos son positivos, False si valores bajos son mejores",
                        verbose_name="¿Mayor es Mejor?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo KPI",
                "verbose_name_plural": "Catálogo de KPIs",
                "db_table": "analytics_catalogo_kpi",
                "ordering": ["categoria", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionSemaforo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "umbral_rojo_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor mínimo del rango rojo (null = sin límite inferior)",
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral Rojo Mínimo",
                    ),
                ),
                (
                    "umbral_rojo_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor máximo del rango rojo (null = sin límite superior)",
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral Rojo Máximo",
                    ),
                ),
                (
                    "umbral_amarillo_min",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor mínimo del rango amarillo",
                        max_digits=15,
                        verbose_name="Umbral Amarillo Mínimo",
                    ),
                ),
                (
                    "umbral_amarillo_max",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor máximo del rango amarillo",
                        max_digits=15,
                        verbose_name="Umbral Amarillo Máximo",
                    ),
                ),
                (
                    "umbral_verde_min",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor mínimo del rango verde",
                        max_digits=15,
                        verbose_name="Umbral Verde Mínimo",
                    ),
                ),
                (
                    "umbral_verde_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor máximo del rango verde (null = sin límite superior)",
                        max_digits=15,
                        null=True,
                        verbose_name="Umbral Verde Máximo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Semáforo",
                "verbose_name_plural": "Configuraciones de Semáforos",
                "db_table": "analytics_configuracion_semaforo",
                "ordering": ["kpi"],
            },
        ),
        migrations.CreateModel(
            name="FichaTecnicaKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        help_text="Qué se busca medir y por qué es importante",
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        help_text="Fórmula matemática para calcular el indicador",
                        verbose_name="Fórmula",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Definición de cada variable de la fórmula (JSON dict)",
                        verbose_name="Variables",
                    ),
                ),
                (
                    "fuente_datos",
                    models.TextField(
                        help_text="De dónde se obtienen los datos para el cálculo",
                        verbose_name="Fuente de Datos",
                    ),
                ),
                (
                    "fecha_inicio_medicion",
                    models.DateField(
                        help_text="Desde cuándo se empezó a medir este indicador",
                        verbose_name="Fecha Inicio Medición",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Información adicional relevante",
                        verbose_name="Notas Adicionales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Técnica KPI",
                "verbose_name_plural": "Fichas Técnicas de KPIs",
                "db_table": "analytics_ficha_tecnica_kpi",
                "ordering": ["kpi"],
            },
        ),
        migrations.CreateModel(
            name="MetaKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del período de la meta",
                        verbose_name="Inicio del Período",
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        help_text="Fecha de finalización del período de la meta",
                        verbose_name="Fin del Período",
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor objetivo principal a alcanzar",
                        max_digits=15,
                        verbose_name="Valor Meta",
                    ),
                ),
                (
                    "valor_minimo_aceptable",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor mínimo aceptable (umbral crítico)",
                        max_digits=15,
                        verbose_name="Mínimo Aceptable",
                    ),
                ),
                (
                    "valor_satisfactorio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor que se considera satisfactorio",
                        max_digits=15,
                        verbose_name="Valor Satisfactorio",
                    ),
                ),
                (
                    "valor_sobresaliente",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor excepcional (supera expectativas)",
                        max_digits=15,
                        verbose_name="Valor Sobresaliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta KPI",
                "verbose_name_plural": "Metas de KPIs",
                "db_table": "analytics_meta_kpi",
                "ordering": ["kpi", "-periodo_inicio"],
            },
        ),
    ]
