# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("config_indicadores", "0001_initial"),
        ("configuracion", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogokpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="catalogokpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="catalogokpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsemaforo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsemaforo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsemaforo",
            name="kpi",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuracion_semaforo",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsemaforo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="kpi",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ficha_tecnica",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="responsable_analisis",
            field=models.ForeignKey(
                help_text="Cargo responsable de analizar resultados y tomar acciones",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kpis_analizar",
                to="core.cargo",
                verbose_name="Responsable de Análisis",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="responsable_medicion",
            field=models.ForeignKey(
                help_text="Cargo responsable de recopilar y registrar los datos",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kpis_medir",
                to="core.cargo",
                verbose_name="Responsable de Medición",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicakpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="metakpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="metakpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="metakpi",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metas",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="metakpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogokpi",
            index=models.Index(
                fields=["empresa", "categoria"], name="analytics_c_empresa_1a5889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogokpi",
            index=models.Index(
                fields=["empresa", "tipo_indicador"],
                name="analytics_c_empresa_2d7484_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogokpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_c_empresa_6421b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalogokpi",
            unique_together={("empresa", "codigo")},
        ),
        migrations.AddIndex(
            model_name="metakpi",
            index=models.Index(
                fields=["empresa", "kpi"], name="analytics_m_empresa_f32326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metakpi",
            index=models.Index(
                fields=["periodo_inicio", "periodo_fin"],
                name="analytics_m_periodo_098b2b_idx",
            ),
        ),
    ]
