# Generated by Django 5.0.14 on 2026-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_indicadores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogokpi',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del indicador (ej: SST-001, FIN-002)', max_length=50, verbose_name='Código KPI'),
        ),
    ]
