# Generated by Django 5.0.14 on 2026-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formacion_reinduccion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacitacion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único de la capacitación (ej: CAP-2025-001)",
                max_length=20,
                verbose_name="Código de Capacitación",
            ),
        ),
        migrations.AlterField(
            model_name="planformacion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código único del plan (ej: PF-2025)",
                max_length=20,
                verbose_name="Código del Plan",
            ),
        ),
    ]
