# Generated by Django 5.0.9 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_remove_legacy_fields'),
        ('formacion_reinduccion', '0003_gamelevel_gamequizquestion_gameprogress_gamesession'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamelevel',
            name='formacion_gamelevel_empresa_codigo_uniq',
        ),
        migrations.RemoveIndex(
            model_name='gamelevel',
            name='formacion_r_gamelevel_emp_act_cre',
        ),
        migrations.RemoveIndex(
            model_name='gamelevel',
            name='formacion_r_gamelevel_emp_upd',
        ),
        migrations.RemoveIndex(
            model_name='gamelevel',
            name='formacion_r_gamelevel_emp_del',
        ),
        migrations.RemoveIndex(
            model_name='gameprogress',
            name='formacion_r_gameprog_emp_act_cre',
        ),
        migrations.RemoveIndex(
            model_name='gameprogress',
            name='formacion_r_gameprog_emp_upd',
        ),
        migrations.RemoveIndex(
            model_name='gameprogress',
            name='formacion_r_gameprog_emp_del',
        ),
        migrations.RemoveIndex(
            model_name='gamequizquestion',
            name='formacion_r_gamequizq_emp_act_cre',
        ),
        migrations.RemoveIndex(
            model_name='gamequizquestion',
            name='formacion_r_gamequizq_emp_upd',
        ),
        migrations.RemoveIndex(
            model_name='gamequizquestion',
            name='formacion_r_gamequizq_emp_del',
        ),
        migrations.RemoveIndex(
            model_name='gamesession',
            name='formacion_r_gamesess_emp_act_cre',
        ),
        migrations.RemoveIndex(
            model_name='gamesession',
            name='formacion_r_gamesess_emp_upd',
        ),
        migrations.RemoveIndex(
            model_name='gamesession',
            name='formacion_r_gamesess_emp_del',
        ),
        migrations.RenameIndex(
            model_name='gamelevel',
            new_name='talent_hub__empresa_344964_idx',
            old_name='formacion_gamelevel_emp_zona',
        ),
        migrations.RenameIndex(
            model_name='gamelevel',
            new_name='talent_hub__numero__d6129b_idx',
            old_name='formacion_gamelevel_num_nivel',
        ),
        migrations.RenameIndex(
            model_name='gamequizquestion',
            new_name='talent_hub__nivel_i_3b2d0c_idx',
            old_name='formacion_gamequiz_nivel_cat',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='talent_hub__colabor_6312bd_idx',
            old_name='formacion_gamesession_col_fecha',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='talent_hub__nivel_i_e3da39_idx',
            old_name='formacion_gamesession_niv_comp',
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='gamequizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='gamequizquestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='gamequizquestion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gamequizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización'),
        ),
        migrations.AlterUniqueTogether(
            name='gamelevel',
            unique_together={('empresa', 'codigo')},
        ),
    ]
