# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoReglamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_aprobacion_legal",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Aprobación Legal"
                    ),
                ),
                (
                    "vigencia_anios",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Vigencia (años)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Reglamento",
                "verbose_name_plural": "Tipos de Reglamento",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Reglamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (menor número = primero)",
                        verbose_name="Orden",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En Revision"),
                            ("aprobado", "Aprobado"),
                            ("vigente", "Vigente"),
                            ("obsoleto", "Obsoleto"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "version_actual",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versión Actual"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "fecha_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vigencia"
                    ),
                ),
                (
                    "fecha_proxima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Revisión"
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reglamentos/documentos/",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "aplica_sst",
                    models.BooleanField(default=False, verbose_name="Aplica a SST"),
                ),
                (
                    "aplica_ambiental",
                    models.BooleanField(
                        default=False, verbose_name="Aplica a Ambiental"
                    ),
                ),
                (
                    "aplica_calidad",
                    models.BooleanField(default=False, verbose_name="Aplica a Calidad"),
                ),
                (
                    "aplica_pesv",
                    models.BooleanField(default=False, verbose_name="Aplica a PESV"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglamentos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado Por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglamentos",
                        to="reglamentos_internos.tiporeglamento",
                        verbose_name="Tipo de Reglamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reglamento Interno",
                "verbose_name_plural": "Reglamentos Internos",
                "ordering": ["empresa", "orden", "tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="VersionReglamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "numero_version",
                    models.CharField(max_length=20, verbose_name="Número de Versión"),
                ),
                ("fecha_version", models.DateField(verbose_name="Fecha de Versión")),
                (
                    "cambios_realizados",
                    models.TextField(verbose_name="Cambios Realizados"),
                ),
                (
                    "motivo_cambio",
                    models.TextField(blank=True, verbose_name="Motivo del Cambio"),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reglamentos/versiones/",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado Por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "elaborado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_elaboradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Elaborado Por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "reglamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="reglamentos_internos.reglamento",
                        verbose_name="Reglamento",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_revisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado Por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de Reglamento",
                "verbose_name_plural": "Versiones de Reglamentos",
                "ordering": ["-fecha_version"],
            },
        ),
        migrations.CreateModel(
            name="PublicacionReglamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "version_publicada",
                    models.CharField(max_length=20, verbose_name="Versión Publicada"),
                ),
                (
                    "fecha_publicacion",
                    models.DateField(verbose_name="Fecha de Publicación"),
                ),
                (
                    "medio",
                    models.CharField(
                        choices=[
                            ("cartelera", "Cartelera"),
                            ("email", "Correo Electrónico"),
                            ("intranet", "Intranet"),
                            ("reunion", "Reunión"),
                            ("impreso", "Documento Impreso"),
                        ],
                        max_length=15,
                        verbose_name="Medio de Publicación",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "evidencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reglamentos/publicaciones/",
                        verbose_name="Evidencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "publicado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publicado Por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "reglamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicaciones",
                        to="reglamentos_internos.reglamento",
                        verbose_name="Reglamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicación de Reglamento",
                "verbose_name_plural": "Publicaciones de Reglamentos",
                "ordering": ["-fecha_publicacion"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "reglamento"],
                        name="reglamentos_empresa_4563f3_idx",
                    ),
                    models.Index(
                        fields=["empresa", "fecha_publicacion"],
                        name="reglamentos_empresa_958a21_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocializacionReglamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("induccion", "Inducción"),
                            ("reinduccion", "Reinducción"),
                            ("capacitacion", "Capacitación"),
                            ("reunion", "Reunión"),
                            ("virtual", "Virtual"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Socialización",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "duracion_horas",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Duración (horas)",
                    ),
                ),
                (
                    "numero_asistentes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Número de Asistentes"
                    ),
                ),
                (
                    "temas_tratados",
                    models.TextField(blank=True, verbose_name="Temas Tratados"),
                ),
                (
                    "lista_asistencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reglamentos/socializaciones/",
                        verbose_name="Lista de Asistencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "facilitador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="socializaciones_facilitadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Facilitador",
                    ),
                ),
                (
                    "reglamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socializaciones",
                        to="reglamentos_internos.reglamento",
                        verbose_name="Reglamento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socialización de Reglamento",
                "verbose_name_plural": "Socializaciones de Reglamentos",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "reglamento"],
                        name="reglamentos_empresa_5aa990_idx",
                    ),
                    models.Index(
                        fields=["empresa", "fecha"],
                        name="reglamentos_empresa_a6e627_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reglamento",
            index=models.Index(
                fields=["empresa", "estado"], name="reglamentos_empresa_456148_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reglamento",
            index=models.Index(fields=["estado"], name="reglamentos_estado_95d384_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reglamento",
            unique_together={("empresa", "tipo", "codigo")},
        ),
        migrations.AddIndex(
            model_name="versionreglamento",
            index=models.Index(
                fields=["empresa", "reglamento"], name="reglamentos_empresa_bcf6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionreglamento",
            index=models.Index(
                fields=["empresa", "fecha_version"],
                name="reglamentos_empresa_ff37ee_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="versionreglamento",
            unique_together={("reglamento", "numero_version")},
        ),
    ]
