# Generated by Django 5.0.9 on 2025-12-28 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0006_sedeempresa_updated_by_and_more"),
        ("reglamentos_internos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicacionreglamento",
            options={
                "ordering": ["-fecha_publicacion"],
                "verbose_name": "Publicación de Reglamento",
                "verbose_name_plural": "Publicaciones de Reglamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="reglamento",
            options={
                "ordering": ["empresa", "orden", "tipo", "nombre"],
                "verbose_name": "Reglamento Interno",
                "verbose_name_plural": "Reglamentos Internos",
            },
        ),
        migrations.AlterModelOptions(
            name="socializacionreglamento",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Socialización de Reglamento",
                "verbose_name_plural": "Socializaciones de Reglamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="tiporeglamento",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Tipo de Reglamento",
                "verbose_name_plural": "Tipos de Reglamento",
            },
        ),
        migrations.AlterModelOptions(
            name="versionreglamento",
            options={
                "ordering": ["-fecha_version"],
                "verbose_name": "Versión de Reglamento",
                "verbose_name_plural": "Versiones de Reglamentos",
            },
        ),
        migrations.RemoveIndex(
            model_name="reglamento",
            name="reglamentos_empresa_456148_idx",
        ),
        migrations.AlterUniqueTogether(
            name="reglamento",
            unique_together={("empresa", "tipo", "codigo")},
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                help_text="Empresa a la que pertenece este registro",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AddField(
            model_name="publicacionreglamento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="reglamento",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="reglamento",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                help_text="Empresa a la que pertenece este registro",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="reglamento",
            name="orden",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Orden de visualización (menor número = primero)",
                verbose_name="Orden",
            ),
        ),
        migrations.AddField(
            model_name="reglamento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="socializacionreglamento",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="socializacionreglamento",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                help_text="Empresa a la que pertenece este registro",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="socializacionreglamento",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="socializacionreglamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AddField(
            model_name="socializacionreglamento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="tiporeglamento",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="tiporeglamento",
            name="orden",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Orden de visualización (menor número = primero)",
                verbose_name="Orden",
            ),
        ),
        migrations.AddField(
            model_name="tiporeglamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                null=True,
                verbose_name="Fecha de Eliminación",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                help_text="Empresa a la que pertenece este registro",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AddField(
            model_name="versionreglamento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="evidencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reglamentos/publicaciones/",
                verbose_name="Evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="fecha_publicacion",
            field=models.DateField(verbose_name="Fecha de Publicación"),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="medio",
            field=models.CharField(
                choices=[
                    ("cartelera", "Cartelera"),
                    ("email", "Correo Electrónico"),
                    ("intranet", "Intranet"),
                    ("reunion", "Reunión"),
                    ("impreso", "Documento Impreso"),
                ],
                max_length=15,
                verbose_name="Medio de Publicación",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="publicado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicaciones_realizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Publicado Por",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="reglamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publicaciones",
                to="reglamentos_internos.reglamento",
                verbose_name="Reglamento",
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="ubicacion",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="publicacionreglamento",
            name="version_publicada",
            field=models.CharField(max_length=20, verbose_name="Versión Publicada"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="aplica_ambiental",
            field=models.BooleanField(default=False, verbose_name="Aplica a Ambiental"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="aplica_calidad",
            field=models.BooleanField(default=False, verbose_name="Aplica a Calidad"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="aplica_pesv",
            field=models.BooleanField(default=False, verbose_name="Aplica a PESV"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="aplica_sst",
            field=models.BooleanField(default=False, verbose_name="Aplica a SST"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reglamentos_aprobados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado Por",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="codigo",
            field=models.CharField(max_length=50, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reglamentos/documentos/",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("en_revision", "En Revision"),
                    ("aprobado", "Aprobado"),
                    ("vigente", "Vigente"),
                    ("obsoleto", "Obsoleto"),
                ],
                db_index=True,
                default="borrador",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="fecha_aprobacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Aprobación"
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="fecha_proxima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Próxima Revisión"
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="fecha_vigencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Vigencia"
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reglamentos",
                to="reglamentos_internos.tiporeglamento",
                verbose_name="Tipo de Reglamento",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Fecha y hora de la última actualización (automático)",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="reglamento",
            name="version_actual",
            field=models.CharField(
                default="1.0", max_length=20, verbose_name="Versión Actual"
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="duracion_horas",
            field=models.DecimalField(
                decimal_places=1,
                default=1.0,
                max_digits=4,
                verbose_name="Duración (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="facilitador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socializaciones_facilitadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Facilitador",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="fecha",
            field=models.DateField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="lista_asistencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reglamentos/socializaciones/",
                verbose_name="Lista de Asistencia",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="numero_asistentes",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Número de Asistentes"
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="reglamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socializaciones",
                to="reglamentos_internos.reglamento",
                verbose_name="Reglamento",
            ),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="temas_tratados",
            field=models.TextField(blank=True, verbose_name="Temas Tratados"),
        ),
        migrations.AlterField(
            model_name="socializacionreglamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("induccion", "Inducción"),
                    ("reinduccion", "Reinducción"),
                    ("capacitacion", "Capacitación"),
                    ("reunion", "Reunión"),
                    ("virtual", "Virtual"),
                ],
                max_length=15,
                verbose_name="Tipo de Socialización",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="codigo",
            field=models.CharField(max_length=20, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="requiere_aprobacion_legal",
            field=models.BooleanField(
                default=False, verbose_name="Requiere Aprobación Legal"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeglamento",
            name="vigencia_anios",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Vigencia (años)"
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_aprobadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado Por",
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="cambios_realizados",
            field=models.TextField(verbose_name="Cambios Realizados"),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Fecha y hora de creación del registro (automático)",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reglamentos/versiones/",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="elaborado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_elaboradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Elaborado Por",
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="fecha_aprobacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Aprobación"
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="fecha_version",
            field=models.DateField(verbose_name="Fecha de Versión"),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="motivo_cambio",
            field=models.TextField(blank=True, verbose_name="Motivo del Cambio"),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="numero_version",
            field=models.CharField(max_length=20, verbose_name="Número de Versión"),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="reglamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versiones",
                to="reglamentos_internos.reglamento",
                verbose_name="Reglamento",
            ),
        ),
        migrations.AlterField(
            model_name="versionreglamento",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_revisadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado Por",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacionreglamento",
            index=models.Index(
                fields=["empresa", "reglamento"], name="reglamentos_empresa_4563f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicacionreglamento",
            index=models.Index(
                fields=["empresa", "fecha_publicacion"],
                name="reglamentos_empresa_958a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reglamento",
            index=models.Index(
                fields=["empresa", "estado"], name="reglamentos_empresa_456148_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reglamento",
            index=models.Index(fields=["estado"], name="reglamentos_estado_95d384_idx"),
        ),
        migrations.AddIndex(
            model_name="socializacionreglamento",
            index=models.Index(
                fields=["empresa", "reglamento"], name="reglamentos_empresa_5aa990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socializacionreglamento",
            index=models.Index(
                fields=["empresa", "fecha"], name="reglamentos_empresa_a6e627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionreglamento",
            index=models.Index(
                fields=["empresa", "reglamento"], name="reglamentos_empresa_bcf6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionreglamento",
            index=models.Index(
                fields=["empresa", "fecha_version"],
                name="reglamentos_empresa_ff37ee_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="reglamento",
            name="empresa_id",
        ),
    ]
