# Generated by Django 5.0.9 on 2025-12-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0017_add_origen_proveedor_externo_standby"),
        ("recepciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="numero_certificado_peso",
            field=models.CharField(
                blank=True,
                help_text="Número del certificado de la báscula externa",
                max_length=50,
                null=True,
                verbose_name="Número de certificado de peso",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="origen_recepcion",
            field=models.CharField(
                choices=[
                    ("UNIDAD_INTERNA", "Unidad Interna (Econorte)"),
                    ("PROVEEDOR_EXTERNO", "Proveedor Externo"),
                ],
                db_index=True,
                default="UNIDAD_INTERNA",
                help_text="Origen del material: Unidad Interna (Econorte) o Proveedor Externo",
                max_length=20,
                verbose_name="Origen de recepción",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="peso_externo_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso certificado por báscula externa (solo PROVEEDOR_EXTERNO)",
                max_digits=10,
                null=True,
                verbose_name="Peso externo certificado (kg)",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="proveedor_externo",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor externo que entrega el material (solo PROVEEDOR_EXTERNO)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recepciones_proveedor",
                to="proveedores.proveedor",
                verbose_name="Proveedor Externo",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="prueba_acidez",
            field=models.ForeignKey(
                blank=True,
                help_text="Prueba de acidez asociada (solo para ACU y SEBO_PROCESADO)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recepciones",
                to="proveedores.pruebaacidez",
                verbose_name="Prueba de Acidez",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="tipo_materia_prima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HUESO_CRUDO", "Hueso Crudo"),
                    ("HUESO_SECO", "Hueso Seco"),
                    ("HUESO_CALCINADO", "Hueso Calcinado"),
                    ("HUESO_CENIZA", "Hueso Ceniza"),
                    ("SEBO_CRUDO_CARNICERIA", "Sebo Crudo Carnicería"),
                    ("SEBO_CRUDO_MATADERO", "Sebo Crudo Matadero"),
                    ("SEBO_CUERO", "Sebo de Cuero"),
                    ("SEBO_CUERO_VIRIL", "Sebo de Cuero de Viril"),
                    ("SEBO_POLLO", "Sebo Pollo"),
                    ("SEBO_PROCESADO_A", "Sebo Procesado Tipo A (1-5% Acidez)"),
                    ("SEBO_PROCESADO_B", "Sebo Procesado Tipo B (5.1-8% Acidez)"),
                    ("SEBO_PROCESADO_B1", "Sebo Procesado Tipo B1 (8.1-10% Acidez)"),
                    ("SEBO_PROCESADO_B2", "Sebo Procesado Tipo B2 (10.1-15% Acidez)"),
                    ("SEBO_PROCESADO_B4", "Sebo Procesado Tipo B4 (15.1-20% Acidez)"),
                    ("SEBO_PROCESADO_C", "Sebo Procesado Tipo C (>20.1% Acidez)"),
                    ("CHICHARRON", "Chicharrón"),
                    ("CABEZAS", "Cabezas"),
                    ("ACU", "ACU - Aceite de Cocina Usado"),
                ],
                help_text="Código específico de materia prima (solo para PROVEEDOR_EXTERNO o si aplica)",
                max_length=25,
                null=True,
                verbose_name="Tipo de materia prima",
            ),
        ),
        migrations.AddField(
            model_name="recepcionmateriaprima",
            name="usa_peso_externo",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el proveedor trae peso certificado de báscula externa",
                verbose_name="Usa peso externo",
            ),
        ),
        migrations.AlterField(
            model_name="recepcionmateriaprima",
            name="estado",
            field=models.CharField(
                choices=[
                    ("INICIADA", "Iniciada"),
                    ("PESADA", "Pesada"),
                    ("CONFIRMADA", "Confirmada"),
                    ("STANDBY", "En Espera"),
                    ("CANCELADA", "Cancelada"),
                ],
                db_index=True,
                default="INICIADA",
                help_text="Estado actual de la recepción",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="recepcionmateriaprima",
            name="peso_esperado_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Suma de todos los kg de las recolecciones incluidas (UNIDAD_INTERNA) o peso declarado (PROVEEDOR_EXTERNO)",
                max_digits=10,
                verbose_name="Peso esperado (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="recepcionmateriaprima",
            name="recolector",
            field=models.ForeignKey(
                blank=True,
                help_text="Recolector que entrega el material (solo UNIDAD_INTERNA)",
                limit_choices_to={
                    "cargo__code": "recolector_econorte",
                    "is_active": True,
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recepciones_entregadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recolector",
            ),
        ),
        migrations.AddIndex(
            model_name="recepcionmateriaprima",
            index=models.Index(
                fields=["origen_recepcion", "estado"],
                name="recepciones_origen__9da5fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recepcionmateriaprima",
            index=models.Index(
                fields=["proveedor_externo", "fecha_recepcion"],
                name="recepciones_proveed_6d4b78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recepcionmateriaprima",
            index=models.Index(
                fields=["tipo_materia_prima"], name="recepciones_tipo_ma_10b7da_idx"
            ),
        ),
    ]
