# Generated by Django 5.0.9 on 2026-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del almacén (ej: ALM-001)",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del almacén",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es el almacén principal",
                        verbose_name="Es principal",
                    ),
                ),
                (
                    "permite_despacho",
                    models.BooleanField(default=True, verbose_name="Permite despacho"),
                ),
                (
                    "permite_recepcion",
                    models.BooleanField(default=True, verbose_name="Permite recepción"),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "db_table": "supply_chain_almacen",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la unidad (ej: KG, TON, LB, LT, UN)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo de la unidad (ej: Kilogramos, Toneladas)",
                        max_length=100,
                        verbose_name="Nombre completo",
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(
                        help_text="Símbolo corto para mostrar en UI (ej: kg, t, lb, L)",
                        max_length=10,
                        verbose_name="Símbolo/Abreviatura",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PESO", "Peso"),
                            ("VOLUMEN", "Volumen"),
                            ("LONGITUD", "Longitud"),
                            ("UNIDAD", "Unidad"),
                            ("OTRO", "Otro"),
                        ],
                        default="PESO",
                        max_length=20,
                        verbose_name="Tipo de medida",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "factor_conversion_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Factor para convertir a kilogramos base (ej: 1 para KG, 1000 para TON, 0.4536 para LB)",
                        max_digits=10,
                        null=True,
                        verbose_name="Factor de conversión a KG",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "supply_chain_unidad_medida",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
