# Generated by Django 5.0.9 on 2026-01-23 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_initial'),
        ('core', '0002_initial'),
        ('organizacion', '0001_initial'),
        ('gestion_estrategica_contexto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaDofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Encuesta')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones para los participantes', verbose_name='Descripción')),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para acceso anónimo vía enlace público', unique=True, verbose_name='Token de Acceso Público')),
                ('es_publica', models.BooleanField(default=False, help_text='Si es pública, cualquiera con el enlace puede responder', verbose_name='¿Es Pública?')),
                ('requiere_justificacion', models.BooleanField(default=True, help_text='Si los participantes deben justificar su clasificación', verbose_name='¿Requiere Justificación?')),
                ('fecha_inicio', models.DateTimeField(help_text='Cuándo se abre la encuesta para respuestas', verbose_name='Fecha de Inicio')),
                ('fecha_cierre', models.DateTimeField(help_text='Cuándo se cierra la encuesta', verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('procesada', 'Procesada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_invitados', models.PositiveIntegerField(default=0, verbose_name='Total Invitados')),
                ('total_respondidos', models.PositiveIntegerField(default=0, verbose_name='Total Respondidos')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('analisis_dofa', models.ForeignKey(help_text='Análisis DOFA al que pertenece esta encuesta', on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='gestion_estrategica_contexto.analisisdofa', verbose_name='Análisis DOFA')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_dofa_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Encuesta DOFA',
                'verbose_name_plural': 'Encuestas DOFA',
                'db_table': 'encuestas_dofa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario Específico'), ('area', 'Por Área'), ('cargo', 'Por Cargo')], default='usuario', max_length=20, verbose_name='Tipo de Participante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('fecha_inicio_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio Respuesta')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_encuesta', to='organizacion.area', verbose_name='Área')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_encuesta', to='core.cargo', verbose_name='Cargo')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='encuestas.encuestadofa', verbose_name='Encuesta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_encuesta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Participante de Encuesta',
                'verbose_name_plural': 'Participantes de Encuesta',
                'db_table': 'encuestas_participante',
                'ordering': ['encuesta', 'tipo', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='TemaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('titulo', models.CharField(help_text='Aspecto a evaluar (ej: Gestión del conocimiento)', max_length=200, verbose_name='Título del Tema')),
                ('descripcion', models.TextField(blank=True, help_text='Contexto adicional para el participante', verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('area', models.ForeignKey(blank=True, help_text='Área organizacional a la que aplica este tema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_encuesta', to='organizacion.area', verbose_name='Área Relacionada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='encuestas.encuestadofa', verbose_name='Encuesta')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tema de Encuesta',
                'verbose_name_plural': 'Temas de Encuesta',
                'db_table': 'encuestas_tema',
                'ordering': ['encuesta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('token_anonimo', models.CharField(blank=True, help_text='Identificador para respuestas anónimas', max_length=64, verbose_name='Token Anónimo')),
                ('clasificacion', models.CharField(choices=[('fortaleza', 'Fortaleza'), ('debilidad', 'Debilidad')], help_text='¿Es Fortaleza o Debilidad?', max_length=15, verbose_name='Clasificación')),
                ('justificacion', models.TextField(blank=True, help_text='Razón de la clasificación', verbose_name='Justificación')),
                ('impacto_percibido', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=10, verbose_name='Impacto Percibido')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('respondente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_encuesta_dofa', to=settings.AUTH_USER_MODEL, verbose_name='Respondente')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.temaencuesta', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'db_table': 'encuestas_respuesta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encuestadofa',
            index=models.Index(fields=['empresa', 'estado'], name='encuestas_d_empresa_03924c_idx'),
        ),
        migrations.AddIndex(
            model_name='encuestadofa',
            index=models.Index(fields=['token_publico'], name='encuestas_d_token_p_2c1d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='encuestadofa',
            index=models.Index(fields=['fecha_inicio', 'fecha_cierre'], name='encuestas_d_fecha_i_1f8ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteencuesta',
            index=models.Index(fields=['encuesta', 'estado'], name='encuestas_p_encuest_4354d2_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteencuesta',
            index=models.Index(fields=['usuario'], name='encuestas_p_usuario_a33c35_idx'),
        ),
        migrations.AddIndex(
            model_name='temaencuesta',
            index=models.Index(fields=['encuesta', 'orden'], name='encuestas_t_encuest_722f80_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaencuesta',
            index=models.Index(fields=['tema', 'clasificacion'], name='encuestas_r_tema_id_83d0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaencuesta',
            index=models.Index(fields=['respondente'], name='encuestas_r_respond_15906e_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaencuesta',
            index=models.Index(fields=['token_anonimo'], name='encuestas_r_token_a_8a96cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(condition=models.Q(('respondente__isnull', False)), fields=('tema', 'respondente'), name='unique_respuesta_usuario_tema'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(condition=models.Q(('token_anonimo__gt', '')), fields=('tema', 'token_anonimo'), name='unique_respuesta_anonimo_tema'),
        ),
    ]
