# Generated by Django 5.0.14 on 2026-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL para navegar al hacer clic",
                        max_length=500,
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "datos_extra",
                    models.JSONField(
                        blank=True,
                        help_text="Datos adicionales en formato JSON",
                        null=True,
                        verbose_name="Datos Extra",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "esta_leida",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Está Leída"
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura"
                    ),
                ),
                (
                    "esta_archivada",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Está Archivada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notif_notificacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionMasiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "destinatarios_tipo",
                    models.CharField(
                        choices=[
                            ("todos", "Todos"),
                            ("rol", "Por Rol"),
                            ("area", "Por Área"),
                            ("usuarios_especificos", "Usuarios Específicos"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Destinatarios",
                    ),
                ),
                (
                    "total_enviadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Enviadas"
                    ),
                ),
                (
                    "total_leidas",
                    models.PositiveIntegerField(default=0, verbose_name="Total Leídas"),
                ),
            ],
            options={
                "verbose_name": "Notificación Masiva",
                "verbose_name_plural": "Notificaciones Masivas",
                "db_table": "notif_notificacion_masiva",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "recibir_app",
                    models.BooleanField(
                        default=True,
                        help_text="Mostrar notificación en la aplicación",
                        verbose_name="Recibir en App",
                    ),
                ),
                (
                    "recibir_email",
                    models.BooleanField(
                        default=True,
                        help_text="Enviar por correo electrónico",
                        verbose_name="Recibir Email",
                    ),
                ),
                (
                    "recibir_push",
                    models.BooleanField(
                        default=False,
                        help_text="Enviar notificación push",
                        verbose_name="Recibir Push",
                    ),
                ),
                (
                    "horario_inicio",
                    models.TimeField(
                        blank=True,
                        help_text="No enviar notificaciones antes de esta hora",
                        null=True,
                        verbose_name="Horario Inicio",
                    ),
                ),
                (
                    "horario_fin",
                    models.TimeField(
                        blank=True,
                        help_text="No enviar notificaciones después de esta hora",
                        null=True,
                        verbose_name="Horario Fin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Notificación",
                "verbose_name_plural": "Preferencias de Notificación",
                "db_table": "notif_preferencia_notificacion",
            },
        ),
        migrations.CreateModel(
            name="TipoNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único identificador del tipo",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Icono a mostrar (bell, warning, check, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        help_text="Color del icono/notificación",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("tarea", "Tarea"),
                            ("alerta", "Alerta"),
                            ("recordatorio", "Recordatorio"),
                            ("aprobacion", "Aprobación"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "plantilla_titulo",
                    models.CharField(
                        help_text='Plantilla para el título. Ej: "Nueva {entidad} asignada"',
                        max_length=500,
                        verbose_name="Plantilla Título",
                    ),
                ),
                (
                    "plantilla_mensaje",
                    models.TextField(
                        help_text="Plantilla para el mensaje. Usa {variable} para placeholders",
                        verbose_name="Plantilla Mensaje",
                    ),
                ),
                (
                    "url_template",
                    models.CharField(
                        blank=True,
                        help_text='Plantilla URL para navegar. Ej: "/modulo/{id}"',
                        max_length=500,
                        null=True,
                        verbose_name="URL Template",
                    ),
                ),
                (
                    "es_email",
                    models.BooleanField(
                        default=False,
                        help_text="También enviar por correo electrónico",
                        verbose_name="Enviar Email",
                    ),
                ),
                (
                    "es_push",
                    models.BooleanField(
                        default=False,
                        help_text="Enviar notificación push",
                        verbose_name="Enviar Push",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Notificación",
                "verbose_name_plural": "Tipos de Notificación",
                "db_table": "notif_tipo_notificacion",
                "ordering": ["categoria", "nombre"],
            },
        ),
    ]
