# Generated by Django 5.0.9 on 2026-01-05 19:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_dynamic_models_dia6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del estado (ej: APROBADO, EN_PRODUCCION)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado', max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(default='gray', help_text='Color para representación visual (success, warning, danger, info, gray)', max_length=20, verbose_name='Color')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del estado', verbose_name='Descripción')),
                ('es_inicial', models.BooleanField(default=False, help_text='¿Es el estado inicial al crear un pedido?', verbose_name='Es Estado Inicial')),
                ('es_final', models.BooleanField(default=False, help_text='¿Es un estado terminal (entregado/cancelado)?', verbose_name='Es Estado Final')),
                ('permite_modificacion', models.BooleanField(default=True, help_text='¿Se puede editar el pedido en este estado?', verbose_name='Permite Modificación')),
                ('permite_facturar', models.BooleanField(default=False, help_text='¿Se puede generar factura desde este estado?', verbose_name='Permite Facturar')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Estado activo?', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'db_table': 'sales_crm_estado_pedido',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la factura (ej: FAC-2025-0001)', max_length=50, unique=True, verbose_name='Código')),
                ('fecha_factura', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de emisión de la factura', verbose_name='Fecha de Factura')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la factura', verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', help_text='Estado actual de la factura', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal de la factura', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor del descuento aplicado', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de impuestos (IVA)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de la factura', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Facturación Electrónica (DIAN)', max_length=255, null=True, verbose_name='CUFE')),
                ('xml_url', models.URLField(blank=True, help_text='URL del XML de la factura electrónica', null=True, verbose_name='URL XML')),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF de la factura', null=True, verbose_name='URL PDF')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la factura', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'sales_crm_factura',
                'ordering': ['-fecha_factura', '-codigo'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del método (ej: EFECTIVO, TRANSFERENCIA)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del método de pago', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del método de pago', verbose_name='Descripción')),
                ('requiere_referencia', models.BooleanField(default=False, help_text='¿Requiere número de referencia/transacción?', verbose_name='Requiere Referencia')),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='¿Requiere código de autorización?', verbose_name='Requiere Autorización')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Método activo?', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'sales_crm_metodo_pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del pago (ej: PAG-0001)', max_length=50, unique=True, verbose_name='Código')),
                ('fecha_pago', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha en que se realizó el pago', verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de referencia/transacción/autorización', max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pago', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
                'db_table': 'sales_crm_pago_factura',
                'ordering': ['-fecha_pago', '-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del pedido (ej: PED-2025-0001)', max_length=50, unique=True, verbose_name='Código')),
                ('fecha_pedido', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha en que se realizó el pedido', verbose_name='Fecha de Pedido')),
                ('fecha_entrega_estimada', models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True, verbose_name='Fecha Entrega Estimada')),
                ('direccion_entrega', models.TextField(help_text='Dirección donde se entregará el pedido', verbose_name='Dirección de Entrega')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del pedido', verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal del pedido (antes de descuentos e impuestos)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento general (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='% Descuento')),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor del descuento aplicado', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (Valor)')),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de impuestos (IVA Colombia = 19%)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total del pedido (incluye descuentos e impuestos)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'sales_crm_pedido',
                'ordering': ['-fecha_pedido', '-codigo'],
            },
        ),
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la condición (ej: CONTADO, 30_DIAS)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la condición de pago', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la condición de pago', verbose_name='Descripción')),
                ('dias_plazo', models.IntegerField(default=0, help_text='Días de plazo para el pago (0 = contado)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Plazo')),
                ('aplica_descuento', models.BooleanField(default=False, help_text='¿Aplica descuento por pronto pago?', verbose_name='Aplica Descuento')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento por pronto pago (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='% Descuento')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Condición activa?', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condición de Pago',
                'verbose_name_plural': 'Condiciones de Pago',
                'db_table': 'sales_crm_condicion_pago',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='sales_crm_c_codigo_7267e5_idx'), models.Index(fields=['activo', 'orden'], name='sales_crm_c_activo_c2e617_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('descripcion', models.TextField(help_text='Descripción del producto (se copia del producto)', verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad solicitada', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(help_text='Unidad de medida (kg, unidades, etc.)', max_length=50, verbose_name='Unidad de Medida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('descuento_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento específico de esta línea (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='% Descuento Línea')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal de la línea (cantidad × precio - descuento)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de la línea en el pedido', verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'sales_crm_detalle_pedido',
                'ordering': ['pedido', 'orden'],
            },
        ),
    ]
