# Generated by Django 5.0.9 on 2026-01-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_dynamic_models_dia6'),
        ('gestion_clientes', '0001_initial'),
        ('pedidos_facturacion', '0001_initial'),
        ('pipeline_ventas', '0001_initial'),
        ('producto_terminado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(help_text='Producto a vender', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='producto_terminado.productoterminado', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='estadopedido',
            index=models.Index(fields=['codigo'], name='sales_crm_e_codigo_aeded3_idx'),
        ),
        migrations.AddIndex(
            model_name='estadopedido',
            index=models.Index(fields=['activo', 'orden'], name='sales_crm_e_activo_d4b4a5_idx'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente facturado', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='gestion_clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['codigo'], name='sales_crm_m_codigo_6b6e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['activo', 'orden'], name='sales_crm_m_activo_a76d58_idx'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='factura',
            field=models.ForeignKey(help_text='Factura que se paga', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos_facturacion.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='metodo_pago',
            field=models.ForeignKey(help_text='Método utilizado para el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos_facturacion.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que registró el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='condicion_pago',
            field=models.ForeignKey(help_text='Condición de pago del pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos_facturacion.condicionpago', verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Cotización que origina el pedido (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pipeline_ventas.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual del pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos_facturacion.estadopedido', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor responsable del pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(help_text='Pedido que origina la factura', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='pedidos_facturacion.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(help_text='Pedido al que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos_facturacion.pedido', verbose_name='Pedido'),
        ),
        migrations.AddIndex(
            model_name='pagofactura',
            index=models.Index(fields=['empresa', 'factura'], name='sales_crm_p_empresa_aefb35_idx'),
        ),
        migrations.AddIndex(
            model_name='pagofactura',
            index=models.Index(fields=['empresa', 'fecha_pago'], name='sales_crm_p_empresa_e5af59_idx'),
        ),
        migrations.AddIndex(
            model_name='pagofactura',
            index=models.Index(fields=['codigo'], name='sales_crm_p_codigo_95405a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'codigo'], name='sales_crm_p_empresa_0b0ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'cliente'], name='sales_crm_p_empresa_ab6ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'vendedor'], name='sales_crm_p_empresa_5342e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'estado'], name='sales_crm_p_empresa_19284b_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'fecha_pedido'], name='sales_crm_p_empresa_197f09_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo'], name='sales_crm_p_codigo_f87ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'codigo'], name='sales_crm_f_empresa_a131d2_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'cliente'], name='sales_crm_f_empresa_a6e09c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'pedido'], name='sales_crm_f_empresa_1705bf_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'estado'], name='sales_crm_f_empresa_de26d8_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'fecha_factura'], name='sales_crm_f_empresa_6898fd_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='sales_crm_f_empresa_49df8c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['codigo'], name='sales_crm_f_codigo_843f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['empresa', 'pedido'], name='sales_crm_d_empresa_d3473b_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['empresa', 'producto'], name='sales_crm_d_empresa_e31854_idx'),
        ),
    ]
