# Generated by Django 5.0.9 on 2025-12-23 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoRequisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("requiere_renovacion", models.BooleanField(default=True)),
                (
                    "dias_anticipacion_alerta",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Requisito",
                "verbose_name_plural": "Tipos de Requisito",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RequisitoLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("entidad_emisora", models.CharField(max_length=200)),
                ("base_legal", models.TextField(blank=True)),
                ("aplica_sst", models.BooleanField(default=False)),
                ("aplica_ambiental", models.BooleanField(default=False)),
                ("aplica_calidad", models.BooleanField(default=False)),
                ("aplica_pesv", models.BooleanField(default=False)),
                ("es_obligatorio", models.BooleanField(default=True)),
                (
                    "periodicidad_renovacion",
                    models.CharField(blank=True, max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos",
                        to="requisitos_legales.tiporequisito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito Legal",
                "verbose_name_plural": "Requisitos Legales",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaRequisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(db_index=True, default=1),
                ),
                ("numero_documento", models.CharField(blank=True, max_length=100)),
                ("fecha_expedicion", models.DateField(blank=True, null=True)),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("proximo_vencer", "Proximo a Vencer"),
                            ("vencido", "Vencido"),
                            ("en_tramite", "En Tramite"),
                            ("renovando", "En Renovacion"),
                            ("no_aplica", "No Aplica"),
                        ],
                        db_index=True,
                        default="en_tramite",
                        max_length=20,
                    ),
                ),
                (
                    "documento_soporte",
                    models.FileField(
                        blank=True, null=True, upload_to="requisitos/documentos/"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("justificacion_no_aplica", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresa_requisitos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisito_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renovaciones",
                        to="requisitos_legales.empresarequisito",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitos_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresas",
                        to="requisitos_legales.requisitolegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito de Empresa",
                "verbose_name_plural": "Requisitos de Empresa",
                "ordering": ["fecha_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="AlertaVencimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dias_antes", models.PositiveSmallIntegerField()),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("email", "Correo Electronico"),
                            ("sistema", "Notificacion Sistema"),
                            ("ambos", "Correo y Sistema"),
                        ],
                        default="sistema",
                        max_length=10,
                    ),
                ),
                ("destinatarios", models.TextField(blank=True)),
                ("fecha_programada", models.DateField()),
                ("enviada", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("mensaje_personalizado", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa_requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="requisitos_legales.empresarequisito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Vencimiento",
                "verbose_name_plural": "Alertas de Vencimiento",
                "ordering": ["fecha_programada"],
                "unique_together": {("empresa_requisito", "dias_antes")},
            },
        ),
        migrations.AddIndex(
            model_name="empresarequisito",
            index=models.Index(
                fields=["empresa_id", "estado"], name="requisitos__empresa_027d9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="empresarequisito",
            index=models.Index(
                fields=["empresa_id", "fecha_vencimiento"],
                name="requisitos__empresa_e5663b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisitolegal",
            unique_together={("tipo", "codigo")},
        ),
    ]
