# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acciones_indicador", "0001_initial"),
        ("config_indicadores", "0001_initial"),
        ("configuracion", "0001_initial"),
        ("indicadores_area", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadplankpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="actividadplankpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="actividadplankpi",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_kpi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="actividadplankpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="integracionaccioncorrectiva",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="integracionaccioncorrectiva",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="integracionaccioncorrectiva",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_accion",
                to="config_indicadores.catalogokpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planes_kpi_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="planaccionkpi",
            name="valor_kpi",
            field=models.ForeignKey(
                help_text="Valor específico que originó el plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_accion",
                to="indicadores_area.valorkpi",
                verbose_name="Valor KPI",
            ),
        ),
        migrations.AddField(
            model_name="integracionaccioncorrectiva",
            name="plan_kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integraciones_mejora",
                to="acciones_indicador.planaccionkpi",
                verbose_name="Plan KPI",
            ),
        ),
        migrations.AddField(
            model_name="actividadplankpi",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="acciones_indicador.planaccionkpi",
                verbose_name="Plan de Acción",
            ),
        ),
        migrations.AddField(
            model_name="seguimientoplankpi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="seguimientoplankpi",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="configuracion.empresaconfig",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="seguimientoplankpi",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seguimientos",
                to="acciones_indicador.planaccionkpi",
                verbose_name="Plan de Acción",
            ),
        ),
        migrations.AddField(
            model_name="seguimientoplankpi",
            name="realizado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seguimientos_kpi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Realizado Por",
            ),
        ),
        migrations.AddField(
            model_name="seguimientoplankpi",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionkpi",
            index=models.Index(
                fields=["empresa", "kpi"], name="analytics_p_empresa_fc21b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionkpi",
            index=models.Index(
                fields=["estado", "prioridad"], name="analytics_p_estado_fef96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionkpi",
            index=models.Index(
                fields=["fecha_meta"], name="analytics_p_fecha_m_5db6d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planaccionkpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_p_empresa_d9cf29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionaccioncorrectiva",
            index=models.Index(
                fields=["plan_kpi"], name="analytics_i_plan_kp_7b6fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionaccioncorrectiva",
            index=models.Index(
                fields=["accion_correctiva_id"], name="analytics_i_accion__9ada15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integracionaccioncorrectiva",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_i_empresa_200ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadplankpi",
            index=models.Index(
                fields=["plan", "estado"], name="analytics_a_plan_id_d1cdd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadplankpi",
            index=models.Index(
                fields=["responsable"], name="analytics_a_respons_3737a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadplankpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_a_empresa_30ac43_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actividadplankpi",
            unique_together={("plan", "numero_actividad")},
        ),
        migrations.AddIndex(
            model_name="seguimientoplankpi",
            index=models.Index(
                fields=["plan", "fecha_seguimiento"],
                name="analytics_s_plan_id_7f17dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientoplankpi",
            index=models.Index(
                fields=["empresa", "is_active"], name="analytics_s_empresa_e878cd_idx"
            ),
        ),
    ]
