# Generated by Django 5.0.9 on 2026-03-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_unify_sede_unidadnegocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la configuración', max_length=255, verbose_name='Nombre')),
                ('tipo_exportacion', models.CharField(choices=[('kpi_valores', 'Valores de KPIs'), ('analisis_tendencias', 'Análisis de Tendencias'), ('anomalias', 'Anomalías Detectadas'), ('planes_accion', 'Planes de Acción'), ('informes', 'Informes Generados'), ('dashboard_completo', 'Dashboard Completo')], help_text='Qué datos se exportarán', max_length=30, verbose_name='Tipo de Exportación')),
                ('formato_config', models.JSONField(default=dict, help_text='Configuración específica del formato (columnas, filtros, etc.)', verbose_name='Configuración de Formato')),
                ('formato_archivo', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('xml', 'XML')], default='excel', max_length=10, verbose_name='Formato de Archivo')),
                ('destino', models.CharField(choices=[('descarga', 'Descarga Manual'), ('email', 'Envío por Email'), ('ftp', 'Servidor FTP'), ('api', 'API Externa')], default='descarga', max_length=15, verbose_name='Destino')),
                ('destino_config', models.JSONField(default=dict, help_text='Configuración del destino (emails, FTP, API endpoint, etc.)', verbose_name='Configuración de Destino')),
                ('filtros_json', models.JSONField(default=dict, help_text='Filtros a aplicar en los datos exportados', verbose_name='Filtros')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('frecuencia_automatica', models.CharField(blank=True, help_text='Si se programa exportación automática (diario, semanal, mensual)', max_length=20, verbose_name='Frecuencia Automática')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Exportación',
                'verbose_name_plural': 'Configuraciones de Exportación',
                'db_table': 'analytics_configuracion_exportacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro (automático)', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la última actualización (automático)', verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o ha sido eliminado lógicamente', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de eliminación lógica (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('programada', 'Programada'), ('automatica', 'Automática')], max_length=15, verbose_name='Tipo')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ejecución')),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('parcial', 'Parcial')], max_length=10, verbose_name='Estado')),
                ('registros_exportados', models.IntegerField(default=0, verbose_name='Registros Exportados')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='analytics/exportaciones/%Y/%m/', verbose_name='Archivo Generado')),
                ('tamaño_archivo_bytes', models.IntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('duracion_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del Error')),
                ('parametros_usados', models.JSONField(default=dict, help_text='Filtros y parámetros aplicados en esta exportación', verbose_name='Parámetros Usados')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exportacion_integracion.configuracionexportacion', verbose_name='Configuración')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='configuracion.empresaconfig', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Exportación',
                'verbose_name_plural': 'Logs de Exportación',
                'db_table': 'analytics_log_exportacion',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.AddIndex(
            model_name='configuracionexportacion',
            index=models.Index(fields=['empresa', 'tipo_exportacion'], name='analytics_c_empresa_c2a3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionexportacion',
            index=models.Index(fields=['esta_activa'], name='analytics_c_esta_ac_46067d_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionexportacion',
            index=models.Index(fields=['empresa', 'is_active'], name='analytics_c_empresa_8ba2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='logexportacion',
            index=models.Index(fields=['empresa', 'configuracion'], name='analytics_l_empresa_c50ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='logexportacion',
            index=models.Index(fields=['fecha_ejecucion'], name='analytics_l_fecha_e_28b56d_idx'),
        ),
        migrations.AddIndex(
            model_name='logexportacion',
            index=models.Index(fields=['estado'], name='analytics_l_estado_71021b_idx'),
        ),
        migrations.AddIndex(
            model_name='logexportacion',
            index=models.Index(fields=['usuario'], name='analytics_l_usuario_2e4138_idx'),
        ),
        migrations.AddIndex(
            model_name='logexportacion',
            index=models.Index(fields=['empresa', 'is_active'], name='analytics_l_empresa_8bf539_idx'),
        ),
    ]
