# Generated by Django 5.0.14 on 2026-04-19 18:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0003_unify_sede_unidadnegocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        max_length=100, verbose_name="Número de cotización"
                    ),
                ),
                (
                    "fecha_cotizacion",
                    models.DateField(verbose_name="Fecha de cotizacion"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total"
                    ),
                ),
                (
                    "tiempo_entrega_dias",
                    models.PositiveIntegerField(
                        verbose_name="Tiempo de entrega (días)"
                    ),
                ),
                (
                    "condiciones_pago",
                    models.TextField(verbose_name="Condiciones de pago"),
                ),
                (
                    "archivo_cotizacion",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cotizaciones/%Y/%m/",
                        verbose_name="Archivo de cotización",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "db_table": "supply_chain_cotizacion",
                "ordering": ["-fecha_cotizacion", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto_servicio",
                    models.CharField(max_length=255, verbose_name="Producto/Servicio"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "cantidad_solicitada",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Cantidad solicitada",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        verbose_name="Cantidad recibida",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=50, verbose_name="Unidad de medida"),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra",
                "verbose_name_plural": "Detalles de Orden de Compra",
                "db_table": "supply_chain_detalle_orden_compra",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DetalleRequisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto_servicio",
                    models.CharField(max_length=255, verbose_name="Producto/Servicio"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=50, verbose_name="Unidad de medida"),
                ),
                (
                    "especificaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Especificaciones técnicas"
                    ),
                ),
                (
                    "precio_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio estimado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Detalle de Requisición",
                "verbose_name_plural": "Detalles de Requisición",
                "db_table": "supply_chain_detalle_requisicion",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EstadoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_ordenes",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se pueden generar órdenes con este estado",
                        verbose_name="Permite órdenes",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Contrato",
                "verbose_name_plural": "Estados de Contrato",
                "db_table": "supply_chain_estado_contrato",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_evaluacion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se puede evaluar la cotización en este estado",
                        verbose_name="Permite evaluación",
                    ),
                ),
                ("es_estado_inicial", models.BooleanField(default=False)),
                ("es_estado_final", models.BooleanField(default=False)),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Cotización",
                "verbose_name_plural": "Estados de Cotización",
                "db_table": "supply_chain_estado_cotizacion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_accion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este estado requiere acciones correctivas",
                        verbose_name="Requiere acción",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Material",
                "verbose_name_plural": "Estados de Material",
                "db_table": "supply_chain_estado_material",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_edicion",
                    models.BooleanField(default=True, verbose_name="Permite edición"),
                ),
                (
                    "permite_recepcion",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se puede registrar recepción de materiales",
                        verbose_name="Permite recepción",
                    ),
                ),
                ("es_estado_inicial", models.BooleanField(default=False)),
                ("es_estado_final", models.BooleanField(default=False)),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Orden de Compra",
                "verbose_name_plural": "Estados de Orden de Compra",
                "db_table": "supply_chain_estado_orden_compra",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoRequisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del estado (ej: BORRADOR, ENVIADA, APROBADA)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del estado",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "permite_edicion",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la requisición puede editarse en este estado",
                        verbose_name="Permite edición",
                    ),
                ),
                (
                    "es_estado_inicial",
                    models.BooleanField(
                        default=False,
                        help_text="Estado por defecto para nuevas requisiciones",
                        verbose_name="Es estado inicial",
                    ),
                ),
                (
                    "es_estado_final",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que la requisición ha terminado su ciclo",
                        verbose_name="Es estado final",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="Color para identificación visual (ej: #28A745)",
                        max_length=7,
                        null=True,
                        verbose_name="Color (HEX)",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Requisición",
                "verbose_name_plural": "Estados de Requisición",
                "db_table": "supply_chain_estado_requisicion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de evaluación"
                    ),
                ),
                (
                    "criterios_evaluacion",
                    models.JSONField(verbose_name="Criterios de evaluación"),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Puntaje total"
                    ),
                ),
                ("recomendacion", models.TextField(verbose_name="Recomendación")),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones adicionales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluación de Cotización",
                "verbose_name_plural": "Evaluaciones de Cotizaciones",
                "db_table": "supply_chain_evaluacion_cotizacion",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código ISO de la moneda (ej: COP, USD, EUR)",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la moneda (ej: Peso Colombiano)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(
                        help_text="Símbolo de la moneda (ej: $, US$, €)",
                        max_length=5,
                        verbose_name="Símbolo",
                    ),
                ),
                (
                    "es_moneda_base",
                    models.BooleanField(
                        default=False,
                        help_text="Moneda principal del sistema",
                        verbose_name="Es moneda base",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "db_table": "supply_chain_moneda",
                "ordering": ["orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de orden",
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de orden"),
                ),
                (
                    "fecha_entrega_esperada",
                    models.DateField(verbose_name="Fecha de entrega esperada"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total"
                    ),
                ),
                (
                    "condiciones_pago",
                    models.TextField(verbose_name="Condiciones de pago"),
                ),
                ("lugar_entrega", models.TextField(verbose_name="Lugar de entrega")),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "db_table": "supply_chain_orden_compra",
                "ordering": ["-fecha_orden", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrioridadRequisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "nivel",
                    models.PositiveIntegerField(
                        help_text="1=Más baja, valores mayores=Mayor prioridad",
                        verbose_name="Nivel de prioridad",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Color (HEX)"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prioridad de Requisición",
                "verbose_name_plural": "Prioridades de Requisición",
                "db_table": "supply_chain_prioridad_requisicion",
                "ordering": ["-nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Requisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Código autogenerado de la requisición",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "area_solicitante",
                    models.CharField(
                        help_text="Departamento o área que realiza la solicitud",
                        max_length=200,
                        verbose_name="Área solicitante",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "fecha_requerida",
                    models.DateField(
                        help_text="Fecha en la que se necesitan los productos/servicios",
                        verbose_name="Fecha requerida",
                    ),
                ),
                (
                    "justificacion",
                    models.TextField(
                        help_text="Razón de la solicitud de compra",
                        verbose_name="Justificación",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Requisición de Compra",
                "verbose_name_plural": "Requisiciones de Compra",
                "db_table": "supply_chain_requisicion",
                "ordering": ["-fecha_solicitud", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del tipo (ej: SUMINISTRO, SERVICIO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del tipo de contrato",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_entregables",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este tipo de contrato requiere definir entregables",
                        verbose_name="Requiere entregables",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "db_table": "supply_chain_tipo_contrato",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número de contrato"
                    ),
                ),
                ("objeto", models.TextField(verbose_name="Objeto del contrato")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de finalización")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor total del contrato",
                    ),
                ),
                (
                    "condiciones",
                    models.TextField(verbose_name="Condiciones contractuales"),
                ),
                (
                    "archivo_contrato",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contratos/%Y/%m/",
                        verbose_name="Archivo del contrato",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_proveedores",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Proveedor",
                "verbose_name_plural": "Contratos de Proveedores",
                "db_table": "supply_chain_contrato",
                "ordering": ["-fecha_inicio", "-created_at"],
            },
        ),
    ]
