# Generated by Django 5.0.14 on 2026-02-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanTrabajoAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="ID de la empresa (multi-tenant)",
                        verbose_name="ID Empresa",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico del plan (ej: PTA-2024)",
                        max_length=50,
                        unique=True,
                        verbose_name="Codigo del Plan",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del plan",
                        max_length=255,
                        verbose_name="Nombre del Plan",
                    ),
                ),
                (
                    "periodo",
                    models.IntegerField(
                        help_text="Año del plan de trabajo",
                        verbose_name="Periodo (Año)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En Revision"),
                            ("APROBADO", "Aprobado"),
                            ("EN_EJECUCION", "En Ejecucion"),
                            ("CERRADO", "Cerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        help_text="Estado actual del plan",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del plan",
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Fecha de finalizacion del plan",
                        verbose_name="Fecha de Finalizacion",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Aprobacion"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion general del plan",
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planes_trabajo_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planes_trabajo_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Responsable de coordinar el plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_trabajo_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Trabajo Anual",
                "verbose_name_plural": "Planes de Trabajo Anual",
                "db_table": "hseq_plan_trabajo_anual",
                "ordering": ["-periodo", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ObjetivoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico del objetivo",
                        max_length=50,
                        verbose_name="Codigo del Objetivo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Objetivo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del Objetivo"),
                ),
                (
                    "perspectiva_bsc",
                    models.CharField(
                        choices=[
                            ("FINANCIERA", "Perspectiva Financiera"),
                            ("CLIENTES", "Perspectiva de Clientes"),
                            ("PROCESOS", "Perspectiva de Procesos Internos"),
                            ("APRENDIZAJE", "Perspectiva de Aprendizaje y Crecimiento"),
                        ],
                        help_text="Perspectiva del Balanced Scorecard",
                        max_length=50,
                        verbose_name="Perspectiva BSC",
                    ),
                ),
                (
                    "objetivo_bsc_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del objetivo en el sistema BSC",
                        max_length=50,
                        verbose_name="ID Objetivo BSC",
                    ),
                ),
                (
                    "tipo_objetivo",
                    models.CharField(
                        choices=[
                            ("ESTRATEGICO", "Estrategico"),
                            ("TACTICO", "Tactico"),
                            ("OPERATIVO", "Operativo"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Objetivo",
                    ),
                ),
                (
                    "area_aplicacion",
                    models.CharField(
                        choices=[
                            ("SST", "Seguridad y Salud en el Trabajo"),
                            ("CALIDAD", "Calidad"),
                            ("AMBIENTAL", "Ambiental"),
                            ("INTEGRAL", "Integral HSEQ"),
                        ],
                        max_length=100,
                        verbose_name="Area de Aplicacion",
                    ),
                ),
                (
                    "meta_descripcion",
                    models.TextField(
                        help_text="Descripcion cualitativa de la meta a alcanzar",
                        verbose_name="Descripcion de la Meta",
                    ),
                ),
                (
                    "meta_cuantitativa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor numerico de la meta (ej: 95 para 95%)",
                        max_digits=10,
                        null=True,
                        verbose_name="Meta Cuantitativa",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        help_text="Unidad de medida (%, numero, dias, etc.)",
                        max_length=50,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "indicador_nombre",
                    models.CharField(
                        help_text="Nombre del indicador de cumplimiento",
                        max_length=255,
                        verbose_name="Nombre del Indicador",
                    ),
                ),
                (
                    "formula_calculo",
                    models.TextField(
                        blank=True,
                        help_text="Formula para calcular el indicador",
                        verbose_name="Formula de Calculo",
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Valor actual del indicador",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Actual",
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de cumplimiento de la meta",
                        max_digits=5,
                        verbose_name="Porcentaje de Cumplimiento (%)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("EN_SEGUIMIENTO", "En Seguimiento"),
                            ("CUMPLIDO", "Cumplido"),
                            ("NO_CUMPLIDO", "No Cumplido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_meta",
                    models.DateField(
                        help_text="Fecha limite para cumplir el objetivo",
                        verbose_name="Fecha Meta",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objetivos_sistema_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objetivos_sistema_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Objetivo",
                    ),
                ),
                (
                    "plan_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetivos",
                        to="planificacion_sistema.plantrabajoanual",
                        verbose_name="Plan de Trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo del Sistema",
                "verbose_name_plural": "Objetivos del Sistema",
                "db_table": "hseq_objetivo_sistema",
                "ordering": ["perspectiva_bsc", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ActividadPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico de la actividad",
                        max_length=50,
                        verbose_name="Codigo de Actividad",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Actividad"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("CAPACITACION", "Capacitacion"),
                            ("INSPECCION", "Inspeccion"),
                            ("AUDITORIA", "Auditoria"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("SIMULACRO", "Simulacro"),
                            ("REVISION", "Revision"),
                            ("EVALUACION", "Evaluacion"),
                            ("ACTUALIZACION", "Actualizacion"),
                            ("MEJORA", "Mejora"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Actividad",
                    ),
                ),
                (
                    "area_responsable",
                    models.CharField(
                        help_text="Area o departamento responsable",
                        max_length=100,
                        verbose_name="Area Responsable",
                    ),
                ),
                (
                    "fecha_programada_inicio",
                    models.DateField(verbose_name="Fecha Programada de Inicio"),
                ),
                (
                    "fecha_programada_fin",
                    models.DateField(verbose_name="Fecha Programada de Finalizacion"),
                ),
                (
                    "fecha_real_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Real de Inicio"
                    ),
                ),
                (
                    "fecha_real_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Real de Finalizacion"
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(
                        blank=True,
                        help_text="Recursos humanos, materiales, financieros necesarios",
                        verbose_name="Recursos Necesarios",
                    ),
                ),
                (
                    "presupuesto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Presupuesto estimado para la actividad",
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto Estimado (COP)",
                    ),
                ),
                (
                    "presupuesto_ejecutado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Presupuesto realmente ejecutado",
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto Ejecutado (COP)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                            ("RETRASADA", "Retrasada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de avance de la actividad (0-100)",
                        max_digits=5,
                        verbose_name="Porcentaje de Avance (%)",
                    ),
                ),
                (
                    "evidencias",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion de evidencias generadas",
                        verbose_name="Evidencias",
                    ),
                ),
                (
                    "resultados_obtenidos",
                    models.TextField(
                        blank=True,
                        help_text="Resultados concretos obtenidos",
                        verbose_name="Resultados Obtenidos",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "colaboradores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="actividades_plan_colaborador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Colaboradores",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_plan_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_plan_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "plan_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="planificacion_sistema.plantrabajoanual",
                        verbose_name="Plan de Trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del Plan",
                "verbose_name_plural": "Actividades del Plan",
                "db_table": "hseq_actividad_plan",
                "ordering": ["fecha_programada_inicio", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaGestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico del programa",
                        max_length=50,
                        verbose_name="Codigo del Programa",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Programa"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del Programa"),
                ),
                (
                    "tipo_programa",
                    models.CharField(
                        choices=[
                            ("PVE", "Vigilancia Epidemiologica"),
                            ("CAPACITACION", "Capacitacion"),
                            ("INSPECCIONES", "Inspecciones"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("AMBIENTAL", "Gestion Ambiental"),
                            ("RESIDUOS", "Gestion de Residuos"),
                            ("EMERGENCIAS", "Plan de Emergencias"),
                            ("MEDICINA", "Medicina Preventiva"),
                            ("HIGIENE", "Higiene Industrial"),
                            ("SEGURIDAD", "Seguridad Industrial"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Programa",
                    ),
                ),
                (
                    "alcance",
                    models.TextField(
                        help_text="Alcance y cobertura del programa",
                        verbose_name="Alcance del Programa",
                    ),
                ),
                (
                    "objetivos",
                    models.TextField(
                        help_text="Objetivos especificos del programa",
                        verbose_name="Objetivos del Programa",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Finalizacion")),
                (
                    "recursos_asignados",
                    models.TextField(
                        blank=True,
                        help_text="Recursos humanos, tecnicos y financieros",
                        verbose_name="Recursos Asignados",
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto (COP)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADO", "Planificado"),
                            ("EN_EJECUCION", "En Ejecucion"),
                            ("COMPLETADO", "Completado"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANIFICADO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de Avance (%)",
                    ),
                ),
                (
                    "indicadores_medicion",
                    models.TextField(
                        blank=True,
                        help_text="Indicadores para medir efectividad del programa",
                        verbose_name="Indicadores de Medicion",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "coordinadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="programas_gestion_coordinador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coordinadores",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programas_gestion_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "plan_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programas",
                        to="planificacion_sistema.plantrabajoanual",
                        verbose_name="Plan de Trabajo",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programas_gestion_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable del Programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Gestion",
                "verbose_name_plural": "Programas de Gestion",
                "db_table": "hseq_programa_gestion",
                "ordering": ["tipo_programa", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ActividadPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Codigo de Actividad"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Actividad"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                ("fecha_programada", models.DateField(verbose_name="Fecha Programada")),
                (
                    "fecha_ejecucion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Ejecucion Real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("EJECUTADA", "Ejecutada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "resultado",
                    models.TextField(
                        blank=True,
                        help_text="Resultado obtenido de la actividad",
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "evidencias",
                    models.TextField(
                        blank=True,
                        help_text="Evidencias generadas",
                        verbose_name="Evidencias",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_programa_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_programa_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="planificacion_sistema.programagestion",
                        verbose_name="Programa de Gestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del Programa",
                "verbose_name_plural": "Actividades del Programa",
                "db_table": "hseq_actividad_programa",
                "ordering": ["fecha_programada", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoCronograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="ID Empresa"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Periodo del seguimiento (ej: Enero 2024, Q1 2024, Semana 12)",
                        max_length=50,
                        verbose_name="Periodo de Seguimiento",
                    ),
                ),
                (
                    "fecha_seguimiento",
                    models.DateField(
                        help_text="Fecha en que se realiza el seguimiento",
                        verbose_name="Fecha de Seguimiento",
                    ),
                ),
                (
                    "actividades_totales",
                    models.IntegerField(default=0, verbose_name="Total de Actividades"),
                ),
                (
                    "actividades_completadas",
                    models.IntegerField(
                        default=0, verbose_name="Actividades Completadas"
                    ),
                ),
                (
                    "actividades_en_proceso",
                    models.IntegerField(
                        default=0, verbose_name="Actividades En Proceso"
                    ),
                ),
                (
                    "actividades_retrasadas",
                    models.IntegerField(
                        default=0, verbose_name="Actividades Retrasadas"
                    ),
                ),
                (
                    "actividades_pendientes",
                    models.IntegerField(
                        default=0, verbose_name="Actividades Pendientes"
                    ),
                ),
                (
                    "porcentaje_avance_general",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de Avance General (%)",
                    ),
                ),
                (
                    "presupuesto_planificado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto Planificado (COP)",
                    ),
                ),
                (
                    "presupuesto_ejecutado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Presupuesto Ejecutado (COP)",
                    ),
                ),
                (
                    "desviaciones_identificadas",
                    models.TextField(
                        blank=True,
                        help_text="Desviaciones respecto a lo planificado",
                        verbose_name="Desviaciones Identificadas",
                    ),
                ),
                (
                    "causas_desviacion",
                    models.TextField(
                        blank=True,
                        help_text="Causas raiz de las desviaciones",
                        verbose_name="Causas de Desviacion",
                    ),
                ),
                (
                    "acciones_correctivas",
                    models.TextField(
                        blank=True,
                        help_text="Acciones para corregir desviaciones",
                        verbose_name="Acciones Correctivas",
                    ),
                ),
                (
                    "acciones_preventivas",
                    models.TextField(
                        blank=True,
                        help_text="Acciones para prevenir futuras desviaciones",
                        verbose_name="Acciones Preventivas",
                    ),
                ),
                (
                    "nivel_cumplimiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELENTE", "Excelente (>90%)"),
                            ("BUENO", "Bueno (75-90%)"),
                            ("ACEPTABLE", "Aceptable (60-75%)"),
                            ("DEFICIENTE", "Deficiente (<60%)"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Cumplimiento",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Generales"
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones para mejorar el desempeno",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_cronograma_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "plan_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="planificacion_sistema.plantrabajoanual",
                        verbose_name="Plan de Trabajo",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Cronograma",
                "verbose_name_plural": "Seguimientos de Cronograma",
                "db_table": "hseq_seguimiento_cronograma",
                "ordering": ["-fecha_seguimiento"],
            },
        ),
        migrations.AddIndex(
            model_name="plantrabajoanual",
            index=models.Index(
                fields=["empresa_id", "periodo"], name="hseq_plan_t_empresa_7f9482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantrabajoanual",
            index=models.Index(fields=["estado"], name="hseq_plan_t_estado_4b5bc2_idx"),
        ),
        migrations.AddIndex(
            model_name="plantrabajoanual",
            index=models.Index(fields=["codigo"], name="hseq_plan_t_codigo_4575ae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="plantrabajoanual",
            unique_together={("empresa_id", "periodo")},
        ),
        migrations.AddIndex(
            model_name="objetivosistema",
            index=models.Index(
                fields=["empresa_id", "plan_trabajo"],
                name="hseq_objeti_empresa_6146d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="objetivosistema",
            index=models.Index(
                fields=["perspectiva_bsc"], name="hseq_objeti_perspec_36ff4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objetivosistema",
            index=models.Index(
                fields=["tipo_objetivo"], name="hseq_objeti_tipo_ob_0eda60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objetivosistema",
            index=models.Index(fields=["estado"], name="hseq_objeti_estado_2e09cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="objetivosistema",
            unique_together={("plan_trabajo", "codigo")},
        ),
        migrations.AddIndex(
            model_name="actividadplan",
            index=models.Index(
                fields=["empresa_id", "plan_trabajo"],
                name="hseq_activi_empresa_830bc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actividadplan",
            index=models.Index(fields=["estado"], name="hseq_activi_estado_87a40f_idx"),
        ),
        migrations.AddIndex(
            model_name="actividadplan",
            index=models.Index(
                fields=["tipo_actividad"], name="hseq_activi_tipo_ac_c66312_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadplan",
            index=models.Index(
                fields=["responsable"], name="hseq_activi_respons_fbb9eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actividadplan",
            unique_together={("plan_trabajo", "codigo")},
        ),
        migrations.AddIndex(
            model_name="programagestion",
            index=models.Index(
                fields=["empresa_id", "plan_trabajo"],
                name="hseq_progra_empresa_ce663f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programagestion",
            index=models.Index(
                fields=["tipo_programa"], name="hseq_progra_tipo_pr_0de386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programagestion",
            index=models.Index(fields=["estado"], name="hseq_progra_estado_95a51b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="programagestion",
            unique_together={("plan_trabajo", "codigo")},
        ),
        migrations.AddIndex(
            model_name="actividadprograma",
            index=models.Index(
                fields=["empresa_id", "programa"], name="hseq_activi_empresa_f0ae89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadprograma",
            index=models.Index(fields=["estado"], name="hseq_activi_estado_7120a7_idx"),
        ),
        migrations.AddIndex(
            model_name="actividadprograma",
            index=models.Index(
                fields=["fecha_programada"], name="hseq_activi_fecha_p_743dfd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actividadprograma",
            unique_together={("programa", "codigo")},
        ),
        migrations.AddIndex(
            model_name="seguimientocronograma",
            index=models.Index(
                fields=["empresa_id", "plan_trabajo"],
                name="hseq_seguim_empresa_197fa8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientocronograma",
            index=models.Index(
                fields=["fecha_seguimiento"], name="hseq_seguim_fecha_s_b30423_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientocronograma",
            index=models.Index(
                fields=["periodo"], name="hseq_seguim_periodo_c9e8f6_idx"
            ),
        ),
    ]
