# Generated by Django 5.0.14 on 2026-03-02 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificacion_sistema", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadplan",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="actividadplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="actividadplan",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="actividadplan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="actividadprograma",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="actividadprograma",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="actividadprograma",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="actividadprograma",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="objetivosistema",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="objetivosistema",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="objetivosistema",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="objetivosistema",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="plantrabajoanual",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="plantrabajoanual",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="plantrabajoanual",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="plantrabajoanual",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="programagestion",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="programagestion",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="programagestion",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="programagestion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="seguimientocronograma",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="seguimientocronograma",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="seguimientocronograma",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Eliminado"
            ),
        ),
        migrations.AddField(
            model_name="seguimientocronograma",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="actividadplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="actividadplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="actividadplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="actividadprograma",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="actividadprograma",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="actividadprograma",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="objetivosistema",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="objetivosistema",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="objetivosistema",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="plantrabajoanual",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="plantrabajoanual",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="plantrabajoanual",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="programagestion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="programagestion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="programagestion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientocronograma",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientocronograma",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="seguimientocronograma",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
    ]
