# Generated by Django 5.0.14 on 2026-03-19 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_gestion_documental", "0004_sellado_pdf_pyhanko"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AceptacionDocumental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_documento",
                    models.CharField(
                        help_text="Snapshot de la versión al momento de asignación",
                        max_length=20,
                        verbose_name="Versión del Documento",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Lectura"),
                            ("EN_PROGRESO", "Leyendo"),
                            ("ACEPTADO", "Leído y Aceptado"),
                            ("RECHAZADO", "Rechazado"),
                            ("VENCIDO", "Plazo Vencido"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True,
                        help_text="Plazo máximo para completar la lectura",
                        null=True,
                        verbose_name="Fecha Límite",
                    ),
                ),
                (
                    "fecha_inicio_lectura",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que el usuario abrió el documento por primera vez",
                        null=True,
                        verbose_name="Inicio de Lectura",
                    ),
                ),
                (
                    "fecha_aceptacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Aceptación"
                    ),
                ),
                (
                    "fecha_rechazo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Rechazo"
                    ),
                ),
                (
                    "porcentaje_lectura",
                    models.IntegerField(
                        default=0,
                        help_text="0-100, basado en secciones visibles del documento",
                        verbose_name="Porcentaje de Lectura",
                    ),
                ),
                (
                    "tiempo_lectura_seg",
                    models.IntegerField(
                        default=0,
                        help_text="Segundos totales con el documento visible",
                        verbose_name="Tiempo de Lectura (seg)",
                    ),
                ),
                (
                    "scroll_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"secciones_vistas": [0,1,2], "total_secciones": 5, "timestamps": [...]}',
                        verbose_name="Datos de Scroll",
                    ),
                ),
                (
                    "texto_aceptacion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Declaración firmada por el usuario al aceptar",
                        verbose_name="Texto de Aceptación",
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de Rechazo"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Navegador y dispositivo del usuario",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "empresa_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Empresa ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asignado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aceptaciones_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "control_documental",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registro de distribución que originó esta asignación",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aceptaciones",
                        to="infra_gestion_documental.controldocumental",
                        verbose_name="Control Documental",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aceptaciones",
                        to="infra_gestion_documental.documento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aceptaciones_documentales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aceptación Documental",
                "verbose_name_plural": "Aceptaciones Documentales",
                "db_table": "documental_aceptacion_documental",
                "ordering": ["-fecha_asignacion"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "usuario", "estado"],
                        name="documental__empresa_335867_idx",
                    ),
                    models.Index(
                        fields=["empresa_id", "documento"],
                        name="documental__empresa_9ec622_idx",
                    ),
                    models.Index(
                        fields=["fecha_limite"], name="documental__fecha_l_75f070_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="documental__estado_1abc7d_idx"
                    ),
                ],
                "unique_together": {
                    ("documento", "version_documento", "usuario", "empresa_id")
                },
            },
        ),
    ]
