# Generated by Django 5.0.14 on 2026-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_gestion_documental", "0007_sprint4_formula_calculo_campo_formulario"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="lectura_obligatoria",
            field=models.BooleanField(
                default=False,
                help_text="Si True, se asigna automáticamente a cada nuevo usuario del tenant",
                verbose_name="Lectura Obligatoria",
            ),
        ),
    ]
