# Generated by Django 5.0.14 on 2026-04-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_gestion_documental", "0008_add_lectura_obligatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipodocumento",
            name="nivel_seguridad_firma",
            field=models.IntegerField(
                choices=[
                    (1, "Estándar — Solo firma manuscrita"),
                    (2, "Reforzado — Firma + código TOTP"),
                    (3, "Máximo — Firma + TOTP + OTP email"),
                ],
                default=1,
                help_text="Define qué verificación se pide al firmar documentos de este tipo. Nivel 1: firma manuscrita. Nivel 2: firma + TOTP. Nivel 3: firma + TOTP + OTP email.",
                verbose_name="Nivel de Seguridad para Firma",
            ),
        ),
    ]
