# Generated by Django 5.0.14 on 2026-04-04 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("infra_gestion_documental", "0016_add_tabla_retencion_documental"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="modulo_origen",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Módulo C2 que generó este registro: 'hseq', 'talento_humano', 'pesv', etc.",
                max_length=50,
                verbose_name="Módulo Origen",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="referencia_origen_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID Referencia Origen"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="referencia_origen_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_originados",
                to="contenttypes.contenttype",
                verbose_name="Tipo de Referencia Origen",
            ),
        ),
    ]
