# Generated by Django 5.0.14 on 2026-04-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_gestion_documental", "0019_add_firma_workflow_campo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="codigo_legacy",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código del documento antes de ingresar al sistema StrateKaz",
                max_length=100,
                null=True,
                verbose_name="Código original de la empresa",
            ),
        ),
        migrations.AlterField(
            model_name="tablaretenciondocumental",
            name="requiere_acta_destruccion",
            field=models.BooleanField(
                default=False, verbose_name="Requiere Acta de Destrucción"
            ),
        ),
    ]
