# Generated by Django 5.0.14 on 2026-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infra_gestion_documental", "0026_evento_documental"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventodocumental",
            new_name="documental__documen_0f49f2_idx",
            old_name="doc_evt_doc_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="eventodocumental",
            new_name="documental__usuario_b0f718_idx",
            old_name="doc_evt_usr_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="eventodocumental",
            new_name="documental__tipo_ev_009dc2_idx",
            old_name="doc_evt_tipo_ts_idx",
        ),
    ]
