# Generated by Django 5.0.14 on 2026-02-25 14:22
# Modified: data-safe FK→IntegerField via SeparateDatabaseAndState

from django.conf import settings
from django.db import migrations, models


def _drop_fk_sql(table, column):
    """SQL to drop FK constraints and allow NULL on a column (per-schema safe)."""
    return [f"""
DO $$
DECLARE _con TEXT;
BEGIN
    FOR _con IN
        SELECT con.conname FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
        WHERE nsp.nspname = current_schema()
          AND rel.relname = '{table}'
          AND att.attname = '{column}'
          AND con.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', '{table}', _con);
    END LOOP;
    BEGIN
        EXECUTE 'ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL';
    EXCEPTION WHEN others THEN
        NULL;
    END;
END $$;"""]


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_legacy_fields"),
        ("tesoreria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add new cache CharField fields (genuinely new DB columns)
        migrations.AddField(
            model_name="cuentaporcobrar",
            name="cliente_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: razón social del cliente",
                max_length=200,
                verbose_name="Nombre Cliente",
            ),
        ),
        migrations.AddField(
            model_name="cuentaporcobrar",
            name="factura_codigo",
            field=models.CharField(
                blank=True,
                help_text="Cache: código/número de la factura",
                max_length=50,
                verbose_name="Código Factura",
            ),
        ),
        migrations.AddField(
            model_name="cuentaporpagar",
            name="liquidacion_nomina_codigo",
            field=models.CharField(
                blank=True,
                help_text="Cache: código de la liquidación de nómina",
                max_length=50,
                verbose_name="Código Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="cuentaporpagar",
            name="orden_compra_codigo",
            field=models.CharField(
                blank=True,
                help_text="Cache: código de la orden de compra",
                max_length=50,
                verbose_name="Código Orden de Compra",
            ),
        ),
        migrations.AddField(
            model_name="cuentaporpagar",
            name="proveedor_nombre",
            field=models.CharField(
                blank=True,
                help_text="Cache: razón social del proveedor",
                max_length=200,
                verbose_name="Nombre Proveedor",
            ),
        ),
        # Step 2: Data-safe FK→IntegerField swap
        # DB column names stay the same (*_id), only FK constraints are dropped
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="cuentaporcobrar",
                    name="admin_finan_cliente_10a109_idx",
                ),
                migrations.RemoveIndex(
                    model_name="cuentaporpagar",
                    name="admin_finan_proveed_bcfbab_idx",
                ),
                migrations.RemoveField(
                    model_name="cuentaporcobrar",
                    name="cliente",
                ),
                migrations.RemoveField(
                    model_name="cuentaporcobrar",
                    name="factura",
                ),
                migrations.RemoveField(
                    model_name="cuentaporpagar",
                    name="liquidacion_nomina",
                ),
                migrations.RemoveField(
                    model_name="cuentaporpagar",
                    name="orden_compra",
                ),
                migrations.RemoveField(
                    model_name="cuentaporpagar",
                    name="proveedor",
                ),
                migrations.AddField(
                    model_name="cuentaporcobrar",
                    name="cliente_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del cliente que debe pagar (sales_crm.Cliente)",
                        null=True,
                        verbose_name="ID Cliente",
                    ),
                ),
                migrations.AddField(
                    model_name="cuentaporcobrar",
                    name="factura_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID de la factura que origina el cobro (sales_crm.Factura)",
                        null=True,
                        verbose_name="ID Factura",
                    ),
                ),
                migrations.AddField(
                    model_name="cuentaporpagar",
                    name="liquidacion_nomina_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID de la liquidación de nómina que origina el pago (talent_hub.LiquidacionNomina)",
                        null=True,
                        verbose_name="ID Liquidación de Nómina",
                    ),
                ),
                migrations.AddField(
                    model_name="cuentaporpagar",
                    name="orden_compra_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID de la orden de compra que origina el pago (supply_chain.OrdenCompra)",
                        null=True,
                        verbose_name="ID Orden de Compra",
                    ),
                ),
                migrations.AddField(
                    model_name="cuentaporpagar",
                    name="proveedor_id",
                    field=models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID del proveedor al que se debe pagar (supply_chain.Proveedor)",
                        null=True,
                        verbose_name="ID Proveedor",
                    ),
                ),
                migrations.AddIndex(
                    model_name="cuentaporcobrar",
                    index=models.Index(
                        fields=["cliente_id", "estado"], name="admin_finan_cliente_10a109_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="cuentaporpagar",
                    index=models.Index(
                        fields=["proveedor_id", "estado"], name="admin_finan_proveed_bcfbab_idx"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        _drop_fk_sql("tesoreria_cuentaporcobrar", "cliente_id")
                        + _drop_fk_sql("tesoreria_cuentaporcobrar", "factura_id")
                        + _drop_fk_sql("tesoreria_cuentaporpagar", "proveedor_id")
                        + _drop_fk_sql("tesoreria_cuentaporpagar", "orden_compra_id")
                        + _drop_fk_sql("tesoreria_cuentaporpagar", "liquidacion_nomina_id")
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
