# Generated by Django 5.0.9 on 2026-01-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si el registro está activo o ha sido eliminado lógicamente",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora de eliminación lógica (null = no eliminado)",
                        null=True,
                        verbose_name="Fecha de Eliminación",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del módulo (ej: hseq_management, supply_chain)",
                        max_length=100,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del modelo Django (ej: AccionCorrectiva, Pedido)",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "auditar_creacion",
                    models.BooleanField(
                        default=True,
                        help_text="Registrar cuando se crea un nuevo registro",
                        verbose_name="Auditar Creación",
                    ),
                ),
                (
                    "auditar_modificacion",
                    models.BooleanField(
                        default=True,
                        help_text="Registrar cuando se modifica un registro",
                        verbose_name="Auditar Modificación",
                    ),
                ),
                (
                    "auditar_eliminacion",
                    models.BooleanField(
                        default=True,
                        help_text="Registrar cuando se elimina un registro",
                        verbose_name="Auditar Eliminación",
                    ),
                ),
                (
                    "auditar_consulta",
                    models.BooleanField(
                        default=False,
                        help_text="Registrar cuando se consulta el modelo (APIs sensibles)",
                        verbose_name="Auditar Consulta",
                    ),
                ),
                (
                    "campos_sensibles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de campos que NO se deben registrar (ej: password, token)",
                        verbose_name="Campos Sensibles",
                    ),
                ),
                (
                    "dias_retencion",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Días que se conservarán los logs antes de ser purgados",
                        verbose_name="Días de Retención",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="configuracion.empresaconfig",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la última actualización",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Auditoría",
                "verbose_name_plural": "Configuraciones de Auditoría",
                "db_table": "audit_configuracion_auditoria",
                "ordering": ["modulo", "modelo"],
                "unique_together": {("empresa", "modulo", "modelo")},
            },
        ),
        migrations.CreateModel(
            name="LogAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de Sesión"),
                            ("logout", "Cierre de Sesión"),
                            ("login_fallido", "Inicio de Sesión Fallido"),
                            ("sesion_expirada", "Sesión Expirada"),
                            ("cambio_password", "Cambio de Contraseña"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Dirección IP desde donde se realizó el acceso",
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User Agent del navegador/aplicación",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Geolocalización aproximada (ciudad, país)",
                        max_length=200,
                        null=True,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de dispositivo (desktop, mobile, tablet)",
                        max_length=50,
                        null=True,
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "navegador",
                    models.CharField(
                        blank=True,
                        help_text="Navegador utilizado",
                        max_length=100,
                        null=True,
                        verbose_name="Navegador",
                    ),
                ),
                (
                    "fue_exitoso",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Fue Exitoso"
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el evento falló",
                        null=True,
                        verbose_name="Mensaje de Error",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó el evento (null si falló el login)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_acceso",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acceso",
                "verbose_name_plural": "Logs de Acceso",
                "db_table": "audit_log_acceso",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="audit_log_a_usuario_923a58_idx",
                    ),
                    models.Index(
                        fields=["tipo_evento", "-created_at"],
                        name="audit_log_a_tipo_ev_061cda_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="audit_log_a_ip_addr_f0aee2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="ID del Objeto"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="Representación en texto del objeto modificado",
                        max_length=500,
                        verbose_name="Representación del Objeto",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("modificar", "Modificar"),
                            ("eliminar", "Eliminar"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "cambios",
                    models.JSONField(
                        help_text='Diccionario con los cambios: {"campo": {"old": valor_antiguo, "new": valor_nuevo}}',
                        verbose_name="Cambios",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Contenido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó el cambio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_cambio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Cambio",
                "verbose_name_plural": "Logs de Cambios",
                "db_table": "audit_log_cambio",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="audit_log_c_content_238355_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="audit_log_c_usuario_33d5d9_idx",
                    ),
                    models.Index(
                        fields=["accion", "-created_at"],
                        name="audit_log_c_accion_e4b204_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha y hora de creación del registro (automático)",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Fecha y hora de la última actualización (automático)",
                        verbose_name="Última Actualización",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Módulo"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="URL del endpoint consultado",
                        max_length=500,
                        verbose_name="Endpoint",
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parámetros de la consulta (filtros, búsqueda, etc.)",
                        verbose_name="Parámetros",
                    ),
                ),
                (
                    "registros_accedidos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de registros devueltos en la consulta",
                        verbose_name="Registros Accedidos",
                    ),
                ),
                (
                    "fue_exportacion",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Fue Exportación"
                    ),
                ),
                (
                    "formato_exportacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Formato de Exportación",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_consulta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Consulta",
                "verbose_name_plural": "Logs de Consultas",
                "db_table": "audit_log_consulta",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="audit_log_c_usuario_4995c7_idx",
                    ),
                    models.Index(
                        fields=["modulo", "-created_at"],
                        name="audit_log_c_modulo_2c1e11_idx",
                    ),
                    models.Index(
                        fields=["fue_exportacion", "-created_at"],
                        name="audit_log_c_fue_exp_95f681_idx",
                    ),
                ],
            },
        ),
    ]
